project:
  type: website
  output-dir: docs
  render:
    - "notes/"

website:
  page-navigation: true
  # navbar:
  #   background: primary
  #   search: true
  #   left:
  #     - text: "Home"
  #       href: index.qmd
  sidebar:
    style: "docked"
    search: true
    collapse-level: 3
    contents:
      - index.qmd
      - notes/ch01.qmd
      - notes/ch02.qmd
      - notes/ch03.qmd
      - notes/ch04.qmd
      - notes/ch05.qmd
      - notes/ch06.qmd
      - notes/ch07.qmd
      
bibliography: references.bib
link-citations: true

# format:
  # pdf:
  #   documentclass: scrreprt
  #   papersize: a4
  #   toc: true
  #   toc-depth: 2
  #   number-sections: true
  #   colorlinks: true
  #   include-in-header: 
  #     text: |
  #       \usepackage{kotex}