project:
  type: website
  output-dir: docs
  preview:
    port: 9999
    browser: false  
  render:
    - "index.qmd"
    - "notes/"
    - "!ref/"

execute:
  freeze: auto
  eval: true

website:
  title: "R과 데이터 분석 입문"
  reader-mode: true
  twitter-card: true
  open-graph: true
  page-navigation: true
  sidebar:
    style: "docked"
    search: true
    collapse-level: 1
    contents:
      - index.qmd
      - section: R과 데이터 분석
        contents:
          - notes/ch01.qmd
          - notes/ch02.qmd
          - notes/ch03.qmd
          - notes/ch04.qmd
          - notes/ch05.qmd
          - notes/ch06.qmd
          - notes/ch07.qmd

      # - section: "R로 배우는 확률"
      #   contents:        
      #   - notes/statistics/ch01.qmd
      #   - notes/statistics/ch02.qmd
      #   - notes/statistics/ch03.qmd
      #   - notes/statistics/ch04.qmd
      #   - notes/statistics/ch05.qmd
      #   - notes/statistics/ch06.qmd
      #   - notes/statistics/ch07.qmd
      # - section: "확률과 검증"
      #   contents:
      #   - notes/statistics/ch08.qmd        
      #   - notes/statistics/ch09.qmd
      #   - notes/statistics/ch10.qmd
      #   - notes/statistics/ch11.qmd
      #   - notes/statistics/ch12.qmd
      #   - notes/statistics/ch13.qmd
      #   - notes/statistics/ch14.qmd
      #   - notes/statistics/ch15.qmd
      #   - notes/statistics/ch16.qmd
      #   - notes/statistics/ch17.qmd
      # - section: "확률과 추론"
      #   contents:
      #   - notes/statistics/ch18.qmd
      #   - notes/statistics/ch19.qmd
      #   - notes/statistics/ch20.qmd
      - references.qmd
book:
  title: "R과 데이터 분석 입문"
  author: "Sangkon Han(sd)"
  date: today
  chapters:
    - index.qmd
    # - part: "R과 데이터 분석"
    #   chapters:
    #     - notes/statistics/ch01.qmd
    #     - notes/statistics/ch02.qmd
    #     - notes/statistics/ch03.qmd
    #     - notes/statistics/ch04.qmd
    #     - notes/statistics/ch05.qmd
    #     - notes/statistics/ch06.qmd
    #     - notes/statistics/ch07.qmd
    # - part: "확률과 검증"
    #   chapters:
    #     - notes/statistics/ch08.qmd
    #     - notes/statistics/ch09.qmd
    #     - notes/statistics/ch10.qmd
    #     - notes/statistics/ch11.qmd
    #     - notes/statistics/ch12.qmd
    #     - notes/statistics/ch13.qmd
    #     - notes/statistics/ch14.qmd
    #     - notes/statistics/ch15.qmd
    #     - notes/statistics/ch16.qmd
    #     - notes/statistics/ch17.qmd
    # - part: "확률과 추론"
    #   chapters:
    #     - notes/statistics/ch18.qmd
    #     - notes/statistics/ch19.qmd
    #     - notes/statistics/ch20.qmd
    - references.qmd

bibliography: references.bib

format:
  html:
    toc: true
    toc-depth: 3
    number-sections: true
  # pdf:
  #   documentclass: scrbook
  #   mainfont: "KoPubBatang-Light"
  #   sansfont: "KoPubBatang-Light"
  #   monofont: "D2Coding"
  #   pdf-engine: xelatex
  #   paper: a4paper
  #   code-cap-location: bottom
  #   code-block-border-left: "#e8e8e8"
  #   highlight-style: pygments
  #   geometry:      
  #     - left=20mm
  #     - top=20mm 
  #   titlepage: false
  #   include-in-header:
  #     - text: |
  #         \usepackage{kotex}
  #         \usepackage{indentfirst}
  #         \usepackage{setspace}
  #         \usepackage{hyperref}
  #         \usepackage{makeidx}
  #         \usepackage{tikz}
  #         \setstretch{1.15}
  #         \makeindex