---
title: "데이터 랭글링의 기초"
---

> 인간과 데이터의 관계는 오래되었습니다. 

우리의 뇌가 포착하고 저장할 수 있는 정보의 양이 제한적이라는 것을 알고, 우리는 데이터를 보존하고 구성하는 방법을 만들어야 했습니다. 데이터를 보존하고 저장한다는 최초의 개념은 기원전 19,000년으로 거슬러 올라가며, 당시 뼈 막대기를 사용해 사물의 개수를 세고 그 위에 정보를 새겨 계산 막대(tally stick)로 사용한 것으로 추정됩니다. 그 이후로 단어, 글씨, 숫자 및 기타 여러 형태의 데이터 수집 방법이 개발되고 진화해 왔습니다. 1663년, 존 그랜트(John Graunt)는 영국 런던 시의 성별에 따른 출생과 사망을 연구하면서 최초로 인정받는 데이터 분석 중 하나를 수행했습니다. 1928년, 프리츠 플로이머(Fritz Pfleumer)는 소리를 저장하는 솔루션인 자기 테이프에 대한 특허를 받았으며, 이는 다른 연구자들이 하드 디스크 드라이브와 같이 현재도 사용되는 많은 저장 기술을 개발하는 계기가 되었습니다.

시간을 빠르게 돌려 현대 컴퓨터 시대의 초기인 1970년대에 IBM 연구원인 레이먼드 보이스(Raymond Boyce)와 도널드 챔벌린(Donald Chamberlin)은 데이터베이스에 보관된 데이터에 액세스하고 수정하기 위해 구조화된 질의 언어(Structured Query Language, SQL)를 만들었습니다. 이 언어는 여전히 사용되고 있으며, 사실 많은 데이터 랭글링 개념이 이로부터 파생되었습니다. `SELECT`, `WHERE`, `GROUP BY`, `JOIN` 과 같은 개념들은 데이터 세트로 수행하고자 하는 모든 작업에 깊이 관여합니다. 따라서 비록 필수는 아니지만, 이러한 기본 명령어에 대한 약간의 지식은 이 책을 읽어 나가는 데 도움이 될 것입니다.

## 데이터 랭글링이란?

데이터 랭글링은 분석 및 데이터 과학에서 사용하기에 더 적합하도록 특정 상태에서 다른 상태로 데이터를 수정, 정제, 구성 및 변환하는 과정입니다. 이 개념은 데이터 먼징(data munging)이라고도 불리며, 두 단어 모두 데이터 세트를 변경, 조작, 변환 및 증강하는 행위와 관련이 있습니다.

저는 여러분이 이미 데이터 랭글링을 수행해 보았을 것이라고 확신합니다. 이는 우리 모두에게 흔한 작업입니다. 초등학교 시절부터 우리는 표를 만들고 사람들의 의견을 세어 데이터 세트로 구성하는 방법을 배웠습니다. MS Excel이나 유사한 도구에 익숙하다면 표를 정렬, 필터링하거나 열을 추가했던 모든 순간들을 기억해 보세요. 수행했을 수도 있는 수많은 조회(lookup) 작업들은 말할 것도 없습니다. 그 모든 것이 데이터 랭글링 과정의 일부입니다. 데이터를 어떤 식으로든 개선하여 분석에 더 적합하게 만들기 위해 수행하는 모든 작업은 데이터 랭글링으로 간주될 수 있습니다.

데이터 과학자로서 여러분은 데이터 세트를 비즈니스 결정의 기반이 될 인사이트로 변환해야 한다는 임무를 띠고 지속적으로 다양한 종류의 데이터를 제공받게 될 것입니다. 텍스트나 표와 같은 구조화된 형태로 대부분의 데이터가 제시되던 몇 년 전과 달리, 오늘날의 데이터는 비디오, 오디오 또는 이들의 조합과 같은 비구조화된 형식을 포함하여 다른 여러 형태로 올 수 있습니다. 따라서 데이터가 바로 작업할 수 있는 상태로 제시되는 경우는 드물며, 사용할 준비가 된 상태로 만들기 위해 어느 정도의(때로는 상당히 많은) 노력이 필요하다는 것이 명확해집니다.

## 왜 데이터 랭글링인가?

이제 데이터 랭글링이 무엇을 의미하는지 알게 되었으니, 이것이 대단히 중요한 주제라는 저와 같은 시각을 가지셨을 것이라 확신합니다. (그렇지 않다면 이 책을 읽고 계시지 않았겠죠). 통계 및 데이터 과학 분야에는 다음과 같이 자주 반복되는 문구가 있습니다. 

> 쓰레기가 들어가면 쓰레기가 나온다(garbage in, garbage out). 

이 유명한 격언은 데이터 랭글링의 중요성에 대한 핵심적인 생각을 대변합니다. 왜냐하면 우리의 분석이나 심지어 우리의 모델조차도 우리가 주입하는 데이터만큼만 좋을 것이라는 점을 가르쳐주기 때문입니다. 이 중요성을 설명하기 위해 사슬에서 약한 고리(weakest link in the chain) 비유를 사용할 수도 있습니다. 이는 여러분의 데이터가 부실하다면 분석의 나머지 부분도 질문과 반박에 의해 쉽게 무너질 수 있음을 의미합니다.

훌륭한 데이터 랭글링을 수행하면 전체 분석 프로세스의 전반적인 품질이 향상됩니다. 다음은 그 이점들입니다.

1. 구조화된 데이터: 데이터가 체계적으로 구성되어 다른 데이터 과학자들이 쉽게 이해할 수 있습니다.

2. 더 빠른 결과: 데이터가 이미 사용할 수 있는 상태라면, 그래프을 생성하거나 알고리즘의 입력으로 사용하는 것이 확실히 더 빠를 것입니다.

3. 더 나은 데이터 흐름: 데이터를 모델링이나 대시보드에 사용할 수 있으려면 적절하게 형식이 지정되고 정제되어야 합니다. 훌륭한 데이터 랭글링은 데이터가 프로세스의 다음 단계로 이어질 수 있게 하여 데이터 파이프라인과 자동화를 가능하게 합니다.

4. 집계(Aggregation): 이전 섹션의 예에서 보았듯이, 데이터는 컴퓨터가 이해할 수 있는 적합한 형식이어야 합니다. 잘 랭글링된 데이터 세트가 있으면 인사이트 추출을 위해 데이터를 빠르게 집계할 수 있습니다.

5. 데이터 품질: 데이터 랭글링은 데이터를 사용할 준비가 된 상태로 변환하는 것에 관한 것입니다. 이 과정에서 여러분은 데이터를 정제, 집계, 필터링 및 분류하고, 데이터를 시각화하며, 그 품질을 평가하고, 이상치를 처리하며, 잘못되었거나 불완전한 데이터를 식별할 것입니다.

6. 데이터 풍부화(Data enriching): 랭글링 중에 원래의 변수에서 새로운 변수를 생성하거나 다른 데이터 세트를 결합하여 데이터를 더 완전하게 만듦으로써 데이터를 풍부하게 할 수 있습니다.

데이터 과학과 관련이 있든 없든 모든 프로젝트는 데이터 랭글링의 이점을 누릴 수 있습니다. 방금 나열한 것처럼 데이터 랭글링은 분석에 많은 이점을 가져다주며 궁극적으로 결과물의 품질에 영향을 미칩니다. 그러나 최상의 결과를 얻기 위해 따라야 할 단계들이 있습니다.

## 데이터 랭글링의 핵심 단계

데이터 과학자와 분석가가 데이터 랭글링 과정을 헤쳐 나가는 데 도움이 되는 몇 가지 기본 단계가 있습니다. 자연스럽게, 데이터 세트를 처음 보면 먼저 그것을 이해한 다음, 모델의 입력으로 사용하기 전에 구성, 정제, 풍부화 및 검증하는 것이 중요합니다.

1. 이해(Understand): 새로운 데이터를 손에 넣었을 때 취해야 할 첫 번째 단계는 이를 이해하는 것입니다. 변수에 대한 설명이 있는 문서인 데이터 사전(data dictionary)이 있다면 이를 읽어보거나, 혹은 데이터의 소유자(들)와 이야기하여 각 데이터 포인트가 무엇을 나타내며, 이것들이 주요 목적 및 여러분이 답변하고자 하는 비즈니스 질문과 어떻게 연결되는지 또는 연결되지 않는지 제대로 파악하는 시간을 가지세요. 이렇게 하면 다음 단계가 더 명확해집니다.

2. 형식 지정(Format): 두 번째 단계는 데이터를 형식화하거나 구성하는 것입니다. 원시 데이터는 사용할 수 없는 방식으로 구조화되지 않거나 형식이 지정되지 않은 상태로 올 수 있습니다. 따라서 깔끔한(tidy) 형식에 익숙해지는 것이 중요합니다. 깔끔한 데이터(Tidy data)는 2014년 해들리 위컴(Hadley Wickham)이 같은 이름의 논문 'Tidy data'에서 개발한 개념으로, 데이터 세트를 구성하고 구조화하는 표준 방법을 제시하여 정제 및 탐색 단계를 더 쉽게 만듭니다. 또 다른 이점은 동일한 형식을 사용하는 여러 도구 간에 데이터 세트를 전송하기 쉽다는 점입니다. 현재 깔끔한 데이터 개념은 널리 받아들여지고 있으므로, 파이프라인 아래로 이동시킬 때마다 데이터 세트를 먼징하는 대신 분석에 집중할 수 있도록 도와줍니다.

깔끔한 데이터는 데이터의 구조가 의미론(semantics)과 연결되는 방식, 즉 레이아웃이 값의 의미와 어떻게 연결되는지를 표준화합니다. 더 구체적으로 말하면, 구조란 레이블을 지정할 수 있는 행과 열을 의미합니다. 대부분의 경우 열에는 레이블이 지정되지만 행에는 지정되지 않습니다. 반면, 모든 값은 변수 및 관측치(observation)와 관련이 있습니다. 이것이 데이터 의미론입니다. 깔끔한 데이터 세트에서 변수는 속성의 모든 값을 보유하는 열이 되고, 각 행은 하나의 관측치와 연관됩니다.예를 들어, 마력(horsepower) 열과 관련하여 우리는 4대의 다른 자동차에 대해 110, 110, 93, 110과 같은 값을 볼 수 있습니다. 관측치 수준에서 보면 각 행은 하나의 관측치이며, 각 속성 또는 변수에 대해 하나의 값을 가지므로 하나의 자동차는 마력=110, 6기통, 갤런당 21마일 등과 연관될 수 있습니다.

위컴에 따르면, 깔끔한 데이터의 세 가지 규칙은 다음과 같습니다.

- 모든 열은 변수
- 모든 행은 관측치
- 모든 셀은 단일 값

1. 정제(Clean): 이 단계는 데이터의 전반적인 품질을 결정하는 데 관련이 있습니다. 분할, 변수 파싱, 결측값 처리, 이상치 처리 및 잘못된 항목 제거 등 데이터 정제에는 다양한 형태가 있습니다.

2. 풍부화(Enrich): 데이터 랭글링 단계를 진행하고 데이터에 더 익숙해짐에 따라 의문이 생길 것이며, 때로는 더 많은 데이터가 필요해질 것입니다. 이는 다른 데이터 세트를 원래 데이터 세트에 결합하여 새 변수를 가져오거나 기존 변수를 사용하여 새 변수를 생성함으로써 해결할 수 있습니다.

3. 검증(Validate): 검증한다는 것은 정제, 형식 지정 및 변환이 모두 올바르게 수행되었는지, 데이터가 모델링이나 기타 분석을 위한 준비가 되었는지 확인하는 것입니다.

4. 분석/모델(Analysis/Model): 모든 것이 완료되면 여러분의 데이터 세트는 대시보드 생성이나 모델링과 같은 프로젝트의 다음 단계에서 사용할 준비가 된 것입니다.

모든 프로세스와 마찬가지로 최고의 성능에 도달하고 노력을 표준화하며 필요에 따라 재생산하고 확장할 수 있도록 단계를 따라야 합니다. 다음으로, 프로세스를 따르고 재현하기 쉽게 만들어주는 데이터 과학 프로젝트를 위한 세 가지 프레임워크를 살펴볼 것입니다.

## 데이터 과학의 프레임워크

데이터 과학은 다른 과학과 다르지 않으며, 일반적인 몇몇 단계를 따릅니다. 따라서 사람들이 프로세스를 진행하도록 안내하고 기업에서 표준화된 프로세스를 구현하는 데 도움을 주는 프레임워크를 설계할 수 있습니다. 데이터 과학자는 획득하는 순간부터 종착점까지 데이터의 흐름을 전체적으로(holistic) 이해하는 것이 중요합니다. 결과적인 비즈니스 지식이야말로 의사 결정을 뒷받침할 것이기 때문입니다. 

데이터 과학 프로젝트에 사용할 수 있는 세 가지 알려진 프레임워크인 KDD, SEMMA, CRISP-DM 에 대해 자세히 살펴볼 것입니다.

### KDD

KDD 는 데이터베이스에서의 지식 발견(Knowledge Discovery in Databases) 을 의미합니다. 이는 대규모 데이터베이스의 맥락에서 데이터로부터 지식을 추출하는 프레임워크입니다. 이 프로세스는 반복적이며 다음 단계를 따릅니다.

1. 데이터(Data): 데이터베이스에서 데이터를 획득
2. 선택(Selection): 선택된 변수나 관심 샘플을 가진 데이터의 하위 집합(subset)인 대표 대상 집합을 생성
3. 전처리(Preprocessing): 이상치를 제거하고 누락되거나 잡음이 많은 데이터를 처리하기 위한 데이터 정제 및 전처리
4. 변환(Transformation): 차원 축소를 변환 및 사용하여 데이터 형식을 지정
5. 데이터 마이닝(Data Mining): 알고리즘을 사용하여 관심 있는 패턴을 분석하고 검색 (분류 및 클러스터링)
6. 해석/평가(Interpretation/Evaluation): 마이닝된 패턴을 해석하고 평가

평가 후 결과가 만족스럽지 않으면 더 많은 데이터, 다른 하위 집합 또는 조정된 알고리즘 등 향상된 기능과 함께 프로세스를 반복할 수 있습니다.

### SEMMA

SEMMA 는 샘플링(Sample), 탐색(Explore), 수정(Modify), 모델링(Model), 평가(Assess) 를 의미합니다. 이들이 프로세스의 단계입니다. SEMMA는 데이터 과학과 함께 더 자연스럽게 흐르는 순환 프로세스입니다. KDD와 같은 단계는 포함하지 않습니다. 단계는 다음과 같습니다.

1. 샘플(Sample): 통계에 기반하여 대표성을 가질 만큼 충분히 크되 작업하기에 빠를 만큼 충분히 작은 샘플이 필요
2. 탐색(Explore): 이 단계 동안의 목표는 데이터를 이해하고 시각화 및 기술 통계를 생성하여 패턴과 이상치를 찾는 것
3. 수정(Modify): 이곳은 데이터 랭글링이 더 집중적인 역할을 수행하는 곳으로, 데이터를 모델링에 사용할 수 있도록 변환이 일어남
4. 모델(Model): 이 단계는 알고리즘을 사용하여 데이터로부터 추정치, 예측 또는 인사이트를 생성하는 곳
5. 평가(Assess): 결과 평가

### CRISP-DM

이 프레임워크의 약어는 데이터 마이닝을 위한 산업 간 표준 프로세스(Cross-Industry Standard Process for Data Mining) 를 의미합니다. 이는 데이터 과학자에게 프로젝트의 전형적인 단계를 제공할 뿐만 아니라 데이터 마이닝 수명 주기에 대한 개요를 제공합니다. CRISP-DM 수명 주기에는 6단계가 있으며 화살표는 각 단계 간의 종속성을 나타냅니다. 그러나 여기서 핵심은 따라야 할 엄격한 순서가 없다는 것입니다. 프로젝트는 프로세스 중에 앞뒤로 이동할 수 있어 유연한 프레임워크가 됩니다. 단계를 살펴보겠습니다.

1. 비즈니스 이해(Business understanding): 앞서 제시된 다른 두 가지 프레임워크와 마찬가지로, 모든 것은 문제, 즉 비즈니스를 이해하는 것에서 시작됩니다. 비즈니스 규칙과 특수성을 이해하는 것은 종종 솔루션에 빨리 도달하는 것보다 훨씬 더 중요합니다. 솔루션이 해당 종류의 비즈니스에 이상적이지 않을 수 있기 때문입니다. 비즈니스 규칙은 항상 솔루션을 주도해야 합니다.

2. 데이터 이해(Data understanding): 여기에는 데이터 수집 및 탐색이 포함됩니다. 수집된 데이터가 전체를 대표하는지 확인하고, 데이터에 익숙해져 오류, 잘못된 데이터, 결측값을 찾고 품질을 평가할 수 있어야 합니다. 이 모든 작업은 데이터 이해의 일부입니다.

3. 데이터 준비(Data preparation): 수집된 데이터에 익숙해지면 이를 랭글링하고 모델링을 위해 준비할 때입니다.

4. 모델링(Modeling): 여기에는 처리된 데이터에 데이터 과학 알고리즘을 적용하거나 원하는 분석을 수행하는 작업이 포함됩니다.

5. 평가(Evaluation): 이 단계는 솔루션이 비즈니스 요구 사항과 일치하는지, 성능이 우수한지 평가하는 데 사용됩니다.
6. 배포(Deployment): 이 단계에서 모델은 그 목적을 달성합니다(그룹이나 값을 예측하는 애플리케이션, 대시보드 등).

자세히 살펴보면 이 세 가지 프레임워크는 공통점이 많습니다. 이들은 데이터를 이해하는 것으로 시작하여 정제 및 변환을 통한 데이터 랭글링을 거쳐 모델링 단계로 이동한 다음 모델의 평가로 끝나며, 대개 결함을 평가하고 결과를 개선하기 위한 반복 작업을 진행합니다.
