<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.9.38">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>탐색적 데이터 분석</title>
<style>
/* Default styles provided by pandoc.
** See https://pandoc.org/MANUAL.html#variables-for-html for config info.
*/
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
html { -webkit-text-size-adjust: 100%; }
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="../site_libs/quarto-nav/quarto-nav.js"></script>
<script src="../site_libs/quarto-nav/headroom.min.js"></script>
<script src="../site_libs/clipboard/clipboard.min.js"></script>
<script src="../site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="../site_libs/quarto-search/fuse.min.js"></script>
<script src="../site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="../">
<link href="../notes/ch05.html" rel="prev">
<script src="../site_libs/quarto-html/quarto.js" type="module"></script>
<script src="../site_libs/quarto-html/tabsets/tabsets.js" type="module"></script>
<script src="../site_libs/quarto-html/popper.min.js"></script>
<script src="../site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="../site_libs/quarto-html/anchor.min.js"></script>
<link href="../site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="../site_libs/quarto-html/quarto-syntax-highlighting-15634bcf2e68342d4ad2dfa704d543f6.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="../site_libs/bootstrap/bootstrap.min.js"></script>
<link href="../site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="../site_libs/bootstrap/bootstrap-cf5ee1d16def7895729d1ac812351ea4.min.css" rel="stylesheet" append-hash="true" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "sidebar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "start",
  "type": "textbox",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>

  <script src="https://cdnjs.cloudflare.com/polyfill/v3/polyfill.min.js?features=es6"></script>
  <script defer="" src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

<script type="text/javascript">
const typesetMath = (el) => {
  if (window.MathJax) {
    // MathJax Typeset
    window.MathJax.typeset([el]);
  } else if (window.katex) {
    // KaTeX Render
    var mathElements = el.getElementsByClassName("math");
    var macros = [];
    for (var i = 0; i < mathElements.length; i++) {
      var texText = mathElements[i].firstChild;
      if (mathElements[i].tagName == "SPAN" && texText && texText.data) {
        window.katex.render(texText.data, mathElements[i], {
          displayMode: mathElements[i].classList.contains('display'),
          throwOnError: false,
          macros: macros,
          fleqn: false
        });
      }
    }
  }
}
window.Quarto = {
  typesetMath
};
</script>

</head>

<body class="nav-sidebar docked fullcontent quarto-light">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
  <nav class="quarto-secondary-nav">
    <div class="container-fluid d-flex">
      <button type="button" class="quarto-btn-toggle btn" data-bs-toggle="collapse" role="button" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
        <i class="bi bi-layout-text-sidebar-reverse"></i>
      </button>
        <nav class="quarto-page-breadcrumbs" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="../notes/ch06.html">탐색적 데이터 분석</a></li></ol></nav>
        <a class="flex-grow-1" role="navigation" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">      
        </a>
      <button type="button" class="btn quarto-search-button" aria-label="Search" onclick="window.quartoOpenSearch();">
        <i class="bi bi-search"></i>
      </button>
    </div>
  </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article">
<!-- sidebar -->
  <nav id="quarto-sidebar" class="sidebar collapse collapse-horizontal quarto-sidebar-collapse-item sidebar-navigation docked overflow-auto">
        <div class="mt-2 flex-shrink-0 align-items-center">
        <div class="sidebar-search">
        <div id="quarto-search" class="" title="Search"></div>
        </div>
        </div>
    <div class="sidebar-menu-container"> 
    <ul class="list-unstyled mt-1">
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../notes/ch01.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">통계학의 중요성!</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../notes/ch02.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">R 입문</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../notes/ch03.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">데이터 수집</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../notes/ch04.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">데이터 추출</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../notes/ch05.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">데이터 불러오기</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../notes/ch06.html" class="sidebar-item-text sidebar-link active">
 <span class="menu-text">탐색적 데이터 분석</span></a>
  </div>
</li>
    </ul>
    </div>
</nav>
<div id="quarto-sidebar-glass" class="quarto-sidebar-collapse-item" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item"></div>
<!-- margin-sidebar -->
    
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">탐색적 데이터 분석</h1>
</div>



<div class="quarto-title-meta">

    
  
    
  </div>
  


</header>


<blockquote class="blockquote">
<p>데이터를 수집하고 나면, 통계 프로세스의 다음 단계는 데이터를 탐색하기 시작하는 것입니다. 이때 연구 대상의 수가 많을 수 있으므로 전체 데이터셋을 일일이 탐색할 수 없는 경우가 많습니다. 따라서 우리는 그래픽 요약과 수치 요약이라는 데이터의 요약본을 활용해야 합니다. 기술 통계(Descriptive statistics)라고 불리는 이러한 요약은 통계 프로세스의 끝이 아닙니다. 통계 프로세스는 끊임없이 반복되므로 실제로는 끝이 없습니다. 또한 기술 통계만으로 확정적인 결정을 내려서는 안 됩니다. 그보다는 기술 통계가 데이터셋에서 어떤 일이 일어나고 있는지에 대한 일반적인 아이디어를 제공하고, 데이터셋 내 변수들 사이의 흥미로운 관계가 있는 방향을 제시해 줄 수 있습니다.</p>
</blockquote>
<section id="모수와-통계량" class="level2">
<h2 class="anchored" data-anchor-id="모수와-통계량">모수와 통계량</h2>
<p>통계 프로세스의 목표는 데이터로부터 질문에 답하도록 돕는 것임을 상기해 보겠습니다. 실제로 우리는 모집단(Population) 전체에 대한 질문에 답하는 것이 아니라, 모집단의 단일 수치에 대한 질문에 답하는 것입니다. 예를 들어, 운동이 혈압을 낮추는 데 도움이 되는지 물을 때, 우리는 실제로는 “평균적으로, 운동을 하는 개인들로 구성된 모집단이 혈압 수치의 감소를 경험할까요?”를 묻는 것입니다. 모집단 전체를 설명하는 이 단일 수치를 모수(Parameter) 또는 모집단 모수라고 부릅니다. 이는 고정되어 있고 알 수 없는 것으로 간주되며, 통계 프로세스를 통해 질문에 답하기 위해서는 관심 있는 모수의 값을 추정해야 합니다.</p>
<p>이러한 모수를 추정하기 위해, 설계된 실험이나 관찰 연구로부터 얻은 표본(Sample)이 필요합니다. 그러나 질문에 답하기 위해 표본 전체를 사용할 수 없는 것과 마찬가지로, 모집단 모수를 추정하기 위해 표본 전체를 사용할 수는 없습니다. 대신, 모수를 추정하기 위해 표본에서 적절하게 선택된 요약 수치를 사용할 것입니다. 이것이 통계량(Statistic), 즉 표본으로부터 계산된 모든 수치입니다.</p>
<p>각 변수의 유형(수치형 및 범주형)에 따라 우리가 다루어야 할 모집단 모수와 통계량이 다릅니다. 범주형 변수의 경우 고려해야 할 사항이 적으므로 거기서부터 시작하겠습니다.</p>
</section>
<section id="범주형-변수" class="level2">
<h2 class="anchored" data-anchor-id="범주형-변수">범주형 변수</h2>
<p>범주형 변수는 본질적으로 범주이기 때문에, 우리가 관심을 갖는 모수와 통계량은 각각 모집단 또는 표본이 각 범주에 속하는 비율입니다. 모집단을 살펴볼 때, 주요 관심 모수는 모집단 비율(Population proportion, <span class="math inline">\(p\)</span>로 표기)이며, 이는 관심 있는 특정 범주에 속하는 모집단의 비율입니다. 이는 모든 모수와 마찬가지로 알 수 없고 고정된 양이며 우리가 추정해야 할 값입니다. 모집단 비율을 추정하기 위해 표본 비율(Sample proportion, <span class="math inline">\(\hat{p}\)</span>으로 표기), 즉 관심 있는 특정 범주에 속하는 표본의 비율을 사용합니다. 수학적으로는 다음과 같습니다.</p>
<p><span class="math display">\[\hat{p} = \frac{\text{해당 범주의 대상 수}}{\text{표본 크기}}\]</span></p>
<p>표본이 모집단을 잘 대표한다고 가정하면(보통 무작위 표본 추출을 통해 보장됨), 표본 비율은 모집단 비율을 추정하는 역할을 잘 수행할 것입니다.</p>
<p>우리는 범주형 변수를 다루고 있으며 궁극적으로 특정 범주에 속하는 대상의 비율에 관심이 있기 때문에, 일반적인 요약 방식은 도수분포표(Frequency table)입니다. 도수분포표는 각 범주에 속하는 대상의 수(도수)를 제공하며, 때로는 연구에 참여한 총 대상의 수도 제공합니다. 도수분포표로부터 범주형 반응의 각 범주에 대한 표본 비율을 쉽게 얻을 수 있습니다.</p>
<p>예를 들어, 2016년 퓨 리서치 그룹(Pew Research Group)은 미국인들이 어떤 형태로 책을 소비하는지 알아보기 위해 1,488명을 대상으로 설문조사를 실시했습니다. 그 결과 395명은 책을 읽지 않았고, 577명은 종이책만 읽었으며, 425명은 디지털 책과 종이책을 모두 읽었고, 91명은 디지털 책만 읽는 것으로 나타났습니다. 도수분포표는 다음과 같습니다.</p>
<table class="caption-top table">
<thead>
<tr class="header">
<th>책 안 읽음</th>
<th>종이책만</th>
<th>디지털만</th>
<th>종이책 및 디지털</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>395</td>
<td>577</td>
<td>91</td>
<td>425</td>
</tr>
</tbody>
</table>
<p>종이책만 읽는 사람들의 표본 비율은 얼마입니까? 종이책만 읽는 사람의 수를 전체 표본 크기로 나누면 되므로, 종이책만 읽는 독자의 표본 비율은 <span class="math inline">\(\hat{p} = 577/1488 \approx 0.378\)</span>입니다.</p>
<p>종종 우리는 두 범주형 변수가 어떻게 관련되어 있는지에 관심을 갖습니다. 이를 고려할 때, 단일 변수에 대해서만 각 범주의 대상 수를 세는 도수분포표는 부적절한 요약입니다. 두 변수 간의 관계에 관심이 있을 때 좋은 기술 통계량은 분할표(Contingency table)입니다. 분할표는 <span class="math inline">\(m \times p\)</span> 표로, 표의 각 셀에 있는 도수는 행과 열의 조합으로 정의된 특정 범주의 조합에 속하는 대상의 수를 나타냅니다. 또한 분할표는 각 행과 열에 대한 주변 합계(Marginal totals)를 제공하며, 이는 표의 다른 차원을 무시하고 행 또는 열 범주에 속하는 대상을 나타내므로 본질적으로 행 또는 열에 대한 도수분포표를 생성합니다.</p>
<p>2017년 퓨 리서치 그룹은 미국인들이 과학 뉴스를 활발하게 소비하게 만드는 원인이 무엇인지 알아보기 위해 3,701명을 대상으로 설문조사를 실시했습니다. 조사한 변수 중에는 흑인, 백인, 히스패닉을 포함한 민족 집단이 있었습니다. 그런 다음 이 대상들에게 자신이 과학 뉴스를 활발하게 소비하는지(Active), 가끔 소비하는지(Casual), 아니면 관심이 없는지(Uninterested) 물었습니다. 데이터에 대한 분할표는 다음과 같습니다.</p>
<table class="caption-top table">
<thead>
<tr class="header">
<th></th>
<th>활발함</th>
<th>가끔</th>
<th>무관심</th>
<th>무응답</th>
<th>행 합계</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>백인</td>
<td>487</td>
<td>916</td>
<td>1431</td>
<td>28</td>
<td>2862</td>
</tr>
<tr class="even">
<td>흑인</td>
<td>59</td>
<td>98</td>
<td>227</td>
<td>8</td>
<td>392</td>
</tr>
<tr class="odd">
<td>히스패닉</td>
<td>89</td>
<td>152</td>
<td>183</td>
<td>23</td>
<td>447</td>
</tr>
<tr class="even">
<td>열 합계</td>
<td>635</td>
<td>1166</td>
<td>1841</td>
<td>59</td>
<td>3701</td>
</tr>
</tbody>
</table>
<p>열에 대한 도수분포표(“여러분은 과학 뉴스를 활발하게 소비합니까, 가끔 소비합니까, 아니면 무관심합니까?”라는 질문으로 정의됨)는 무엇이며, 히스패닉이면서 활발한 과학 소비자들의 표본 비율은 얼마입니까? 열 합계를 보면 열에 대한 도수분포표는 다음과 같음을 알 수 있습니다.</p>
<table class="caption-top table">
<thead>
<tr class="header">
<th>활발함</th>
<th>가끔</th>
<th>무관심</th>
<th>무응답</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>635</td>
<td>1166</td>
<td>1841</td>
<td>59</td>
</tr>
</tbody>
</table>
<p>또한 표에서 히스패닉 행과 활발함 열을 찾으면, 히스패닉이면서 활발한 과학 소비자인 개인의 표본 비율이 <span class="math inline">\(\hat{p} = 89/3701 \approx 0.024\)</span>임을 알 수 있습니다.</p>
<p>도수분포표와 분할표를 손으로 계산하는 것은 지루한 작업입니다. 다행히 R에는 이 두 표를 모두 생성하는 함수가 있습니다. R의 table 함수는 하나 이상의 범주형 변수를 입력받아 원하는 도수분포표 또는 분할표를 출력합니다. 이에 사용되는 코드는 다음과 같습니다.</p>
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb1"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="fu">table</span>(variable1, variable2)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<p>여기서 <code>variable1</code>은 표에서 원하는 첫 번째 변수이고, <code>variable2</code>는 분할표를 만드는 경우에 사용하는 선택적인 두 번째 변수입니다.</p>
<p>범주형 변수에 대한 시각적 요약은 미디어에서 인기가 있으며, 특히 원형 차트(Pie chart)와 막대 차트(Bar chart)가 그렇습니다. 우리는 이러한 차트들을 논의하지 않을 것인데, 왜냐하면 그것들이 해석상 여러 가지 문제, 특히 원형 차트가 그렇기 때문입니다.</p>
<p>데이터 시각화 분야에서 저명한 통계학자인 에드워드 터프티(Edward Tufte)는 “원형 차트 사용자는 its와 it’s를 혼동하거나 there와 their를 구별하지 못하는 사람들과 똑같은 의심과 회의를 받아 마땅하다”라고 언급한 바 있습니다. 요컨대, 범주형 데이터에 대한 좋은 기술 통계량은 표본 비율, 도수분포표, 분할표입니다.</p>
<section id="연습-문제" class="level3">
<h3 class="anchored" data-anchor-id="연습-문제">연습 문제</h3>
<p>기술이 사회에 긍정적인 영향을 미쳤다고 믿는지 여부에 대해 미국의 성인을 대상으로 설문조사를 실시했습니다. 대상자들에게 “기술이 우리 사회에 미친 영향은…”이라는 질문을 던졌고, 가능한 응답은 ‘대체로 긍정적(Mostly Positive)’, ‘긍정적과 부정적 동일(Equally Positive and Negative)’, ’대체로 부정적(Mostly Negative)’이었습니다. 설문조사에 대한 도수분포표는 다음과 같았습니다.</p>
<table class="caption-top table">
<thead>
<tr class="header">
<th>긍정적</th>
<th>긍정/부정 동일</th>
<th>부정적</th>
<th>무응답</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>2458</td>
<td>1796</td>
<td>378</td>
<td>94</td>
</tr>
</tbody>
</table>
<ol type="1">
<li>이 설문조사에서 관심 모집단은 무엇입니까?</li>
<li>이 설문조사의 표본 크기는 얼마입니까?</li>
<li>기술이 사회에 대체로 긍정적인 영향을 미쳤다고 믿는 사람들의 표본 비율은 얼마입니까?</li>
</ol>
<p>2018년 퓨 리서치 그룹은 유전자 변형 생물에 대한 사람들의 의견을 조사하는 설문조사를 실시했습니다. 두 가지 질문은 “여러분이 소비하는 음식 중 유기농은 얼마나 됩니까?”와 “인터넷 접속이 가능합니까?”였습니다. 이에 대한 설문조사 응답은 아래와 같습니다.</p>
<table class="caption-top table">
<thead>
<tr class="header">
<th></th>
<th>인터넷 없음</th>
<th>인터넷 있음</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>전혀 없음</td>
<td>48</td>
<td>334</td>
</tr>
<tr class="even">
<td>별로 없음</td>
<td>66</td>
<td>990</td>
</tr>
<tr class="odd">
<td>어느 정도 있음</td>
<td>62</td>
<td>848</td>
</tr>
<tr class="even">
<td>대부분임</td>
<td>11</td>
<td>166</td>
</tr>
</tbody>
</table>
<ol start="4" type="1">
<li>이 설문조사의 표본 크기는 얼마입니까?</li>
<li>인터넷 접속이 불가능한 사람들의 표본 비율은 얼마입니까?</li>
<li>“여러분이 소비하는 음식 중 유기농은 얼마나 됩니까?”라는 질문에 대한 도수분포표는 무엇입니까?</li>
</ol>
</section>
</section>
<section id="단일-수치형" class="level2">
<h2 class="anchored" data-anchor-id="단일-수치형">단일 수치형</h2>
<p>수치형 변수는 범주형 변수보다 더 많은 측면을 가지고 있기 때문에 더 다양한 기술 통계량과 탐색적 분석을 고려해야 합니다. 범주형 변수의 경우, 데이터를 이해하기 위해 반응 범주에 속한 개인의 비율만 고려하면 됩니다. 단일 수치형 변수의 경우, 값의 중심(Center), 값의 퍼짐(Spread), 분포의 모양(Shape)을 포함하여 값의 분포에 관한 모든 측면을 고려해야 합니다. 이러한 각 측면을 설명하는 데 사용할 수 있는 다양한 통계량을 논의하겠습니다.</p>
<p>수치형 변수에서 고려해야 할 중요한 측면은 해당 변수의 중심이 어디에 위치하는가입니다. 모집단을 고려하든 표본을 고려하든, 대부분의 통계 기법은 관심 있는 특정 변수의 값 분포의 중심을 고려하는 것을 포함합니다. 일반적으로 모집단 전체를 고려할 때 중심을 설명하는 두 가지 모집단 모수는 모집단 평균(Population mean, μ로 표기)과 모집단 중앙값(Population median)입니다. 모집단 평균은 모집단의 모든 구성원에 대한 평균값이며, 모집단 중앙값은 모집단의 중간점으로 모집단의 50%가 해당 값보다 아래에 있고 나머지 50%가 위에 있는 값입니다. 모든 모수와 마찬가지로 이 값들은 고정되어 있고 알 수 없는 것으로 간주됩니다.</p>
<p>이러한 모수의 실제 값은 일반적으로 알려져 있지 않기 때문에 표본 통계량, 구체적으로 표본 평균과 표본 중앙값을 통해 추정해야 합니다. 이를 정의하기 위해 먼저 표본에 대한 몇 가지 표기법을 이야기해야 합니다. 크기가 <span class="math inline">\(n\)</span>인 표본이 있다고 해 보겠습니다. 우리가 수집한 변수의 값을 다음과 같이 나타냅니다.</p>
<p><span class="math display">\[x_1,x_2,\cdots,x_n\]</span></p>
<p>여기서 <span class="math inline">\(x_1\)</span>은 첫 번째 대상에 대한 변수 값이고, <span class="math inline">\(x_2\)</span>는 두 번째 대상에 대한 변수 값이며, <span class="math inline">\(x_n\)</span>은 마지막 대상의 값 등입니다. 대상 번호에 따라 변수 값의 순서를 매기는 것 외에도, 표본의 변수 값을 작은 것부터 큰 것까지 순서대로 정렬할 수도 있습니다. 이를 다음과 같이 나타냅니다.</p>
<p><span class="math display">\[x_{(1)},x_{(2)},\cdots,x_{(n)}\]</span></p>
<p>여기서 <span class="math inline">\(x_{(1)}\)</span>은 표본에서 변수의 작은 값이고, <span class="math inline">\(x_{(2)}\)</span>는 표본에서 두 번째로 작은 값이며, <span class="math inline">\(x_{(n)}\)</span>은 표본에서 큰 값 등입니다.</p>
<p>이제 표본을 정의했으므로 표본 통계량에 대해 이야기할 수 있습니다. 모집단 평균에 대한 최선의 추정치인 표본 평균(Sample mean, <span class="math inline">\(\bar{x}\)</span>으로 표기)은 단순히 표본에 있는 모든 값의 평균이므로 다음과 같습니다.</p>
<p><span class="math display">\[\bar{x}=\frac{1}{n}\sum_{i=1}^{n}x_i=\frac{1}{n}(x_1+x_2+\cdots+x_n)\]</span></p>
<p>모집단 중앙값에 대한 최선의 추정치인 표본 중앙값(Sample median, <span class="math inline">\(\tilde{x}\)</span>으로 표기)은 표본에서 변수의 중앙값이므로, 표본 중앙값에는 두 가지 가능한 공식이 있습니다. 표본 크기가 홀수인 경우, 표본 중앙값은 다음과 같습니다.</p>
<p><span class="math display">\[\tilde{x}=x_{(n+12)}\]</span></p>
<p>즉, 데이터의 절반(<span class="math inline">\(\frac{n-1}{2}\)</span>개의 데이터 포인트)이 해당 값보다 크거나 작은 표본 내의 지점입니다. 표본 크기가 짝수인 경우, 표본 중앙값은 다음과 같습니다.</p>
<p><span class="math display">\[\tilde{x}=\frac{x_{(n/2)}+x_{(n/2+1)}}{2}\]</span></p>
<p>즉, 중간에 가까운 두 표본 값의 평균입니다.</p>
<p>예를 들어, 나이절 리처즈(Nigel Richards)는 일반적으로 세계 최고의 스크래블(Scrabble) 플레이어 중 한 명으로 간주됩니다. 2014년 한 대회에서 그는 다음과 같은 점수를 기록했습니다.</p>
<p>550, 526, 458, 440, 440, 389, 432, 508, 433, 433, 548, 497, 531, 484.</p>
<p>이 데이터의 표본 평균은 <span class="math inline">\(\bar{x}=\frac{1}{14}(550+526+\cdots+484)=476.36\)</span>입니다. 표본 중앙값을 구하려면 먼저 점수를 432부터 550까지 작은 것부터 큰 것 순으로 정렬해야 합니다. 그런 다음 표본 크기가 <span class="math inline">\(n=14\)</span>로 짝수이므로, 중간에 가까운 두 값인 458과 484를 찾아 평균을 내어 <span class="math inline">\(\tilde{x}=471\)</span>이라는 중앙값을 얻습니다.</p>
<p>349, 432, 433, 433, 440, 440, 458, 484, 497, 500, 508, 526, 531, 548</p>
<p>R에서 평균과 중앙값은 각각 <code>mean</code>과 <code>median</code> 함수를 사용하여 계산됩니다. 아래에서 <code>variable</code>로 명명된 데이터에 대한 평균과 중앙값을 계산하는 코드는 다음과 같습니다.</p>
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb2"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb2-1"><a href="#cb2-1" aria-hidden="true" tabindex="-1"></a><span class="fu">mean</span>(variable)</span>
<span id="cb2-2"><a href="#cb2-2" aria-hidden="true" tabindex="-1"></a><span class="fu">median</span>(variable)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<p>이제 데이터의 중심에 대한 두 가지 요약 수치가 있으므로, 어느 것이 더 나은지라는 타당한 질문이 생길 수 있습니다. 표본 중앙값과 표본 평균 모두 각자가 더 나은 선택이 될 수 있는 속성을 가지고 있습니다. 표본 평균은 로버스트(Robust, 강건한)하지 않은데, 이는 이상치에 민감하다는 것을 의미합니다. 이상치(Outlier)는 데이터셋 내 다른 값들로부터 멀리 떨어져 있는 특이한 포인트입니다. 이에 대해서는 나중에 더 자세히 논의하겠습니다. 표본 내의 단일 값이 이상치가 되도록 변경되면 표본 평균은 급격하게 변할 것입니다. 반면에 표본 중앙값은 로버스트하며, 이는 표본 중앙값이 이상치에 의해 크게 영향을 받지 않음을 의미합니다. 일반적으로 우리는 통계량이 로버스트하기를 원하므로, 이는 중앙값의 장점이 됩니다.</p>
<p>그럼에도 불구하고 일반적으로 변수의 중심을 요약하는 데는 표본 평균을 사용합니다. 그 이유는 평균이 통계적 추론을 하기에 편리한 여러 이론적 속성을 가지고 있기 때문인데, 이는 표본 중앙값보다 훨씬 더 그렇습니다. 이러한 속성들을 지금 논의하지는 않겠지만 나중에 다루겠습니다. 달리 명시되지 않는 한 변수의 중심을 설명하는 데 표본 평균을 사용할 것이라는 점으로 충분합니다.</p>
<section id="연습-문제-1" class="level3">
<h3 class="anchored" data-anchor-id="연습-문제-1">연습 문제</h3>
<p>유명한 통계학자인 윌리엄 고셋(William Gosset)은 두 가지 수면제가 수면 시간 증가에 미치는 영향을 비교한 데이터셋에 대해 주요 분석을 수행했습니다. 두 가지 변수가 수집되었는데, 수면제 X로 인한 수면 시간 증가와 수면제 Y로 인한 수면 시간 증가입니다.</p>
<table class="caption-top table">
<thead>
<tr class="header">
<th>환자</th>
<th>약물 X</th>
<th>약물 Y</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>1</td>
<td>0.7</td>
<td>1.9</td>
</tr>
<tr class="even">
<td>2</td>
<td>−1.6</td>
<td>0.8</td>
</tr>
<tr class="odd">
<td>3</td>
<td>−0.2</td>
<td>1.1</td>
</tr>
<tr class="even">
<td>4</td>
<td>−1.2</td>
<td>0.1</td>
</tr>
<tr class="odd">
<td>5</td>
<td>−0.1</td>
<td>−0.1</td>
</tr>
<tr class="even">
<td>6</td>
<td>3.4</td>
<td>4.4</td>
</tr>
<tr class="odd">
<td>7</td>
<td>3.7</td>
<td>5.5</td>
</tr>
<tr class="even">
<td>8</td>
<td>0.8</td>
<td>1.6</td>
</tr>
<tr class="odd">
<td>9</td>
<td>0.0</td>
<td>4.6</td>
</tr>
<tr class="even">
<td>10</td>
<td>2.0</td>
<td>3.4</td>
</tr>
</tbody>
</table>
<ol start="7" type="1">
<li><span class="math inline">\(x_1\)</span>, <span class="math inline">\(y_8\)</span>, <span class="math inline">\(x_{(2)}\)</span>, <span class="math inline">\(y_{(6)}\)</span>은 무엇입니까?</li>
<li><span class="math inline">\(\bar{y}\)</span>는 무엇입니까?</li>
<li><span class="math inline">\(\tilde{x}\)</span>는 무엇입니까?</li>
</ol>
<p>15개 실험실 그룹이 케일 내 살충제 DDT의 양(ppm 단위)을 조사하고 있었습니다. 15개의 정렬된 측정값은 아래와 같습니다.</p>
<pre class="text"><code>2.79, 2.93, 3.06, 3.07, 3.08, 3.18, 3.22, 3.22, 3.33, 3.34, 3.34, 3.38, 3.56, 3.78, 4.64</code></pre>
<ol start="10" type="1">
<li><span class="math inline">\(DDT_3\)</span>와 <span class="math inline">\(DDT_{14}\)</span>는 무엇입니까?</li>
<li>DDT의 평균인 <span class="math inline">\(\bar{DDT}\)</span>는 무엇입니까?</li>
<li>DDT의 중앙값인 <span class="math inline">\(\tilde{DDT}\)</span>는 무엇입니까?</li>
</ol>
</section>
<section id="변수의-퍼짐" class="level3">
<h3 class="anchored" data-anchor-id="변수의-퍼짐">변수의 퍼짐</h3>
<p>수치형 변수의 두 번째로 중요한 측면은 변수의 퍼짐(Spread)입니다. 두 변수의 중심이 동일하더라도 퍼짐의 정도가 다르면 다른 값을 갖게 됩니다. <span class="math inline">\(x_1=99\)</span>, <span class="math inline">\(x_2=100\)</span>, <span class="math inline">\(x_3=101\)</span>인 변수 X와 <span class="math inline">\(y_1=1\)</span>, <span class="math inline">\(y_2=100\)</span>, <span class="math inline">\(y_3=199\)</span>인 변수 Y를 고려해 보겠습니다. 두 변수 모두 <span class="math inline">\(\bar{x}=\bar{y}=100\)</span>이지만, 퍼짐의 정도가 다르고 값들도 다릅니다. 데이터의 퍼짐을 설명하는 데는 범위를 시작으로 많은 다양한 통계량이 있습니다.</p>
<p>데이터셋의 범위(Range)는 표본 내 변수의 최대값에서 최소값을 뺀 것이며, <span class="math inline">\(x_n - x_{(1)}\)</span>로 나타냅니다. 이는 퍼짐에 대한 간단한 요약이지만 몇 가지 결함이 있습니다. 즉, 범위가 이상치에 대해 로버스트하거나 저항력이 있을까요? 그 이유는 명확합니다. 범위는 최대값 마이너스 최소값이기 때문에, 데이터셋에서 하나의 데이터 포인트가 이상치로 변경되면 범위는 크게 증가할 것입니다.</p>
<p>범위는 R에서 다양한 방법으로 계산할 수 있습니다. 최소값과 최대값을 개별적으로 구한 다음 범위를 계산할 수도 있지만, 더 간단한 방법은 range 함수를 사용하는 것입니다. range 함수는 최소값과 최대값을 모두 반환하므로 범위 계산이 쉬워집니다. table, mean, median과 마찬가지로 변수를 함수에 입력하기만 하면 되며, 다음과 같은 코드를 사용합니다.</p>
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb4"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb4-1"><a href="#cb4-1" aria-hidden="true" tabindex="-1"></a><span class="fu">range</span>(variable)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<p>또 다른 방향으로, 표본 내 개별 값의 퍼짐을 설명하는 방법으로 편차(Deviation, <span class="math inline">\(d_i\)</span>로 표기), 즉 각 관측값과 표본 평균의 차이가 있습니다. 수학적으로 말하면 다음과 같습니다.</p>
<p><span class="math display">\[d_i = x_i - \bar{x}\]</span></p>
<p>편차는 개별 데이터 포인트에 유용하지만, 표본 전체의 변수에 대한 퍼짐을 요약하는 단일 수치를 원합니다. 편차의 요약을 사용하여 퍼짐에 대한 요약을 생성할 수 있습니다. 평균 편차를 사용하여 퍼짐을 설명할 수도 있겠지만, 여기에는 약간의 문제가 있습니다. 구체적으로 평균 편차는 항상 0이 되므로 퍼짐을 설명하기에 부적절합니다. 데이터의 퍼짐을 반영할 수 있는 값을 가진 편차의 다른 요약 방식을 찾아야 합니다.</p>
<p>분산(Variance)이 바로 변수의 퍼짐을 설명하기 위한 요약 방식입니다. 분산은 모집단 또는 표본에 대해 편차 제곱의 평균으로 계산됩니다. 모집단 분산(<span class="math inline">\(\sigma^2\)</span>으로 표기)은 모집단 전체에 대한 편차 제곱의 평균이며, 모든 모수와 마찬가지로 고정되어 있고 알 수 없는 값입니다. 표본 분산(<span class="math inline">\(s^2\)</span>으로 표기)은 모집단 분산을 추정하며 표본 내 편차 제곱의 평균입니다. 수학적으로는 다음과 같습니다.</p>
<p><span class="math display">\[s^2 = \frac{1}{n-1}\sum_{i}(x_i - \bar{x})^2 = \frac{1}{n-1}((x_1 - \bar{x})^2 + \cdots + (x_n - \bar{x})^2)\]</span></p>
<p>편차 제곱의 합을 <span class="math inline">\(n\)</span>이 아닌 <span class="math inline">\(n-1\)</span>로 나누기 때문에 엄밀한 의미에서의 평균은 아님을 알 수 있을 것입니다. 이는 표본 분산을 모집단 분산의 불편 추정량(Unbiased estimator)으로 만들기 위함입니다. 분산과 직접적으로 연관된 것이 표준편차입니다. 표준편차(Standard deviation)는 분산의 제곱근이며, 역시 알 수 없는 모집단 모수(<span class="math inline">\(\sigma\)</span>로 표기)와 표본 통계량(s로 표기)으로 제공됩니다. 따라서 <span class="math inline">\(\sigma=\sqrt{\sigma^2}\)</span>이고 <span class="math inline">\(s=\sqrt{s^2}\)</span>입니다. 표준편차를 알면 분산을 알 수 있고 그 반대도 마찬가지입니다.</p>
<p>R에는 분산과 표준편차를 계산하는 두 가지 간단한 함수인 var와 sd 함수가 각각 있습니다. 평균 및 분산을 구하려는 데이터를 입력하기만 하면 되며, 코드는 다음과 같습니다.</p>
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb5"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb5-1"><a href="#cb5-1" aria-hidden="true" tabindex="-1"></a><span class="fu">var</span>(variable)</span>
<span id="cb5-2"><a href="#cb5-2" aria-hidden="true" tabindex="-1"></a><span class="fu">sd</span>(variable)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<p>표본 분산과 표본 표준편차는 편차 제곱의 함수이기 때문에 항상 0보다 크거나 같습니다. 표본 분산 또는 표본 표준편차가 0이라는 것은 표본의 모든 관측값이 동일한 값을 가진다는 것을 의미합니다. 표본 분산 또는 표준편차가 커질수록 데이터의 퍼짐이 커집니다.</p>
<p>예를 들어, 스위트 브라이어(Sweet Briar) 축구팀은 2017년 시즌 15경기에서 다음과 같은 실점(적은 것부터 많은 것 순)을 기록했습니다. 1, 1, 2, 2, 4, 5, 6, 6, 7, 7, 10, 10, 10, 10, 11. 실점 수의 분산과 표준편차를 구하려면 먼저 표본 평균을 구해야 하며, 이는 <span class="math inline">\(\bar{x}=6.133\)</span>입니다. 그러면 표본 분산은 다음과 같습니다.</p>
<p><span class="math display">\[s^2 = \frac{1}{15-1} \times ((1-6.133)^2 + (1-6.133)^2 + \cdots + (10-6.133)^2 + (11-6.133)^2) = 12.69524\]</span></p>
<p>표본 표준편차는 표본 분산의 제곱근이 되므로 <span class="math inline">\(s=\sqrt{12.69524}=3.563038\)</span>입니다. 분산과 표준편차가 데이터에서 흔히 사용되는 퍼짐의 측도이지만, 둘 다 이상치에 로버스트하지 않습니다. 최대 실점 수를 11에서 50으로 바꾸면 분산과 표준편차는 급격하게 변할 것입니다. 여기서 질문이 생깁니다. 분산이나 표준편차를 대체할 수 있는 로버스트한 퍼짐의 측도가 있을까요?</p>
<p>사분위수 범위(Interquartile Range, IQR)가 바로 데이터셋에서 이상치에 강한 퍼짐의 측도입니다. IQR은 표본의 75번째 백분위수와 25번째 백분위수 사이의 거리로 정의됩니다. 75번째 백분위수는 데이터의 75%가 그 값보다 작은 지점이며, 25번째 백분위수는 데이터의 25%가 그 값보다 작은 지점입니다. 75번째 백분위수를 계산할 때 우리는 본질적으로 데이터셋의 상위 절반의 중앙값을 찾는 것이며, 25번째 백분위수는 데이터셋의 하위 절반의 중앙값입니다.</p>
<p>이제 스위트 브라이어의 실점 데이터를 다시 살펴보겠습니다. 상기하자면 팀은 2017년에 다음과 같은 실점을 기록했습니다. 1, 1, 2, 2, 4, 5, 6, 6, 7, 7, 10, 10, 10, 10, 11. 75번째 및 25번째 백분위수를 찾으려면 데이터셋을 상위 및 하위 절반으로 나누기 위해 먼저 중앙값을 찾아야 합니다. 관측값이 15개이므로 중앙값은 <span class="math inline">\(x_{8}=6\)</span>입니다. 이는 데이터셋을 두 개의 절반으로 나눕니다.</p>
<p>상위 절반: 7, 7, 10, 10, 10, 10, 11 하위 절반: 1, 1, 2, 2, 4, 5, 6</p>
<p>75번째 백분위수는 상위 절반의 중앙값인 $x_{12}=10입니다. 25번째 백분위수는 하위 절반의 중앙값인 <span class="math inline">\(x_{4}=2\)</span>입니다. 따라서 IQR은 10-2=8이 됩니다. R은 IQR을 계산하기 위해 IQR 함수를 사용합니다.</p>
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb6"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb6-1"><a href="#cb6-1" aria-hidden="true" tabindex="-1"></a><span class="fu">IQR</span>(variable)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<p>R은 위와 다른 알고리즘을 사용하여 IQR을 계산하므로, 표본 크기가 작을 때는 손으로 계산한 IQR이 R의 결과와 다른 경우가 많다는 점에 유의해 주시면 좋습니다.</p>
</section>
<section id="연습-문제-2" class="level3">
<h3 class="anchored" data-anchor-id="연습-문제-2">연습 문제</h3>
<p>뉴욕 양키스의 구원 투수 아롤디스 채프먼(Aroldis Chapman)은 일반적으로 야구 역사상 빠른 공을 던지는 투수로 간주되며, 105 MPH를 돌파한 최초의 투수로 알려져 있습니다. 2017년 9월 한 경기 등판에서 그는 다음과 같은 12개의 투구를 했으며, 속도는 변수 x로 저장되었습니다.</p>
<pre class="text"><code>100.7, 102.9, 103.7, 100.6, 99.7, 99.8, 100.7, 100.2, 101.1, 101.9, 102.9, 102.9</code></pre>
<ol start="13" type="1">
<li><span class="math inline">\(\bar{x}\)</span>는 무엇입니까?</li>
<li><span class="math inline">\(\tilde{x}\)</span>는 무엇입니까?</li>
<li><span class="math inline">\(s^2\)</span>는 무엇입니까?</li>
<li>s는 무엇입니까?</li>
<li>IQR은 얼마입니까?</li>
</ol>
<p>심근 산소 소비량은 심장이 최적으로 기능하는 데 얼마나 많은 산소가 필요한지를 나타내는 척도입니다. 일곱 마리의 개가 수의사에게 가서 심근 산소 소비량을 측정하여 변수 x로 기록했습니다.</p>
<p>78, 92, 116, 90, 106, 78, 99</p>
<ol start="18" type="1">
<li><span class="math inline">\(\bar{x}\)</span>는 무엇입니까?</li>
<li><span class="math inline">\(\tilde{x}\)</span>는 무엇입니까?</li>
<li><span class="math inline">\(s^2\)</span>는 무엇입니까?</li>
<li>s는 무엇입니까?</li>
<li>IQR은 얼마입니까?</li>
</ol>
</section>
<section id="시각적-요약" class="level3">
<h3 class="anchored" data-anchor-id="시각적-요약">시각적 요약</h3>
<p>수치형 변수의 마지막 측면은 변수의 값 분포 모양(Shape)입니다. 모양을 설명하기 위해 계산할 수 있는 수치적 통계량도 있지만, 우리는 주로 시각적 요약을 통해 이를 조사합니다. 우리의 목적을 위해 일반적인 요약 방식 중 하나인 히스토그램에 집중할 것입니다.</p>
<p>히스토그램(Histogram)은 수치 값들을 가져와서 빈(bin)이라고 불리는 동일한 크기의 구간에 배치함으로써 수치 값 분포의 모양을 시각적으로 표시하는 데 도움을 줍니다. 그런 다음 히스토그램은 막대를 사용하여 각 빈의 도수를 그래프로 나타냅니다.</p>
<p>2017년 주지사 선거에서 애머스트 카운티(Amherst County)에는 보고해야 할 11개의 선거구가 있었습니다. 각 구역의 투표율은 다음과 같았습니다.</p>
<table class="caption-top table">
<thead>
<tr class="header">
<th>선거구</th>
<th>투표율</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>1</td>
<td>0.409</td>
</tr>
<tr class="even">
<td>2</td>
<td>0.427</td>
</tr>
<tr class="odd">
<td>3</td>
<td>0.439</td>
</tr>
<tr class="even">
<td>4</td>
<td>0.477</td>
</tr>
<tr class="odd">
<td>5</td>
<td>0.461</td>
</tr>
<tr class="even">
<td>6</td>
<td>0.475</td>
</tr>
<tr class="odd">
<td>7</td>
<td>0.524</td>
</tr>
<tr class="even">
<td>8</td>
<td>0.52</td>
</tr>
<tr class="odd">
<td>9</td>
<td>0.445</td>
</tr>
<tr class="even">
<td>10</td>
<td>0.363</td>
</tr>
<tr class="odd">
<td>11</td>
<td>0.399</td>
</tr>
</tbody>
</table>
<p>히스토그램을 만들려면 빈의 크기를 결정해야 합니다. 이 데이터의 경우 0.35에서 0.4, 0.4에서 0.45, 0.45에서 0.5, 0.5에서 0.55까지의 구간을 사용할 수 있습니다. 첫 번째 빈에는 두 개의 관측값이 있고, 두 번째 빈에는 네 개, 세 번째 빈에는 세 개, 네 번째 빈에는 두 개의 관측값이 있습니다. R은 히스토그램을 생성하기 위해 hist 함수를 사용합니다. 기본적인 히스토그램은 데이터만 입력하여 생성할 수 있습니다.</p>
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb8"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb8-1"><a href="#cb8-1" aria-hidden="true" tabindex="-1"></a><span class="fu">hist</span>(variable)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<p>히스토그램을 그릴 때 데이터에 대한 정보를 알려주는 몇 가지 사항을 찾아야 합니다. 첫 번째는 히스토그램의 모양으로, 대칭(Symmetric) 또는 왜곡된(Skewed, 비대칭) 모양입니다. 대칭 히스토그램은 이름이 의미하는 바와 같이 데이터가 중앙값을 기준으로 양쪽으로 고르게 나뉘고 동일한 모양을 하고 있는 것입니다. 단, 대칭 히스토그램이 완벽하게 대칭일 필요는 없으며 대략적으로 그러하면 됩니다. 왜곡된 히스토그램은 비대칭 히스토그램이며 오른쪽 또는 왼쪽으로 왜곡될 수 있는데, 왜곡의 방향은 데이터의 긴 꼬리가 있는 쪽입니다.</p>
<p>두 번째로 볼 것은 히스토그램에서 모드(Mode, 최빈값) 또는 국소적 높은 지점의 개수입니다. 흔한 모드의 개수는 하나(단봉, Unimodal)와 둘(쌍봉, Bimodal)입니다. 아주 드문 경우에 삼봉(Trimodal) 히스토그램을 볼 수도 있습니다. 가까이 있는 모드들은 값이 어떻게 빈으로 묶이느냐에 따라 실제로는 하나의 모드일 수도 있습니다.</p>
<p>마지막으로 볼 세 가지 사항은 데이터의 중심이 위치한 곳, 데이터가 얼마나 퍼져 있는지, 그리고 이상치가 있는지 여부입니다. 일반적으로 중심과 퍼짐을 설명하기 위해 표본 평균과 표본 분산을 사용하지만, 이상치는 어떻게 식별할까요? 우리는 여러 번 다양한 통계량과 요약이 이상치에 민감하다고 언급했지만, 잠재적 이상치를 식별하는 방법에 대해서는 이야기하지 않았습니다. 데이터 포인트가 확실하게 이상치인지 반드시 알 수 있는 것은 아니기 때문에 잠재적이라는 표현을 사용했습니다.</p>
</section>
</section>
<section id="이상치-식별" class="level2">
<h2 class="anchored" data-anchor-id="이상치-식별">이상치 식별</h2>
<p>이상치를 식별하는 첫 번째 가능성은 히스토그램을 통한 시각적 방법입니다. 데이터의 정상적인 영역 밖에 존재하는 명확한 데이터 포인트가 있다면, 그 데이터 포인트가 이상치일 가능성이 높습니다.</p>
<p>이러한 시각적 방법이 유용할 수 있지만, 관측값이 잠재적 이상치인지 여부를 판단하기 위해 일반적으로 더 엄격하고 정량적인 것을 원합니다. 이를 염두에 두고 잠재적 이상치를 식별하기 위해 소위 Z-점수(Z-score, <span class="math inline">\(z_i\)</span>로 표기)를 사용할 수 있습니다. 관측값에 대한 Z-점수는 관측값과 표본 평균의 차이를 표본 표준편차로 나눈 값입니다. 즉, 다음과 같습니다.</p>
<p><span class="math display">\[z_i = \frac{x_i - \bar{x}}{s}\]</span></p>
<p>일반적인 아이디어는 관측값이 이상치라면 평균에서 멀리 떨어져 있을 것이고, 따라서 큰 양수 또는 작은 음수의 Z-점수를 가질 것이라는 점입니다. 일반적으로 |<span class="math inline">\(z_i\)</span>|&gt;3라면, 즉 관측값이 평균에서 표준편차의 3배보다 더 떨어져 있다면, 해당 관측값을 잠재적 이상치로 표시합니다.</p>
<p>예를 들어, 평균적으로 올드 페이스풀(Old Faithful) 간헐천은 분출 사이에 72.31분의 간격이 있으며 표준편차는 13.89분입니다. 만약 여러분이 분출을 2시간 동안 기다리고 있었다면, 이 관측값은 이상치일 가능성이 있을까요? 그렇습니다. 2시간의 대기는 (120−72.31)/13.89=3.43이라는 Z-점수를 가지며, 이는 절대값이 3보다 크기 때문입니다.</p>
<p>Z-점수가 이상치를 식별하는 데 유용할 수 있지만, 큰 주의 사항이 있습니다. Z-점수는 종 모양(Bell-shaped) 데이터에 대해서만 이상치를 식별하는 데 사용될 수 있다는 것입니다. 종 모양 데이터는 궁극적으로 통계학에서 중요한 특정 유형의 대칭 데이터이며, 나중에 과정에서 논의하겠습니다.</p>
<p>데이터셋이 종 모양이 아니라면 Z-점수를 사용하여 이상치를 식별할 수 없는데, 이는 궁극적으로 Z-점수 계산이 유효하려면 종 모양 데이터를 필요로 하기 때문입니다. 많은 데이터셋이 종 모양이 아닐 것이므로, 잠재적 이상치를 식별하기 위한 다른 방법이 필요합니다.</p>
<p>그러한 방법은 사분위수 범위를 사용하여 찾을 수 있습니다. 75번째 백분위수(제3사분위수 또는 Q3라고도 함)와 25번째 백분위수(제1사분위수 또는 Q1라고도 함)를 찾으면, 사분위수 범위를 IQR=Q3−Q1로 계산합니다. 그런 다음 관측값이 다음과 같은 경우 잠재적 이상치로 표시할 수 있습니다.</p>
<p><span class="math display">\[x_i&gt;Q_3+1.5×IQR \text{ 또는 } x_i&lt;Q_1−1.5×IQR.\]</span></p>
<p>여기서의 일반적인 아이디어는 Z-점수와 유사합니다. 관측값이 데이터의 대다수가 위치한 곳(여기서는 제1사분위수에서 제3사분위수까지로 정의됨)에서 특히 멀리 떨어져 있다면 이상치일 가능성이 높습니다. Z-점수 방법과 IQR 방법의 주요 차이점은 IQR은 종 모양 데이터를 요구하지 않으며, 로버스트하지 않은 표본 평균과 표본 표준편차 대신 로버스트한 IQR에 의존한다는 것입니다. 하지만 두 방법 모두 용도가 있으며 하나를 선택해야 하는 경우가 있습니다.</p>
<p>올드 페이스풀 데이터의 히스토그램을 만들어 보면 그것이 심한 비종모양(Non-bell shaped)임을 알 수 있을 것입니다. 이를 염두에 두고 이상치를 식별하기 위해 IQR을 사용해야 합니다. 75번째 백분위수(또는 제3사분위수)는 82이고 25번째 백분위수(제1사분위수)는 58이므로, IQR은 82−58=24입니다. 이는 82+24×1.5=118보다 크거나 58−24×1.5=22보다 작은 데이터 포인트가 이상치임을 의미합니다. 따라서 2시간을 기다렸다면 이는 여전히 이상치가 될 것입니다.</p>
<section id="연습-문제-3" class="level3">
<h3 class="anchored" data-anchor-id="연습-문제-3">연습 문제</h3>
<p>찰스 다윈(Charles Darwin)은 동일한 조건에서 자란 자가 수분 및 타가 수분 옥수수 식물 쌍 사이의 성장 차이를 연구했습니다. 키의 차이(타가 수분 마이너스 자가 수분)가 측정되었으며, 다음과 같은 15개의 데이터 포인트가 기록되었습니다[83].</p>
<pre class="text"><code>6.125, −8.375, 1.000, 2.000, 0.750, 2.875, 3.500, 5.125, 1.750, 3.625, 7.000, 3.000, 9.375, 7.500, −6.000</code></pre>
<ol start="23" type="1">
<li>Z-점수를 사용할 때 데이터에 이상치가 있을까요?</li>
<li>IQR을 사용할 때 데이터에 이상치가 있을까요?</li>
</ol>
<p>앨버트 A. 마이컬슨(Albert A. Michelson)은 빛의 속도를 추정하는 데 도움을 준 실험을 수행한 폴란드계 물리학자였습니다. 아래의 20개 관측값은 그러한 실험 중 하나의 결과이며, 측정된 변수는 299,000km를 초과하는 km/s 단위의 빛의 속도입니다.</p>
<pre class="text"><code>850, 850, 1000, 810, 960, 800, 830, 830, 880, 720, 880, 840, 890, 770, 910, 720, 890, 810, 870, 940</code></pre>
<ol start="25" type="1">
<li>Z-점수를 사용할 때 데이터에 이상치가 있을까요?</li>
<li>IQR을 사용할 때 데이터에 이상치가 있을까요?</li>
</ol>
<p>히스토그램의 속성을 설명하는 것은 단일 수치형 변수를 이해하는 데 도움이 됩니다.</p>
<ol start="27" type="1">
<li>아래 히스토그램의 모양, 모드, 중심, 이상치 등을 설명하시오.</li>
</ol>
</section>
</section>
<section id="변수-간의-관계-탐색" class="level2">
<h2 class="anchored" data-anchor-id="변수-간의-관계-탐색">변수 간의 관계 탐색</h2>
<p>단일 변수를 살펴보는 많은 분석을 할 수 있지만, 통계학의 많은 질문은 두 변수 사이의 관계를 살펴보겠습니다. 성별이 급여에 어떤 영향을 미치는지, 연봉이 정치적 성향에 어떤 영향을 미치는지 등을 살펴볼 수 있습니다. 이러한 경우 우리는 설명 변수와 반응 사이의 연관성(Association)을 찾고 있는 것입니다. 반응 변수(Response)는 관심 변수로, 우리가 궁극적으로 예측하거나 비교하고자 하는 것입니다. 설명 변수(Explanatory variable, 때로는 예측 변수라고 함)는 반응 변수를 설명하거나 예측하기를 기대하는 변수입니다. 마지막으로 두 변수 간의 연관성은 두 변수 사이의 관계로, 설명 변수의 값이 반응 변수의 특정 값을 가질 가능성을 더 높게 만드는 것을 의미합니다.</p>
<p>예를 들어, 한 연구자가 어떤 사료가 어린 닭의 몸무게를 많이 증가시키는지 조사하고 있다고 해 보겠습니다. 연구자는 각 닭을 네 가지 사료 중 하나에 무작위로 배정하고, 실험 전과 사료를 먹인 지 60일이 지난 후의 몸무게를 측정하여 그 차이를 계산합니다. 이 실험에서 설명 변수와 반응 변수는 무엇입니까? 반응 변수는 몸무게의 변화이고 설명 변수는 사료입니다.</p>
<p>우리는 분할표를 사용하여 두 범주형 변수 간의 연관성을 조사했지만, 이제부터는 범주형 설명 변수와 수치형 반응 변수에 대한 탐색적 분석을 살펴보고, 이어서 두 수치형 변수 간의 연관성을 살펴보겠습니다.</p>
<section id="범주형-설명-변수와-수치형-반응-변수" class="level3">
<h3 class="anchored" data-anchor-id="범주형-설명-변수와-수치형-반응-변수">범주형 설명 변수와 수치형 반응 변수</h3>
<p>범주형 설명 변수와 수치형 반응 변수 사이의 관계를 살펴볼 때 갈 수 있는 경로는 많습니다. 단순히 범주형 설명 변수의 수준(Level)에 따라 표본 평균이나 표본 중앙값을 비교하여 주요 차이점을 찾는 것부터 시작할 수 있습니다. 이것은 반응 변수의 가변성(Variability)을 고려하지 않으므로, 이를 그림에 포함시켜야 합니다.</p>
<p>이러한 관계를 탐색하는 방법은 많지만, 우리는 시각적 비교, 구체적으로 상자 그림에 집중할 것입니다. 상자 그림(Boxplot)은 여러 그룹 간에 반응 변수가 겹치는 부분이 있는지 시각적으로 확인할 수 있게 해주며, 단일 변수를 시각화하는 데에도 사용될 수 있습니다. 상자 그림은 기본적으로 변수의 다섯 수 요약(Five number summary, 5NS)을 시각적으로 나타낸 것입니다. 다섯 수 요약은 변수 값에 대한 간단한 요약으로 최소값, 최대값, 중앙값, 제1사분위수(Q1, 25번째 백분위수), 제3사분위수(Q3, 75번째 백분위수)로 구성됩니다. 다시 말하지만, 상자 그림은 이 다섯 수 요약을 시각적으로 플로팅한 것일 뿐이며 단계는 간단합니다.</p>
<ol type="1">
<li>다섯 수 요약을 계산합니다.</li>
<li>사분위수 범위(IQR)를 사용하여 이상치가 있는지 확인합니다.</li>
<li>수직선 위에 제1사분위수(Q1), 중앙값, 제3사분위수(Q3)에 세 개의 수직선을 그립니다. 이 세 선으로 상자를 형성합니다.</li>
<li>Q1에서 이상치가 아닌 작은 값까지 수평선을 그립니다.</li>
<li>Q3에서 이상치가 아닌 큰 값까지 수평선을 그립니다.</li>
<li>모든 이상치를 기호로 표시합니다.</li>
</ol>
<p>R은 다섯 수 요약을 계산하기 위해 summary 함수를 사용합니다. 이 함수는 또한 표본 평균과 결측 데이터 포인트가 있는 경우 그 개수도 반환합니다.</p>
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb11"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb11-1"><a href="#cb11-1" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(variable)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<p>소프트커버 교재 표본의 페이지 수를 나타내는 다음 데이터셋을 고려해 보겠습니다. 203, 336, 378, 385, 417, 436, 469, 585. 시작하기 위해 다섯 수 요약을 만들어야 하며, 이는 최소값=103, 최대값=585, 중앙값=401, Q1=357, Q3=452.5가 될 것입니다. 다음으로 IQR을 사용하여 이상치를 식별해야 합니다. IQR은 452.5−357=95.5입니다. 이는 452.5+1.5×95.5=595.75보다 크거나 357−1.5×95=213.75보다 작은 데이터 포인트가 이상치임을 의미합니다. 따라서 203이라는 이상치가 하나 있습니다. 다음으로 Q1, 중앙값, Q3에 세 개의 수직선을 배치하고 그 선들로 상자를 만듭니다. 다음 두 단계에서는 이상치가 아닌 데이터 값 중 크고 작은 값까지 선을 그립니다. 마지막으로 이상치 포인트를 원하는 기호로 표시합니다.</p>
<p>개별 상자 그림을 생성하는 것 외에도, 상자 그림을 나란히 배치하여 범주형 설명 변수의 두 개 이상의 범주를 비교할 수 있습니다. 두 상자 그림 사이에 상당한 겹침이 있다면 설명 변수와 반응 변수 사이에 연관성이 없을 가능성이 높습니다. 겹치는 부분이 없다면 연관성이 있을 가능성이 있습니다.</p>
<p>R의 boxplot 함수를 사용하면 개별 상자 그림과 병렬 상자 그림을 모두 생성할 수 있습니다. 이 함수의 세부 사항은 기본적인 상자 그림은 다음을 사용하여 생성할 수 있습니다.</p>
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb12"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb12-1"><a href="#cb12-1" aria-hidden="true" tabindex="-1"></a><span class="fu">boxplot</span>(variable)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</section>
<section id="연습-문제-4" class="level3">
<h3 class="anchored" data-anchor-id="연습-문제-4">연습 문제</h3>
<ol start="28" type="1">
<li>다음 데이터(배리 본즈의 한 시즌 고의 사구 횟수)가 주어졌을 때, 상자 그림을 생성하시오</li>
</ol>
<pre class="text"><code>2, 3, 3, 9, 14, 15, 18, 22, 22, 22, 25, 29, 30, 32, 34, 35, 38, 43, 43, 61, 68, 120</code></pre>
<ol start="29" type="1">
<li>에드거 앤더슨(Edgar Anderson)의 붓꽃(iris) 데이터셋[20]은 중요한 역사적 통계 데이터셋 중 하나입니다. 두 붓꽃 종의 꽃받침(sepal) 길이에 대한 다음 다섯 수 요약(이상치 없음)이 주어졌을 때, 상자 그림을 생성하시오.</li>
</ol>
<table class="caption-top table">
<thead>
<tr class="header">
<th>종</th>
<th>최소값</th>
<th>Q1</th>
<th>중앙값</th>
<th>Q3</th>
<th>최대값</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>세토사(Setosa)</td>
<td>4.3</td>
<td>4.8</td>
<td>5</td>
<td>5.2</td>
<td>5.8</td>
</tr>
<tr class="even">
<td>버시컬러(Versicolor)</td>
<td>4.9</td>
<td>5.6</td>
<td>5.9</td>
<td>6.3</td>
<td>7.0</td>
</tr>
</tbody>
</table>
<ol start="30" type="1">
<li>종과 꽃받침 길이 사이에 연관성이 있는 것으로 보일까요?</li>
</ol>
</section>
</section>
<section id="두-수치형-변수-간의-연관성-탐색" class="level2">
<h2 class="anchored" data-anchor-id="두-수치형-변수-간의-연관성-탐색">두 수치형 변수 간의 연관성 탐색</h2>
<p>범주형 설명 변수와 수치형 반응 변수 사이의 연관성을 탐색하는 것 외에도, 두 수치형 변수 사이의 연관성을 조사할 수 있습니다. 여전히 설명 변수와 반응 변수가 있으며, 우리의 목표는 여전히 둘 사이의 연관성을 찾는 것입니다. 하지만 이제 설명 변수가 수치형이므로 이 연관성을 조사하는 방법이 달라질 것입니다.</p>
<p>두 수치형 변수 사이의 연관성을 조사하는 첫 번째 방법은 산점도를 사용하여 플로팅하는 것입니다. 산점도(Scatterplot)는 설명 변수(X)와 반응 변수(Y)의 모든 쌍을 데카르트 평면 위에 (x,y) 쌍으로 플로팅한 그림입니다.</p>
<p>plot 함수를 사용하면 두 변수에 대한 산점도를 생성할 수 있습니다. 다른 시나리오에서 plot을 사용하면 산점도 이외의 그래픽이 생성될 수도 있지만, 아래 코드를 사용하면 variable1이 x좌표가 되고 variable2가 y좌표가 되는 간단한 산점도를 생성할 수 있습니다.</p>
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb14"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb14-1"><a href="#cb14-1" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(variable1, variable2)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<p>히스토그램을 사용하여 변수의 모양을 고려할 때와 마찬가지로, 산점도에서도 찾아야 할 구체적인 것들이 있습니다. 첫 번째로 볼 것은 데이터의 어떤 패턴입니다. 이것은 선형(Linear), 이차(Quadratic) 또는 우리가 생각할 수 있는 다른 어떤 패턴일 수도 있습니다.</p>
<p>두 번째로, 설명 변수와 반응 변수 사이에 증가하는 관계 또는 감소하는 관계가 있는지 확인합니다. 증가한다는 것은 설명 변수가 커짐에 따라 반응 변수도 커지는 것을 의미합니다. 반면에 감소한다는 것은 설명 변수가 커짐에 따라 반응 변수가 작아지는 것을 의미합니다.</p>
<p>세 번째로 볼 것은 설명 변수나 반응 변수에서의 특이 사항, 특히 이상치입니다. 이러한 이상치의 존재는 우리의 결과를 급격하게 변화시키거나 잠재적으로 무효화할 수 있습니다. 다른 특이 사항으로는 설명 변수나 반응 변수, 혹은 둘 다에서의 군집(Cluster)이 포함될 수 있습니다.</p>
<p>마지막으로, 설명 변수와 반응 변수 사이의 관계가 선형이라고 가정할 때 연관성이 얼마나 강한지 확인합니다. 설명 변수와 반응 변수 사이의 연관성이 강할수록 산점도는 직선에 훨씬 더 가깝게 보이며, 약한 연관성은 산점도가 무작위로 흩어진 것처럼 보이게 합니다.</p>
<p>설명 변수와 반응 변수 사이의 연관성 강도를 나타내는 데 “강하다”와 “약하다”를 사용하는 것은 주관적이고 모호할 수 있습니다. 이 연관성을 설명하기 위해 더 좋은 방법, 구체적으로 표본에서 계산할 수 있는 통계량이 필요합니다.</p>
<p>변수 간의 연관성을 설명하는 이 더 좋은 방법이 상관계수(Correlation)입니다. 이는 모집단 모수(ρ, 모집단 전체에 대해 두 수치형 변수 사이의 고정되고 알 수 없는 실제 상관관계)와 표본 통계량(r, 표본에서 계산된 두 수치형 변수 사이의 상관관계)으로 존재합니다. 상관계수는 두 변수 사이의 연관성 강도뿐만 아니라 설명 변수와 반응 변수 사이 관계의 방향(증가/감소)을 모두 요약할 수 있습니다.</p>
<p>상관계수는 궁극적으로 문제의 두 변수에 대한 Z-점수 곱의 평균입니다. 즉, 다음과 같습니다.</p>
<p><span class="math display">\[r = \frac{1}{n-1} \sum_{i=1}^{n} \left( \frac{x_i - \bar{x}}{s_x} \right) \left( \frac{y_i - \bar{y}}{s_y} \right)\]</span></p>
<p>여기서 <span class="math inline">\(\bar{x}\)</span>와 <span class="math inline">\(\bar{y}\)</span>는 <span class="math inline">\(x\)</span>와 <span class="math inline">\(y\)</span>의 표본 평균이고, <span class="math inline">\(s_x\)</span>와 <span class="math inline">\(s_y\)</span>는 <span class="math inline">\(x\)</span>와 <span class="math inline">\(y\)</span>의 표본 표준편차입니다. 따라서 상관계수를 손으로 계산하려면 다음 단계를 따릅니다.</p>
<ol type="1">
<li>x와 y의 표본 평균을 계산합니다.</li>
<li>x와 y의 표본 표준편차를 계산합니다.</li>
<li>x의 각 관측값에 대한 Z-점수를 계산합니다.</li>
<li>y의 각 관측값에 대한 Z-점수를 계산합니다.</li>
<li>각 관측값에 대해 x의 Z-점수와 y의 Z-점수를 곱합니다.</li>
<li>곱해진 모든 Z-점수를 더하고 표본 크기 n 마이너스 1로 나눕니다.</li>
</ol>
<p>1980년대의 한 농업 연구자는 파종 밀도가 작물 수확량에 미치는 영향을 조사하고 있었습니다. 그는 다양한 파종 밀도로 밭을 심고 결과 수확량을 기록했습니다.</p>
<table class="caption-top table">
<thead>
<tr class="header">
<th>파종 밀도</th>
<th>보리 이삭당 알곡 수</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>50</td>
<td>21.2</td>
</tr>
<tr class="even">
<td>75</td>
<td>19.9</td>
</tr>
<tr class="odd">
<td>100</td>
<td>19.2</td>
</tr>
<tr class="even">
<td>125</td>
<td>18.4</td>
</tr>
<tr class="odd">
<td>150</td>
<td>17.9</td>
</tr>
</tbody>
</table>
<p>상관계수를 구하려면 먼저 파종 밀도(100)와 수확량 무게(19.32)의 표본 평균을 구해야 합니다. 다음으로 파종 밀도(39.53)와 수확량 무게(1.29)의 표본 표준편차가 필요합니다. 그런 다음 Z-점수를 계산하고 함께 곱해야 합니다.</p>
<table class="caption-top table">
<thead>
<tr class="header">
<th>관측치</th>
<th>파종 밀도 Z-점수</th>
<th>수확량 무게 Z-점수</th>
<th>곱해진 Z-점수</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>1</td>
<td>−1.26</td>
<td>1.45</td>
<td>−1.83</td>
</tr>
<tr class="even">
<td>2</td>
<td>−0.63</td>
<td>0.45</td>
<td>−0.28</td>
</tr>
<tr class="odd">
<td>3</td>
<td>0.00</td>
<td>−0.09</td>
<td>0.00</td>
</tr>
<tr class="even">
<td>4</td>
<td>0.63</td>
<td>−1.71</td>
<td>−0.45</td>
</tr>
<tr class="odd">
<td>5</td>
<td>1.26</td>
<td>−1.09</td>
<td>−1.38</td>
</tr>
</tbody>
</table>
<p>마지막으로 세 번째 열의 모든 값을 더하고 5−1=4로 나누어 상관계수 −3.94/4=−0.985를 얻습니다.</p>
<p>보시다시피 이 과정은 손으로 하기 지루합니다. 따라서 우리는 종종 R의 cor 함수를 사용합니다. 상관시키고자 하는 두 변수가 주어지면 이 함수는 위에서 계산한 것과 같은 상관계수를 반환할 것입니다.</p>
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb15"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb15-1"><a href="#cb15-1" aria-hidden="true" tabindex="-1"></a><span class="fu">cor</span>(variable1, variable2)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<p>표본 상관계수 r은 먼저 관계의 방향을 알려주는데, r이 양수이면 두 변수 사이에 증가하는 관계가 있음을 의미합니다. r은 −1과 1 사이의 값을 가지며, 두 변수 사이 연관성의 강도도 알려줄 수 있습니다. |r|이 1에 가까우면 두 변수 사이에 강한 관계가 있음을 의미하며, |r|이 0에 가까우면 변수들 사이의 관계가 약하다는 것을 의미합니다.</p>
<p>상관관계를 다룰 때 두 가지 주요 주의 사항이 있습니다. 첫 번째는 상관계수가 두 변수 사이의 선형 관계에 대해서만 유효하고 해석 가능하다는 것입니다. 관심 있는 두 변수가 이차, 삼차, 지수 등 다른 관계를 가지고 있다면 상관계수를 해석할 수 없으며 계산된 값은 유효하지 않습니다. 또한 상관계수는 로버스트한 통계량이 아니므로 어느 한 변수의 이상치가 상관계수 값에 강한 영향을 미칩니다.</p>
<p>두 번째 주의 사항은 두 변수가 연관되어 있습니다(또는 상관계수가 높습니다)는 것이 한 변수가 다른 변수를 유발한다는 것을 의미하지 않는다는 점입니다. 다른 식으로 말하면, 상관관계는 인과관계를 의미하지 않습니다(Correlation does not imply causation). 인과관계(Causation)를 확립할 수 있는 유일한 방법은 앞서 논의한 것과 같은 설계된 실험뿐입니다. 증거를 위해 인과관계가 없을 가능성이 높지만 고도로 상관된 변수 쌍의 사례들로 가득 찬 ‘허위 상관(Spurious Correlations)’ 웹사이트를 방문해 보길 권합니다. 예를 들어 버지니아주의 결혼율은 1인당 고과당 옥수수 시럽 소비량과 믿을 수 없을 정도로 높게 상관되어 있지만(r=0.982), 버지니아주의 높은 결혼율이 옥수수 시럽의 1인당 소비량을 증가시킬 것이라고는 전혀 기대할 수 없습니다. 또 다른 예로, 버지니아주의 변호사 수는 마가린의 1인당 소비량과 믿을 수 없을 정도로 높게 상관되어 있지만(r=−0.946), 버지니아주의 많은 변호사 수가 마가린의 1인당 소비량을 감소시킬 것이라고는 전혀 기대할 수 없습니다. 여기서의 교훈은 다시 한번 말하지만, 상관관계는 인과관계를 의미하지 않는다는 것입니다.</p>
<p>궁극적으로 두 수치형 변수 사이의 연관성을 살펴볼 때는 산점도와 상관계수를 모두 사용하여 설명 변수와 반응 변수의 관계를 이해해야 합니다. 더 나아가, 데이터가 허용하는 것 이상으로 주장하지 않도록 상당한 상식(Common sense)을 발휘해야 합니다.</p>
<section id="연습-문제-5" class="level3">
<h3 class="anchored" data-anchor-id="연습-문제-5">연습 문제</h3>
<ol start="31" type="1">
<li><p>아래에 주어진 산점도를 패턴, 방향 등의 관점에서 설명하시오.</p></li>
<li><p>다음 데이터가 주어졌을 때, 두 변수 사이의 상관계수를 계산하시오.</p></li>
</ol>
<table class="caption-top table">
<thead>
<tr class="header">
<th>월드 시리즈 총 득점</th>
<th>도쿄 디즈니랜드 방문객 수(백만 명)</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>39</td>
<td>13.906</td>
</tr>
<tr class="even">
<td>39</td>
<td>14.293</td>
</tr>
<tr class="odd">
<td>59</td>
<td>13.646</td>
</tr>
<tr class="even">
<td>41</td>
<td>14.452</td>
</tr>
<tr class="odd">
<td>68</td>
<td>13.996</td>
</tr>
<tr class="even">
<td>22</td>
<td>14.847</td>
</tr>
</tbody>
</table>
<ol start="33" type="1">
<li>신발 한 켤레의 각 신발에 대한 마모량을 나타내는 다음 데이터가 주어졌을 때, 두 변수 사이의 상관계수를 계산하시오.</li>
</ol>
<table class="caption-top table">
<thead>
<tr class="header">
<th>신발 A</th>
<th>신발 B</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>13.2</td>
<td>14.0</td>
</tr>
<tr class="even">
<td>8.2</td>
<td>8.8</td>
</tr>
<tr class="odd">
<td>10.9</td>
<td>11.2</td>
</tr>
<tr class="even">
<td>14.3</td>
<td>14.2</td>
</tr>
<tr class="odd">
<td>10.7</td>
<td>11.8</td>
</tr>
<tr class="even">
<td>6.6</td>
<td>6.4</td>
</tr>
<tr class="odd">
<td>9.5</td>
<td>9.8</td>
</tr>
<tr class="even">
<td>10.8</td>
<td>11.3</td>
</tr>
<tr class="odd">
<td>8.8</td>
<td>9.3</td>
</tr>
<tr class="even">
<td>13.3</td>
<td>13.6</td>
</tr>
</tbody>
</table>
</section>
</section>
<section id="탐색적-분석을-의사결정으로-연결하기" class="level2">
<h2 class="anchored" data-anchor-id="탐색적-분석을-의사결정으로-연결하기">탐색적 분석을 의사결정으로 연결하기</h2>
<p>탐색적 데이터 분석은 그래프와 요약 통계를 많이 만드는 절차가 아니라, 다음 분석에서 무엇을 조심해야 하는지 결정하는 절차입니다. 평균과 중앙값이 크게 다르면 분포의 비대칭성을 의심해야 하고, 표준 편차가 집단마다 크게 다르면 이후 평균 비교에서 등분산 가정을 그대로 둘 수 없습니다. 산점도에서 곡선 패턴이 보이면 단순한 선형 관계로 요약하는 것이 위험할 수 있습니다.</p>
<p>따라서 EDA를 수행할 때에는 결과를 다음과 같은 판단 문장으로 정리하는 습관이 필요합니다.</p>
<ol type="1">
<li>이 변수는 어떤 중심과 산포를 보입니까?</li>
<li>극단값은 측정 오류입니까, 아니면 중요한 사례입니까?</li>
<li>집단 간 비교에서 분포의 형태가 비슷합니까?</li>
<li>두 양적 변수의 관계는 선형으로 볼 수 있습니까?</li>
<li>다음 장의 추론 절차가 요구하는 가정을 위협하는 특징이 있습니까?</li>
</ol>
<p>예를 들어 의료 데이터에서 치료 전후 혈압의 평균 차이가 작더라도 일부 환자에게 큰 변화가 집중되어 있을 수 있습니다. 이때 평균만 보고 치료 효과가 없다고 말하면 중요한 하위 집단을 놓칠 수 있습니다. 반대로 야구 타자의 타율처럼 많은 관측에서 누적되는 지표는 몇 경기의 극단적 결과보다 시즌 전체의 산포와 안정성을 함께 봐야 합니다. EDA는 이러한 맥락을 통계적 추론 전에 드러내는 안전장치입니다.</p>


</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
  window.document.addEventListener("DOMContentLoaded", function (event) {
    const icon = "";
    const anchorJS = new window.AnchorJS();
    anchorJS.options = {
      placement: 'right',
      icon: icon
    };
    anchorJS.add('.anchored');
    const isCodeAnnotation = (el) => {
      for (const clz of el.classList) {
        if (clz.startsWith('code-annotation-')) {                     
          return true;
        }
      }
      return false;
    }
    const onCopySuccess = function(e) {
      // button target
      const button = e.trigger;
      // don't keep focus
      button.blur();
      // flash "checked"
      button.classList.add('code-copy-button-checked');
      var currentTitle = button.getAttribute("title");
      button.setAttribute("title", "Copied!");
      let tooltip;
      if (window.bootstrap) {
        button.setAttribute("data-bs-toggle", "tooltip");
        button.setAttribute("data-bs-placement", "left");
        button.setAttribute("data-bs-title", "Copied!");
        tooltip = new bootstrap.Tooltip(button, 
          { trigger: "manual", 
            customClass: "code-copy-button-tooltip",
            offset: [0, -8]});
        tooltip.show();    
      }
      setTimeout(function() {
        if (tooltip) {
          tooltip.hide();
          button.removeAttribute("data-bs-title");
          button.removeAttribute("data-bs-toggle");
          button.removeAttribute("data-bs-placement");
        }
        button.setAttribute("title", currentTitle);
        button.classList.remove('code-copy-button-checked');
      }, 1000);
      // clear code selection
      e.clearSelection();
    }
    const getTextToCopy = function(trigger) {
      const outerScaffold = trigger.parentElement.cloneNode(true);
      const codeEl = outerScaffold.querySelector('code');
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
    const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
      text: getTextToCopy
    });
    clipboard.on('success', onCopySuccess);
    if (window.document.getElementById('quarto-embedded-source-code-modal')) {
      const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
        text: getTextToCopy,
        container: window.document.getElementById('quarto-embedded-source-code-modal')
      });
      clipboardModal.on('success', onCopySuccess);
    }
      var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
      var mailtoRegex = new RegExp(/^mailto:/);
        var filterRegex = new RegExp('/' + window.location.host + '/');
      var isInternal = (href) => {
          return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
      }
      // Inspect non-navigation links and adorn them if external
     var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
      for (var i=0; i<links.length; i++) {
        const link = links[i];
        if (!isInternal(link.href)) {
          // undo the damage that might have been done by quarto-nav.js in the case of
          // links that we want to consider external
          if (link.dataset.originalHref !== undefined) {
            link.href = link.dataset.originalHref;
          }
        }
      }
    function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
      const config = {
        allowHTML: true,
        maxWidth: 500,
        delay: 100,
        arrow: false,
        appendTo: function(el) {
            return el.parentElement;
        },
        interactive: true,
        interactiveBorder: 10,
        theme: 'quarto',
        placement: 'bottom-start',
      };
      if (contentFn) {
        config.content = contentFn;
      }
      if (onTriggerFn) {
        config.onTrigger = onTriggerFn;
      }
      if (onUntriggerFn) {
        config.onUntrigger = onUntriggerFn;
      }
      window.tippy(el, config); 
    }
    const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
    for (var i=0; i<noterefs.length; i++) {
      const ref = noterefs[i];
      tippyHover(ref, function() {
        // use id or data attribute instead here
        let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
        try { href = new URL(href).hash; } catch {}
        const id = href.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note) {
          return note.innerHTML;
        } else {
          return "";
        }
      });
    }
    const xrefs = window.document.querySelectorAll('a.quarto-xref');
    const processXRef = (id, note) => {
      // Strip column container classes
      const stripColumnClz = (el) => {
        el.classList.remove("page-full", "page-columns");
        if (el.children) {
          for (const child of el.children) {
            stripColumnClz(child);
          }
        }
      }
      stripColumnClz(note)
      if (id === null || id.startsWith('sec-')) {
        // Special case sections, only their first couple elements
        const container = document.createElement("div");
        if (note.children && note.children.length > 2) {
          container.appendChild(note.children[0].cloneNode(true));
          for (let i = 1; i < note.children.length; i++) {
            const child = note.children[i];
            if (child.tagName === "P" && child.innerText === "") {
              continue;
            } else {
              container.appendChild(child.cloneNode(true));
              break;
            }
          }
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(container);
          }
          return container.innerHTML
        } else {
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(note);
          }
          return note.innerHTML;
        }
      } else {
        // Remove any anchor links if they are present
        const anchorLink = note.querySelector('a.anchorjs-link');
        if (anchorLink) {
          anchorLink.remove();
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        if (note.classList.contains("callout")) {
          return note.outerHTML;
        } else {
          return note.innerHTML;
        }
      }
    }
    for (var i=0; i<xrefs.length; i++) {
      const xref = xrefs[i];
      tippyHover(xref, undefined, function(instance) {
        instance.disable();
        let url = xref.getAttribute('href');
        let hash = undefined; 
        if (url.startsWith('#')) {
          hash = url;
        } else {
          try { hash = new URL(url).hash; } catch {}
        }
        if (hash) {
          const id = hash.replace(/^#\/?/, "");
          const note = window.document.getElementById(id);
          if (note !== null) {
            try {
              const html = processXRef(id, note.cloneNode(true));
              instance.setContent(html);
            } finally {
              instance.enable();
              instance.show();
            }
          } else {
            // See if we can fetch this
            fetch(url.split('#')[0])
            .then(res => res.text())
            .then(html => {
              const parser = new DOMParser();
              const htmlDoc = parser.parseFromString(html, "text/html");
              const note = htmlDoc.getElementById(id);
              if (note !== null) {
                const html = processXRef(id, note);
                instance.setContent(html);
              } 
            }).finally(() => {
              instance.enable();
              instance.show();
            });
          }
        } else {
          // See if we can fetch a full url (with no hash to target)
          // This is a special case and we should probably do some content thinning / targeting
          fetch(url)
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.querySelector('main.content');
            if (note !== null) {
              // This should only happen for chapter cross references
              // (since there is no id in the URL)
              // remove the first header
              if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
                note.children[0].remove();
              }
              const html = processXRef(null, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      }, function(instance) {
      });
    }
        let selectedAnnoteEl;
        const selectorForAnnotation = ( cell, annotation) => {
          let cellAttr = 'data-code-cell="' + cell + '"';
          let lineAttr = 'data-code-annotation="' +  annotation + '"';
          const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
          return selector;
        }
        const selectCodeLines = (annoteEl) => {
          const doc = window.document;
          const targetCell = annoteEl.getAttribute("data-target-cell");
          const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
          const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
          const lines = annoteSpan.getAttribute("data-code-lines").split(",");
          const lineIds = lines.map((line) => {
            return targetCell + "-" + line;
          })
          let top = null;
          let height = null;
          let parent = null;
          if (lineIds.length > 0) {
              //compute the position of the single el (top and bottom and make a div)
              const el = window.document.getElementById(lineIds[0]);
              top = el.offsetTop;
              height = el.offsetHeight;
              parent = el.parentElement.parentElement;
            if (lineIds.length > 1) {
              const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
              const bottom = lastEl.offsetTop + lastEl.offsetHeight;
              height = bottom - top;
            }
            if (top !== null && height !== null && parent !== null) {
              // cook up a div (if necessary) and position it 
              let div = window.document.getElementById("code-annotation-line-highlight");
              if (div === null) {
                div = window.document.createElement("div");
                div.setAttribute("id", "code-annotation-line-highlight");
                div.style.position = 'absolute';
                parent.appendChild(div);
              }
              div.style.top = top - 2 + "px";
              div.style.height = height + 4 + "px";
              div.style.left = 0;
              let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
              if (gutterDiv === null) {
                gutterDiv = window.document.createElement("div");
                gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
                gutterDiv.style.position = 'absolute';
                const codeCell = window.document.getElementById(targetCell);
                const gutter = codeCell.querySelector('.code-annotation-gutter');
                gutter.appendChild(gutterDiv);
              }
              gutterDiv.style.top = top - 2 + "px";
              gutterDiv.style.height = height + 4 + "px";
            }
            selectedAnnoteEl = annoteEl;
          }
        };
        const unselectCodeLines = () => {
          const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
          elementsIds.forEach((elId) => {
            const div = window.document.getElementById(elId);
            if (div) {
              div.remove();
            }
          });
          selectedAnnoteEl = undefined;
        };
          // Handle positioning of the toggle
      window.addEventListener(
        "resize",
        throttle(() => {
          elRect = undefined;
          if (selectedAnnoteEl) {
            selectCodeLines(selectedAnnoteEl);
          }
        }, 10)
      );
      function throttle(fn, ms) {
      let throttle = false;
      let timer;
        return (...args) => {
          if(!throttle) { // first call gets through
              fn.apply(this, args);
              throttle = true;
          } else { // all the others get throttled
              if(timer) clearTimeout(timer); // cancel #2
              timer = setTimeout(() => {
                fn.apply(this, args);
                timer = throttle = false;
              }, ms);
          }
        };
      }
        // Attach click handler to the DT
        const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
        for (const annoteDlNode of annoteDls) {
          annoteDlNode.addEventListener('click', (event) => {
            const clickedEl = event.target;
            if (clickedEl !== selectedAnnoteEl) {
              unselectCodeLines();
              const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
              if (activeEl) {
                activeEl.classList.remove('code-annotation-active');
              }
              selectCodeLines(clickedEl);
              clickedEl.classList.add('code-annotation-active');
            } else {
              // Unselect the line
              unselectCodeLines();
              clickedEl.classList.remove('code-annotation-active');
            }
          });
        }
    const findCites = (el) => {
      const parentEl = el.parentElement;
      if (parentEl) {
        const cites = parentEl.dataset.cites;
        if (cites) {
          return {
            el,
            cites: cites.split(' ')
          };
        } else {
          return findCites(el.parentElement)
        }
      } else {
        return undefined;
      }
    };
    var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
    for (var i=0; i<bibliorefs.length; i++) {
      const ref = bibliorefs[i];
      const citeInfo = findCites(ref);
      if (citeInfo) {
        tippyHover(citeInfo.el, function() {
          var popup = window.document.createElement('div');
          citeInfo.cites.forEach(function(cite) {
            var citeDiv = window.document.createElement('div');
            citeDiv.classList.add('hanging-indent');
            citeDiv.classList.add('csl-entry');
            var biblioDiv = window.document.getElementById('ref-' + cite);
            if (biblioDiv) {
              citeDiv.innerHTML = biblioDiv.innerHTML;
            }
            popup.appendChild(citeDiv);
          });
          return popup.innerHTML;
        });
      }
    }
  });
  </script>
<nav class="page-navigation">
  <div class="nav-page nav-page-previous">
      <a href="../notes/ch05.html" class="pagination-link" aria-label="데이터 불러오기">
        <i class="bi bi-arrow-left-short"></i> <span class="nav-page-text">데이터 불러오기</span>
      </a>          
  </div>
  <div class="nav-page nav-page-next">
  </div>
</nav>
</div> <!-- /content -->




</body></html>