<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.9.38">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>두 모수에 대한 신뢰 구간 – R과 데이터 분석 입문</title>
<style>
/* Default styles provided by pandoc.
** See https://pandoc.org/MANUAL.html#variables-for-html for config info.
*/
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
html { -webkit-text-size-adjust: 100%; }
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="../site_libs/quarto-nav/quarto-nav.js"></script>
<script src="../site_libs/quarto-nav/headroom.min.js"></script>
<script src="../site_libs/clipboard/clipboard.min.js"></script>
<script src="../site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="../site_libs/quarto-search/fuse.min.js"></script>
<script src="../site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="../">
<script src="../site_libs/quarto-html/quarto.js" type="module"></script>
<script src="../site_libs/quarto-html/tabsets/tabsets.js" type="module"></script>
<script src="../site_libs/quarto-html/popper.min.js"></script>
<script src="../site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="../site_libs/quarto-html/anchor.min.js"></script>
<link href="../site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="../site_libs/quarto-html/quarto-syntax-highlighting-15634bcf2e68342d4ad2dfa704d543f6.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="../site_libs/bootstrap/bootstrap.min.js"></script>
<link href="../site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="../site_libs/bootstrap/bootstrap-cf5ee1d16def7895729d1ac812351ea4.min.css" rel="stylesheet" append-hash="true" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "sidebar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "start",
  "type": "textbox",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>

  <script src="https://cdnjs.cloudflare.com/polyfill/v3/polyfill.min.js?features=es6"></script>
  <script defer="" src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

<script type="text/javascript">
const typesetMath = (el) => {
  if (window.MathJax) {
    // MathJax Typeset
    window.MathJax.typeset([el]);
  } else if (window.katex) {
    // KaTeX Render
    var mathElements = el.getElementsByClassName("math");
    var macros = [];
    for (var i = 0; i < mathElements.length; i++) {
      var texText = mathElements[i].firstChild;
      if (mathElements[i].tagName == "SPAN" && texText && texText.data) {
        window.katex.render(texText.data, mathElements[i], {
          displayMode: mathElements[i].classList.contains('display'),
          throwOnError: false,
          macros: macros,
          fleqn: false
        });
      }
    }
  }
}
window.Quarto = {
  typesetMath
};
</script>

<meta property="og:title" content="두 모수에 대한 신뢰 구간 – R과 데이터 분석 입문">
<meta property="og:description" content="">
<meta property="og:site_name" content="R과 데이터 분석 입문">
<meta name="twitter:title" content="두 모수에 대한 신뢰 구간 – R과 데이터 분석 입문">
<meta name="twitter:description" content="">
<meta name="twitter:card" content="summary">
</head>

<body class="nav-sidebar docked quarto-light">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
  <nav class="quarto-secondary-nav">
    <div class="container-fluid d-flex">
      <button type="button" class="quarto-btn-toggle btn" data-bs-toggle="collapse" role="button" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
        <i class="bi bi-layout-text-sidebar-reverse"></i>
      </button>
        <nav class="quarto-page-breadcrumbs" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item">
      R과 데이터 분석 입문
      </li></ol></nav>
        <a class="flex-grow-1" role="navigation" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">      
        </a>
      <button type="button" class="btn quarto-search-button" aria-label="Search" onclick="window.quartoOpenSearch();">
        <i class="bi bi-search"></i>
      </button>
    </div>
  </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article">
<!-- sidebar -->
  <nav id="quarto-sidebar" class="sidebar collapse collapse-horizontal quarto-sidebar-collapse-item sidebar-navigation docked overflow-auto">
    <div class="pt-lg-2 mt-2 text-left sidebar-header">
    <div class="sidebar-title mb-0 py-0">
      <a href="../">R과 데이터 분석 입문</a> 
        <div class="sidebar-tools-main">
  <a href="" class="quarto-reader-toggle quarto-navigation-tool px-1" onclick="window.quartoToggleReader(); return false;" title="Toggle reader mode">
  <div class="quarto-reader-toggle-btn">
  <i class="bi"></i>
  </div>
</a>
</div>
    </div>
      </div>
        <div class="mt-2 flex-shrink-0 align-items-center">
        <div class="sidebar-search">
        <div id="quarto-search" class="" title="Search"></div>
        </div>
        </div>
    <div class="sidebar-menu-container"> 
    <ul class="list-unstyled mt-1">
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">R 언어</span></a>
  </div>
</li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-1" role="navigation" aria-expanded="false">
 <span class="menu-text">R과 데이터 분석</span></a>
          <a class="sidebar-item-toggle text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-1" role="navigation" aria-expanded="false" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-1" class="collapse list-unstyled sidebar-section depth1 ">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../notes/ch01.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">통계학의 중요성!</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../notes/ch02.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">R 입문</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../notes/ch03.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">데이터 수집</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../notes/ch04.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">데이터 추출</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../notes/ch05.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">데이터 불러오기</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../notes/ch06.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">탐색적 데이터 분석</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../notes/ch07.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">탐색적 분석(실습)</span></a>
  </div>
</li>
      </ul>
  </li>
    </ul>
    </div>
</nav>
<div id="quarto-sidebar-glass" class="quarto-sidebar-collapse-item" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item"></div>
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">On this page</h2>
   
  <ul>
  <li><a href="#p_1---p_2에-대한-신뢰-구간" id="toc-p_1---p_2에-대한-신뢰-구간" class="nav-link active" data-scroll-target="#p_1---p_2에-대한-신뢰-구간"><span class="header-section-number">1</span> <span class="math inline">\(p_1 - p_2\)</span>에 대한 신뢰 구간</a>
  <ul class="collapse">
  <li><a href="#연습-문제" id="toc-연습-문제" class="nav-link" data-scroll-target="#연습-문제"><span class="header-section-number">1.1</span> 연습 문제</a></li>
  </ul></li>
  <li><a href="#mu_1-mu_2에-대한-신뢰-구간" id="toc-mu_1-mu_2에-대한-신뢰-구간" class="nav-link" data-scroll-target="#mu_1-mu_2에-대한-신뢰-구간"><span class="header-section-number">2</span> <span class="math inline">\(\mu_1\)</span> − <span class="math inline">\(\mu_2\)</span>에 대한 신뢰 구간</a>
  <ul class="collapse">
  <li><a href="#합동-분산" id="toc-합동-분산" class="nav-link" data-scroll-target="#합동-분산"><span class="header-section-number">2.1</span> 합동 분산</a></li>
  <li><a href="#이분산" id="toc-이분산" class="nav-link" data-scroll-target="#이분산"><span class="header-section-number">2.2</span> 이분산</a></li>
  <li><a href="#해석-및-예제" id="toc-해석-및-예제" class="nav-link" data-scroll-target="#해석-및-예제"><span class="header-section-number">2.3</span> 해석 및 예제</a></li>
  <li><a href="#연습-문제-1" id="toc-연습-문제-1" class="nav-link" data-scroll-target="#연습-문제-1"><span class="header-section-number">2.4</span> 연습 문제</a></li>
  </ul></li>
  <li><a href="#mu_d에-대한-신뢰-구간" id="toc-mu_d에-대한-신뢰-구간" class="nav-link" data-scroll-target="#mu_d에-대한-신뢰-구간"><span class="header-section-number">3</span> <span class="math inline">\(\mu_D\)</span>에 대한 신뢰 구간</a>
  <ul class="collapse">
  <li><a href="#연습-문제-2" id="toc-연습-문제-2" class="nav-link" data-scroll-target="#연습-문제-2"><span class="header-section-number">3.1</span> 연습 문제</a></li>
  </ul></li>
  <li><a href="#mu_1---mu_2-mu_d에-대한-신뢰-구간과-가설-검정" id="toc-mu_1---mu_2-mu_d에-대한-신뢰-구간과-가설-검정" class="nav-link" data-scroll-target="#mu_1---mu_2-mu_d에-대한-신뢰-구간과-가설-검정"><span class="header-section-number">4</span> <span class="math inline">\(\mu_1\)</span> - <span class="math inline">\(\mu_2\)</span>, <span class="math inline">\(\mu_D\)</span>에 대한 신뢰 구간과 가설 검정</a>
  <ul class="collapse">
  <li><a href="#연습-문제-3" id="toc-연습-문제-3" class="nav-link" data-scroll-target="#연습-문제-3"><span class="header-section-number">4.1</span> 연습 문제</a></li>
  </ul></li>
  <li><a href="#두-모수-신뢰-구간의-실질적-해석" id="toc-두-모수-신뢰-구간의-실질적-해석" class="nav-link" data-scroll-target="#두-모수-신뢰-구간의-실질적-해석"><span class="header-section-number">5</span> 두 모수 신뢰 구간의 실질적 해석</a></li>
  <li><a href="#두-모수-신뢰-구간-추정" id="toc-두-모수-신뢰-구간-추정" class="nav-link" data-scroll-target="#두-모수-신뢰-구간-추정"><span class="header-section-number">6</span> 두 모수 신뢰 구간 추정</a></li>
  </ul>
</nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">두 모수에 대한 신뢰 구간</h1>
</div>



<div class="quarto-title-meta">

    
  
    
  </div>
  


</header>


<blockquote class="blockquote">
<p>최근 생성형 AI 모델의 답변 품질을 비교하거나 A/B 테스트 결과를 다루는 데이터 파이프라인에서도 이러한 신뢰 구간 추정은 필수적인 역할을 수행합니다. 이번 장에서는 구간을 유도하고 해석하는 방법뿐만 아니라, 타당한 값의 범위를 제공하는 것 이상으로 뻗어 나가는 신뢰 구간의 다양한 응용 사례를 살펴보겠습니다.</p>
</blockquote>
<p>단일 표본 가설 검정을 처음 소개할 때, 단일 표본에 관한 통계적 추론(statistical inference)의 유일한 형태는 아니라고 언급했습니다. 관심 모수(parameter)에 대해 타당한 값의 범위를 제공하는 신뢰 구간(confidence interval) 또한 각 가설 검정에 대응하는 강력하고 유효한 추론 도구입니다.</p>
<p>두 표본 검정의 경우에도 마찬가지입니다. 두 모집단 평균(population mean)이 서로 다른지 검정했던 것처럼, 두 모집단 비율(population proportion)의 차이, 두 모집단 평균의 차이, 또는 쌍체 평균(paired mean) 간의 차이에 대해서도 타당한 값의 범위를 추정할 수 있습니다.</p>
<section id="p_1---p_2에-대한-신뢰-구간" class="level2" data-number="1">
<h2 data-number="1" class="anchored" data-anchor-id="p_1---p_2에-대한-신뢰-구간"><span class="header-section-number">1</span> <span class="math inline">\(p_1 - p_2\)</span>에 대한 신뢰 구간</h2>
<p>두 비율에 대한 신뢰 구간을 계산할 때, 우리는 두 모집단 비율 <span class="math inline">\(p_1\)</span>과 <span class="math inline">\(p_2\)</span> 사이의 관계에 관한 핵심 정보를 담은 단일 구간을 얻고자 합니다. 각 모수에 대해 개별적으로 신뢰 구간을 계산하는 방법은 이미 익혔지만, 이는 두 구간 사이의 상대적 관계에 대해서는 어떠한 정보도 제공하지 않습니다.</p>
<p>그러나 이 두 모수를 비교 검정했던 방식과 유사하게 접근하면 우리의 목표를 달성할 수 있습니다. 두 표본 비율 검정에서 비율을 개별적으로 검증하는 대신 비율의 차이 <span class="math inline">\(p_1 - p_2\)</span>를 직접 검정했습니다. 신뢰 구간 역시 같은 논리로 <span class="math inline">\(p_1 - p_2\)</span>에 대한 <span class="math inline">\((1 - \alpha)\)</span> 100% 신뢰 구간을 생성할 것입니다. 이 구간은 <span class="math inline">\(p_1\)</span>과 <span class="math inline">\(p_2\)</span> 사이의 격차를 알려주며, 그 차이에 대한 타당한 값의 범위를 제시합니다.</p>
<p>이전과 마찬가지로 우리의 목표는 다음 확률을 만족하는 <span class="math inline">\((\text{하한}, \text{상한})\)</span> 형태의 <span class="math inline">\(p_1 - p_2\)</span> 구간을 찾는 것입니다.</p>
<p><span class="math display">\[
P(\text{Lower} &lt; p_1 - p_2 &lt; \text{Upper}) = 1 - \alpha
\]</span></p>
<p>이 구간을 얻기 위해서는 중심 극한 정리(central limit theorem)가 제공하는 확률 분포와 약간의 대수학이 필요합니다. p에 대한 신뢰 구간을 생성할 때, 확률 분포의 기초를 표준 정규 분포(standard normal distribution)에 두었습니다.</p>
<p>중심 극한 정리가 원시 데이터를 이 분포와 자연스럽게 연결해 주었기 때문에 이는 매우 탁월한 선택이었습니다. 두 비율에 대한 구간을 다룰 때도 표준 정규 분포는 출발점으로서 훌륭한 역할을 합니다. 먼저 다음과 같은 임계값(critical value) <span class="math inline">\(z^*\)</span>를 선택해 보겠습니다. 이 확률 문구를 잠시 머릿속에 간직해 두십시오.</p>
<p><span class="math display">\[
P(-z^* &lt; N(0,1) &lt; z^*) = 1 - \alpha
\]</span></p>
<p>다음으로, 중심 극한 정리와 정규 분포의 수학적 성질을 활용하여 관측 데이터와 모수 <span class="math inline">\(p_1\)</span> 및 <span class="math inline">\(p_2\)</span>를 표준 정규 분포와 연결할 고리를 찾아야 합니다. 이전의 구간 추정 및 가설 검정에서 수행했던 방식 그대로 진행하겠습니다. 중심 극한 정리에 따르면, 표본 크기(sample size)가 충분히 크고 성공과 실패 사례가 충분히 수집된다면, 두 표본 비율(sample proportion) <span class="math inline">\(\hat{p}_1\)</span>과 <span class="math inline">\(\hat{p}_2\)</span>는 각각 독립적으로 실제 모집단 비율 <span class="math inline">\(p_1\)</span>과 <span class="math inline">\(p_2\)</span>를 중심으로 하는 정규 분포를 형성합니다.</p>
<p><span class="math display">\[
\begin{aligned}
\hat{p}_1&amp;\sim N(p_1, p_1(1-p_1)/n_1) \\
\hat{p}_2&amp;\sim N(p_2, p_2(1-p_2)/n_2)
\end{aligned}
\]</span></p>
<p>현재 우리의 관심사는 <span class="math inline">\(p_1 - p_2\)</span>에 대한 구간입니다. 이를 염두에 두고 <span class="math inline">\(\hat{p}_1 - \hat{p}_2\)</span>의 분포 형태를 탐구해 보겠습니다. 독립적인 두 표본 비율의 차이를 구하면, 그 분포 역시 <span class="math inline">\(p_1 - p_2\)</span>를 중심으로 하는 새로운 정규 분포가 됩니다.</p>
<p><span class="math display">\[
\begin{aligned}
\hat{p}_1-\hat{p}_2 &amp; \sim N(p_1-p_2, \frac{p_1(1-p_1)}{n_1} + \frac{p_2(1-p_2)}{n_2})
\end{aligned}
\]</span></p>
<p>이는 <span class="math inline">\(\hat{p}_1 - \hat{p}_2\)</span>의 표준 오차(standard error)가 <span class="math inline">\(p_1(1-p_1)n_1+p_2(1-p_2)n_2\)</span>임을 의미합니다. 이 표준 오차의 정확한 값을 도출하려면 <span class="math inline">\(p_1\)</span>과 <span class="math inline">\(p_2\)</span>의 참값을 알아야 하지만, 둘 다 알 수 없는 모수이므로 이는 현실적으로 불가능합니다. 따라서 표준 오차를 계산하기 위해 각 모집단 비율에 대한 실증적 추정치(estimate)를 대입해야 합니다. 이 추정치는 각 표본에서 구한 표본 비율이 되며, <span class="math inline">\(p_1\)</span> 대신 <span class="math inline">\(\hat{p}_1\)</span>을, <span class="math inline">\(p_2\)</span> 대신 <span class="math inline">\(\hat{p}_2\)</span>를 대입합니다.</p>
<p>이제 <span class="math inline">\(\hat{p}_1 - \hat{p}_2\)</span>의 분포가 정규 분포임이 입증되었으므로, 평균 <span class="math inline">\(p_1 - p_2\)</span>를 빼고 추정된 표준 오차로 나누어 이를 표준 정규 분포로 변환할 수 있습니다.</p>
<p><span class="math display">\[
\begin{aligned}
\hat{p}_1-\hat{p}_2-(p_1-p_2)&amp;\sim N\left(0,\frac{p_1(1-p_1)}{n_1}+\frac{p_2(1-p_2)}{n_2}\right)
\end{aligned}
\]</span></p>
<p>이 수식 전체가 표준 정규 분포를 따르므로, 앞서 설정해 둔 초기 확률 문구의 표준 정규 분포 자리에 이를 그대로 대입할 수 있습니다. 그렇게 하면 해당 확률 문구는 다음과 같이 전개됩니다.</p>
<p><span class="math display">\[
P(-z^*&lt;\hat{p}_1-\hat{p}_2-(p_1-p_2)\sqrt{\frac{\hat{p}_1(1-\hat{p}_1)}{n_1}+\frac{\hat{p}_2(1-\hat{p}_2)}{n_2}}&lt;z^*)=1-\alpha
\]</span></p>
<p>이제 <span class="math inline">\((1-\alpha)\)</span> 100% 신뢰 구간을 구하려면 위 부등식을 가져와 <span class="math inline">\(p_1-p_2\)</span>를 기준으로 다시 풀어내야 합니다. 이 과정에서 약간의 대수학이 요구되며, 그 결과 우리가 그토록 원했던 확률적 특성을 지닌 신뢰 구간 공식이 탄생합니다.</p>
<p><span class="math display">\[
\begin{aligned}
&amp;P(-z^*&lt;\hat{p}_1-\hat{p}_2-(p_1-p_2)\sqrt{\frac{\hat{p}_1(1-\hat{p}_1)}{n_1}+\frac{\hat{p}_2(1-\hat{p}_2)}{n_2}}&lt;z^*)\\
&amp;=P(\hat{p}_1-\hat{p}_2-z^*\sqrt{\frac{\hat{p}_1(1-\hat{p}_1)}{n_1}+\frac{\hat{p}_2(1-\hat{p}_2)}{n_2}}&lt;p_1-p_2&lt;\hat{p}_1-\hat{p}_2+z^*\sqrt{\frac{\hat{p}_1(1-\hat{p}_1)}{n_1}+\frac{\hat{p}_2(1-\hat{p}_2)}{n_2}})
\end{aligned}
\]</span></p>
<p>이것이 바로 <span class="math inline">\(p_1-p_2\)</span>에 대한 <span class="math inline">\((1-\alpha)\)</span> 100% 신뢰 구간입니다. 우리는 이 구간이 실제 <span class="math inline">\(p_1-p_2\)</span> 값을 포괄할 것이라고 <span class="math inline">\((1-\alpha)\)</span> 100% 확신합니다(다시 말해, 우리의 추정이 맞을 것이라고 강하게 확신합니다). 이전과 마찬가지로 <span class="math inline">\(P(-z^*&lt;N(0,1)&lt;z^*)=1-\alpha\)</span>를 만족하는 <span class="math inline">\(z^*\)</span>를 직접 구하는 것은 복잡하므로, 대신 <span class="math inline">\(P(N(0,1)&lt;z^*)=1-\alpha/2\)</span>를 만족하는 <span class="math inline">\(z^*\)</span>를 찾습니다. 여기서 <span class="math inline">\(\alpha\)</span>는 연구자가 설정한 신뢰 수준(confidence level)에서 파생됩니다.</p>
<p><span class="math display">\[
\hat{p}_1-\hat{p}_2±z^*\sqrt{\frac{\hat{p}_1(1-\hat{p}_1)}{n_1}+\frac{\hat{p}_2(1-\hat{p}_2)}{n_2}}
\]</span></p>
<p>여기서 <span class="math inline">\(\hat{p}_1\)</span>과 <span class="math inline">\(\hat{p}_2\)</span>는 표본 비율이고, <span class="math inline">\(n_1\)</span>과 <span class="math inline">\(n_2\)</span>는 각 표본의 크기이며, <span class="math inline">\(z^*\)</span>는 대수적으로 도출한 임계값입니다. 실제 분석 환경에서는 R의 <code>qnorm</code> 함수 등을 사용하여 임계값 <span class="math inline">\(z^*\)</span>를 손쉽게 찾을 것입니다.</p>
<p>이 신뢰 구간 공식에서는 가설 검정에서 핵심적인 역할을 했던 합동 비율(pooled proportion)이 등장하지 않는다는 사실을 눈치채셨을 것입니다. 이러한 차이는 가설 검정과 신뢰 구간의 근본적인 가정 차이로 명쾌하게 설명할 수 있습니다. 가설 검정에서는 귀무 가설(null hypothesis)이 참이라고 가정하며, 이는 <span class="math inline">\(p_1=p_2=p\)</span>임을 뜻하므로 전체 데이터를 모아 공통 비율 p를 추정하는 합동 비율이 반드시 필요했습니다. 반면 신뢰 구간 추정에서는 애초에 참이라고 전제할 귀무 가설이 존재하지 않으므로, 억지로 공통 비율을 추정할 이유가 없습니다.</p>
<p>이 신뢰 구간은 철저히 중심 극한 정리의 결과에 의존하므로, 구간의 통계적 유효성을 담보하기 위해서는 중심 극한 정리의 기본 가정이 반드시 충족되어야 합니다. 두 개의 표본 비율 <span class="math inline">\(\hat{p}_1\)</span>과 <span class="math inline">\(\hat{p}_2\)</span>를 다루고 있으므로 가정이 두 표본 모두에서 완벽히 충족되어야 합니다. 이는 두 표본의 크기가 모두 충분히 커야 하며(일반적으로 <span class="math inline">\(n_1\ge 30\)</span> 및 <span class="math inline">\(n_2\ge 30\)</span>), 두 집단 모두에서 성공과 실패 횟수가 넉넉하게(보통 각각 최소 10개 이상) 관찰되어야 함을 뜻합니다. 최근 대규모 데이터셋을 다루는 AI 분석 자동화 도구들 역시 내부적으로 이러한 조건을 꼼꼼히 점검한 뒤 신뢰 구간을 제공합니다.</p>
<p>실제 사례를 통해 이 과정을 살펴보겠습니다. 2018년 수행된 한 설문 조사에서 퓨 리서치(Pew Research) 그룹은 743명의 십 대와 1,058명의 성인에게 “휴대폰 사용에 많은 시간을 보내십니까?”라는 질문을 던졌습니다 [65]. 십 대 중 401명과 성인 중 381명이 “그렇다”고 답했습니다. 십 대와 성인의 실제 비율 <span class="math inline">\(p_{Teen}\)</span>과 <span class="math inline">\(p_{Adult}\)</span> 사이의 차이에 대해 98% 신뢰 구간을 생성해 보겠습니다.</p>
<p>신뢰 구간의 공식 요소를 채우려면 각 표본 비율, 표본 크기 및 임계값이 필요합니다. 두 그룹의 표본 비율은 <span class="math inline">\(\hat{p}_{Teen}=401/743=0.5397\)</span> 및 <span class="math inline">\(\hat{p}_{Adult}=381/1058=0.3601\)</span>입니다. 표본 크기는 <span class="math inline">\(n_{Teen}=743\)</span> 및 <span class="math inline">\(n_{Adult}=1058\)</span>이 됩니다. 이제 남은 것은 임계값 <span class="math inline">\(z^*\)</span>를 찾는 작업입니다. 신뢰 수준이 98%이므로 <span class="math inline">\(\alpha\)</span> 수준은 <span class="math inline">\(\alpha=0.02\)</span>이며, 따라서 <span class="math inline">\(P(N(0,1)&lt;z^*)=1-0.02/2=0.99\)</span>를 만족하는 값을 선택해야 합니다. <code>qnorm(0.99, mean = 0, sd = 1)</code> 코드를 실행하여 임계값 <span class="math inline">\(z^*=2.326348\)</span>를 얻습니다. 따라서 <span class="math inline">\(p_{Teen}-p_{Adult}\)</span>에 대한 98% 신뢰 구간은 다음과 같이 계산됩니다.</p>
<p><span class="math display">\[
\begin{aligned}
&amp;\hat{p}_{Teen}-\hat{p}_{Adult}±z^*\sqrt{\frac{\hat{p}_{Teen}(1-\hat{p}_{Teen})}{n_{Teen}}+\frac{\hat{p}_{Adult}(1-\hat{p}_{Adult})}{n_{Adult}}} \\
&amp;=0.5397-0.3601±2.326348\sqrt{\frac{0.5397(1-0.5397)}{743}+\frac{0.3601(1-0.3601)}{1058}} \\
&amp;=0.1796±2.326348(0.0271)\ &amp;=0.1796±0.0629\cr &amp;=0.1249,0.2343
\end{aligned}
\]</span></p>
<p>결론적으로 우리는 구간 <span class="math inline">\((0.1249, 0.2343)\)</span>이 <span class="math inline">\(p_{Teen}-p_{Adult}\)</span>의 실제 차이값을 확고히 포함한다고 98% 확신합니다.</p>
<p>R의 <code>prop.test</code> 함수를 활용하면 <span class="math inline">\(p_1-p_2\)</span>에 대한 신뢰 구간을 매우 간편하게 도출할 수 있습니다. 함수의 <code>conf.level</code> 옵션을 통해 원하는 신뢰 수준을 지정하기만 하면 R이 알아서 관심 있는 신뢰 구간을 계산하여 출력합니다. 이에 관한 더 자세한 내용과 응용 예제는 <a href="ch17.md">제17장</a>에 상세히 소개되어 있습니다.</p>
<section id="연습-문제" class="level3" data-number="1.1">
<h3 data-number="1.1" class="anchored" data-anchor-id="연습-문제"><span class="header-section-number">1.1</span> 연습 문제</h3>
<ol type="1">
<li><p>2018년 한 여론 조사에서 대학 학위를 소지한 미국인 2,500명 중 1,750명이 거대 기술(Tech) 기업의 제품과 서비스가 사회에 “나쁜 영향보다는 긍정적인 영향을 미쳤다”고 평가한 반면, 대학 학위가 없는 미국인 2,082명 중에서는 1,228명이 유사하게 답했습니다. <span class="math inline">\(p_{College}-p_{NoCollege}\)</span>에 대한 96% 신뢰 구간을 산출하고 그 의미를 해석해 보십시오.</p></li>
<li><p>한 의료 데이터 연구자가 당뇨병 투병 여부에 따른 심근경색(Myocardial infarction) 여성 환자의 사망률 차이를 분석하고자 합니다. 코호트 추적 결과, 당뇨병을 앓고 있는 여성 248명 중 70명이 심근경색으로 사망한 반면, 당뇨병이 없는 여성 978명 중에서는 189명이 심근경색으로 사망한 것으로 나타났습니다. <span class="math inline">\(p_{Diabetes}-p_{NoDiabetes}\)</span>에 대한 80% 신뢰 구간을 도출하고 해석해 보십시오.</p></li>
<li><p>난민 위원회(Refugee board)에 의해 비자 신청이 거부된 난민 사건의 경우, 신청인은 해당 결정의 번복을 위해 연방 법원에 공식 항소할 수 있습니다. 이러한 상황에서는 독립적인 평가자가 배정되어 사건의 타당성을 재검토합니다. 캐나다의 사법 시스템상 사건이 발생한 주에 따라 프랑스어나 영어로 변론이 진행됩니다. 분석 결과 영어로 변론된 253건 중 86건의 항소가 인용된 반면, 프랑스어로 변론된 131건 중 44건의 항소가 인용되었습니다. <span class="math inline">\(p_{French}-p_{English}\)</span>에 대한 95% 신뢰 구간을 계산하고 해석해 보십시오. (여기서 <span class="math inline">\(p\)</span>는 성공적인 항소의 실제 모집단 비율입니다.)</p></li>
</ol>
</section>
</section>
<section id="mu_1-mu_2에-대한-신뢰-구간" class="level2" data-number="2">
<h2 data-number="2" class="anchored" data-anchor-id="mu_1-mu_2에-대한-신뢰-구간"><span class="header-section-number">2</span> <span class="math inline">\(\mu_1\)</span> − <span class="math inline">\(\mu_2\)</span>에 대한 신뢰 구간</h2>
<p><span class="math inline">\(p_1-p_2\)</span>에 대한 신뢰 구간의 원리와 동일하게, <span class="math inline">\(\mu_1-\mu_2\)</span>에 대한 <span class="math inline">\((1-\alpha)\)</span> 100% 신뢰 구간은 두 모집단 평균 <span class="math inline">\(\mu_1\)</span>과 <span class="math inline">\(\mu_2\)</span> 사이의 차이에 관해 타당한 값의 범위를 강력하게 제시합니다. 이를 통해 해당 구간은 두 연속형 모수 사이의 본질적 관계에 대한 깊이 있는 통찰을 제공합니다. 이전과 다름없이, <span class="math inline">\((1-\alpha)\)</span> 100% 신뢰 구간을 확보하기 위해 다음 조건을 만족하는 (하한, 상한<span class="math inline">\()\)</span> 형태의 구간을 찾아야 합니다.</p>
<p><span class="math display">\[
P(Lower&lt;\mu_1-\mu_2&lt;Upper)=1-\alpha
\]</span></p>
<p>이 확률을 풀어나가기 위해서는 기준으로 삼을 통계적 확률 분포가 필요합니다. 그렇다면 과연 어떤 분포를 채택해야 할까요? 모든 신뢰 구간 논리의 든든한 출발점인 중심 극한 정리부터 되짚어 보겠습니다. 평균을 다룰 때 중심 극한 정리는 표본 크기가 충분히 크거나 데이터가 정규 분포를 따른다면, 표본 평균(Sample mean)이 실제 모집단 평균 μ를 중심으로 하고 분산(Variance)이 <span class="math inline">\(\sigma^2 / n\)</span>인 정규 분포에 수렴한다고 명시합니다. 이 법칙은 두 표본 평균 <span class="math inline">\(\bar{x}_{1}\)</span>과 <span class="math inline">\(\bar{x}_{2}\)</span> 모두에 예외 없이 적용되어 다음과 같은 전제를 확립합니다.</p>
<p><span class="math display">\[
\begin{aligned}
\bar{x}_{1}&amp;∼N(\mu_1,\sigma_1^2n1) \\
\bar{x}_{2}&amp;∼N(\mu_2,\sigma_2^2n2)
\end{aligned}
\]</span></p>
<p><span class="math inline">\(p_1-p_2\)</span>에 대한 신뢰 구간을 유도했던 방식 그대로, 이 두 독립적인 분포를 대수적으로 결합하여 <span class="math inline">\(\bar{x}_{1}-\bar{x}_{2}\)</span>에 대한 확률 분포를 얻어낼 수 있으며, 이는 필연적으로 또 다른 형태의 정규 분포가 됩니다.</p>
<p><span class="math display">\[
\bar{x}_{1}-\bar{x}_{2}∼N(\mu_1-\mu_2,\sigma_1^2n1+\sigma_2^2n2).
\]</span></p>
<p>이제 해당 변수에서 기댓값인 평균을 빼고 표준 편차로 나누는 표준화 작업을 거치면 이 분포를 0과 1을 모수로 갖는 표준 정규 분포로 변환할 수 있습니다. 그 결과는 다음과 같습니다.</p>
<p><span class="math display">\[
\frac{\bar{x}_{1}-\bar{x}_{2}-(\mu_1-\mu_2)}{\sqrt{\sigma_1^2n1+\sigma_2^2n2}}∼N(0,1)
\]</span></p>
<p>하지만 이 이상적인 수식은 현실에서 심각한 난관에 부딪힙니다. 분모에 위치한 실제 모집단 분산 <span class="math inline">\(\sigma_1^2\)</span>과 <span class="math inline">\(\sigma_2^2\)</span>의 값을 정확히 알아야 계산이 가능하기 때문입니다. 두 값은 신만 아는 모집단 모수이므로 현실 세계의 분석가는 이를 결코 알 수 없습니다. 따라서 우리는 <span class="math inline">\(\sigma_1^2n1+\sigma_2^2n2\)</span> 수식에 대입할 믿을 만한 추정치가 절실히 필요합니다. 다행히 우리는 “모집단 분산이 같은가?”라는 질문의 답변에 따라 상황에 맞게 적용할 수 있는 두 가지 대입법을 이미 가설 검정 파트에서 학습했습니다.</p>
<section id="합동-분산" class="level3" data-number="2.1">
<h3 data-number="2.1" class="anchored" data-anchor-id="합동-분산"><span class="header-section-number">2.1</span> 합동 분산</h3>
<p>우리는 이전에 가설 검정을 수행하며 이 분산 동일성 질문과 마주쳤고, 답변에 따라 두 가지 추정치 중 하나를 유연하게 선택했습니다. 만약 두 집단의 분산이 같다고 판단된다면(일반적으로 <span class="math inline">\(1/4 &lt; s_1^2 / s_2^2 &lt; 4\)</span> 범위에 들면 분산이 타당하게 같다고 간주하는 경험 법칙을 따름), 두 표본 분산의 정보를 한데 섞어 다음과 같은 합동 표본 분산(Pooled sample variance)을 도출할 수 있습니다.</p>
<p><span class="math display">\[
s^2_{p}=\frac{(n_1-1)s_1^2+(n_2-1)s^2}{n_1+n_2-2}
\]</span></p>
<p>이 합동 표본 분산은 단일한 공통 모집단 분산을 강력하게 추정하며, 최종적으로 <span class="math inline">\(\bar{x}_{1}-\bar{x}_{2}\)</span>의 표준 오차 수식에 삽입됩니다. 이 논리를 바탕으로 도출된, 분산이 같을 때의 표준 오차 공식은 다음과 같습니다.</p>
<p><span class="math display">\[
\text{s.e.}(\bar{x}_{1}-\bar{x}_{2})=s_{p} \sqrt{1/n_1 + 1/n_2}
\]</span></p>
<p>이제 우리는 알 수 없는 모집단 분산에 기반한 비현실적인 표준 오차 대신, 실측 데이터로 계산한 이 표준 오차를 대입할 수 있습니다. 그러나 표본 분산을 사용하여 모분산을 대체하는 순간, 통계적 확률 분포의 본질이 변하게 됩니다. 표준 정규 분포를 다루던 상황에서 벗어나, 꼬리가 더 두꺼운 자유도(Degrees of freedom) <span class="math inline">\(\nu=n_1+n_2-2\)</span>인 <span class="math inline">\(t\)</span>-분포로 분석의 초점이 이동합니다.</p>
<p><span class="math display">\[
\frac{\bar{x}_{1}-\bar{x}_{2}-(\mu_1-\mu_2)}{s_{p}\sqrt{1/n_1 + 1/n_2}}∼t_\nu
\]</span></p>
<p>이제 이 <span class="math inline">\(t\)</span>-분포를 우리의 기준 확률 분포로 삼을 것입니다. 따라서 <span class="math inline">\((1-\alpha)\)</span> 100% 신뢰 구간을 구하려면 다음을 만족하는 임계값 <span class="math inline">\(t^*\)</span>를 선택해야 합니다.</p>
<p><span class="math display">\[
P(-t^*&lt;t_\nu&lt;t^*)=1-\alpha
\]</span></p>
<p>앞서 정의한 대로 모수 <span class="math inline">\(\mu_1-\mu_2\)</span> 및 관측 데이터를 이 분포와 연결해 줄 검정 통계량(Test statistic) 구조를 확보했습니다. 이를 위의 확률 문구 중앙에 조심스럽게 대입하면 다음과 같은 부등식이 형성됩니다.</p>
<p><span class="math display">\[
P(-t^*&lt;\frac{\bar{x}_{1}-\bar{x}_{2}-(\mu_1-\mu_2)}{s_{p}\sqrt{1/n_1 + 1/n_2}}&lt;t^*)=1-\alpha
\]</span></p>
<p>이제 확률 문구 내부를 대수적으로 전개하여 <span class="math inline">\(\mu_1-\mu_2\)</span>를 중앙에 고립시키기만 하면, 우리가 찾는 <span class="math inline">\(\mu_1-\mu_2\)</span>에 대한 <span class="math inline">\((1-\alpha)\)</span> 100% 신뢰 구간 공식이 마침내 모습을 드러냅니다.</p>
<p><span class="math display">\[
\begin{aligned}
&amp;P\left(-t^* &lt; \frac{(\bar{x}_1 - \bar{x}_2) - (\mu_1 - \mu_2)}{s_p \sqrt{\frac{1}{n_1} + \frac{1}{n_2}}} &lt; t^*\right) \\
&amp;= 1 - \alpha \\
&amp;= P\left( (\bar{x}_1 - \bar{x}_2) - t^* s_p \sqrt{\frac{1}{n_1} + \frac{1}{n_2}} &lt; \mu_1 - \mu_2 &lt; (\bar{x}_1 - \bar{x}_2) + t^* s_p \sqrt{\frac{1}{n_1} + \frac{1}{n_2}} \right)
\end{aligned}
\]</span></p>
<p>이 수식은 정확히 <span class="math inline">\(P(\text{Lower} &lt; \mu_1 - \mu_2 &lt; \text{Upper}) = 1 - \alpha\)</span> 구조를 만족하는 하한과 상한을 제공합니다. 결론적으로 두 모집단의 분산이 같다고 가정할 때, <span class="math inline">\(\mu_1-\mu_2\)</span>에 대한 <span class="math inline">\((1-\alpha)\)</span> 100% 신뢰 구간은 다음과 같이 요약됩니다.</p>
<p><span class="math display">\[
(\bar{x}_1 - \bar{x}_2) \pm t^* s_p \sqrt{\frac{1}{n_1} + \frac{1}{n_2}}
\]</span></p>
</section>
<section id="이분산" class="level3" data-number="2.2">
<h3 data-number="2.2" class="anchored" data-anchor-id="이분산"><span class="header-section-number">2.2</span> 이분산</h3>
<p>만약 두 모집단의 분산이 명백히 다르다면(이분산), 데이터를 함부로 결합하여 합동 모집단 분산 <span class="math inline">\(\sigma^2\)</span>의 단일 추정치를 얻으려는 시도는 큰 통계적 오류를 낳습니다. 이 경우에는 표준 오차 공식의 <span class="math inline">\(\sigma_1^2\)</span>과 <span class="math inline">\(\sigma_2^2\)</span> 자리에 각 집단의 표본 분산 <span class="math inline">\(s_1^2\)</span>과 <span class="math inline">\(s_2^2\)</span>를 독립적으로 대입하는 전략을 택해야 합니다. 이로써 <span class="math inline">\(\bar{x}_{1}-\bar{x}_{2}\)</span>의 이분산 표준 오차는 다음과 같이 정의됩니다.</p>
<p><span class="math display">\[
s.e.(\bar{x}_{1}-\bar{x}_{2})=\sqrt{s_1^2/n_1+s_2^2/n_2}
\]</span></p>
<p>그런 다음 이론적인 표준 오차를 버리고 이 실증적 표준 오차를 확률 문구에 과감히 대입합니다. 하지만 이 표준 오차를 채택하는 순간, 관련된 확률 분포는 정규 분포에서 복잡한 근사적 <span class="math inline">\(t\)</span>-분포로 탈바꿈합니다. 가설 검정 장에서 살펴본 바와 같이, 이분산 문제에는 수학적으로 완벽한 정확한 해(Exact solution)가 존재하지 않으므로 이 분포는 어디까지나 근사치(Approximation)입니다. 가설 검정 때와 동일하게 웰치-새터스웨이트(Welch-Satterthwaite) 근사법을 동원하여 유효 자유도 <span class="math inline">\(\nu\)</span>를 추정하며, 그 복잡한 공식은 다음과 같습니다.</p>
<p><span class="math display">\[
\nu=\frac{(s_1^2/n_1+s_2^2/n_2)^2}{\frac{1}{n_1-1}(s_1^2/n_1)^2+\frac{1}{n_2-1}(s_2^2/n_2)^2}
\]</span></p>
<p>이제 새롭게 추정된 이 자유도를 지닌 <span class="math inline">\(t\)</span>-분포를 기준 확률 분포로 사용할 것입니다. 따라서 <span class="math inline">\((1-\alpha)\)</span> 100% 신뢰 구간을 구축하기 위해 다시 한번 다음 확률을 만족하는 임계값 <span class="math inline">\(t^*\)</span>를 탐색합니다.</p>
<p><span class="math display">\[
P(-t^*&lt;t_\nu&lt;t^*)=1-\alpha
\]</span></p>
<p>위에서 정립한 모수 <span class="math inline">\(\mu_1-\mu_2\)</span> 및 실측 데이터 간의 검정 통계량 관계식을 이 확률 문구의 중앙에 대입하면 다음과 같은 전개가 이루어집니다.</p>
<p><span class="math display">\[
P(-t^*&lt;\bar{x}_{1}-\bar{x}_{2}-(\mu_1-\mu_2) / \sqrt{s_1^2/n_1+s_2^2/n_2}&lt;t^*)=1-\alpha
\]</span></p>
<p>이제 마지막으로 확률 문구 내부를 치밀하게 정리하여 <span class="math inline">\(\mu_1-\mu_2\)</span>에 대해 풀면, 이분산 상황에 완벽히 대응하는 <span class="math inline">\(\mu_1-\mu_2\)</span>에 대한 <span class="math inline">\((1-\alpha)\)</span> 100% 신뢰 구간을 마침내 획득하게 됩니다.</p>
<p><span class="math display">\[
P\left(-t^*&lt;\frac{\bar{x}_1-\bar{x}_2-(\mu_1-\mu_2)}{\sqrt{s_1^2/n_1+s_2^2/n_2}}&lt;t^*\right)=1-\alpha \
=P\left(\bar{x}_1-\bar{x}_2-t^*\sqrt{s_1^2/n_1+s_2^2/n_2}&lt;\mu_1-\mu_2&lt;\bar{x}_1-\bar{x}_2+t^*\sqrt{s_1^2/n_1+s_2^2/n_2}\right)
\]</span></p>
</section>
<section id="해석-및-예제" class="level3" data-number="2.3">
<h3 data-number="2.3" class="anchored" data-anchor-id="해석-및-예제"><span class="header-section-number">2.3</span> 해석 및 예제</h3>
<p>이렇게 심혈를 기울여 도출한 신뢰 구간에 대한 해석 원리는 등분산 가정이든 이분산 가정이든 관계없이 변함없이 유지됩니다. 즉, 우리는 “위 공식들을 통해 도출된 신뢰 구간이 실제 <span class="math inline">\(\mu_1-\mu_2\)</span>의 참값을 포괄한다고 <span class="math inline">\((1-\alpha)\)</span> 100% 굳게 확신한다”고 선언합니다.</p>
<p>늘 그래왔듯 신뢰 구간의 논리가 중심 극한 정리에 빚을 지고 있다는 사실은, 해당 구간이 수학적 유효성을 지니려면 표본 크기가 넉넉하거나 원래 데이터가 정규 분포를 띠어야 한다는 엄격한 전제 조건을 요구함을 뜻합니다. 특히 두 표본을 동시에 다루고 있으므로 중심 극한 정리가 두 집단 모두에서 성립해야만 합니다. 통상적으로 분석 결과가 안정성을 띠려면 각 표본의 크기가 최소 30 이상이 되거나(<span class="math inline">\(n_1\ge 30\)</span> 및 <span class="math inline">\(n_2\ge 30\)</span>), 두 표본의 분포가 확연한 정규성을 띠어야 합니다.</p>
<p>이를 현실의 데이터 분석 사례에 적용해 보겠습니다. 식품 공학 전문가들이 두 종류의 사과(제품 298과 제품 493)의 당도와 맛 점수를 비교 평가하기 위해 <span class="math inline">\(\mu_{298}-\mu_{493}\)</span>에 대한 90% 신뢰 구간을 산출하고자 합니다 [23]. 각 품종별로 15개의 사과를 블라인드 시식한 결과, 표본 평균은 <span class="math inline">\(\bar{x}_{298}=68.333\)</span> 및 <span class="math inline">\(\bar{x}_{493}=94.067\)</span>로 나타났고, 표본 분산은 <span class="math inline">\(s_{298}^2=758.667\)</span> 및 <span class="math inline">\(s_{493}^2=1688.352\)</span>로 측정되었습니다. 분산 비율 <span class="math inline">\(s_{298}^2/s_{493}^2=758.667/1688.352=0.4494\)</span>가 경험적 기준인 <span class="math inline">\(1/4\)</span>와 4 사이에 안정적으로 위치하므로, 우리는 등분산 가정이 타당하다고 판정합니다. 이에 따라 합동 표본 분산을 다음과 같이 합리적으로 계산합니다.</p>
<p><span class="math display">\[
s^2_{p}=(15-1)×758.667+(15-1)×1688.35215+15-2=1223.51
\]</span></p>
<p>이제 유일하게 남은 과제는 <span class="math inline">\(t^*\)</span> 값을 찾아내는 일입니다. 분산이 같다고 가정했으므로 유효 자유도는 <span class="math inline">\(\nu=15+15-2=28\)</span>이 되며, 이 분포에서 <span class="math inline">\(P(t_{\nu}&lt;t^*)=1-0.1/2=0.95\)</span>를 만족하는 위치를 탐색합니다. 통계 소프트웨어 R에서 <code>qt(0.95, df = 28)</code> 코드를 실행하여 임계값 <span class="math inline">\(t^*=1.701\)</span>을 정확히 도출합니다. 찾아낸 임계값과 요약 데이터를 신뢰 구간 공식에 일괄 대입하면 다음 결과를 얻습니다.</p>
<p><span class="math display">\[
68.333-94.067±1.7011223.51(115+115)=(-47.460,-4.008)
\]</span></p>
<p>결론적으로 우리는 구간 <span class="math inline">\((-47.460, -4.008)\)</span>이 모평균 차이 <span class="math inline">\(\mu_{298}-\mu_{493}\)</span>의 실제 참값을 포괄한다고 90% 확신합니다. 다만, n=15라는 다소 빈약한 표본 크기와 데이터의 완전한 정규성을 입증하기 어렵다는 점에서 이 분석 결과의 완벽한 신뢰성에 대해서는 분석가로서 약간의 비판적 시각을 유지하는 편이 바람직합니다.</p>
</section>
<section id="연습-문제-1" class="level3" data-number="2.4">
<h3 data-number="2.4" class="anchored" data-anchor-id="연습-문제-1"><span class="header-section-number">2.4</span> 연습 문제</h3>
<p>어느 의학 연구팀이 양성(Benign) 종양과 악성(Malignant) 종양을 대상으로 종양 세포 덩어리 두께(Clump thickness)의 모집단 평균에 유의미한 차이가 존재하는지 정밀 조사하고자 합니다. 458개의 양성 종양 샘플을 분석한 결과 표본 평균 <span class="math inline">\(\bar{x}_{Benign}=2.96\)</span>과 표본 표준 편차(Sample standard deviation) <span class="math inline">\(s_{Benign}=1.67\)</span>을 도출했습니다. 241개의 악성 종양 샘플에서는 표본 평균 <span class="math inline">\(\bar{x}_{Malignant}=7.2\)</span>와 표본 표준 편차 <span class="math inline">\(s_{Malignant}=2.43\)</span>을 관측했습니다. (이러한 측정 데이터는 최신 의료 AI 모델의 종양 악성도 분류 피처로도 핵심적인 역할을 합니다)</p>
<ol start="4" type="1">
<li><span class="math inline">\(\mu_{Malignant}-\mu_{Benign}\)</span>에 대한 90% 신뢰 구간을 오차 없이 계산하고 그 임상적 의미를 해석해 보십시오.</li>
</ol>
<p>한 교육 사회학자가 남학생과 여학생 간의 학교 결석률 차이를 분석하고자 합니다. 80명의 여학생을 무작위 추출하여 조사한 결과, 표본 평균 결석 일수는 <span class="math inline">\(\bar{x}_F=15.225\)</span>일이었고 분산은 <span class="math inline">\(s_{F}^2=253.7968\)</span>에 달했습니다. 반면 66명의 남학생 그룹에서는 표본 평균 결석 일수가 <span class="math inline">\(\bar{x}_M=17.955\)</span>일, 분산이 <span class="math inline">\(s_{M}^2=276.6902\)</span>로 집계되었습니다.</p>
<ol start="5" type="1">
<li><span class="math inline">\(\mu_{F}-\mu_{M}\)</span>에 대한 96% 신뢰 구간을 치밀하게 계산하고 결과가 시사하는 바를 논리적으로 해석해 보십시오.</li>
</ol>
<p>환경 과학 연구자가 영국의 리즈(Leeds) 지역을 대상으로 여름과 겨울 두 계절 간 대기 중 오존 수준의 차이를 규명하고자 합니다. 측정이 이루어진 578일의 여름날 동안 평균 오존 수준은 <span class="math inline">\(\bar{x}_S=32.00\)</span> ppb(parts per billion)였고 분산은 <span class="math inline">\(s_{S}^2=106.81\)</span>이었습니다. 대조군으로 측정한 532일의 겨울날 동안에는 평균 오존 수준이 <span class="math inline">\(\bar{x}_W=20.06\)</span> ppb, 분산이 <span class="math inline">\(s_{W}^2=118.72\)</span>로 기록되었습니다.</p>
<ol start="6" type="1">
<li><span class="math inline">\(\mu_{S}-\mu_{W}\)</span>에 대한 92% 신뢰 구간을 도출하고 대기 질 관리 측면에서 이 결과를 어떻게 해석할지 서술해 보십시오.</li>
</ol>
</section>
</section>
<section id="mu_d에-대한-신뢰-구간" class="level2" data-number="3">
<h2 data-number="3" class="anchored" data-anchor-id="mu_d에-대한-신뢰-구간"><span class="header-section-number">3</span> <span class="math inline">\(\mu_D\)</span>에 대한 신뢰 구간</h2>
<p>앞서 평균에 대한 가설 검정 장에서 역설했듯이, 독립된 두 집단을 전제로 하는 이표본 <span class="math inline">\(t\)</span>-검정이나 <span class="math inline">\(\mu_1-\mu_2\)</span>에 대한 신뢰 구간 모델만으로는 우리의 통계적 질문에 온전히 답할 수 없는 특수한 상황이 존재합니다. 바로 관측 대상 간에 강력한 종속성이 존재하는 ’쌍을 이룬 데이터(paired data)’를 마주할 때입니다. 실험 대상이 처리 전후로 두 표본에 모두 등장하거나, 개별 대상의 치료 효과를 명확히 측정하기 위해 기준선(baseline)을 통제할 수 있는 아주 유사한 대응 대상을 의도적으로 짝지어(matching) 놓은 경우가 이에 해당합니다. 이러한 시나리오에서는 두 표본 사이에 떼려야 뗄 수 없는 직접적 연결 고리가 생기므로, 집단 간 독립성을 대전제로 하는 전통적인 이표본 <span class="math inline">\(t\)</span>-검정과 그 파생 신뢰 구간 공식을 적용하는 것은 명백한 통계적 오류입니다.</p>
<p>이러한 특수 상황에서는 두 집단의 뭉뚱그려진 평균을 막연히 비교하는 대신, 완벽히 짝지어진 표본 간의 ‘차이(difference)’ 데이터 자체에 대해 통계적 추론을 집중합니다. 즉, 각 피험자나 매칭된 쌍에 대해 두 그룹 간의 정밀한 차잇값을 계산해 낸 다음, 이 파생된 차이 데이터셋을 대상으로 본질적인 단일 표본 <span class="math inline">\(t\)</span>-검정을 수행하는 우회 전략을 취합니다. 단일 표본 <span class="math inline">\(t\)</span>-검정의 논리를 그대로 차용하여 적절한 변수만 치환하면 되므로, 신뢰 구간을 도출할 때도 이 우아한 논리가 그대로 관철됩니다. 어느 쪽이든 우리는 새롭게 계산된 차이 데이터 집단의 모집단 평균인 <span class="math inline">\(\mu_{D}\)</span>를 추론의 궁극적 타깃으로 삼습니다.</p>
<p>순수한 단일 평균 μ에 대한 <span class="math inline">\((1-\alpha)\)</span> 100% 신뢰 구간은 표본 평균 <span class="math inline">\(\bar{x}\)</span>, 표본 표준 편차 s, 표본 크기 n, 그리고 자유도 <span class="math inline">\(n-1\)</span>을 지닌 <span class="math inline">\(t\)</span>-분포의 임계값 <span class="math inline">\(t^*\)</span>라는 네 가지 핵심 요소에만 배타적으로 의존합니다.</p>
<p><span class="math display">\[
\bar{x}±t^*s/\sqrt{n}
\]</span></p>
<p>우리의 현재 목표는 단일 표본의 평균 μ가 아니라, ’차이가 계산된 데이터’의 단일 평균 <span class="math inline">\(\mu_{D}\)</span>에 관해 타당한 추론을 내리는 것입니다. 서로 얽힌 두 표본의 데이터를 빼기 연산을 통해 ’단일 차이 표본’으로 압축하면, 우리는 방금 확인한 단일 평균 μ에 대한 검정 및 구간 추정 기법을 <span class="math inline">\(\mu_{D}\)</span>에 정확히 동일하게 이식할 수 있습니다. 논리적 비약 없이 치환을 거친 <span class="math inline">\(\mu_{D}\)</span>에 대한 <span class="math inline">\((1-\alpha)\)</span> 100% 신뢰 구간은 다음과 같은 형태를 띱니다.</p>
<p><span class="math display">\[
\bar{x}_{D}±t^*s_{D}/\sqrt{n}
\]</span></p>
<p>이 공식은 원형인 단일 평균 μ에 대한 <span class="math inline">\((1-\alpha)\)</span> 100% 신뢰 구간과 수학적으로 완전히 동일합니다. 단지 우리가 지금 다루는 대상이 짝지은 데이터의 ’차이’임을 명시하기 위해, 모수와 표본 통계량 기호에 D라는 아래 첨자를 추가했을 뿐입니다. 이전의 숱한 예시들과 마찬가지로 확률 <span class="math inline">\(P(t_{n-1} &lt; t^*) = 1-\alpha/2\)</span>를 만족하도록 <span class="math inline">\(t^*\)</span>를 정밀하게 선택합니다. 현대 통계 분석에서는 R의 qt 함수가 이 특정 임계값을 찾는 데 주로 동원됩니다. 최종적인 해석 역시 논리의 일관성을 유지하여, 계산된 신뢰 구간이 미지의 참값 <span class="math inline">\(\mu_{D}\)</span>를 확고히 포함할 것이라고(즉, 우리의 구간 추정이 옳을 것이라고) <span class="math inline">\((1-\alpha)\)</span> 100% 확신한다고 진술합니다.</p>
<p>단일 모집단 평균 <span class="math inline">\(\mu\)</span>에 대한 신뢰 구간 파트에서, 중심 극한 정리가 무리 없이 성립하고 산출된 신뢰 구간이 수학적 유효성을 인정받으려면 표본 크기가 넉넉하거나(<span class="math inline">\(n \ge 30\)</span>) 데이터 자체가 선천적인 정규 분포를 따라야 한다고 누누이 강조했습니다. 쌍을 이룬 신뢰 구간 역시 본질을 파고들면 ’차이 데이터’에 대한 단일 표본 신뢰 구간에 불과하므로, 이 신뢰 구간이 학술적 유효성을 지니려면 앞선 가정이 철저히 충족되어야 함은 너무나 자명합니다. 결론적으로 중심 극한 정리와 파생된 신뢰 구간이 제 기능을 다 하려면 짝지어진 관측치 쌍의 개수 n이 30개 이상 확보되거나, 계산된 차이 데이터셋의 히스토그램이 정규 분포의 종 모양을 아름답게 그려내야 합니다.</p>
<p>이러한 추론의 흐름을 실제 사례에 접목해 보기 위해 통계 패키지 R의 PairedData 라이브러리에 수록된 고전적 예시를 살펴보겠습니다. 재료 공학자들이 채굴된 광석의 철분 함량 비율을 판별하는 두 가지 화분석 공정(A와 B)의 산출 결과에 체계적인 차이가 존재하는지 확인하고자 합니다 [63,67]. 이들은 10개의 동일한 철광석 샘플 블록을 채취하여 각각의 샘플을 방법 A와 방법 B로 이중 측정했습니다. 동일한 물리적 샘플에 대해 두 번의 측정이 이루어졌으므로 이는 전형적인 쌍을 이룬(Paired) 데이터입니다. 표본 분석 결과 두 측정 방식 사이의 평균 차이(A 측정치 마이너스 B 측정치)는 <span class="math inline">\(\bar{x}_D=-0.13\)</span>이었고, 차이값들의 표본 표준 편차는 <span class="math inline">\(s_{D}=0.177\)</span>로 집계되었습니다. 이 데이터를 바탕으로 <span class="math inline">\(\mu_{D}\)</span>에 대한 90% 신뢰 구간을 도출해 보겠습니다. 공식에서 유일하게 비어 있는 조각은 임계값 <span class="math inline">\(t^*\)</span>뿐입니다. 이를 찾기 위해 R에서 <code>qt(0.95, df=9)</code> 함수를 실행하여 <span class="math inline">\(t^*=1.833\)</span>을 얻어냅니다. 확보한 부품들을 모두 조립하면 <span class="math inline">\(\mu_{D}\)</span>에 대한 90% 신뢰 구간은 다음과 같이 완성됩니다.</p>
<p><span class="math display">\[
-0.13±1.833×0.177/\sqrt{10}=(-0.027,-0.233)
\]</span></p>
<p>이 결과를 해석하자면, 참인 모집단 평균 차이가 <span class="math inline">\((-0.027, -0.233)\)</span> 구간 안에 위치할 것이라고 우리는 90% 확신합니다. 그러나 겨우 10개에 불과한 협소한 표본 크기와 차이값 분포에서 엿보이는 정규성 결여는 이 분석 결과의 통계적 유효성에 강한 의구심을 남길 수밖에 없습니다. 실무에서는 이러한 한계를 명확히 인식해야 합니다. (이전 가설 검정 과정과 마찬가지로 R의 <code>t.test</code> 함수는 만능 도구처럼 전반적인 대응 <span class="math inline">\(\mu_{D}\)</span>에 대한 신뢰 구간을 단숨에 계산해 줍니다. 이표본 검정 시 활용했던 부가 옵션들을 상황에 맞게 켜고 끄며 <code>conf.level</code> 인자만 조절하면, 분석가가 염원하는 <span class="math inline">\(\mu_1-\mu_2\)</span> 또는 <span class="math inline">\(\mu_D\)</span>에 대한 모든 <span class="math inline">\((1-\alpha)\)</span> 100% 신뢰 구간을 손쉽게 확보할 수 있습니다.)</p>
<section id="연습-문제-2" class="level3" data-number="3.1">
<h3 data-number="3.1" class="anchored" data-anchor-id="연습-문제-2"><span class="header-section-number">3.1</span> 연습 문제</h3>
<ol start="7" type="1">
<li><p>환경 보건 전문가가 납 제련 공장에서 근무하는 부모를 둔 아이들이 그렇지 않은 일반 가정의 아이들보다 체내 혈중 납 농도가 더 유해한 수준으로 높은지 알아보고자 합니다. 조사팀은 납 공장 근로자의 아동 33명을 코호트로 선정한 뒤, 교란 변수를 차단하기 위해 부모가 납 산업에 종사하지 않는 동일 지역 거주 아동 33명을 대조군(controls)으로 정교하게 짝지어(Matching) 연구를 설계했습니다. 혈액 검사 결과 두 그룹 간 혈중 납 농도의 평균 차이(노출군 마이너스 대조군)는 <span class="math inline">\(\bar{x}_D=15.97\)</span>로 나타났고, 이 차이값들의 표본 분산은 <span class="math inline">\(s_{D}^2=251.65\)</span>로 산출되었습니다. 안타깝게도 차이 데이터의 히스토그램은 오른쪽으로 꼬리가 길게 늘어진 비대칭(skewed right) 형태를 띱니다. <span class="math inline">\(\mu_{D}\)</span>에 대한 99% 신뢰 구간을 엄밀히 계산하고 정책적 관점에서 해석해 보십시오.</p></li>
<li><p>제약 회사 연구진이 HIV 양성 환자의 CD4 면역 세포 수치를 안정화하는 신약의 장기적 효능을 추적하고 있습니다. CD4 수치의 급격한 감소는 환자에게 치명적인 에이즈(AIDS) 발병이 임박했음을 알리는 핵심 바이오마커입니다. 임상 시험에 참여한 20명의 환자를 대상으로 기준선(Baseline) CD4 수치를 정밀 측정하고, 1년간 신약을 투여한 뒤 동일 환자들의 수치를 재측정했습니다. 분석 결과 표본 평균 차이는 <span class="math inline">\(\bar{x}_D=-0.805\)</span>, 표본 표준 편차는 <span class="math inline">\(s_{D}=0.8017\)</span>로 나타났습니다. 다행히 차이값의 히스토그램은 이상적인 정규 분포의 형태를 띠었습니다. <span class="math inline">\(\mu_{D}\)</span>에 대한 90% 신뢰 구간을 도출하고 약효의 실효성을 해석해 보십시오.</p></li>
<li><p>해양 에너지 엔지니어들이 거친 파도의 운동 에너지를 전기로 변환하는 혁신적인 파력 발전 장치를 개발 중입니다. 해상에서 장치의 위치를 고정하기 위해 두 가지 계류(mooring) 기법 중 하나를 채택해야 하는데, 한 기법이 다른 기법보다 시공 비용 면에서 압도적으로 저렴합니다. 연구진은 파도 시뮬레이션 탱크에서 장치의 핵심 연결부에 가해지는 굽힘 응력(bending stress)을 테스트했으며, 동일한 조건의 시뮬레이션 파도를 두 계류 방식에 차례로 적용하여 응력 데이터를 짝지어 수집했습니다. 18번의 정밀 시뮬레이션 결과 평균 응력 차이는 <span class="math inline">\(\bar{x}_D=0.062\)</span>였으며 표본 표준 편차는 <span class="math inline">\(s_{D}=0.29\)</span>로 기록되었습니다. 응력 차이 데이터는 정규 분포를 온전히 따르는 것으로 입증되었습니다. <span class="math inline">\(\mu_{D}\)</span>에 대한 80% 신뢰 구간을 계산하고 비용 절감 기법의 채택 여부를 공학적으로 해석해 보십시오.</p></li>
</ol>
</section>
</section>
<section id="mu_1---mu_2-mu_d에-대한-신뢰-구간과-가설-검정" class="level2" data-number="4">
<h2 data-number="4" class="anchored" data-anchor-id="mu_1---mu_2-mu_d에-대한-신뢰-구간과-가설-검정"><span class="header-section-number">4</span> <span class="math inline">\(\mu_1\)</span> - <span class="math inline">\(\mu_2\)</span>, <span class="math inline">\(\mu_D\)</span>에 대한 신뢰 구간과 가설 검정</h2>
<p>신뢰 구간과 가설 검정이라는 두 가지 거대한 통계적 추론 기둥은 모두 중심 극한 정리라는 동일한 철학적 기반 위에 서 있습니다. 따라서 두 기법 사이에 심오하고 직접적인 연결 고리가 존재할 것이라고 직관적으로 짐작하는 것은 지극히 타당합니다. 우리는 이미 단일 표본 평균에 대한 <span class="math inline">\(t\)</span>-검정과 그에 대응하는 신뢰 구간 사이의 완벽한 호환성을 목격한 바 있습니다. 두 방법론 모두 완전히 동일한 수학적 공식과 동일한 <span class="math inline">\(t\)</span>-분포 곡선으로부터 결과값을 도출하기 때문입니다. 우리는 궁극적으로 <span class="math inline">\(\mu\)</span>에 대한 <span class="math inline">\((1-\alpha)\)</span> 100% 신뢰 구간을 생성해 내는 것만으로도, <span class="math inline">\(\alpha\)</span> 유의 수준(significance level)에서의 <span class="math inline">\(H_0:\mu=\mu_0\)</span> 대 <span class="math inline">\(H_A:\mu \neq \mu_0\)</span> 양측 가설 검정을 완벽하게 대체하여 수행할 수 있음을 입증했습니다. 만약 귀무 가설의 기준값 <span class="math inline">\(\mu_0\)</span>가 산출된 신뢰 구간 내부에 안착한다면 우리는 귀무 가설을 기각하지 못하며, 반대로 <span class="math inline">\(\mu_0\)</span>가 구간 바깥에 위치한다면 주저 없이 귀무 가설을 기각합니다.</p>
<p>이 아름다운 수학적 대칭성은 당연히 이표본 비교 가설 검정의 영역으로까지 유연하게 확장됩니다. 즉, <span class="math inline">\(\mu_1-\mu_2\)</span>에 대한 <span class="math inline">\((1-\alpha)\)</span> 100% 신뢰 구간을 생성함으로써 <span class="math inline">\(H_0:\mu_1-\mu_2=0\)</span> 대 <span class="math inline">\(H_A:\mu_1-\mu_2 \neq 0\)</span>의 가설 검정을 단번에 수행할 수 있습니다. 차이가 없음을 뜻하는 ’0’이라는 값이 우리가 도출한 신뢰 구간 안에 포함된다면 두 모집단 간에 유의미한 차이가 없다는 귀무 가설을 기각하지 못하고, 0이 신뢰 구간 범위를 벗어나 있다면 두 집단 간의 차이가 통계적으로 실재한다는 귀무 가설 기각 판정을 내립니다. 현대 데이터 과학의 자동화된 A/B 테스트 파이프라인(두 추천 알고리즘의 클릭률 차이 검증)에서도 이 직관적인 신뢰 구간 접근법을 통해 가설 검정 결과를 모니터링 대시보드에 시각적으로 구현하곤 합니다.</p>
<p>이 놀라운 호환성을 직접 확인하기 위해 앞 장에서 다루었던 가설 검정 사례를 다시 소환해 보겠습니다. 구체적으로 닭의 체중 증가 실험 데이터셋을 떠올려 보십시오 [10, 60]. 이 실험에서 우리는 대두와 해바라기라는 두 가지 상이한 식이 보충제가 병아리의 성장 속도(체중 증가량)에 유의미한 차이를 유발하는지 <span class="math inline">\(\alpha=0.05\)</span>의 통계적 잣대로 엄격히 검정했습니다. 복잡한 계산 끝에 우리는 귀무 가설을 기각하고 두 보충제의 효과 사이에 뚜렷한 차이가 존재한다는 결론에 도달했습니다. 놀랍게도 <span class="math inline">\(\mu_{soybean}-\mu_{sunflower}\)</span>에 대한 95% 신뢰 구간(유의 수준 <span class="math inline">\(\alpha=0.05\)</span>와 쌍을 이룸)을 계산하는 것만으로도 완전히 똑같은 결론에 안착할 수 있습니다. 당시 수집된 요약 데이터에 따르면, 대두를 섭취한 14마리 병아리의 평균 체중 증가는 <span class="math inline">\(\bar{x}_{soybean}=246.43\)</span>이었고 분산은 <span class="math inline">\(s_{soybean}^2=2,929.96\)</span>이었습니다. 대조적으로 해바라기씨를 섭취한 12마리 병아리는 평균 체중 증가가 <span class="math inline">\(\bar{x}_{sunflower}=328.92\)</span>로 훌쩍 뛰었고 분산은 <span class="math inline">\(s_{sunflower}^2=2,384.99\)</span>였습니다.</p>
<p>두 표본의 분산 비율을 점검한 결과 등분산 가정이 타당하다고 판단했으며, 이에 따라 합동 표본 분산을 다음과 같이 신뢰성 있게 도출해 냈습니다.</p>
<p><span class="math display">\[
s^2_{p}=((12-1)×2,384.99+(14-1)×2,929.96)/(12+14-2)=2,680.182
\]</span></p>
<p>이제 <span class="math inline">\(P(t_{\nu} &lt; t^*) = 1−0.05/2 = 0.975\)</span>의 꼬리 확률을 만족하는 임계값 <span class="math inline">\(t^*\)</span>만 찾으면 신뢰 구간이 완성됩니다. 등분산을 가정했으므로 분포의 자유도는 <span class="math inline">\(\nu=14+12-2=24\)</span>가 됩니다. R 콘솔에서 <code>qt(0.975, df=24)</code>를 호출하여 <span class="math inline">\(t^*=2.064\)</span>라는 정확한 임계값을 얻습니다. 마지막으로 이 모든 숫자들을 신뢰 구간 공식에 일괄 대입하여 95% 신뢰 구간을 산출합니다.</p>
<p><span class="math display">\[
246.43-328.92±2.064×\sqrt{2,680.182(1/14+1/12})=(-124.526,-40.454).
\]</span></p>
<p>차이가 없음을 의미하는 ’0’이라는 절대 수치가 이 신뢰 구간 <span class="math inline">\((-124.526, -40.454)\)</span> 안에 결코 존재하지 않으므로, 우리는 <span class="math inline">\(\alpha=0.05\)</span> 수준에서 귀무 가설을 기각해야 한다는 결론에 자연스럽게 도달합니다. 이는 애초에 기대했던 대로 전통적인 가설 검정 공식을 일일이 계산하여 얻어낸 결과와 완벽하게 일치합니다. 다만, 표본 크기가 30을 밑돈다는 점과 정규성에 대한 잠재적 위반 우려는 여전히 이 분석의 아킬레스건으로 남아 있음을 분석가는 명심해야 합니다.</p>
<p>한 치의 오차 없이 똑같은 치환 논리가 쌍을 이룬(Paired) 검정에도 적용됩니다. <span class="math inline">\(H_0:\mu_{D}=0\)</span> 대 <span class="math inline">\(H_A:\mu_D \neq 0\)</span>의 가설 검정을 수행하기 위해 일일이 <span class="math inline">\(p\)</span>-값을 구하는 대신, 짝을 이루는 α 수준으로 <span class="math inline">\((1-\alpha)\)</span> 100% 신뢰 구간을 계산하기만 하면 됩니다. 만약 0이 해당 구간 내부에 포함되면 귀무 가설 기각에 실패하는 것이고, 0이 구간 범위에서 빗겨나 있다면 귀무 가설을 단호하게 기각합니다.</p>
<p>이 역시 이전 장의 대응표본 가설 검정 사례를 통해 다시 한번 검증해 보겠습니다. 두 측정 장비를 비교한 아침 식사용 시리얼 분석 예시를 떠올려 보십시오 [23]. 우리는 <span class="math inline">\(\alpha=0.05\)</span>의 유의 수준 하에서 <span class="math inline">\(H_0:\mu_{D}=0\)</span> 대 <span class="math inline">\(H_A:\mu_D \neq 0\)</span> 가설을 정밀 검정했고, 최종적으로 귀무 가설을 기각한다는 짜릿한 결론을 얻었습니다. 이 지루한 검정 절차를 밟는 대신, 곧바로 <span class="math inline">\(\mu_{D}\)</span>에 대한 95% 신뢰 구간(다시 한번 <span class="math inline">\(\alpha=0.05\)</span>에 대응)을 쿨하게 계산하여 동일한 검증을 마칠 수 있습니다. 요약 데이터는 <span class="math inline">\(\bar{x}_D=-0.622\)</span>, <span class="math inline">\(s_{D}=1.988\)</span>, <span class="math inline">\(n=100\)</span>이므로, 오직 임계값 <span class="math inline">\(t^*\)</span>만이 유일한 미지수입니다. α 수준이 <span class="math inline">\(\alpha=0.05\)</span>이므로, R에서 <code>qt(0.975, df=99)</code> 코드를 활용하여 <span class="math inline">\(t^*=1.9842\)</span>를 신속히 찾아냅니다. 이 모든 요소들을 종합하여 95% 신뢰 구간을 시원하게 구축합니다.</p>
<p><span class="math display">\[
-0.622±1.9842×1.988/\sqrt{100}=(-1.016,-0.228).
\]</span></p>
<p>결정적인 기준값인 0이 이 구간 <span class="math inline">\((-1.016, -0.228)\)</span> 바깥에 위치하므로, 복잡한 전체 가설 검정 절차를 밟아 도출했던 과거의 결론과 한 치의 어긋남 없이 <span class="math inline">\(\alpha=0.05\)</span> 수준에서 귀무 가설을 확신을 가지고 기각하게 됩니다.</p>
<section id="연습-문제-3" class="level3" data-number="4.1">
<h3 data-number="4.1" class="anchored" data-anchor-id="연습-문제-3"><span class="header-section-number">4.1</span> 연습 문제</h3>
<ol start="10" type="1">
<li><p>식품 공학자가 육류 샘플의 지방 비율을 판별하는 데 쓰이는 두 가지 분석 기법의 정확도에 미세한 차이가 존재하는지 정밀히 비교하고 있습니다. 실험을 위해 20개의 동일한 육류 절단 부위를 신중히 선별했고, 각 부위마다 두 가지 기법을 모두 적용하여 지방 비율의 차이를 도출했습니다. 통계 분석 결과 산출된 <span class="math inline">\(\mu_{D}\)</span>에 대한 95% 신뢰 구간은 <span class="math inline">\((-0.345, 0.265)\)</span>로 나타났으며, 차이값 데이터의 히스토그램은 안정적인 정규 분포 곡선을 따르는 것으로 시각적으로 확인되었습니다. 그렇다면 유의 수준 <span class="math inline">\(\alpha=0.05\)</span> 하에서 수행되는 <span class="math inline">\(H_0:\mu_{D}=0\)</span> 대 <span class="math inline">\(H_A:\mu_D \neq 0\)</span> 가설 검정의 최종 결론은 무엇이 되어야 합니까?</p></li>
<li><p>국제 체조 대회에서 두 명의 심판위원이 93개에 달하는 일련의 루틴을 공동으로 시청한 뒤, 각각 1점에서 10점 사이의 척도로 각 루틴의 수행 점수를 독립적으로 매기도록 배정받았습니다. 두 심판 간의 판정 성향 차이를 알아보기 위해 <span class="math inline">\(\mu_{D}\)</span>에 대한 90% 신뢰 구간을 산출한 결과 <span class="math inline">\((-0.557, -0.045)\)</span>라는 범위가 획득되었습니다. 점수 차이의 히스토그램은 정규 분포 형태와 매우 흡사했습니다. 유의 수준 <span class="math inline">\(\alpha=0.1\)</span> 하에서 진행되는 <span class="math inline">\(H_0:\mu_{D}=0\)</span> 대 <span class="math inline">\(H_A:\mu_D \neq 0\)</span> 가설 검정에서는 어떠한 판정이 도출되겠습니까?</p></li>
<li><p>한 농업 데이터 연구자가 온실 내 두 가지 서로 다른 식물 재배 방식이 작물의 최종 총 수확량(정밀 저울로 중량 측정)에 어떤 영향을 미치는지 교차 비교하고자 합니다. <span class="math inline">\(n_1=20\)</span>과 <span class="math inline">\(n_2=10\)</span>으로 구성된 독립 표본 데이터를 바탕으로 꼼꼼히 산출한 <span class="math inline">\(\mu_1-\mu_2\)</span>에 대한 95% 신뢰 구간은 <span class="math inline">\((0.215, 1.515)\)</span>로 확정되었습니다. 두 표본 데이터셋의 히스토그램은 모두 이상적인 정규 분포의 자태를 뽐냈습니다. 유의 수준 <span class="math inline">\(\alpha=0.05\)</span> 하에서 수행되는 <span class="math inline">\(H_0:\mu_1-\mu_2=0\)</span> 대 <span class="math inline">\(H_A:\mu_1-\mu_2\neq 0\)</span> 가설 검정의 귀결은 과연 무엇입니까?</p></li>
</ol>
</section>
</section>
<section id="두-모수-신뢰-구간의-실질적-해석" class="level2" data-number="5">
<h2 data-number="5" class="anchored" data-anchor-id="두-모수-신뢰-구간의-실질적-해석"><span class="header-section-number">5</span> 두 모수 신뢰 구간의 실질적 해석</h2>
<p>두 모수의 차이에 대해 도출된 신뢰 구간은 비단 두 집단이 통계적으로 유의미하게 같은지 다른지만을 무미건조하게 알려 주는 이분법적 도구가 아닙니다. 이 구간은 관측된 차이가 현실에서 어느 정도 크기까지 확장될 수 있고, 반대로 얼마나 미미한 수준으로 쪼그라들 수도 있는지를 생생하게 묘사하는 지도를 제공합니다.</p>
<p>예를 들어, 의료 현장에서 두 치료법의 평균 회복 시간 차이에 대한 95% 신뢰 구간이 ’0.2일에서 1.1일’로 산출되었다고 가정해 보십시오. 신뢰 구간이 0을 포함하지 않으므로 두 치료법 간 차이는 명백히 “통계적으로 유의하다(양수이다)”고 선언할 수 있습니다. 그러나 신약의 도입 비용이 천문학적인 상황이라면, 기껏해야 하루(1.1일) 남짓, 최악의 경우 반나절(0.2일)도 단축하지 못하는 이 미미한 차이가 병원의 실무적(practical) 운영 관점에서도 과연 도입할 만큼 가치가 있는 것인지(Effect size)는 연구자가 독립적으로 숙고하고 임상적으로 판단해야 할 별개의 영역입니다.</p>
</section>
<section id="두-모수-신뢰-구간-추정" class="level2" data-number="6">
<h2 data-number="6" class="anchored" data-anchor-id="두-모수-신뢰-구간-추정"><span class="header-section-number">6</span> 두 모수 신뢰 구간 추정</h2>
<p>R 환경에서는 복잡한 수작업 계산 없이 <code>prop.test()</code>와 <code>t.test()</code> 함수를 통해 두 모수에 대한 신뢰 구간을 직관적으로 산출할 수 있습니다.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb1"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="co"># 1. 두 비율 차이에 대한 신뢰 구간</span></span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a><span class="co"># 퓨 리서치 설문 예시: 십 대(401/743) vs 성인(381/1058)</span></span>
<span id="cb1-3"><a href="#cb1-3" aria-hidden="true" tabindex="-1"></a>successes <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="dv">401</span>, <span class="dv">381</span>)</span>
<span id="cb1-4"><a href="#cb1-4" aria-hidden="true" tabindex="-1"></a>trials <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="dv">743</span>, <span class="dv">1058</span>)</span>
<span id="cb1-5"><a href="#cb1-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-6"><a href="#cb1-6" aria-hidden="true" tabindex="-1"></a>prop_ci <span class="ot">&lt;-</span> <span class="fu">prop.test</span>(</span>
<span id="cb1-7"><a href="#cb1-7" aria-hidden="true" tabindex="-1"></a>  <span class="at">x =</span> successes,</span>
<span id="cb1-8"><a href="#cb1-8" aria-hidden="true" tabindex="-1"></a>  <span class="at">n =</span> trials,</span>
<span id="cb1-9"><a href="#cb1-9" aria-hidden="true" tabindex="-1"></a>  <span class="at">conf.level =</span> <span class="fl">0.98</span>,</span>
<span id="cb1-10"><a href="#cb1-10" aria-hidden="true" tabindex="-1"></a>  <span class="at">correct =</span> <span class="cn">FALSE</span></span>
<span id="cb1-11"><a href="#cb1-11" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb1-12"><a href="#cb1-12" aria-hidden="true" tabindex="-1"></a><span class="fu">cat</span>(<span class="st">"98% 신뢰 구간: ("</span>, <span class="fu">round</span>(prop_ci<span class="sc">$</span>conf.int[<span class="dv">1</span>], <span class="dv">4</span>), <span class="st">","</span>, <span class="fu">round</span>(prop_ci<span class="sc">$</span>conf.int[<span class="dv">2</span>], <span class="dv">4</span>), <span class="st">")</span><span class="sc">\n</span><span class="st">"</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>98% 신뢰 구간: ( 0.1249 , 0.2343 )</code></pre>
</div>
</div>
<p>위 코드는 앞서 우리가 손으로 계산했던 구간 (0.1249, 0.2343)과 일치하는 결과를 반환합니다.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb3"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb3-1"><a href="#cb3-1" aria-hidden="true" tabindex="-1"></a><span class="co"># 2. 두 평균 차이에 대한 신뢰 구간</span></span>
<span id="cb3-2"><a href="#cb3-2" aria-hidden="true" tabindex="-1"></a><span class="co"># 임의의 시뮬레이션 데이터 생성</span></span>
<span id="cb3-3"><a href="#cb3-3" aria-hidden="true" tabindex="-1"></a><span class="fu">set.seed</span>(<span class="dv">42</span>)</span>
<span id="cb3-4"><a href="#cb3-4" aria-hidden="true" tabindex="-1"></a>group_a <span class="ot">&lt;-</span> <span class="fu">rnorm</span>(<span class="dv">30</span>, <span class="at">mean =</span> <span class="dv">50</span>, <span class="at">sd =</span> <span class="dv">10</span>)</span>
<span id="cb3-5"><a href="#cb3-5" aria-hidden="true" tabindex="-1"></a>group_b <span class="ot">&lt;-</span> <span class="fu">rnorm</span>(<span class="dv">35</span>, <span class="at">mean =</span> <span class="dv">45</span>, <span class="at">sd =</span> <span class="dv">15</span>)</span>
<span id="cb3-6"><a href="#cb3-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-7"><a href="#cb3-7" aria-hidden="true" tabindex="-1"></a><span class="co"># 이분산(Welch's) 가정을 적용한 신뢰 구간</span></span>
<span id="cb3-8"><a href="#cb3-8" aria-hidden="true" tabindex="-1"></a>t_ci_unequal <span class="ot">&lt;-</span> <span class="fu">t.test</span>(</span>
<span id="cb3-9"><a href="#cb3-9" aria-hidden="true" tabindex="-1"></a>  <span class="at">x =</span> group_a,</span>
<span id="cb3-10"><a href="#cb3-10" aria-hidden="true" tabindex="-1"></a>  <span class="at">y =</span> group_b,</span>
<span id="cb3-11"><a href="#cb3-11" aria-hidden="true" tabindex="-1"></a>  <span class="at">alternative =</span> <span class="st">"two.sided"</span>,</span>
<span id="cb3-12"><a href="#cb3-12" aria-hidden="true" tabindex="-1"></a>  <span class="at">var.equal =</span> <span class="cn">FALSE</span>, </span>
<span id="cb3-13"><a href="#cb3-13" aria-hidden="true" tabindex="-1"></a>  <span class="at">conf.level =</span> <span class="fl">0.95</span></span>
<span id="cb3-14"><a href="#cb3-14" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb3-15"><a href="#cb3-15" aria-hidden="true" tabindex="-1"></a><span class="fu">cat</span>(<span class="st">"95% 신뢰 구간: ("</span>, <span class="fu">round</span>(t_ci_unequal<span class="sc">$</span>conf.int[<span class="dv">1</span>], <span class="dv">4</span>), <span class="st">","</span>, <span class="fu">round</span>(t_ci_unequal<span class="sc">$</span>conf.int[<span class="dv">2</span>], <span class="dv">4</span>), <span class="st">")</span><span class="sc">\n</span><span class="st">"</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>95% 신뢰 구간: ( -0.1032 , 13.6906 )</code></pre>
</div>
</div>
<p>두 모집단의 분산이 동일하다고 확신할 만한 강력한 사전 근거가 없다면, 안전망 차원에서 기본값으로 설정된 웰치(Welch) 방식 근사(<code>var.equal = FALSE</code>)를 그대로 유지하는 것이 보수적이고 현명한 통계 분석가의 태도입니다.</p>
<p>만약 분석 데이터가 대응 표본(Paired data)이라면 두 집단 간에 필연적인 종속성이 흐르고 있으므로 반드시 <code>t.test</code> 호출 시 <code>paired = TRUE</code> 인자를 명시하여 R 엔진에 이 사실을 인지시켜야 합니다. 동일한 환자 집단의 약물 투여 전후 임상 수치 측정, 같은 구획의 농지에서 측정한 처리 전후 작물 수확량, 동일한 e-스포츠 선수의 강화 훈련 전후 반응 속도 기록처럼 명백히 짝이 지어진 데이터를 독립 표본 취급하여 함부로 분석하면, 분산과 표준 오차가 완전히 엉뚱하게 계산되어 돌이킬 수 없는 잘못된 의사결정으로 직결될 수 있습니다.</p>


</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
  window.document.addEventListener("DOMContentLoaded", function (event) {
    const icon = "";
    const anchorJS = new window.AnchorJS();
    anchorJS.options = {
      placement: 'right',
      icon: icon
    };
    anchorJS.add('.anchored');
    const isCodeAnnotation = (el) => {
      for (const clz of el.classList) {
        if (clz.startsWith('code-annotation-')) {                     
          return true;
        }
      }
      return false;
    }
    const onCopySuccess = function(e) {
      // button target
      const button = e.trigger;
      // don't keep focus
      button.blur();
      // flash "checked"
      button.classList.add('code-copy-button-checked');
      var currentTitle = button.getAttribute("title");
      button.setAttribute("title", "Copied!");
      let tooltip;
      if (window.bootstrap) {
        button.setAttribute("data-bs-toggle", "tooltip");
        button.setAttribute("data-bs-placement", "left");
        button.setAttribute("data-bs-title", "Copied!");
        tooltip = new bootstrap.Tooltip(button, 
          { trigger: "manual", 
            customClass: "code-copy-button-tooltip",
            offset: [0, -8]});
        tooltip.show();    
      }
      setTimeout(function() {
        if (tooltip) {
          tooltip.hide();
          button.removeAttribute("data-bs-title");
          button.removeAttribute("data-bs-toggle");
          button.removeAttribute("data-bs-placement");
        }
        button.setAttribute("title", currentTitle);
        button.classList.remove('code-copy-button-checked');
      }, 1000);
      // clear code selection
      e.clearSelection();
    }
    const getTextToCopy = function(trigger) {
      const outerScaffold = trigger.parentElement.cloneNode(true);
      const codeEl = outerScaffold.querySelector('code');
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
    const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
      text: getTextToCopy
    });
    clipboard.on('success', onCopySuccess);
    if (window.document.getElementById('quarto-embedded-source-code-modal')) {
      const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
        text: getTextToCopy,
        container: window.document.getElementById('quarto-embedded-source-code-modal')
      });
      clipboardModal.on('success', onCopySuccess);
    }
      var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
      var mailtoRegex = new RegExp(/^mailto:/);
        var filterRegex = new RegExp('/' + window.location.host + '/');
      var isInternal = (href) => {
          return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
      }
      // Inspect non-navigation links and adorn them if external
     var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
      for (var i=0; i<links.length; i++) {
        const link = links[i];
        if (!isInternal(link.href)) {
          // undo the damage that might have been done by quarto-nav.js in the case of
          // links that we want to consider external
          if (link.dataset.originalHref !== undefined) {
            link.href = link.dataset.originalHref;
          }
        }
      }
    function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
      const config = {
        allowHTML: true,
        maxWidth: 500,
        delay: 100,
        arrow: false,
        appendTo: function(el) {
            return el.parentElement;
        },
        interactive: true,
        interactiveBorder: 10,
        theme: 'quarto',
        placement: 'bottom-start',
      };
      if (contentFn) {
        config.content = contentFn;
      }
      if (onTriggerFn) {
        config.onTrigger = onTriggerFn;
      }
      if (onUntriggerFn) {
        config.onUntrigger = onUntriggerFn;
      }
      window.tippy(el, config); 
    }
    const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
    for (var i=0; i<noterefs.length; i++) {
      const ref = noterefs[i];
      tippyHover(ref, function() {
        // use id or data attribute instead here
        let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
        try { href = new URL(href).hash; } catch {}
        const id = href.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note) {
          return note.innerHTML;
        } else {
          return "";
        }
      });
    }
    const xrefs = window.document.querySelectorAll('a.quarto-xref');
    const processXRef = (id, note) => {
      // Strip column container classes
      const stripColumnClz = (el) => {
        el.classList.remove("page-full", "page-columns");
        if (el.children) {
          for (const child of el.children) {
            stripColumnClz(child);
          }
        }
      }
      stripColumnClz(note)
      if (id === null || id.startsWith('sec-')) {
        // Special case sections, only their first couple elements
        const container = document.createElement("div");
        if (note.children && note.children.length > 2) {
          container.appendChild(note.children[0].cloneNode(true));
          for (let i = 1; i < note.children.length; i++) {
            const child = note.children[i];
            if (child.tagName === "P" && child.innerText === "") {
              continue;
            } else {
              container.appendChild(child.cloneNode(true));
              break;
            }
          }
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(container);
          }
          return container.innerHTML
        } else {
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(note);
          }
          return note.innerHTML;
        }
      } else {
        // Remove any anchor links if they are present
        const anchorLink = note.querySelector('a.anchorjs-link');
        if (anchorLink) {
          anchorLink.remove();
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        if (note.classList.contains("callout")) {
          return note.outerHTML;
        } else {
          return note.innerHTML;
        }
      }
    }
    for (var i=0; i<xrefs.length; i++) {
      const xref = xrefs[i];
      tippyHover(xref, undefined, function(instance) {
        instance.disable();
        let url = xref.getAttribute('href');
        let hash = undefined; 
        if (url.startsWith('#')) {
          hash = url;
        } else {
          try { hash = new URL(url).hash; } catch {}
        }
        if (hash) {
          const id = hash.replace(/^#\/?/, "");
          const note = window.document.getElementById(id);
          if (note !== null) {
            try {
              const html = processXRef(id, note.cloneNode(true));
              instance.setContent(html);
            } finally {
              instance.enable();
              instance.show();
            }
          } else {
            // See if we can fetch this
            fetch(url.split('#')[0])
            .then(res => res.text())
            .then(html => {
              const parser = new DOMParser();
              const htmlDoc = parser.parseFromString(html, "text/html");
              const note = htmlDoc.getElementById(id);
              if (note !== null) {
                const html = processXRef(id, note);
                instance.setContent(html);
              } 
            }).finally(() => {
              instance.enable();
              instance.show();
            });
          }
        } else {
          // See if we can fetch a full url (with no hash to target)
          // This is a special case and we should probably do some content thinning / targeting
          fetch(url)
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.querySelector('main.content');
            if (note !== null) {
              // This should only happen for chapter cross references
              // (since there is no id in the URL)
              // remove the first header
              if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
                note.children[0].remove();
              }
              const html = processXRef(null, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      }, function(instance) {
      });
    }
        let selectedAnnoteEl;
        const selectorForAnnotation = ( cell, annotation) => {
          let cellAttr = 'data-code-cell="' + cell + '"';
          let lineAttr = 'data-code-annotation="' +  annotation + '"';
          const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
          return selector;
        }
        const selectCodeLines = (annoteEl) => {
          const doc = window.document;
          const targetCell = annoteEl.getAttribute("data-target-cell");
          const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
          const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
          const lines = annoteSpan.getAttribute("data-code-lines").split(",");
          const lineIds = lines.map((line) => {
            return targetCell + "-" + line;
          })
          let top = null;
          let height = null;
          let parent = null;
          if (lineIds.length > 0) {
              //compute the position of the single el (top and bottom and make a div)
              const el = window.document.getElementById(lineIds[0]);
              top = el.offsetTop;
              height = el.offsetHeight;
              parent = el.parentElement.parentElement;
            if (lineIds.length > 1) {
              const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
              const bottom = lastEl.offsetTop + lastEl.offsetHeight;
              height = bottom - top;
            }
            if (top !== null && height !== null && parent !== null) {
              // cook up a div (if necessary) and position it 
              let div = window.document.getElementById("code-annotation-line-highlight");
              if (div === null) {
                div = window.document.createElement("div");
                div.setAttribute("id", "code-annotation-line-highlight");
                div.style.position = 'absolute';
                parent.appendChild(div);
              }
              div.style.top = top - 2 + "px";
              div.style.height = height + 4 + "px";
              div.style.left = 0;
              let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
              if (gutterDiv === null) {
                gutterDiv = window.document.createElement("div");
                gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
                gutterDiv.style.position = 'absolute';
                const codeCell = window.document.getElementById(targetCell);
                const gutter = codeCell.querySelector('.code-annotation-gutter');
                gutter.appendChild(gutterDiv);
              }
              gutterDiv.style.top = top - 2 + "px";
              gutterDiv.style.height = height + 4 + "px";
            }
            selectedAnnoteEl = annoteEl;
          }
        };
        const unselectCodeLines = () => {
          const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
          elementsIds.forEach((elId) => {
            const div = window.document.getElementById(elId);
            if (div) {
              div.remove();
            }
          });
          selectedAnnoteEl = undefined;
        };
          // Handle positioning of the toggle
      window.addEventListener(
        "resize",
        throttle(() => {
          elRect = undefined;
          if (selectedAnnoteEl) {
            selectCodeLines(selectedAnnoteEl);
          }
        }, 10)
      );
      function throttle(fn, ms) {
      let throttle = false;
      let timer;
        return (...args) => {
          if(!throttle) { // first call gets through
              fn.apply(this, args);
              throttle = true;
          } else { // all the others get throttled
              if(timer) clearTimeout(timer); // cancel #2
              timer = setTimeout(() => {
                fn.apply(this, args);
                timer = throttle = false;
              }, ms);
          }
        };
      }
        // Attach click handler to the DT
        const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
        for (const annoteDlNode of annoteDls) {
          annoteDlNode.addEventListener('click', (event) => {
            const clickedEl = event.target;
            if (clickedEl !== selectedAnnoteEl) {
              unselectCodeLines();
              const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
              if (activeEl) {
                activeEl.classList.remove('code-annotation-active');
              }
              selectCodeLines(clickedEl);
              clickedEl.classList.add('code-annotation-active');
            } else {
              // Unselect the line
              unselectCodeLines();
              clickedEl.classList.remove('code-annotation-active');
            }
          });
        }
    const findCites = (el) => {
      const parentEl = el.parentElement;
      if (parentEl) {
        const cites = parentEl.dataset.cites;
        if (cites) {
          return {
            el,
            cites: cites.split(' ')
          };
        } else {
          return findCites(el.parentElement)
        }
      } else {
        return undefined;
      }
    };
    var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
    for (var i=0; i<bibliorefs.length; i++) {
      const ref = bibliorefs[i];
      const citeInfo = findCites(ref);
      if (citeInfo) {
        tippyHover(citeInfo.el, function() {
          var popup = window.document.createElement('div');
          citeInfo.cites.forEach(function(cite) {
            var citeDiv = window.document.createElement('div');
            citeDiv.classList.add('hanging-indent');
            citeDiv.classList.add('csl-entry');
            var biblioDiv = window.document.getElementById('ref-' + cite);
            if (biblioDiv) {
              citeDiv.innerHTML = biblioDiv.innerHTML;
            }
            popup.appendChild(citeDiv);
          });
          return popup.innerHTML;
        });
      }
    }
  });
  </script>
</div> <!-- /content -->




</body></html>