<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.9.38">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>R 튜토리얼: R에서의 통계적 추론(statistical inference)</title>
<style>
/* Default styles provided by pandoc.
** See https://pandoc.org/MANUAL.html#variables-for-html for config info.
*/
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
html { -webkit-text-size-adjust: 100%; }
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="../site_libs/quarto-nav/quarto-nav.js"></script>
<script src="../site_libs/quarto-nav/headroom.min.js"></script>
<script src="../site_libs/clipboard/clipboard.min.js"></script>
<script src="../site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="../site_libs/quarto-search/fuse.min.js"></script>
<script src="../site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="../">
<script src="../site_libs/quarto-html/quarto.js" type="module"></script>
<script src="../site_libs/quarto-html/tabsets/tabsets.js" type="module"></script>
<script src="../site_libs/quarto-html/popper.min.js"></script>
<script src="../site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="../site_libs/quarto-html/anchor.min.js"></script>
<link href="../site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="../site_libs/quarto-html/quarto-syntax-highlighting-15634bcf2e68342d4ad2dfa704d543f6.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="../site_libs/bootstrap/bootstrap.min.js"></script>
<link href="../site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="../site_libs/bootstrap/bootstrap-cf5ee1d16def7895729d1ac812351ea4.min.css" rel="stylesheet" append-hash="true" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "sidebar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "start",
  "type": "textbox",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>

  <script src="https://cdnjs.cloudflare.com/polyfill/v3/polyfill.min.js?features=es6"></script>
  <script defer="" src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

<script type="text/javascript">
const typesetMath = (el) => {
  if (window.MathJax) {
    // MathJax Typeset
    window.MathJax.typeset([el]);
  } else if (window.katex) {
    // KaTeX Render
    var mathElements = el.getElementsByClassName("math");
    var macros = [];
    for (var i = 0; i < mathElements.length; i++) {
      var texText = mathElements[i].firstChild;
      if (mathElements[i].tagName == "SPAN" && texText && texText.data) {
        window.katex.render(texText.data, mathElements[i], {
          displayMode: mathElements[i].classList.contains('display'),
          throwOnError: false,
          macros: macros,
          fleqn: false
        });
      }
    }
  }
}
window.Quarto = {
  typesetMath
};
</script>

</head>

<body class="nav-sidebar docked fullcontent quarto-light">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
  <nav class="quarto-secondary-nav">
    <div class="container-fluid d-flex">
      <button type="button" class="quarto-btn-toggle btn" data-bs-toggle="collapse" role="button" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
        <i class="bi bi-layout-text-sidebar-reverse"></i>
      </button>
        <nav class="quarto-page-breadcrumbs" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item">R 튜토리얼: R에서의 통계적 추론(statistical inference)</li></ol></nav>
        <a class="flex-grow-1" role="navigation" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">      
        </a>
      <button type="button" class="btn quarto-search-button" aria-label="Search" onclick="window.quartoOpenSearch();">
        <i class="bi bi-search"></i>
      </button>
    </div>
  </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article">
<!-- sidebar -->
  <nav id="quarto-sidebar" class="sidebar collapse collapse-horizontal quarto-sidebar-collapse-item sidebar-navigation docked overflow-auto">
        <div class="mt-2 flex-shrink-0 align-items-center">
        <div class="sidebar-search">
        <div id="quarto-search" class="" title="Search"></div>
        </div>
        </div>
    <div class="sidebar-menu-container"> 
    <ul class="list-unstyled mt-1">
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../notes/ch01.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">통계학의 중요성!</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../notes/ch02.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">R 입문</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../notes/ch03.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">데이터 수집: 방법 및 고려 사항</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../notes/ch04.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">데이터 추출, 난수, 그리고 무작위 표본 선택</span></a>
  </div>
</li>
    </ul>
    </div>
</nav>
<div id="quarto-sidebar-glass" class="quarto-sidebar-collapse-item" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item"></div>
<!-- margin-sidebar -->
    
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">R 튜토리얼: R에서의 통계적 추론(statistical inference)</h1>
</div>



<div class="quarto-title-meta">

    
  
    
  </div>
  


</header>


<section id="서론" class="level2">
<h2 class="anchored" data-anchor-id="서론">서론</h2>
<p>지난 몇 장에서 보았듯이, 가설 검정(hypothesis test)과 신뢰 구간(confidence interval)은 특히 소규모 데이터 세트(dataset)에서 대부분 수작업으로 수행할 수 있는 두 가지 통계 기법입니다. 그러나 현대의 데이터 세트로 작업할 때 흔히 그렇듯이, 실제 데이터는 종종 수백 개 또는 수천 개의 관측값(observation)을 갖는 크고 복잡할 수 있습니다. 이 경우, 이러한 추론 기법을 수작업으로 수행하는 것은 불가능하지는 않더라도 비실용적입니다. 다행히도 R은 이전에 논의한 탐색적 데이터 분석(exploratory data analysis)과 그래프를 제공할 뿐만 아니라, 우리가 논의한 모든 가설 검정과 신뢰 구간에 대해 확률과 p-값(p-value)뿐만 아니라 통계적 추론 전체를 수행할 수 있게 해줍니다.</p>
</section>
<section id="올바른-검정-선택하기" class="level2">
<h2 class="anchored" data-anchor-id="올바른-검정-선택하기">올바른 검정 선택하기</h2>
<p>가설 검정의 한 가지 중요한 측면은 어떤 검정을 사용해야 하는지 인식하는 것입니다. 앞서 말했듯이, 어떤 검정을 사용할지 아는 것은 세 가지 질문으로 요약되며, 이 질문들은 모두 우리의 반응(response)과 표본(sample)과 관련이 있습니다. 세 가지 질문은 다음과 같습니다.</p>
<ol type="1">
<li>우리의 반응이 범주형(categorical)입니까, 아니면 양적(quantitative)입니까?</li>
<li>우리 데이터에 하나 또는 두 개의 표본이 있습니까?</li>
<li>표본이 두 개인 경우, 표본이 독립적입니까? 즉, 표본 사이에 겹침이나 연결이 있습니까?</li>
</ol>
<p>이 질문들을 하나씩 살펴보겠습니다. 먼저 반응이 범주형인지 양적인지부터 시작합니다. 비율에 대한 두 가지 검정인 단일 표본 및 두 표본 비율 검정은 범주형 반응을 다루는 반면, 평균에 대한 세 가지 검정인 단일 표본 t-검정(t-test), 두 표본 t-검정 및 대응 t-검정(paired t-test)은 양적 반응의 결과입니다.</p>
<p>둘째, 데이터의 표본 수를 살펴보겠습니다. 분명히 두 표본 검정인 두 표본 비율 검정, 평균에 대한 두 표본 t-검정 및 평균에 대한 대응 t-검정은 모두 두 개의 표본을 포함합니다. 단일 표본 검정인 단일 표본 비율 검정과 평균에 대한 단일 표본 t-검정은 단일 데이터 표본을 포함합니다.</p>
<p>마지막으로 표본이 독립적인지 고려해야 합니다. 두 표본 검정 중 오직 하나만이 독립적이지 않은데, 바로 대응 t-검정입니다. 이 검정에서는 두 표본 사이에 겹침이 있거나(예: 두 가지 처치를 경험하는 피험자), 표본 사이에 일종의 연결이 있습니다. 일반적으로 그림 17.1의 차트를 보고 올바른 검정 방법을 찾습니다.</p>
</section>
<section id="비율에-대한-추론" class="level2">
<h2 class="anchored" data-anchor-id="비율에-대한-추론">비율에 대한 추론</h2>
<p>가설 검정을 논의하면서 비율과 관련된 두 가지 가설 검정에 대해 배웠습니다. 단일 표본 비율 검정은 단일 모집단 비율(population proportion)이 단일 값과 같은지 또는 다른지 검정하는 것을 다루었습니다. 두 표본 비율 검정은 두 집단의 모집단 비율이 같은지 아니면 어떤 값과 다른지 검정하는 것을 다루었습니다. 마찬가지로 신뢰 구간을 논의할 때 모집단 비율과 관련된 두 가지 신뢰 구간에 대해 배웠습니다. 이 구간들 각각은 이전에 언급한 가설 검정 중 하나에 대응했습니다. p에 대한 <span class="math inline">\((1-\alpha)100\)</span>% 신뢰 구간은 단일 모집단 비율에 대한 구간 추정치(interval estimate)를 제공한 반면, <span class="math inline">\(p_1-p_2\)</span>에 대한 <span class="math inline">\((1-\alpha)100\)</span>% 신뢰 구간은 <span class="math inline">\(p_1-p_2\)</span>에 대해 타당한 값들을 조사했습니다.</p>
<p>총 4개인 이러한 구간과 검정은 모집단 비율에 대한 통계적 추론을 수행하기 위한 우리의 선택지를 나타냅니다. 다행히 R은 이 모든 것을 동일한 함수로 수행하게 함으로써 이러한 추론 방법을 간단하게 구현할 수 있게 해줍니다. prop.test 함수를 사용하면 비율에 대한 가설 검정과 신뢰 구간을 수행할 수 있습니다. 이를 실행하는 코드는 단일 표본 검정 및 구간을 수행하는지 아니면 두 표본 검정 및 구간을 수행하는지에 따라 달라집니다. 먼저 단일 표본 비율 검정부터 살펴보겠습니다.</p>
<section id="단일-비율에-대한-추론" class="level3">
<h3 class="anchored" data-anchor-id="단일-비율에-대한-추론">단일 비율에 대한 추론</h3>
<p>단일 표본 비율 검정의 경우, prop.test 함수는 다섯 개의 인자(argument)를 받습니다. 표본에서의 성공 횟수 x, 표본 크기 n, 귀무 가설(null hypothesis) 값 p, 대립 가설(alternative hypothesis) <span class="math inline">\(alternative\)</span>, 그리고 연속성 수정(continuity correction) <span class="math inline">\(correct\)</span> 적용 여부입니다.</p>
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb1"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="fu">prop.test</span>(<span class="at">x =</span> x, <span class="at">n =</span> n, <span class="at">p =</span> p, <span class="at">alternative =</span> alternative, <span class="at">correct =</span> correct)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<p>함수에 대한 두 가지 참고 사항입니다. <span class="math inline">\(correct\)</span> 인자는 표본에 연속성 수정을 적용할지 여부를 명시하는 TRUE/FALSE 옵션입니다. 소규모 표본에서는 중심 극한 정리(central limit theorem)가 성립하도록 하기 위해 때때로 이를 수행합니다. 그러나 이 조정은 가끔 과도하게 수정되어 일반적으로 수정이 바람직하지 않게 만들기도 합니다. 따라서 우리는 응용 전반에 걸쳐 이 인자를 FALSE로 설정할 것입니다. 둘째, <span class="math inline">\(alternative\)</span> 인자는 세 가지 대립 가설에 기초한 세 가지 가능한 옵션과 함께 우리의 대립 가설이 무엇인지 정의됩니다.</p>
<table class="caption-top table">
<thead>
<tr class="header">
<th>H_A</th>
<th>R-코드</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>H_A:p &lt; p0</td>
<td>alternative = “less”</td>
</tr>
<tr class="even">
<td>H_A:p &gt; p0</td>
<td>alternative = “greater”</td>
</tr>
<tr class="odd">
<td>H_A:p ≠ p0</td>
<td>alternative = “two.sided”</td>
</tr>
</tbody>
</table>
<p>그럼 함수가 어떻게 작동하는지 예제를 통해 살펴보겠습니다. 단일 표본 비율 검정을 단계별로 살펴볼 때 사용했던 예제를 사용하겠습니다. 이 예제에서 우리는 스위트 브라이어 칼리지(Sweet Briar College)의 레거시 학생(legacy student) 비율이 전국 평균인 14%와 다른지 묻고 있었습니다. 이를 검정하기 위해 79명의 학생 표본을 수집했고 그중 12명이 레거시 학생임을 발견했습니다. 이 경우 우리의 가설은 다음과 같았습니다.</p>
<p><span class="math display">\[
H_0:p=0.14H_A:p≠0.14.
\]</span> 이 검정을 수행하기 위해 성공 횟수—<span class="math inline">\(x=12\)</span>—표본 크기—<span class="math inline">\(n=79\)</span>—귀무 값—<span class="math inline">\(p=0.14\)</span>—그리고 대립 가설—alternative = “two.sided”가 필요합니다. 만약 데이터 세트가 csv 파일을 통해 R로 로드되었다면 table 함수를 사용하여 성공 횟수를 찾을 수 있었을 것입니다. R에서 이 검정을 수행하는 코드는 다음과 같습니다.</p>
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb2"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb2-1"><a href="#cb2-1" aria-hidden="true" tabindex="-1"></a><span class="fu">prop.test</span>(</span>
<span id="cb2-2"><a href="#cb2-2" aria-hidden="true" tabindex="-1"></a>  <span class="at">x =</span> <span class="dv">12</span>,</span>
<span id="cb2-3"><a href="#cb2-3" aria-hidden="true" tabindex="-1"></a>  <span class="at">n =</span> <span class="dv">79</span>,</span>
<span id="cb2-4"><a href="#cb2-4" aria-hidden="true" tabindex="-1"></a>  <span class="at">p =</span> <span class="fl">0.14</span>,</span>
<span id="cb2-5"><a href="#cb2-5" aria-hidden="true" tabindex="-1"></a>  <span class="at">alternative =</span> <span class="st">"two.sided"</span>,</span>
<span id="cb2-6"><a href="#cb2-6" aria-hidden="true" tabindex="-1"></a>  <span class="at">correct =</span> <span class="cn">FALSE</span></span>
<span id="cb2-7"><a href="#cb2-7" aria-hidden="true" tabindex="-1"></a>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<p>그러면 R은 가설 검정 절차와 관련된 여러 결과를 출력할 것입니다.</p>
<pre class="text"><code>        1-sample proportions test without continuity correction

data:  12 out of 79, null probability 0.14
X-squared = 0.092897, df = 1, p-value = 0.7605
alternative hypothesis: true p is not equal to 0.14
95 percent confidence interval:
 0.08908268 0.24699854
sample estimates:
        p
0.1518987</code></pre>
<p>여기에는 살펴볼 내용이 많으며, 그중 일부는 직관적입니다. 첫 번째 중요한 출력값은 X-squared 값으로, 이는 검정 통계량(test statistic)의 제곱을 제공합니다. 만약 우리가 익숙한 공식을 사용하여 수작업으로 검정 통계량을 계산했다면, <span class="math inline">\(\hat{p}\)</span>이 <span class="math inline">\(p_0\)</span>보다 크면 X-squared의 양의 제곱근을 얻고, <span class="math inline">\(\hat{p}\)</span>이 <span class="math inline">\(p_0\)</span>보다 작으면 X-squared의 음의 제곱근을 얻었을 것입니다. 따라서 우리 예제의 경우 <span class="math inline">\(\hat{p}=0.1519\)</span>가 귀무 가설 값인 0.14보다 크므로 검정 통계량은 <span class="math inline">\(+0.0929=0.3048\)</span>이 되며, 이는 수작업으로 했을 때 얻은 값과 같습니다. prop.test가 검정 통계량 대신 검정 통계량의 제곱을 보고하는 이유는 이 함수가 통계학의 두 번째 과정에서 배울 수 있는 보다 일반적인 형태의 비율 검정인 카이제곱 독립성 검정(chi-squared test for independence)과 직접적으로 연결되어 있기 때문입니다.</p>
<p>다음으로 p-값이 있는데, 이는 말 그대로 검정 통계량과 대립 가설에 기초한 가설 검정의 p-값입니다. 여기서 p-값은 0.7605이며, 이는 우리가 선택할 어떤 합리적인 유의 수준(significance level)보다도 클 것입니다. 이 역시 단계별로 검정을 진행했을 때 얻은 결과와 일치합니다.</p>
<p>함수는 몇 가지 다른 결과(표본 비율 <span class="math inline">\(\hat{p}\)</span>, 대립 가설)를 반환하지만, 하나가 특히 흥미롭습니다. 함수가 결과에 기초하여 p에 대한 95% 신뢰 구간을 출력하는 것을 볼 수 있습니다. 이것은 95% 신뢰 구간을 원할 때 유용하지만, 90% 또는 99% 신뢰 구간을 원할 때는 어떨까요? prop.test 함수에는 우리가 원하는 어떤 신뢰 구간이든 제공하는 추가 옵션인 신뢰 수준(confidence level) conf.level이 있는 것으로 밝혀졌습니다.</p>
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb4"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb4-1"><a href="#cb4-1" aria-hidden="true" tabindex="-1"></a><span class="fu">prop.test</span>(<span class="at">x =</span> x, <span class="at">n =</span> n, <span class="at">p =</span> p, <span class="at">alternative =</span> alternative, <span class="at">correct =</span> correct, <span class="at">conf.level =</span> conf.level)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<p>함수에서 conf.level은 항상 기본적으로 0.95로 설정되어 있어, 우리가 변경하지 않는 한 95% 신뢰 구간을 반환합니다. 대신 90% 신뢰 구간을 원한다면 conf.level=0.9로 설정합니다. 99%의 경우 conf.level=0.99를 사용합니다. 이전 예제에서 p에 대한 99% 신뢰 구간을 원한다고 가정해 보겠습니다. 동일한 코드를 사용하고 conf.level=0.99를 추가하면 p에 대한 99% 신뢰 구간을 찾을 수 있습니다. 함수 출력에서 찾은 결과는 <span class="math inline">\((0.07538655,0.28235191)\)</span>입니다. 이러한 신뢰 구간에서 주의해야 할 한 가지 중요한 규칙은 단일 표본의 경우 prop.test가 올바른 신뢰 구간을 반환하려면 alternative 옵션을 “two.sided”로 설정해야 한다는 것입니다. 그렇지 않으면 함수 출력은 alternative 인자가 어떻게 설정되었는지에 따라 타당한 값들의 상위 또는 하위 <span class="math inline">\((1-\alpha)100\)</span>%에 기초한 잘못된 구간을 반환할 것입니다.</p>
</section>
<section id="두-비율에-대한-추론" class="level3">
<h3 class="anchored" data-anchor-id="두-비율에-대한-추론">두 비율에 대한 추론</h3>
<p>이것으로 단일 표본 검정과 신뢰 구간을 마무리했습니다. 두 표본의 경우는 어떨까요? 앞서 prop.test 함수가 두 표본 검정 및 구간에 사용될 수 있다고 말했으며, 결과적으로 두 표본 검정에 필요한 코드는 거의 동일한 것으로 나타났습니다. 이 경우 인자는 두 표본 모두에서의 성공 횟수 x, 표본 크기 n, 대립 가설 <span class="math inline">\(alternative\)</span>, 연속성 수정 <span class="math inline">\(correct\)</span>, 그리고 원한다면 신뢰 구간을 위한 신뢰 수준 <span class="math inline">\(conf.level\)</span>입니다.</p>
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb5"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb5-1"><a href="#cb5-1" aria-hidden="true" tabindex="-1"></a><span class="fu">prop.test</span>(<span class="at">x =</span> x, <span class="at">n =</span> n, <span class="at">alternative =</span> alternative, <span class="at">correct =</span> correct, <span class="at">conf.level =</span> conf.level)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<p>여기서 중요한 변화는 성공 횟수 x와 표본 크기 n에서 발생합니다. 이전에는 단일 표본만 다루었으므로 이들은 단일 값이었습니다. 여기서는 비교할 두 집단이 있으므로 x와 n은 모두 값들의 벡터(vector)가 될 것입니다. x의 성공 횟수 순서가 n의 표본 크기 순서와 일치하는지 확인하는 것이 중요합니다. 또한 대립 가설과 alternative 옵션은 이 순서에 영향을 받습니다. 예를 들어, “greater” 옵션은 HA:<span class="math inline">\(p_1&gt;p_2\)</span>를 의미하며, 여기서 모집단 비율 <span class="math inline">\(p_1\)</span>을 갖는 첫 번째 집단은 x와 n에 첫 번째로 입력된 성공 횟수와 표본 크기에 의해 정의됩니다. 따라서 우리는 x와 n의 순서가 alternative 인자가 의미하는 바와 일치하는지 확인해야 합니다.</p>
<p>예를 들어, 두 표본 비율 검정의 단계를 배우는 동안 살펴보았던 예제 [55]를 다시 살펴보겠습니다. 이 예제에서 퓨 리서치 그룹(Pew Research Group)은 667명의 밀레니얼 세대(Millenial)와 558명의 X세대(Generation Xer)에게 미국이 우주 탐사 분야에서 세계적인 리더가 되는 것이 필수적이라고 생각하는지 물었습니다. 467명의 밀레니얼 세대와 407명의 X세대가 질문에 “예”라고 답했습니다. 우리는 궁극적으로 이 두 집단의 모집단 비율 사이에 차이가 있는지 검정하고 싶었습니다. 이 경우 가설은 다음과 같습니다.</p>
<p><span class="math display">\[
H_0:p_{Millenial}-p_{Gen}X=0H_A:p_{Millenial}-p_{Gen}X≠0
\]</span> 여기에서 성공 횟수는 <span class="math inline">\(x=c(467,407)\)</span>가 되고 표본 크기는 <span class="math inline">\(n=c(667,558)\)</span>이 됩니다. 모두 합치면 코드는 다음과 같습니다.</p>
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb6"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb6-1"><a href="#cb6-1" aria-hidden="true" tabindex="-1"></a><span class="fu">prop.test</span>(</span>
<span id="cb6-2"><a href="#cb6-2" aria-hidden="true" tabindex="-1"></a>  <span class="at">x =</span> <span class="fu">c</span>(<span class="dv">467</span>, <span class="dv">407</span>),</span>
<span id="cb6-3"><a href="#cb6-3" aria-hidden="true" tabindex="-1"></a>  <span class="at">n =</span> <span class="fu">c</span>(<span class="dv">667</span>, <span class="dv">558</span>),</span>
<span id="cb6-4"><a href="#cb6-4" aria-hidden="true" tabindex="-1"></a>  <span class="at">alternative =</span> <span class="st">"two.sided"</span>,</span>
<span id="cb6-5"><a href="#cb6-5" aria-hidden="true" tabindex="-1"></a>  <span class="at">correct =</span> <span class="cn">FALSE</span></span>
<span id="cb6-6"><a href="#cb6-6" aria-hidden="true" tabindex="-1"></a>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<p>이 코드의 결과 출력은 아래와 같습니다. 다시 말하지만, 검정 통계량은 X-squared의 양 또는 음의 제곱근이 됩니다. <span class="math inline">\(\hat{p}_1&gt;\hat{p}_2\)</span>이면 양수이고 <span class="math inline">\(\hat{p}_1&lt;\hat{p}_2\)</span>이면 음수입니다. 이 경우 <span class="math inline">\(\hat{p}_1&lt;\hat{p}_2\)</span>이므로 검정 통계량은 X-squared의 음의 제곱근인 <span class="math inline">\(-1.2707=-1.127\)</span>입니다. 검정 통계량과 대립 가설에 의해 결정된 p-값은 0.2596이며, 이는 우리의 유의 수준보다 높을 가능성이 큽니다.</p>
<pre class="text"><code>      2-sample test for equality of proportions without continuity
      correction

data:  c(467, 407) out of c(667, 558)
X-squared = 1.2707, df = 1, p-value = 0.2596
alternative hypothesis: two.sided
95 percent confidence interval:
 -0.07991559  0.02143408
sample estimates:
   prop 1    prop 2
0.7001499 0.7293907</code></pre>
<p>단일 표본의 경우와 마찬가지로 conf.level 옵션을 변경하여 <span class="math inline">\(p_1-p_2\)</span>에 대한 <span class="math inline">\((1-\alpha)100\)</span>% 신뢰 구간을 찾을 수 있습니다. 또한 이전과 마찬가지로 prop.test가 올바른 신뢰 구간을 반환하려면 alternative 옵션을 “two.sided”로 설정해야 합니다. 따라서 우리 예제에서 <span class="math inline">\(pMillenial-pX\)</span>에 대한 90% 신뢰 구간을 찾으려면 코드에 conf.level=0.9만 추가하면 90% 신뢰 구간인 (−0.07176842, 0.01328690)을 얻을 수 있습니다.</p>
</section>
<section id="연습-문제" class="level3">
<h3 class="anchored" data-anchor-id="연습-문제">연습 문제</h3>
<ol type="1">
<li>한 설문 조사에서 남성과 여성의 왼손잡이 비율이 다른지 알아보고자 했습니다. 조사 결과 여성 117명 중 7명, 남성 118명 중 10명이 왼손잡이였습니다. <span class="math inline">\(\alpha=0.1\)</span> 수준에서 HA:pF−pM≠<span class="math inline">\(0\)</span>인 가설 검정을 수행하고, <span class="math inline">\(pF-pM\)</span>에 대한 87% 신뢰 구간을 구해 보세요 [10].</li>
<li>1,500명의 미국인을 대상으로 한 2018년 퓨 리서치 그룹 설문 조사에서 705명이 중국에 대해 부정적인 견해를 가졌습니다. <span class="math inline">\(\alpha=0.05\)</span> 수준에서 HA:<span class="math inline">\(p&lt;0.5\)</span>인 가설 검정을 수행하고, p에 대한 93% 신뢰 구간을 구해 보세요 [74].</li>
<li>1987년의 한 설문 조사에 따르면 대학에 진학한 아내 212명 중 171명의 남편도 대학에 진학했습니다. 한편 대학에 진학하지 않은 아내 541명 중 124명의 남편만이 대학에 진학했습니다. <span class="math inline">\(\alpha=0.05\)</span> 수준에서 HA:<span class="math inline">\(pWifeCollege-pWifeNone&gt;0\)</span>인 가설 검정을 수행해 주세요(여기서 p는 남편이 대학에 진학했을 확률입니다). 또한 <span class="math inline">\(pWifeCollege-pWifeNone\)</span>에 대한 98% 신뢰 구간을 계산해 보세요 [48,104].</li>
<li>동일한 설문 조사에서 기혼 여성 753명 중 428명이 경제 활동에 참여하고 있음을 발견했습니다. <span class="math inline">\(\alpha=0.01\)</span> 수준에서 HA:<span class="math inline">\(p&gt;0.5\)</span>인 가설 검정을 수행하고, p에 대한 84% 신뢰 구간을 구해 보세요 [48,104].</li>
</ol>
</section>
</section>
<section id="평균에-대한-추론" class="level2">
<h2 class="anchored" data-anchor-id="평균에-대한-추론">평균에 대한 추론</h2>
<p>비율에 대한 가설 검정 외에도 평균에 대한 다양한 추론 기법에 대해서도 논의했습니다. 여기에는 그에 대응하는 신뢰 구간뿐만 아니라 평균에 대한 단일 표본 t-검정, 두 표본 t-검정 및 대응 t-검정이 포함되었습니다. 비율에 대한 추론과 유사하게, 이 모든 다양한 옵션은 하나의 단일 함수인 t.test로 수행할 수 있습니다. 이 모든 다양한 검정과 구간을 수행하기 위한 코드의 변형을 논의하기 위해, 각 검정에 대해 함수가 어떻게 작동하는지 살펴보겠습니다.</p>
<section id="단일-평균에-대한-추론" class="level3">
<h3 class="anchored" data-anchor-id="단일-평균에-대한-추론">단일 평균에 대한 추론</h3>
<p>평균에 대한 단일 표본 t-검정의 경우, t.test 함수는 데이터 표본 x, 귀무 값 mu, 그리고 대립 가설 <span class="math inline">\(alternative\)</span>의 세 가지 인자를 필요로 합니다.</p>
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb8"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb8-1"><a href="#cb8-1" aria-hidden="true" tabindex="-1"></a><span class="fu">t.test</span>(<span class="at">x =</span> x, <span class="at">mu =</span> mu, <span class="at">alternative =</span> alternative)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<p>우리 데이터 세트 x는 데이터 프레임(data frame)에서 가져오거나 수동으로 입력한 데이터 값을 포함하는 벡터입니다. 귀무 값 mu는 귀무 가설에서 발견되는 수치 값으로, prop.test 함수의 p와 동등합니다. 마지막으로 <span class="math inline">\(alternative\)</span> 인자는 prop.test 함수에서와 동일하게 대립 가설에 의해 정의됩니다.</p>
<table class="caption-top table">
<thead>
<tr class="header">
<th>H_A</th>
<th>R-코드</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>H_A:μ &lt; μ0</td>
<td>alternative = “less”</td>
</tr>
<tr class="even">
<td>H_A:μ &gt; μ0</td>
<td>alternative = “greater”</td>
</tr>
<tr class="odd">
<td>H_A:μ ≠ μ0</td>
<td>alternative = “two.sided”</td>
</tr>
</tbody>
</table>
<p>이를 설명하기 위해 단일 표본 평균 검정을 설명하는 데 사용했던 예제를 살펴보겠습니다. 우리는 비디오 슬롯 머신(video slot machine)의 평균 지불금(payout)이 이론적 지불금인 $13.13보다 작거나 같은지 검정했습니다. 이 데이터는 DAAG 라이브러리의 vlt 데이터 세트에서 찾을 수 있습니다 [23,44]. 플레이한 345개 게임의 지불 금액은 데이터 세트의 prize 변수에 들어 있습니다. 따라서 가설 검정을 수행하기 위해 다음 코드를 사용할 것입니다.</p>
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb9"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb9-1"><a href="#cb9-1" aria-hidden="true" tabindex="-1"></a><span class="fu">t.test</span>(</span>
<span id="cb9-2"><a href="#cb9-2" aria-hidden="true" tabindex="-1"></a>  <span class="at">x =</span> vlt<span class="sc">$</span>prize,</span>
<span id="cb9-3"><a href="#cb9-3" aria-hidden="true" tabindex="-1"></a>  <span class="at">mu =</span> <span class="fl">13.13</span>,</span>
<span id="cb9-4"><a href="#cb9-4" aria-hidden="true" tabindex="-1"></a>  <span class="at">alternative =</span> <span class="st">"less"</span></span>
<span id="cb9-5"><a href="#cb9-5" aria-hidden="true" tabindex="-1"></a>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<p>그러면 R은 다음 출력을 반환합니다. prop.test 함수와 마찬가지로 t.test 출력은 가설 검정에 필요한 모든 것을 포함합니다. 출력에서 t 값은 이전 장에서 본 공식을 사용한 검정 통계량의 값입니다. df 값은 이 검정의 자유도(degrees of freedom)이며, 이전처럼 <span class="math inline">\(df=n-1\)</span>로 계산됩니다(여기서 n은 표본 크기입니다). p-값은 물론 검정 통계량과 대립 가설에 관해 계산된 우리의 p-값입니다. 보다시피, 이 모든 것이 이전에 보았던 결과와 일치합니다.</p>
<pre class="text"><code>        One Sample t-test

data:  vlt$prize
t = -90.718, df = 344, p-value &lt; 2.2e-16
alternative hypothesis: true mean is less than 13.13
95 percent confidence interval:
      -Inf 0.8989483
sample estimates:
mean of x
0.6724638</code></pre>
<p>prop.test 함수와 마찬가지로, 가설 검정을 수행하는 동일한 함수를 사용하여 <span class="math inline">\((1-\alpha)100\)</span>% 신뢰 구간(이 경우에는 μ에 대한 신뢰 구간)을 생성할 수 있습니다. 기본적으로 t.test 함수는 95% 신뢰 구간을 반환합니다. 그러나 prop.test 함수에서 보았던 것과 동일한 <span class="math inline">\(conf.level\)</span> 인자를 사용하여 구간에 대해 원하는 신뢰 수준을 변경할 수 있습니다.</p>
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb11"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb11-1"><a href="#cb11-1" aria-hidden="true" tabindex="-1"></a><span class="fu">t.test</span>(<span class="at">x =</span> x, <span class="at">mu =</span> <span class="dv">0</span>, <span class="at">alternative =</span> alternative, <span class="at">conf.level =</span> conf.level)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<p>prop.test 함수와 마찬가지로, 우리가 익숙한 공식을 사용하여 신뢰 구간을 얻으려면 대립 가설을 <code>alternative = "two.sided"</code>로 설정해야 합니다. 따라서 기계의 실제 평균 지불금에 대한 99% 신뢰 구간을 원한다고 가정해 보겠습니다. μ에 대한 99% 신뢰 구간 <span class="math inline">\((0.3167728,1.0281548)\)</span>은 다음 코드를 사용하여 생성할 수 있습니다.</p>
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb12"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb12-1"><a href="#cb12-1" aria-hidden="true" tabindex="-1"></a><span class="fu">t.test</span>(</span>
<span id="cb12-2"><a href="#cb12-2" aria-hidden="true" tabindex="-1"></a>  <span class="at">x =</span> vlt<span class="sc">$</span>prize,</span>
<span id="cb12-3"><a href="#cb12-3" aria-hidden="true" tabindex="-1"></a>  <span class="at">mu =</span> <span class="fl">13.13</span>,</span>
<span id="cb12-4"><a href="#cb12-4" aria-hidden="true" tabindex="-1"></a>  <span class="at">alternative =</span> <span class="st">"two.sided"</span>,</span>
<span id="cb12-5"><a href="#cb12-5" aria-hidden="true" tabindex="-1"></a>  <span class="at">conf.level =</span> <span class="fl">0.99</span></span>
<span id="cb12-6"><a href="#cb12-6" aria-hidden="true" tabindex="-1"></a>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</section>
<section id="두-평균에-대한-추론" class="level3">
<h3 class="anchored" data-anchor-id="두-평균에-대한-추론">두 평균에 대한 추론</h3>
<p>평균에 대한 두 표본 t-검정에서 우리의 목표는 두 집단의 모집단 평균이 같은지 아니면 어떤 방식으로든 다른지 확인하는 것입니다. 기존 코드에 약간의 변경을 가하여 이 작업을 수행하는 데 t.test 함수를 사용할 수 있습니다. 이 두 표본 검정을 수행하기 위한 t.test 함수의 인자는 두 모집단에서의 표본 x와 y, 그리고 대립 가설 <span class="math inline">\(alternative\)</span>입니다. 이 모든 인자는 단일 표본 평균 검정에서 보았으므로 우리에게 친숙합니다. 유일한 차이점은 두 번째 표본 y의 추가, 귀무 값의 제거(두 표본 평균 검정에서는 0이므로), 그리고 우리의 주먹구구식 규칙(rule of thumb)에 따라 분산(variance)이 같은지 여부에 따라 TRUE 또는 FALSE로 설정되는 var.equal 옵션입니다.</p>
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb13"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb13-1"><a href="#cb13-1" aria-hidden="true" tabindex="-1"></a><span class="fu">t.test</span>(<span class="at">x =</span> x, <span class="at">y =</span> y, <span class="at">alternative =</span> alternative, <span class="at">var.equal =</span> var_equal)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<p>예를 들어 이전 장의 동조(conformity) 예제를 살펴보겠습니다. 데이터는 carData 라이브러리의 Moore 데이터 세트에 저장되어 있습니다 [48,59]. 우리는 높은 지위의 파트너가 낮은 지위의 파트너보다 동조 수준이 동일한지 아니면 더 높은지 검정하는 데 관심이 있었습니다. 즉, H0:<span class="math inline">\(\mu_{High}-\mu_{Low}=0\)</span> 대 HA:<span class="math inline">\(\mu_{High}-\mu_{Low}&gt;0\)</span>입니다. 분산의 비율인 <span class="math inline">\(s_1^2s_2^2=27.85519.087=1.459\)</span>에 기초하여 우리의 분산이 타당하게 같다고 말할 수 있습니다. 따라서 다음 코드를 사용하여 이를 검정하기 위해 t.test 함수를 사용할 수 있습니다.</p>
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb14"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb14-1"><a href="#cb14-1" aria-hidden="true" tabindex="-1"></a><span class="fu">t.test</span>(</span>
<span id="cb14-2"><a href="#cb14-2" aria-hidden="true" tabindex="-1"></a>  <span class="at">x =</span> Moore<span class="sc">$</span>conformity[Moore<span class="sc">$</span>partner.status <span class="sc">==</span> <span class="st">"high"</span>],</span>
<span id="cb14-3"><a href="#cb14-3" aria-hidden="true" tabindex="-1"></a>  <span class="at">y =</span> Moore<span class="sc">$</span>conformity[Moore<span class="sc">$</span>partner.status <span class="sc">==</span> <span class="st">"low"</span>],</span>
<span id="cb14-4"><a href="#cb14-4" aria-hidden="true" tabindex="-1"></a>  <span class="at">alternative =</span> <span class="st">"greater"</span>,</span>
<span id="cb14-5"><a href="#cb14-5" aria-hidden="true" tabindex="-1"></a>  <span class="at">var.equal =</span> <span class="cn">TRUE</span></span>
<span id="cb14-6"><a href="#cb14-6" aria-hidden="true" tabindex="-1"></a>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<p>함수는 다른 항목들과 함께 검정 통계량과 p-값이 포함된 단일 표본 평균 t-검정과 동일한 출력 세트를 제공합니다. 함수의 출력을 보면 이전에 수작업으로 계산한 결과와 모두 일치함을 알 수 있습니다.</p>
<pre class="text"><code>        Two Sample t-test

data:  Moore$conformity[Moore$partner.status == "high"] and
        Moore$conformity[Moore$partner.status == "low"]
t = 2.957, df = 43, p-value = 0.002515
alternative hypothesis: true difference in means is greater than 0
95 percent confidence interval:
 1.839379      Inf
sample estimates:
mean of x mean of y
14.217391  9.954545</code></pre>
<p>또한 t.test 함수는 기본적으로 95% 신뢰 구간(이 경우에는 <span class="math inline">\(\mu_1-\mu_2\)</span>에 대한 신뢰 구간)을 반환합니다. 함수에서 <span class="math inline">\(conf.level\)</span> 인자를 추가하고 조정하여 이를 변경할 수 있으며, 우리가 익숙한 구간을 얻으려면 <code>alternative = "two.sided"</code>가 필요하다는 점을 명심해야 합니다. 따라서 동조 예제에서 <span class="math inline">\(\mu_{High}-\mu_{Low}\)</span>에 대한 98% 신뢰 구간을 계산하고 싶다면 다음 코드를 사용하여 신뢰 구간이 <span class="math inline">\((0.7795,7.7462)\)</span>임을 얻을 수 있습니다.</p>
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb16"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb16-1"><a href="#cb16-1" aria-hidden="true" tabindex="-1"></a><span class="fu">t.test</span>(</span>
<span id="cb16-2"><a href="#cb16-2" aria-hidden="true" tabindex="-1"></a>  <span class="at">x =</span> Moore<span class="sc">$</span>conformity[Moore<span class="sc">$</span>partner.status <span class="sc">==</span> <span class="st">"high"</span>],</span>
<span id="cb16-3"><a href="#cb16-3" aria-hidden="true" tabindex="-1"></a>  <span class="at">y =</span> Moore<span class="sc">$</span>conformity[Moore<span class="sc">$</span>partner.status <span class="sc">==</span> <span class="st">"low"</span>],</span>
<span id="cb16-4"><a href="#cb16-4" aria-hidden="true" tabindex="-1"></a>  <span class="at">alternative =</span> <span class="st">"two.sided"</span>,</span>
<span id="cb16-5"><a href="#cb16-5" aria-hidden="true" tabindex="-1"></a>  <span class="at">var.equal =</span> <span class="cn">TRUE</span>,</span>
<span id="cb16-6"><a href="#cb16-6" aria-hidden="true" tabindex="-1"></a>  <span class="at">conf.level =</span> <span class="fl">0.98</span></span>
<span id="cb16-7"><a href="#cb16-7" aria-hidden="true" tabindex="-1"></a>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</section>
<section id="평균에-대한-대응-추론" class="level3">
<h3 class="anchored" data-anchor-id="평균에-대한-대응-추론">평균에 대한 대응 추론</h3>
<p>우리의 마지막 추론 범주는 평균에 대한 대응 추론입니다. 이 추론은 대응 데이터(paired data), 즉 표본이 독립적이지 않은 데이터를 가질 때 사용됩니다. 즉, 우리 표본은 서로 겹치거나 어떤 식으로든 영향을 미칩니다. 우리는 여전히 두 집단의 모집단 평균을 비교하고 싶지만, 특히 대응 데이터를 통해 어떤 요인을 통제해야 합니다.</p>
<p>우리 t.test 함수는 이 시나리오도 처리합니다. 우리는 다시 두 표본 x와 y뿐만 아니라 대립 가설 옵션 <span class="math inline">\(alternative\)</span>를 포함합니다. 그러나 함수가 우리가 평균에 대한 두 표본 t-검정을 수행하고 있다고 생각하지 않도록 하려면 함수에 우리가 대응 데이터를 사용하고 있음을 알려야 합니다. 우리는 함수의 <span class="math inline">\(paired\)</span> 인자를 통해 이를 수행하는데, 이 인자는 대응 데이터인 경우 TRUE를, 대응 데이터가 아닌 경우 FALSE 값을 갖습니다. 따라서 평균에 대한 대응 검정의 경우 <span class="math inline">\(paired=TRUE\)</span>로 설정합니다.</p>
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb17"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb17-1"><a href="#cb17-1" aria-hidden="true" tabindex="-1"></a><span class="fu">t.test</span>(<span class="at">x =</span> x, <span class="at">y =</span> y, <span class="at">alternative =</span> alternative, <span class="at">paired =</span> <span class="cn">TRUE</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<p>평균에 대한 대응 t-검정을 위해 x와 y 표본을 입력할 때 표본의 길이가 같고 그에 따라 일치해야 한다는 점에 유의하는 것이 중요합니다. 그렇지 않으면 R은 표본의 길이가 다른 경우 오류를 반환하거나 표본이 올바르게 일치하지 않는 경우 잘못된 결과를 반환할 것입니다. 이 검정에 대해 배우면서 보았던 예제를 통해 이를 설명해 보겠습니다.</p>
<p>고셋(Student)의 수면 데이터에 적용된 것을 살펴보겠습니다 [17]. 이것은 R의 기본 패키지에 있는 sleep 데이터 세트에 저장되어 있습니다. 우리는 두 가지 수면 보조제 사이에 차이가 있는지 검정하는 데 관심이 있었습니다. 즉, H0:<span class="math inline">\(\mu_{D}=0\)</span> 대 HA:μD≠<span class="math inline">\(0\)</span>입니다. 이를 검정하기 위한 코드는 다음과 같습니다.</p>
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb18"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb18-1"><a href="#cb18-1" aria-hidden="true" tabindex="-1"></a><span class="fu">t.test</span>(</span>
<span id="cb18-2"><a href="#cb18-2" aria-hidden="true" tabindex="-1"></a>  <span class="at">x =</span> sleep<span class="sc">$</span>extra[sleep<span class="sc">$</span>group <span class="sc">==</span> <span class="dv">1</span>],</span>
<span id="cb18-3"><a href="#cb18-3" aria-hidden="true" tabindex="-1"></a>  <span class="at">y =</span> sleep<span class="sc">$</span>extra[sleep<span class="sc">$</span>group <span class="sc">==</span> <span class="dv">2</span>],</span>
<span id="cb18-4"><a href="#cb18-4" aria-hidden="true" tabindex="-1"></a>  <span class="at">alternative =</span> <span class="st">"two.sided"</span>,</span>
<span id="cb18-5"><a href="#cb18-5" aria-hidden="true" tabindex="-1"></a>  <span class="at">paired =</span> <span class="cn">TRUE</span></span>
<span id="cb18-6"><a href="#cb18-6" aria-hidden="true" tabindex="-1"></a>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<p>함수는 우리가 기대하는 것과 동일한 결과(검정 통계량 t, 자유도 df, 검정의 p-값 등)를 반환합니다. 보다시피, 이러한 결과는 이전에 수작업으로 계산한 결과와 일치합니다.</p>
<pre class="text"><code>        Paired t-test

data:  sleep$extra[sleep$group == 1] and
sleep$extra[sleep$group == 2]
t = -4.0621, df = 9, p-value = 0.002833
alternative hypothesis: true difference in means is not equal to 0
95 percent confidence interval:
 -2.4598858 -0.7001142
sample estimates:
mean of the differences
                  -1.58</code></pre>
<p>가설 검정 외에도 t.test 함수는 <span class="math inline">\(\mu_{D}\)</span>에 대한 신뢰 구간도 제공합니다. 기본적으로 95% 신뢰 구간이며, 함수에 <span class="math inline">\(conf.level\)</span> 옵션을 추가하여 지정된 신뢰 수준으로 변경할 수 있습니다. 따라서 <span class="math inline">\(\mu_{D}\)</span>에 대한 90% 신뢰 구간을 원한다면 다음 코드를 사용하여 구간이 <span class="math inline">\((-2.2930053,-0.8669947)\)</span>임을 찾을 수 있습니다.</p>
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb20"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb20-1"><a href="#cb20-1" aria-hidden="true" tabindex="-1"></a><span class="fu">t.test</span>(</span>
<span id="cb20-2"><a href="#cb20-2" aria-hidden="true" tabindex="-1"></a>  <span class="at">x =</span> sleep<span class="sc">$</span>extra[sleep<span class="sc">$</span>group <span class="sc">==</span> <span class="dv">1</span>],</span>
<span id="cb20-3"><a href="#cb20-3" aria-hidden="true" tabindex="-1"></a>  <span class="at">y =</span> sleep<span class="sc">$</span>extra[sleep<span class="sc">$</span>group <span class="sc">==</span> <span class="dv">2</span>],</span>
<span id="cb20-4"><a href="#cb20-4" aria-hidden="true" tabindex="-1"></a>  <span class="at">alternative =</span> <span class="st">"two.sided"</span>,</span>
<span id="cb20-5"><a href="#cb20-5" aria-hidden="true" tabindex="-1"></a>  <span class="at">paired =</span> <span class="cn">TRUE</span>,</span>
<span id="cb20-6"><a href="#cb20-6" aria-hidden="true" tabindex="-1"></a>  <span class="at">conf.level =</span> <span class="fl">0.9</span></span>
<span id="cb20-7"><a href="#cb20-7" aria-hidden="true" tabindex="-1"></a>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</section>
<section id="연습-문제-1" class="level3">
<h3 class="anchored" data-anchor-id="연습-문제-1">연습 문제</h3>
<ol start="5" type="1">
<li>MASS 라이브러리의 DDT 데이터 세트를 사용하여, DDT 수치가 <span class="math inline">\(\alpha=0.01\)</span> 수준에서 3 ppm보다 큰지 검정하고 99% 신뢰 구간을 생성해 보세요 [10,49].</li>
<li>DAAG 라이브러리의 monica 데이터 세트는 심장 마비를 경험한 개인의 사망 결과와 피험자에 대한 특정 변수들을 조사합니다. <span class="math inline">\(\alpha=0.05\)</span> 수준에서 심혈관 질환 발병 연령(age)이 여성보다 남성(sex)이 더 낮은지 검정해 보세요. 또한 90% 신뢰 구간을 생성해 보세요 [23].</li>
<li>boot 라이브러리의 cd4 데이터 세트는 임상 시험에 처음 입원했을 때(baseline)와 실험 약물을 복용한 1년 후(oneyear)의 HIV 양성 환자의 CD4 수치를 조사합니다. 임상 시험에서 약물을 복용하는 환자의 모집단 평균 CD4 수치가 초기 측정값과 비교하여 1년 후에 감소하는지 검정해 보세요. 또한 60% 신뢰 구간을 생성해 보세요 [68,69].</li>
<li>carData 라이브러리의 Guyer 데이터 세트는 그룹의 결정이 공개 투표인지 익명 투표인지(condition)에 따른 그룹의 협력(cooperation)을 조사합니다. 협력적 결정의 모집단 평균이 공개 및 익명 투표 시스템에서 같은지 아니면 다른지 검정해 보세요. 또한 <span class="math inline">\(\mu_{Anon}-\mu_{Pub}\)</span>에 대한 97% 신뢰 구간을 생성해 보세요 [48,105].</li>
<li>DAAG 라이브러리의 pair65 데이터 세트는 고무줄을 가열했는지 여부에 따른 고무줄의 신축성(무게를 매달았을 때 늘어난 길이로 측정)을 조사합니다. 고무줄은 초기 탄성이 유사한 것끼리 짝을 지었습니다. 변수 heated는 뜨거운 물에 넣은 9개의 고무줄을 나타내고, ambient는 가열하지 않은 고무줄입니다. 가열된 그룹과 가열되지 않은 그룹의 모집단 평균 신축성이 같은지 아니면 다른지 검정해 보세요 [23].</li>
</ol>
</section>
</section>
<section id="추론-결과를-재사용-가능한-객체로-다루기" class="level2">
<h2 class="anchored" data-anchor-id="추론-결과를-재사용-가능한-객체로-다루기">추론 결과를 재사용 가능한 객체로 다루기</h2>
<p>R의 검정 함수들은 화면에 결과를 출력할 뿐 아니라, 결과를 객체로 저장할 수 있습니다. 분석 보고서에서는 검정 결과를 저장해 두고 필요한 값만 꺼내 쓰면 실수를 줄일 수 있습니다.</p>
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb21"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb21-1"><a href="#cb21-1" aria-hidden="true" tabindex="-1"></a>prop_result <span class="ot">&lt;-</span> <span class="fu">prop.test</span>(</span>
<span id="cb21-2"><a href="#cb21-2" aria-hidden="true" tabindex="-1"></a>  <span class="at">x =</span> <span class="dv">12</span>,</span>
<span id="cb21-3"><a href="#cb21-3" aria-hidden="true" tabindex="-1"></a>  <span class="at">n =</span> <span class="dv">79</span>,</span>
<span id="cb21-4"><a href="#cb21-4" aria-hidden="true" tabindex="-1"></a>  <span class="at">p =</span> <span class="fl">0.14</span>,</span>
<span id="cb21-5"><a href="#cb21-5" aria-hidden="true" tabindex="-1"></a>  <span class="at">alternative =</span> <span class="st">"two.sided"</span>,</span>
<span id="cb21-6"><a href="#cb21-6" aria-hidden="true" tabindex="-1"></a>  <span class="at">correct =</span> <span class="cn">FALSE</span>,</span>
<span id="cb21-7"><a href="#cb21-7" aria-hidden="true" tabindex="-1"></a>  <span class="at">conf.level =</span> <span class="fl">0.95</span></span>
<span id="cb21-8"><a href="#cb21-8" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb21-9"><a href="#cb21-9" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb21-10"><a href="#cb21-10" aria-hidden="true" tabindex="-1"></a>prop_result<span class="sc">$</span>p.value</span>
<span id="cb21-11"><a href="#cb21-11" aria-hidden="true" tabindex="-1"></a>prop_result<span class="sc">$</span>estimate</span>
<span id="cb21-12"><a href="#cb21-12" aria-hidden="true" tabindex="-1"></a>prop_result<span class="sc">$</span>conf.int</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<p><code>t.test()</code> 결과도 같은 방식으로 다룰 수 있습니다. 이 습관은 여러 검정을 반복할 때 특히 중요합니다. p-값을 손으로 복사하면 오타가 나거나, 나중에 데이터가 바뀌었을 때 보고서의 숫자만 오래된 상태로 남을 수 있습니다. 반면 결과 객체에서 값을 꺼내 쓰면 데이터, 코드, 해석의 연결이 유지됩니다.</p>
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb22"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb22-1"><a href="#cb22-1" aria-hidden="true" tabindex="-1"></a>t_result <span class="ot">&lt;-</span> <span class="fu">t.test</span>(</span>
<span id="cb22-2"><a href="#cb22-2" aria-hidden="true" tabindex="-1"></a>  <span class="at">x =</span> sleep<span class="sc">$</span>extra[sleep<span class="sc">$</span>group <span class="sc">==</span> <span class="dv">1</span>],</span>
<span id="cb22-3"><a href="#cb22-3" aria-hidden="true" tabindex="-1"></a>  <span class="at">y =</span> sleep<span class="sc">$</span>extra[sleep<span class="sc">$</span>group <span class="sc">==</span> <span class="dv">2</span>],</span>
<span id="cb22-4"><a href="#cb22-4" aria-hidden="true" tabindex="-1"></a>  <span class="at">paired =</span> <span class="cn">TRUE</span>,</span>
<span id="cb22-5"><a href="#cb22-5" aria-hidden="true" tabindex="-1"></a>  <span class="at">alternative =</span> <span class="st">"two.sided"</span>,</span>
<span id="cb22-6"><a href="#cb22-6" aria-hidden="true" tabindex="-1"></a>  <span class="at">conf.level =</span> <span class="fl">0.90</span></span>
<span id="cb22-7"><a href="#cb22-7" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb22-8"><a href="#cb22-8" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb22-9"><a href="#cb22-9" aria-hidden="true" tabindex="-1"></a>t_result<span class="sc">$</span>p.value</span>
<span id="cb22-10"><a href="#cb22-10" aria-hidden="true" tabindex="-1"></a>t_result<span class="sc">$</span>conf.int</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<p>여러 집단이나 여러 변수에 같은 검정을 반복해야 한다면 먼저 데이터 구조를 정리하고, 어떤 비교가 연구 질문에 해당하는지 명확히 정한 뒤 반복 코드를 작성해야 합니다. 반복을 자동화하는 능력보다 더 중요한 것은 불필요한 다중 비교를 만들지 않는 설계입니다.</p>
</section>
<section id="결론" class="level2">
<h2 class="anchored" data-anchor-id="결론">결론</h2>
<p>모든 형태의 통계적 추론은 간단한 공식과 약간의 코드로 수작업으로 수행할 수 있지만, 이는 지루한 과정이 될 수 있습니다. 이 과정을 거치는 대신 R은 신뢰 구간을 계산하고 모든 종류의 가설 검정을 수행할 수 있는 두 가지 함수를 제공합니다. 그러나 각 함수를 적절하게 적용하는 방법을 인식하고 아는 것이 중요합니다. 그것이 인식되면 통계적 추론 작업은 훨씬 쉬워집니다.</p>


</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
  window.document.addEventListener("DOMContentLoaded", function (event) {
    const icon = "";
    const anchorJS = new window.AnchorJS();
    anchorJS.options = {
      placement: 'right',
      icon: icon
    };
    anchorJS.add('.anchored');
    const isCodeAnnotation = (el) => {
      for (const clz of el.classList) {
        if (clz.startsWith('code-annotation-')) {                     
          return true;
        }
      }
      return false;
    }
    const onCopySuccess = function(e) {
      // button target
      const button = e.trigger;
      // don't keep focus
      button.blur();
      // flash "checked"
      button.classList.add('code-copy-button-checked');
      var currentTitle = button.getAttribute("title");
      button.setAttribute("title", "Copied!");
      let tooltip;
      if (window.bootstrap) {
        button.setAttribute("data-bs-toggle", "tooltip");
        button.setAttribute("data-bs-placement", "left");
        button.setAttribute("data-bs-title", "Copied!");
        tooltip = new bootstrap.Tooltip(button, 
          { trigger: "manual", 
            customClass: "code-copy-button-tooltip",
            offset: [0, -8]});
        tooltip.show();    
      }
      setTimeout(function() {
        if (tooltip) {
          tooltip.hide();
          button.removeAttribute("data-bs-title");
          button.removeAttribute("data-bs-toggle");
          button.removeAttribute("data-bs-placement");
        }
        button.setAttribute("title", currentTitle);
        button.classList.remove('code-copy-button-checked');
      }, 1000);
      // clear code selection
      e.clearSelection();
    }
    const getTextToCopy = function(trigger) {
      const outerScaffold = trigger.parentElement.cloneNode(true);
      const codeEl = outerScaffold.querySelector('code');
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
    const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
      text: getTextToCopy
    });
    clipboard.on('success', onCopySuccess);
    if (window.document.getElementById('quarto-embedded-source-code-modal')) {
      const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
        text: getTextToCopy,
        container: window.document.getElementById('quarto-embedded-source-code-modal')
      });
      clipboardModal.on('success', onCopySuccess);
    }
      var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
      var mailtoRegex = new RegExp(/^mailto:/);
        var filterRegex = new RegExp('/' + window.location.host + '/');
      var isInternal = (href) => {
          return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
      }
      // Inspect non-navigation links and adorn them if external
     var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
      for (var i=0; i<links.length; i++) {
        const link = links[i];
        if (!isInternal(link.href)) {
          // undo the damage that might have been done by quarto-nav.js in the case of
          // links that we want to consider external
          if (link.dataset.originalHref !== undefined) {
            link.href = link.dataset.originalHref;
          }
        }
      }
    function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
      const config = {
        allowHTML: true,
        maxWidth: 500,
        delay: 100,
        arrow: false,
        appendTo: function(el) {
            return el.parentElement;
        },
        interactive: true,
        interactiveBorder: 10,
        theme: 'quarto',
        placement: 'bottom-start',
      };
      if (contentFn) {
        config.content = contentFn;
      }
      if (onTriggerFn) {
        config.onTrigger = onTriggerFn;
      }
      if (onUntriggerFn) {
        config.onUntrigger = onUntriggerFn;
      }
      window.tippy(el, config); 
    }
    const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
    for (var i=0; i<noterefs.length; i++) {
      const ref = noterefs[i];
      tippyHover(ref, function() {
        // use id or data attribute instead here
        let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
        try { href = new URL(href).hash; } catch {}
        const id = href.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note) {
          return note.innerHTML;
        } else {
          return "";
        }
      });
    }
    const xrefs = window.document.querySelectorAll('a.quarto-xref');
    const processXRef = (id, note) => {
      // Strip column container classes
      const stripColumnClz = (el) => {
        el.classList.remove("page-full", "page-columns");
        if (el.children) {
          for (const child of el.children) {
            stripColumnClz(child);
          }
        }
      }
      stripColumnClz(note)
      if (id === null || id.startsWith('sec-')) {
        // Special case sections, only their first couple elements
        const container = document.createElement("div");
        if (note.children && note.children.length > 2) {
          container.appendChild(note.children[0].cloneNode(true));
          for (let i = 1; i < note.children.length; i++) {
            const child = note.children[i];
            if (child.tagName === "P" && child.innerText === "") {
              continue;
            } else {
              container.appendChild(child.cloneNode(true));
              break;
            }
          }
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(container);
          }
          return container.innerHTML
        } else {
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(note);
          }
          return note.innerHTML;
        }
      } else {
        // Remove any anchor links if they are present
        const anchorLink = note.querySelector('a.anchorjs-link');
        if (anchorLink) {
          anchorLink.remove();
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        if (note.classList.contains("callout")) {
          return note.outerHTML;
        } else {
          return note.innerHTML;
        }
      }
    }
    for (var i=0; i<xrefs.length; i++) {
      const xref = xrefs[i];
      tippyHover(xref, undefined, function(instance) {
        instance.disable();
        let url = xref.getAttribute('href');
        let hash = undefined; 
        if (url.startsWith('#')) {
          hash = url;
        } else {
          try { hash = new URL(url).hash; } catch {}
        }
        if (hash) {
          const id = hash.replace(/^#\/?/, "");
          const note = window.document.getElementById(id);
          if (note !== null) {
            try {
              const html = processXRef(id, note.cloneNode(true));
              instance.setContent(html);
            } finally {
              instance.enable();
              instance.show();
            }
          } else {
            // See if we can fetch this
            fetch(url.split('#')[0])
            .then(res => res.text())
            .then(html => {
              const parser = new DOMParser();
              const htmlDoc = parser.parseFromString(html, "text/html");
              const note = htmlDoc.getElementById(id);
              if (note !== null) {
                const html = processXRef(id, note);
                instance.setContent(html);
              } 
            }).finally(() => {
              instance.enable();
              instance.show();
            });
          }
        } else {
          // See if we can fetch a full url (with no hash to target)
          // This is a special case and we should probably do some content thinning / targeting
          fetch(url)
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.querySelector('main.content');
            if (note !== null) {
              // This should only happen for chapter cross references
              // (since there is no id in the URL)
              // remove the first header
              if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
                note.children[0].remove();
              }
              const html = processXRef(null, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      }, function(instance) {
      });
    }
        let selectedAnnoteEl;
        const selectorForAnnotation = ( cell, annotation) => {
          let cellAttr = 'data-code-cell="' + cell + '"';
          let lineAttr = 'data-code-annotation="' +  annotation + '"';
          const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
          return selector;
        }
        const selectCodeLines = (annoteEl) => {
          const doc = window.document;
          const targetCell = annoteEl.getAttribute("data-target-cell");
          const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
          const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
          const lines = annoteSpan.getAttribute("data-code-lines").split(",");
          const lineIds = lines.map((line) => {
            return targetCell + "-" + line;
          })
          let top = null;
          let height = null;
          let parent = null;
          if (lineIds.length > 0) {
              //compute the position of the single el (top and bottom and make a div)
              const el = window.document.getElementById(lineIds[0]);
              top = el.offsetTop;
              height = el.offsetHeight;
              parent = el.parentElement.parentElement;
            if (lineIds.length > 1) {
              const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
              const bottom = lastEl.offsetTop + lastEl.offsetHeight;
              height = bottom - top;
            }
            if (top !== null && height !== null && parent !== null) {
              // cook up a div (if necessary) and position it 
              let div = window.document.getElementById("code-annotation-line-highlight");
              if (div === null) {
                div = window.document.createElement("div");
                div.setAttribute("id", "code-annotation-line-highlight");
                div.style.position = 'absolute';
                parent.appendChild(div);
              }
              div.style.top = top - 2 + "px";
              div.style.height = height + 4 + "px";
              div.style.left = 0;
              let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
              if (gutterDiv === null) {
                gutterDiv = window.document.createElement("div");
                gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
                gutterDiv.style.position = 'absolute';
                const codeCell = window.document.getElementById(targetCell);
                const gutter = codeCell.querySelector('.code-annotation-gutter');
                gutter.appendChild(gutterDiv);
              }
              gutterDiv.style.top = top - 2 + "px";
              gutterDiv.style.height = height + 4 + "px";
            }
            selectedAnnoteEl = annoteEl;
          }
        };
        const unselectCodeLines = () => {
          const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
          elementsIds.forEach((elId) => {
            const div = window.document.getElementById(elId);
            if (div) {
              div.remove();
            }
          });
          selectedAnnoteEl = undefined;
        };
          // Handle positioning of the toggle
      window.addEventListener(
        "resize",
        throttle(() => {
          elRect = undefined;
          if (selectedAnnoteEl) {
            selectCodeLines(selectedAnnoteEl);
          }
        }, 10)
      );
      function throttle(fn, ms) {
      let throttle = false;
      let timer;
        return (...args) => {
          if(!throttle) { // first call gets through
              fn.apply(this, args);
              throttle = true;
          } else { // all the others get throttled
              if(timer) clearTimeout(timer); // cancel #2
              timer = setTimeout(() => {
                fn.apply(this, args);
                timer = throttle = false;
              }, ms);
          }
        };
      }
        // Attach click handler to the DT
        const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
        for (const annoteDlNode of annoteDls) {
          annoteDlNode.addEventListener('click', (event) => {
            const clickedEl = event.target;
            if (clickedEl !== selectedAnnoteEl) {
              unselectCodeLines();
              const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
              if (activeEl) {
                activeEl.classList.remove('code-annotation-active');
              }
              selectCodeLines(clickedEl);
              clickedEl.classList.add('code-annotation-active');
            } else {
              // Unselect the line
              unselectCodeLines();
              clickedEl.classList.remove('code-annotation-active');
            }
          });
        }
    const findCites = (el) => {
      const parentEl = el.parentElement;
      if (parentEl) {
        const cites = parentEl.dataset.cites;
        if (cites) {
          return {
            el,
            cites: cites.split(' ')
          };
        } else {
          return findCites(el.parentElement)
        }
      } else {
        return undefined;
      }
    };
    var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
    for (var i=0; i<bibliorefs.length; i++) {
      const ref = bibliorefs[i];
      const citeInfo = findCites(ref);
      if (citeInfo) {
        tippyHover(citeInfo.el, function() {
          var popup = window.document.createElement('div');
          citeInfo.cites.forEach(function(cite) {
            var citeDiv = window.document.createElement('div');
            citeDiv.classList.add('hanging-indent');
            citeDiv.classList.add('csl-entry');
            var biblioDiv = window.document.getElementById('ref-' + cite);
            if (biblioDiv) {
              citeDiv.innerHTML = biblioDiv.innerHTML;
            }
            popup.appendChild(citeDiv);
          });
          return popup.innerHTML;
        });
      }
    }
  });
  </script>
</div> <!-- /content -->




</body></html>