<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.9.38">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>단순 선형 회귀</title>
<style>
/* Default styles provided by pandoc.
** See https://pandoc.org/MANUAL.html#variables-for-html for config info.
*/
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
html { -webkit-text-size-adjust: 100%; }
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="../site_libs/quarto-nav/quarto-nav.js"></script>
<script src="../site_libs/quarto-nav/headroom.min.js"></script>
<script src="../site_libs/clipboard/clipboard.min.js"></script>
<script src="../site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="../site_libs/quarto-search/fuse.min.js"></script>
<script src="../site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="../">
<script src="../site_libs/quarto-html/quarto.js" type="module"></script>
<script src="../site_libs/quarto-html/tabsets/tabsets.js" type="module"></script>
<script src="../site_libs/quarto-html/popper.min.js"></script>
<script src="../site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="../site_libs/quarto-html/anchor.min.js"></script>
<link href="../site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="../site_libs/quarto-html/quarto-syntax-highlighting-15634bcf2e68342d4ad2dfa704d543f6.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="../site_libs/bootstrap/bootstrap.min.js"></script>
<link href="../site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="../site_libs/bootstrap/bootstrap-cf5ee1d16def7895729d1ac812351ea4.min.css" rel="stylesheet" append-hash="true" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "sidebar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "start",
  "type": "textbox",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>

  <script src="https://cdnjs.cloudflare.com/polyfill/v3/polyfill.min.js?features=es6"></script>
  <script defer="" src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

<script type="text/javascript">
const typesetMath = (el) => {
  if (window.MathJax) {
    // MathJax Typeset
    window.MathJax.typeset([el]);
  } else if (window.katex) {
    // KaTeX Render
    var mathElements = el.getElementsByClassName("math");
    var macros = [];
    for (var i = 0; i < mathElements.length; i++) {
      var texText = mathElements[i].firstChild;
      if (mathElements[i].tagName == "SPAN" && texText && texText.data) {
        window.katex.render(texText.data, mathElements[i], {
          displayMode: mathElements[i].classList.contains('display'),
          throwOnError: false,
          macros: macros,
          fleqn: false
        });
      }
    }
  }
}
window.Quarto = {
  typesetMath
};
</script>

</head>

<body class="nav-sidebar docked fullcontent quarto-light">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
  <nav class="quarto-secondary-nav">
    <div class="container-fluid d-flex">
      <button type="button" class="quarto-btn-toggle btn" data-bs-toggle="collapse" role="button" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
        <i class="bi bi-layout-text-sidebar-reverse"></i>
      </button>
        <nav class="quarto-page-breadcrumbs" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item">단순 선형 회귀</li></ol></nav>
        <a class="flex-grow-1" role="navigation" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">      
        </a>
      <button type="button" class="btn quarto-search-button" aria-label="Search" onclick="window.quartoOpenSearch();">
        <i class="bi bi-search"></i>
      </button>
    </div>
  </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article">
<!-- sidebar -->
  <nav id="quarto-sidebar" class="sidebar collapse collapse-horizontal quarto-sidebar-collapse-item sidebar-navigation docked overflow-auto">
        <div class="mt-2 flex-shrink-0 align-items-center">
        <div class="sidebar-search">
        <div id="quarto-search" class="" title="Search"></div>
        </div>
        </div>
    <div class="sidebar-menu-container"> 
    <ul class="list-unstyled mt-1">
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../notes/ch01.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">통계학의 중요성!</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../notes/ch02.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">R 입문</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../notes/ch03.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">데이터 수집</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../notes/ch04.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">데이터 추출</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../notes/ch05.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">데이터 불러오기</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../notes/ch06.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">탐색적 데이터 분석</span></a>
  </div>
</li>
    </ul>
    </div>
</nav>
<div id="quarto-sidebar-glass" class="quarto-sidebar-collapse-item" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item"></div>
<!-- margin-sidebar -->
    
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">단순 선형 회귀</h1>
</div>



<div class="quarto-title-meta">

    
  
    
  </div>
  


</header>


<section id="서론" class="level2">
<h2 class="anchored" data-anchor-id="서론">서론</h2>
<p>상관관계(Correlation)에 대한 추론을 수행하면서, 우리는 두 양적 변수 사이의 선형 관계를 방향과 강도 측면에서 이해하기 시작합니다. 하지만 상관관계 추론은 변수들이 서로에게 어떻게 영향을 미치는지에 대해서는 아무것도 알려주지 않습니다.</p>
<p>예를 들어, x변수가 1만큼 증가할 때 y변수가 증가한다고 합시다. 즉, 두 변수 간에 양의 선형 관계가 있다고 합시다. 예측 변수(Predictor) x가 1만큼 증가할 때마다 반응 변수(Response) y는 약 0.4만큼 증가한다고 가정합시다. 그리고 x가 1만큼 증가할 때마다 y는 약 1.8만큼 증가하는 다른 경우도 존재한다고 가정합시다. 두 상관 관계는 동일하지만 기울기가 다릅니다. 우리는 이 두 관계를 구분하고 변수들 사이의 관계를 더 온전히 이해할 수 있는 방법이 필요합니다.</p>
<p>단순 선형 회귀(Simple linear regression)는 이를 수행하는 방법입니다. 선형 관계가 있는 두 변수, 즉 하나의 예측 변수와 하나의 반응 변수를 취하여 그 관계를 잘 설명하는 직선을 찾아냅니다. 이 직선은 상관관계보다 더 많은 정보를 제공합니다. 이 기법을 통해 반응 변수 예측을 포함하여 이 직선의 다양한 측면과 결과를 살펴볼 수 있습니다. 이는 분석과 우리가 답할 수 있는 질문 측면에서 다양한 가능성을 열어줍니다.</p>
<p>단순 선형 회귀를 위한 많은 계산을 수작업으로 유도할 수 있지만, 데이터셋의 크기를 고려할 때 이를 직접 완료하는 것은 비실용적입니다. 따라서 추정치가 어떻게 유도되는지 일반적인 용어로 논의하되 전체 유도 과정을 거치지는 않을 것입니다. 예시로서 다음 데이터셋을 살펴보겠습니다.</p>
<p>올드 페이스풀(Old Faithful) 간헐천의 분출 시간 길이와 다음 분출까지의 대기 시간 사이에는 연관성이 있다고 알려져 있습니다. 우리는 대기 시간을 예측하기 위한 단순 선형 회귀를 개발하기 위해 R의 faithful 데이터셋을 사용해 이 현상을 살펴보겠습니다.</p>
</section>
<section id="직선의-기초" class="level2">
<h2 class="anchored" data-anchor-id="직선의-기초">직선의 기초</h2>
<p>수학에서 직선의 기울기-절편 형태는 다음과 같습니다.</p>
<p><span class="math display">\[y=\beta_0+\beta_1x\]</span></p>
<p>여기서 y는 종속 변수—또는 우리가 예측하려는 변수—이고, x는 독립 변수—예측에 사용하려는 변수—입니다. 이 직선 형태에는 두 가지 핵심 요소가 있습니다. 기울기(Slope) <span class="math inline">\(\beta_1\)</span>과 절편(Intercept) <span class="math inline">\(\beta_0\)</span>입니다. 기울기는 독립 변수가 한 단위 증가할 때 종속 변수가 얼마나 증가하는지를 설명합니다. 기울기가 양수이면 독립 변수와 종속 변수 사이의 관계는 양의 관계입니다. 기울기가 음수이면 관계는 음의 관계입니다. 마지막으로 기울기가 0이면 독립 변수는 종속 변수에 아무런 영향을 미치지 않습니다.</p>
<p>절편은 독립 변수가 0일 때의 종속 변수 값을 알려줍니다. 직선에 x=0을 대입해 보면 이를 명확히 알 수 있습니다. 이 경우 다음과 같이 됩니다.</p>
<p><span class="math display">\[y=\beta_0+\beta_1 \times 0 = \beta_0\]</span></p>
</section>
<section id="단순-선형-회귀-모델" class="level2">
<h2 class="anchored" data-anchor-id="단순-선형-회귀-모델">단순 선형 회귀 모델</h2>
<p>직선의 많은 기본 개념이 단순 선형 회귀로 확장됩니다. 단순 선형 회귀에서 우리는 반응 변수 y가 예측 변수 x와 선형 관계를 갖는다고 말합니다. 이를 직선 형태로 나타내면 다음과 같습니다.</p>
<p><span class="math display">\[y_i=\beta_0+\beta_1 x_i.\]</span></p>
<p>마찬가지로, 절편 <span class="math inline">\(\beta_0\)</span>는 예측 변수가 0일 때 기대되는 반응 변수의 값입니다. 비록 이 값이 논리적으로 말이 되지 않을 수도 있지만 말입니다. 기울기 <span class="math inline">\(\beta_1\)</span>은 예측 변수가 한 단위 증가할 때 반응 변수가 얼마나 증가할 것으로 기대되는지를 나타냅니다.</p>
<p>현재 설명된 예측 변수와 반응 변수 사이의 관계 방식은 반응 변수의 값들이 직선 위에 완벽하게 놓여 있다는 것을 의미하며, 이는 반응 변수를 완벽하게 예측할 수 있어야 함을 뜻합니다. 올드 페이스풀 간헐천 데이터의 그래프를 보면 이는 분명히 사실이 아니며 일반적으로도 그렇지 않을 것입니다. 이 사실 때문에 우리는 반응 변수에 오차(Error)가 있음을 인정해야 합니다. 즉, 직선이 반응 변수를 예측하는 데 좋은 역할을 할 수 있지만, 항상 설명할 수 없는 무작위 오차가 존재합니다. 이를 염두에 두고 이 오차를 나타내기 위해 직선 방정식에 추가적인 항을 넣어야 합니다.</p>
<p><span class="math display">\[y_i=\beta_0+\beta_1 x_i + \epsilon_i.\]</span></p>
<p>이것이 우리의 표준 단순 선형 회귀 모델입니다. 이 새로운 모델에서 무작위 오차는 <span class="math inline">\(\epsilon_i\)</span>—i번째 무작위 오차—로 표현됩니다. 이는 확률 변수(Random variable)이므로 어떤 형태의 확률 분포를 따른다는 것을 의미합니다. 어떤 경우에는 오차가 정규 분포(Normal distribution)를 따른다고 가정하지만, 여기서는 그렇게 하지 않을 것입니다. 그러나 오차 <span class="math inline">\(\epsilon_i\)</span>에 대해 몇 가지 가정을 세우며, 이제 이를 논의하겠습니다.</p>
<ul>
<li>오차 <span class="math inline">\(\epsilon_i\)</span>는 독립적</li>
<li>오차의 기댓값(Expected value)은 0</li>
<li>오차의 분산(Variance)은 일정하며, <span class="math inline">\(\sigma^2\)</span>로 표기</li>
</ul>
<p>이러한 가정들 중 어느 하나라도 참이 아니면 회귀선에 영향을 줄 수 있습니다. 오차가 독립적이지 않으면 회귀에 대한 추론에 편향이 생길 것입니다. 오차의 평균값이 0이 아니면 이를 수용하기 위해 절편의 추정치가 변할 것입니다. 마지막으로 오차의 분산이 일정하지 않으면—생각보다 흔한 경우입니다—회귀 모델에 대한 추론이 다시 한번 부정확해질 것입니다. 이러한 가정들은 회귀 모델이 적절히 작동하는 데 필수적이므로, 나중에 더 자세히 다룰 이러한 가정들을 확인해야 합니다.</p>
</section>
<section id="회귀-모델-추정" class="level2">
<h2 class="anchored" data-anchor-id="회귀-모델-추정">회귀 모델 추정</h2>
<p>회귀 모델에는 세 가지 모수(Parameter)가 있습니다. 절편 <span class="math inline">\(\beta_0\)</span>, 기울기 <span class="math inline">\(\beta_1\)</span>, 그리고 오차의 분산 <span class="math inline">\(\sigma^2\)</span>입니다. 이들 각각은 고정되어 있지만 알 수 없는 값이므로 추정되어야 합니다. 기울기와 절편을 결정하면 추정 회귀선이 나오므로 여기서부터 시작할 것입니다.</p>
<p>회귀선을 추정할 때 우리의 목표는 점들 전체가 회귀선에 최대한 가깝게 위치하도록 만드는 것입니다. 다시 말해, 점들과 직선 사이의 전체 거리를 최대한 작게 만들고 싶습니다. 이 거리는 오차의 제곱을 통해 표현되며, 그 합계를 오차 제곱합(Sum of Squared Errors) 또는 SSE라고 부릅니다. 따라서 SSE를 찾으려면 먼저 오차를 찾아야 합니다. 회귀선을 바탕으로 오차 <span class="math inline">\(\epsilon_i\)</span>에 대해 풀면 다음과 같습니다.</p>
<p><span class="math display">\[\epsilon_i=y_i-\beta_0-\beta_1 x_i.\]</span></p>
<p>오차를 구하고 나면 SSE를 쉽게 찾을 수 있습니다. 각 오차를 제곱한 다음 모두 더하면 됩니다.</p>
<p><span class="math display">\[\text{SSE}=\sum_{i=1}^n \epsilon_i^2 = \sum_{i=1}^n (y_i - \beta_0 - \beta_1 x_i)^2.\]</span></p>
<p>SSE를 정의했으므로 이제 SSE를 최대한 작게 만드는 <span class="math inline">\(\beta_0\)</span>와 <span class="math inline">\(\beta_1\)</span>의 값을 선택하고 싶습니다. 이 과정이 어떻게 수행되는지 구체적으로 다루지는 않겠지만, 미적분학 배경이 있는 사람이라면 함수를 최소화하는 것과 유사한 방식으로 이루어진다는 것을 알 수 있을 것입니다. 기울기와 절편에 대한 추정치—각각 <span class="math inline">\(\beta_1\)</span>과 <span class="math inline">\(\beta_0\)</span>—를 유도하는 이 과정을 거치면 다음과 같음을 알 수 있습니다.</p>
<p><span class="math display">\[\hat{\beta}_1 = r_{x,y} \frac{s_y}{s_x}\]</span> <span class="math display">\[\hat{\beta}_0 = \bar{y} - \hat{\beta}_1 \bar{x}\]</span></p>
<p>여기서 <span class="math inline">\(r_{x,y}\)</span>는 예측 변수와 반응 변수 사이의 상관관계이고, <span class="math inline">\(s_x\)</span>와 <span class="math inline">\(s_y\)</span>는 각각 예측 변수와 반응 변수의 표본 표준 편차(Sample standard deviation)이며, <span class="math inline">\(\bar{x}\)</span>와 <span class="math inline">\(\bar{y}\)</span>는 예측 변수와 반응 변수의 표본 평균(Sample mean)입니다. 특히 기울기 추정치를 구하는 과정에서 상관관계와 회귀 사이의 연관성을 볼 수 있습니다. 상관관계가 양수이면 기울기도 양수일 것입니다. 상관관계가 음수이면 기울기도 음수일 것입니다. 상관관계가 커짐에 따라 기울기도 커집니다. 마지막으로 상관관계가 0에 가까우면—두 변수 사이의 연관성이 약함을 의미함—기울기 추정치 또한 0에 가까울 것입니다. 이는 예측 변수가 반응 변수에 미치는 영향이 적음을 의미합니다.</p>
<p>이를 올드 페이스풀 데이터셋에 적용해 보겠습니다. 이 데이터셋에서 분출 시간과 대기 시간 사이의 상관관계는 r=0.9008이고, 예측 변수인 분출 시간의 표준 편차는 <span class="math inline">\(s_x\)</span>=1.1414, 반응 변수인 대기 시간의 표준 편차는 <span class="math inline">\(s_y\)</span>=13.5950임을 R에서 찾을 수 있습니다. 따라서 회귀선의 기울기 추정치는 <span class="math inline">\(\hat{\beta}_1 = 0.9008 \times 13.595 / 1.1414 = 10.7296\)</span>가 될 것입니다. 이는 올드 페이스풀의 분출이 1분 길어질 때마다 다음 분출까지 10.7296분의 추가 대기 시간을 기대할 수 있음을 의미합니다.</p>
<p>다음 단계는 절편 추정치 <span class="math inline">\(\hat{\beta}_0\)</span>를 구하는 것입니다. 이를 위해 기울기 추정치 <span class="math inline">\(\hat{\beta}_1=10.7296\)</span>와 분출 시간 평균 <span class="math inline">\(\bar{x}=3.4878\)</span> 및 대기 시간 평균 <span class="math inline">\(\bar{y}=70.8971\)</span>이 필요합니다. 이는 절편이 <span class="math inline">\(\hat{\beta}_0=70.8971−10.7296×3.4878=33.4744\)</span>가 됨을 의미합니다. 따라서 추정 회귀선은 다음과 같습니다.</p>
<p><span class="math display">\[y_i = 33.4744 + 10.7296x_i.\]</span></p>
<p>모델에 대해 추정해야 할 마지막 모수는 오차의 분산 <span class="math inline">\(\sigma^2\)</span>입니다. 오차들이 주어졌을 때, 해당 값들의 표본 분산을 사용하여 오차의 참 분산을 추정할 수 있습니다. 물론 이 작업의 어려움은 우리가 오차를 모른다는 데 있습니다. 오차의 공식은 <span class="math inline">\(\epsilon_i=y_i−\beta_0−\beta_1x_i\)</span>이므로, 오차의 참값을 알기 위해서는 <span class="math inline">\(\beta_0\)</span>와 <span class="math inline">\(\beta_1\)</span>의 참값을 알아야 하는데 이는 불가능합니다.</p>
<p>우리는 <span class="math inline">\(\beta_0\)</span>와 <span class="math inline">\(\beta_1\)</span>을 모르지만, 추정치 <span class="math inline">\(\hat{\beta}_0\)</span>와 <span class="math inline">\(\hat{\beta}_1\)</span>은 가지고 있습니다. 이 계수 추정치들을 사용하여 오차의 근사치를 구할 수 있습니다. 이러한 오차의 추정치를 잔차(Residual)라고 하며, <span class="math inline">\(e_i\)</span>로 표기합니다.</p>
<p><span class="math display">\[e_i=y_i−\hat{\beta}_0−\hat{\beta}_1x_i.\]</span></p>
<p>이 잔차들을 사용하여 오차의 분산 <span class="math inline">\(\sigma^2\)</span>를 추정할 수 있습니다. 이 추정치를 평균 제곱 오차(Mean Squared Error, MSE)라고 하며, <span class="math inline">\(\hat{\sigma}^2\)</span>로 표기하고 다음과 같이 계산합니다.</p>
<p><span class="math display">\[\hat{\sigma}^2 = \frac{1}{n-2}\sum_{i=1}^n e_i^2.\]</span></p>
<p>이를 수작업으로 계산하는 것은 꽤 지루할 수 있으므로, R을 사용하여 이 계산을 수행할 것입니다.</p>
</section>
<section id="r에서의-회귀" class="level2">
<h2 class="anchored" data-anchor-id="r에서의-회귀">R에서의 회귀</h2>
<p>R에서 회귀 모델의 구성 요소—표본 상관관계, 표준 편차, 평균—를 계산한 다음 이를 사용하여 기울기와 절편을 계산할 수도 있지만, R은 훨씬 더 쉬운 방법을 제공합니다.</p>
<p>R의 <code>lm</code> 함수는 단순 선형 회귀 모델을 추정하는 데 사용됩니다. 이 함수는 반응 변수와 예측 변수, 그리고 데이터셋을 입력으로 받아 기울기, 절편, MSE를 포함한 다양한 중요 통계량을 출력합니다. <code>lm</code> 함수의 코드는 다음과 같습니다.</p>
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb1"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="fu">lm</span>(response <span class="sc">~</span> predictor, <span class="at">data =</span> dataset)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<p>여기서 Response는 반응 변수, Predictor는 예측 변수, 그리고 dataset은 변수들이 저장된 데이터셋입니다. 이를 올드 페이스풀 예시에 적용한다면—데이터셋 이름은 faithful, 반응 변수는 대기 시간 waiting, 예측 변수는 분출 시간 eruptions—코드는 다음과 같을 것입니다.</p>
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb2"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb2-1"><a href="#cb2-1" aria-hidden="true" tabindex="-1"></a><span class="fu">lm</span>(waiting <span class="sc">~</span> eruptions, <span class="at">data =</span> faithful)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<p>그러면 R은 아래와 같은 결과를 반환합니다. (Intercept) 열은 절편 추정치 <span class="math inline">\(\hat{\beta}_0\)</span>의 값을 제공하고, <code>eruptions</code> 열은 기울기 추정치 <span class="math inline">\(\hat{\beta}_1\)</span>을 제공합니다. 이 열의 이름은 예측 변수의 이름에 따라 달라집니다.</p>
<pre class="text"><code>Call:
lm(formula = waiting ~ eruptions, data = faithful)
Coefficients:
(Intercept)    eruptions
      33.47        10.73</code></pre>
<p>여러 경우에 <code>lm</code> 함수의 R 출력 결과 중 일부를 불러와야 할 때가 있습니다. 이를 위해 <code>lm</code> 함수의 결과를 저장해야 합니다. R에서 일반적인 변수, 벡터 또는 데이터 프레임을 저장하는 것과 동일하게 수행할 수 있습니다.</p>
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb4"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb4-1"><a href="#cb4-1" aria-hidden="true" tabindex="-1"></a>model_name <span class="ot">&lt;-</span> <span class="fu">lm</span>(...)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<p>예를 들어, 올드 페이스풀 회귀를 slr로 저장한다고 가정해 보겠습니다. 코드는 다음과 같습니다.</p>
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb5"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb5-1"><a href="#cb5-1" aria-hidden="true" tabindex="-1"></a>slr <span class="ot">&lt;-</span> <span class="fu">lm</span>(waiting <span class="sc">~</span> eruptions, <span class="at">data =</span> faithful)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<p><code>lm</code> 출력 결과를 불러와야 하는 한 가지 사례는 오차 분산의 추정치인 MSE를 구하는 것입니다. MSE는 <code>lm</code> 객체의 요약 정보에 저장되어 있으며, R의 <code>summary</code> 함수를 통해 접근할 수 있습니다. 이 함수는 이전에 변수의 다섯 수치 요약(Five-number summary)을 구하는 데 사용된 적이 있습니다. <code>summary</code> 함수의 입력값이 <code>lm</code> 객체인 경우, 회귀에 대한 요약을 반환합니다.</p>
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb6"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb6-1"><a href="#cb6-1" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(model_object)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<p>이 요약 정보는 회귀 모델을 평가할 때 우리의 몇 가지 요구를 충족시킬 것입니다. slr로 저장된 올드 페이스풀 회귀의 요약 정보에 접근하고 싶다면 코드는 다음과 같습니다.</p>
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb7"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb7-1"><a href="#cb7-1" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(slr)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<p>그러면 R은 아래와 같은 요약 정보를 반환합니다. MSE 또는 거기서 파생된 통계량은 요약 정보의 <code>Residual standard error</code> 부분에 저장되어 있습니다. 잔차 표준 오차(Residual standard error)는 MSE의 제곱근이며, 이는 오차의 표준 편차에 대한 추정치 <span class="math inline">\(\hat{\sigma}\)</span>가 됩니다. 올드 페이스풀 회귀에서 잔차 표준 오차는 5.914이며, 따라서 MSE와 오차 분산 추정치는 <span class="math inline">\(\hat{\sigma}^2 = 5.914^2 = 34.9755\)</span>가 됩니다.</p>
<pre class="text"><code>Call:
lm(formula = waiting ~ eruptions, data = faithful)

Residuals:
     Min       1Q   Median       3Q      Max
-12.0796  -4.4831   0.2122   3.9246  15.9719

Coefficients:
            Estimate Std. Error t value Pr(&gt;|t|)
(Intercept)  33.4744     1.1549   28.98   &lt;2e-16 
eruptions    10.7296     0.3148   34.09   &lt;2e-16 
---
Signif. codes:  0 '' 0.001 '' 0.01 '' 0.05 '.' 0.1 ' ' 1

Residual standard error: 5.914 on 270 degrees of freedom
Multiple R-squared:  0.8115,    Adjusted R-squared:  0.8108
F-statistic:  1162 on 1 and 270 DF,  p-value: &lt; 2.2e-16</code></pre>
</section>
<section id="연습-문제" class="level2">
<h2 class="anchored" data-anchor-id="연습-문제">연습 문제</h2>
<ol type="1">
<li>R의 기본 패키지에 포함된 cars 데이터셋을 로드해 주세요. 차량의 속도(speed)를 사용하여 차량의 정지 거리(dist)를 잘 예측하는 회귀 모델은 무엇인가?</li>
<li>Ecdat 패키지에서 Icecream 데이터셋을 R로 로드해 주세요. 월평균 기온(temp)을 사용하여 월간 아이스크림 소비량(cons)을 예측하는 최적의 회귀 모델은 무엇입니까? 오차 분산의 추정치는 얼마입니까?</li>
<li>DAAG 라이브러리에서 humanpower1 데이터셋을 로드해 주세요. 이 데이터셋은 산소 섭취량과 킬로그램당 와트 단위의 전력 출력 사이의 관계를 살펴보겠습니다. 산소 섭취량(o2)을 예측 변수로 사용하여 킬로그램당 와트 전력 출력(wattsPerKg)을 예측하는 최적의 회귀 모델은 무엇입니까? 오차 분산의 추정치는 얼마입니까?</li>
</ol>
</section>
<section id="회귀를-이용한-예측-생성" class="level2">
<h2 class="anchored" data-anchor-id="회귀를-이용한-예측-생성">회귀를 이용한 예측 생성</h2>
<p>회귀의 주요 목표 중 하나는 예측을 생성하는 것입니다. 우리는 정지 거리를 예측하고 싶고, 올드 페이스풀의 대기 시간을 예측하고 싶습니다. 따라서 회귀 모델을 사용하여 이러한 예측을 만드는 방법이 필요합니다.</p>
<p>방금 올드 페이스풀의 분출이 2분 동안 지속되는 것을 관찰했다고 가정해 보겠습니다. 대기 시간을 어떻게 예측할 수 있을까요? 우리는 일반적으로 추정 회귀선이 예측 변수(분출 시간)와 반응 변수(대기 시간) 사이의 관계를 잘 추측한 것이라고 가정합니다. 그 직선은 분출 시간의 모든 가능한 값을 통과하므로, 대기 시간에 대한 최선의 추측—우리의 예측—은 관심 있는 예측 변수 값에서의 회귀선 값이 되어야 한다는 것이 타당해 보입니다. 따라서 올드 페이스풀의 분출이 2분이었다면, 대기 시간은 33.47 + 10.73 × 2 = 54.93분이 될 것으로 기대할 수 있습니다.</p>
<p>일반적으로 예측값은 <span class="math inline">\(\hat{y}\)</span>으로 표기하며, 특정 <span class="math inline">\(x_i\)</span> 값이 주어졌을 때의 이 예측값들을 <span class="math inline">\(\hat{y}_i=\hat{\beta}_0+\hat{\beta}_1x_i\)</span>로 설정합니다. <span class="math inline">\(x_i\)</span> 값이 데이터셋에 포함된 값일 때, <span class="math inline">\(\hat{y}_i\)</span>를 적합값(Fitted value)이라고 부릅니다. <span class="math inline">\(x_i\)</span>가 예측 변수의 새로운 값일 경우, <span class="math inline">\(\hat{y}_i\)</span>를 예측값(Prediction)이라고 부릅니다.</p>
<p>또한 적합값을 사용하여 잔차를 생성할 수도 있습니다. 잔차는 <span class="math inline">\(e_i=y_i−\hat{\beta}_0−\hat{\beta}_1x_i\)</span>로 정의되었고 적합값은 <span class="math inline">\(\hat{y}_i=\hat{\beta}_0+\hat{\beta}_1x_i\)</span>임을 상기해 주세요. 따라서 잔차는 다음과 같이 계산될 수 있습니다.</p>
<p><span class="math inline">\(e_i = y_i - \hat{y}_i\)</span></p>
<p>이런 방식으로, 잔차는 흔히 “관측값 마이너스 예측값”으로 계산되는 것으로 언급됩니다.</p>
<p>개별적인 예측값은 수작업으로 만들기가 비교적 쉽지만, 적합값이나 예측값이 대량으로 필요한 경우 R은 몇 가지 옵션을 제공합니다. 관측치에 대한 적합값이 필요한 경우, 이는 저장된 <code>lm</code> 객체 내에 <code>fitted.values</code>라는 이름으로 저장되어 있습니다. 플로팅이나 분석을 위해 이에 접근하려면 다음 코드를 사용합니다.</p>
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb9"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb9-1"><a href="#cb9-1" aria-hidden="true" tabindex="-1"></a><span class="fu">fitted</span>(model_object)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<p>slr로 저장된 올드 페이스풀 회귀에서는 <code>fitted(slr)</code> 코드를 사용하여 적합값에 접근합니다. 잔차도 <code>lm</code> 객체 내에 <code>residuals</code>라는 이름으로 저장되어 있으므로 유사한 방식으로 접근할 수 있습니다. 올드 페이스풀 회귀의 경우, 다음을 사용하여 잔차에 접근할 수 있습니다.</p>
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb10"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb10-1"><a href="#cb10-1" aria-hidden="true" tabindex="-1"></a><span class="fu">resid</span>(slr)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<p>원하는 예측값이 예측 변수의 새로운 값을 나타내는 경우, <code>predict</code> 함수를 사용하여 이러한 값들을 생성합니다. <code>predict</code> 함수는 저장된 <code>lm</code> 객체—우리의 선형 회귀를 나타냄—와 예측 변수의 새로운 값 또는 값들을 포함하는 데이터 프레임을 입력으로 받습니다.</p>
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb11"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb11-1"><a href="#cb11-1" aria-hidden="true" tabindex="-1"></a><span class="fu">predict</span>(<span class="at">object =</span> model_object, <span class="at">newdata =</span> new_data)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<p>새로운 예측 변수 값을 위한 데이터 프레임에서 인식해야 할 핵심 사항이 하나 있습니다. 예측 변수가 <code>lm</code> 공식에서 구체적으로 명명되었으므로, <code>newdata</code> 데이터 프레임 내의 변수 이름도 이와 일치해야 합니다. 예를 들어, slr로 저장된 올드 페이스풀 회귀에서 이전 분출이 2.75분 동안 지속되었다고 가정하고 대기 시간에 대한 예측값을 생성하고 싶다고 해 보겠습니다. 이를 위한 R 코드는 다음과 같습니다.</p>
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb12"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb12-1"><a href="#cb12-1" aria-hidden="true" tabindex="-1"></a><span class="fu">predict</span>(<span class="at">object =</span> slr, <span class="at">newdata =</span> <span class="fu">data.frame</span>(<span class="at">eruptions =</span> <span class="fl">2.75</span>))</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<p>그러면 R은 62.9809라는 예측값을 반환할 것입니다. 약간의 산술 계산을 통해 이것이 (물론 반올림 오차 범위 내에서) 정확함을 확인할 수 있습니다.</p>
<p>예측값과 관련하여 특히 주목해야 할 중요한 사항 중 하나는 예측을 생성해서는 안 되는 값들이 있다는 점입니다. 일반적으로 예측 변수 범위 밖의 값에 대해 예측을 생성해서는 안 되는데, 이를 외삽(Extrapolating)이라고 합니다. 외삽이 왜 문제가 될까요? 우리는 일반적으로 예측 변수와 반응 변수 사이의 관계가 예측 변수의 범위 내에서 선형이라고 가정합니다. 그 범위 밖에서 예측 변수와 반응 변수가 어떻게 관련되어 있는지는 알 수 없습니다. 계속 선형일 수도 있고, 급격하게 변할 수도 있습니다.</p>
<p>그 예시를 서 볼 수 있는데, 예측 변수의 좁은 범위에서는 선형으로 보이지만 예측 변수와 반응 변수 사이의 전반적인 관계는 고도로 비선형으로 남아 있습니다. 만약 좁은 범위를 근거로 선형성을 가정하고 외삽한다면, 실제와는 판이하게 다른 예측을 하게 될 것입니다.</p>
</section>
<section id="연습-문제-1" class="level2">
<h2 class="anchored" data-anchor-id="연습-문제-1">연습 문제</h2>
<ol start="4" type="1">
<li>R의 cars 데이터셋을 바탕으로—speed를 사용하여 dist를 예측함—시속 30마일(MPH)일 때의 예상 정지 거리는 얼마인가 [31]?</li>
<li>HistData 라이브러리에서 Galton 데이터셋을 R로 로드해 주세요. 평균 부모 키(parent)를 사용하여 자녀 키(child)를 예측하는 회귀를 실행하고, 평균 부모 키가 68.5인치일 때 자녀 키를 예측해 주세요 [75,76].</li>
<li>HSAUR 라이브러리에서 water 데이터셋을 로드해 주세요 [99,102]. 이 데이터셋은 물의 경도와 사망률 사이의 관계를 살펴보겠습니다. 단순 선형 회귀를 바탕으로, 물의 칼슘 농도(경도, hardness)가 60ppm일 때 남성 주민 100,000명당 기대되는 사망률(mortality)은 얼마입니까?</li>
</ol>
</section>
<section id="회귀의-가정" class="level2">
<h2 class="anchored" data-anchor-id="회귀의-가정">회귀의 가정</h2>
<p>모든 통계 기법과 마찬가지로, 회귀 분석도 기법의 결과가 유효하기 위해 반드시 참이어야 하는 가정들이 있습니다. 이미 몇 가지를 논의했지만, 가정을 하나 더 추가해야 합니다. 바로 가정한 모델이 적절하다는 것, 즉 예측 변수와 반응 변수 사이의 관계가 실제로 선형이라는 것입니다. 이로써 가정은 총 네 가지가 됩니다.</p>
<ul>
<li>• 선형 모델이 적절합니다.</li>
<li>• 오차는 독립적입니다.</li>
<li>• 오차의 기댓값은 0입니다.</li>
<li>• 오차의 분산은 일정하다<span class="math inline">\((\sigma^2\)</span>).</li>
</ul>
<p>회귀 결과를 신뢰하려면 이러한 가정들이 유지되어야 합니다. 따라서 우리는 이들 각각을 확인해야 하며, 순서대로 진행할 것입니다.</p>
<section id="가정-1-선형성" class="level3">
<h3 class="anchored" data-anchor-id="가정-1-선형성">가정 1: 선형성</h3>
<p>이 가정은 우리가 회귀 모델을 어떻게 정의했는지에서 비롯됩니다. 회귀 모델이 yi=β0+β1xi+ϵ<span class="math inline">\(i\)</span>라고 서술했음을 상기해 주세요.</p>
<p>이는 모델에서 선형 성분만 허용합니다. 만약 예측 변수와 반응 변수 사이의 실제 관계가 이차식(Quadratic)—즉, <span class="math inline">\(xi2\)</span> 성분을 포함함—이라면 우리의 회귀 모델은 부적절할 것입니다. 이 가정을 확인하기 위해, 각 관측치에 대한 회귀 잔차를 해당 관측치의 적합값에 대해 도표로 그립니다. 선형성이 유지된다면 잔차는 아무런 패턴도 보이지 않고 무작위로 흩어져 있는 것처럼 보일 것입니다. 잔차에 어떤 패턴이라도 있다면, 이는 선형성 가정이 유지되지 않음을 의미합니다. ([R에서 이를 확인하려면 적합값과 잔차를 찾아야 합니다. 적합값 <span class="math inline">\(\hat{y}_{i}=\hat{\beta}_0+\hat{\beta}_1xi\)</span>는 우리 데이터셋의 주어진 관측치에 대한 예측값이고, 잔차 <span class="math inline">\(ei\)</span>는 무작위 오차 ϵ<span class="math inline">\(i\)</span>에 대한 추정치로, 관측값 마이너스 예측값<span class="math inline">\((ei=yi-\hat{y}_{i}\)</span>)으로 계산됨을 상기해 주세요.</p>
<p>적합값은 <code>lm</code> 객체 내에 <code>fitted.values</code>라는 이름으로 저장되어 있고, 잔차는 같은 곳에 <code>residuals</code>라는 이름으로 저장되어 있습니다. 이에 접근하기 위해 데이터 프레임에서 변수를 호출하는 것과 유사하게 <code>$</code> 표기법을 사용할 수 있습니다. 예를 들어, 올드 페이스풀 데이터셋에 대한 단순 선형 회귀를 slr이라는 이름으로 저장했음을 상기해 주세요. 이러한 잔차와 적합값을 보고 싶다면 다음을 사용합니다.</p>
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb13"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb13-1"><a href="#cb13-1" aria-hidden="true" tabindex="-1"></a><span class="fu">fitted</span>(slr)</span>
<span id="cb13-2"><a href="#cb13-2" aria-hidden="true" tabindex="-1"></a><span class="fu">resid</span>(slr)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<p>가정을 확인하려면 다음 기본 코드를 사용합니다.</p>
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb14"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb14-1"><a href="#cb14-1" aria-hidden="true" tabindex="-1"></a><span class="fu">tibble</span>(<span class="at">fitted =</span> <span class="fu">fitted</span>(slr), <span class="at">residual =</span> <span class="fu">resid</span>(slr)) <span class="sc">|&gt;</span></span>
<span id="cb14-2"><a href="#cb14-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ggplot</span>(<span class="fu">aes</span>(<span class="at">x =</span> fitted, <span class="at">y =</span> residual)) <span class="sc">+</span></span>
<span id="cb14-3"><a href="#cb14-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_hline</span>(<span class="at">yintercept =</span> <span class="dv">0</span>, <span class="at">linetype =</span> <span class="st">"dashed"</span>) <span class="sc">+</span></span>
<span id="cb14-4"><a href="#cb14-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>()</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<p>그러면 그림 19.6과 같은 그래프가 생성됩니다. 이 그래프의 코드에는 다른 것들 중에서도 도표 문자와 축 레이블을 변경하기 위한 몇 가지 추가 옵션이 포함되어 있음에 유의해 주세요. 이 도표를 보면 선형성 가정이 유지되는 것으로 보입니다.</p>
<p>가정을 확인하기 위해 적합값 대비 잔차를 도표로 그리는 과정에서 더 쉬운 방법이 있을 것 같아 보일 수 있습니다. 즉, 단순히 예측 변수 대비 반응 변수를 도표로 그릴 수도 있습니다. 이 관계에서 선형성이 보이라면 가정이 충족된 것일 것입니다. 하지만 예측 변수 대비 반응 변수를 그리는 것은 오해의 소지가 있을 수 있습니다. 다음 데이터를 생각해 보세요. 제임스 포브스(James Forbes)는 고도—기압으로 표현됨—가 물의 끓는점에 미치는 영향을 조사한 스코틀랜드 연구자였습니다. 데이터는 MASS 라이브러리의 forbes 데이터셋에 저장되어 있습니다 [10,93]. 예측 변수인 기압 대비 반응 변수인 끓는점을 도표로 그려보면, 하나의 이상한 이상치(Outlier) 점이 있긴 하지만 관계가 선형인 것처럼 보입니다. 그러나 선형 회귀를 실행하고 적합값 대비 잔차를 도표로 그려보면 잔차에서 명확한 곡선 패턴이 보입니다. 잔차는 이러한 패턴을 훨씬 더 잘 잡아내므로 가정을 확인하는 데 더 적합합니다. (선형성 가정이 위반된 경우, 종종 반응 변수를 변환하여 선형성이 존재하는 모델을 만들 수 있습니다. 포브스의 데이터가 그 예시인데, 기압을 사용하여 끓는점의 로그(Log)를 모델링하는 것이 적절한 모델이 됩니다.</p>
</section>
<section id="가정-2-독립성" class="level3">
<h3 class="anchored" data-anchor-id="가정-2-독립성">가정 2: 독립성</h3>
<p>오차들이 서로 종속적일 때는 대개 두 가지 원인 중 하나가 있습니다. 예측 변수가 시간 관련 변수여서 오차들이 서로 연관되어 있거나—이를 종단적(Longitudinal) 또는 시계열(Time-series) 데이터라고 함—, 관측치들이 다른 관측치와 물리적으로 인접해 있어 예측 변수들이 연관되어 있는 경우—이를 공간(Spatial) 데이터라고 함—입니다. 이러한 사례들은 이 책의 범위를 벗어나므로 그 확인 방법과 해결책은 여기서 다루지 않습니다. 여기서 논의하는 단순한 사례들—비종단적 및 비공간적 데이터—의 경우, 독립성 가정은 흔히 참인 것으로 받아들여지며 따라서 공식적으로 확인하지 않습니다.</p>
</section>
<section id="가정-3-오차의-평균은-0" class="level3">
<h3 class="anchored" data-anchor-id="가정-3-오차의-평균은-0">가정 3: 오차의 평균은 0</h3>
<p>오차의 기댓값이 0인지 확인하는 과정에서, 우리는 오차 ϵ<span class="math inline">\(i\)</span>가 알려지지 않은 확률 변수임을 상기해야 합니다. 따라서 이러한 오차에 대한 대리치(Proxy)가 필요한데, 잔차 <span class="math inline">\(ei\)</span> 형태의 대리치를 이미 가지고 있습니다. 이를 염두에 두고 잔차의 기댓값에 대한 추정치를 찾을 수 있다면 이를 가정을 확인하는 데 사용할 수 있습니다. 보통 단순한 표본 평균을 사용하여 기댓값을 추정할 수 있습니다. 그렇다면 잔차의 표본 평균 <span class="math inline">\(e¯\)</span>은 얼마입니까? 약간의 수학을 이용하면 실제로 <span class="math inline">\(e¯=0\)</span>임을 보일 수 있으며, 이는 어떤 데이터셋과 어떤 회귀에서든 마찬가지일 것입니다. 이 때문에 우리는 일반적으로 이 가정도 유지되는 것으로 받아들일 것입니다.</p>
</section>
<section id="가정-4-등분산성" class="level3">
<h3 class="anchored" data-anchor-id="가정-4-등분산성">가정 4: 등분산성</h3>
<p>오차의 분산이 일정하다는 가정—등분산성(Homoskedasticity)이라고 함—은 생각보다 자주 위반됩니다. 많은 실제 데이터셋에서 반응 변수의 값이 커짐에 따라 반응 변수의 가변성도 증가합니다. 이 오차 분산을 확인하는 과정에는 당연하게도 회귀 오차의 대리치인 잔차가 관여합니다. 선형성을 확인할 때와 마찬가지로, 등분산성을 확인하기 위해 적합값 대비 잔차를 도표로 그립니다. 선형성과 마찬가지로 오차가 등분산적이라면 적합값 대비 잔차 도표는 무작위로 흩어진 패턴을 보일 것입니다. 만약 패턴, 특히 서 보이는 것과 유사한 “부채꼴 패턴”이 보이라면 오차는 이분산적(Heteroskedastic)이며 가정이 위반된 것입니다.</p>
<p>선형성과 마찬가지로 잔차는 원시 데이터 도표보다 가정 위반을 더 명확하게 보여줍니다. 올드 페이스풀 회귀의 경우 그림 19.6을 보면 부채꼴 패턴이 없으므로 오차는 등분산적입니다. 오차가 이분산적인 경우, 선형성 사례와 유사하게 반응 변수를 변환하면 여러 경우에 오차가 등분산적이 되어 가정을 충족하게 됩니다.</p>
</section>
</section>
<section id="회귀에-대한-추론" class="level2">
<h2 class="anchored" data-anchor-id="회귀에-대한-추론">회귀에 대한 추론</h2>
<p>이제 회귀 모델을 적합시키고 예측값을 생성하며 가정을 확인했으므로, 회귀에 대한 핵심 질문에 도달했습니다. “우리의 예측 변수는 회귀 모델에서 유용합니까?” 다시 말해, “반응 변수를 예측하는 데 도움이 될까요?”</p>
<p>이는 지극히 중요한 질문입니다. 예측 변수가 쓸모없다는 주장과 유용하다는 주장을 테스트하여 이 질문에 대한 답을 결정할 방법이 필요합니다. 다행히 통계학은 가설 검정(Hypothesis testing)을 통해 그러한 메커니즘을 제공합니다. 이 가설 검정의 단계는 이전과 동일하며, 올드 페이스풀 간헐천의 분출 시간이 다음 분출까지의 대기 시간을 예측하는지 여부를 테스트하는 관점에서 단계를 진행할 것입니다.</p>
<section id="가설-설정" class="level3">
<h3 class="anchored" data-anchor-id="가설-설정">가설 설정</h3>
<p>가설 검정에서 우리의 목표는 관심 질문에 답하는 모수에 대한 주장을 테스트하는 것입니다. 이 경우 우리의 질문은 “예측 변수가 반응 변수를 예측하는 데 도움이 될까요?”입니다. 우리의 귀무 가설(Null hypothesis)—현상 유지 또는 “흥미로운 일이 없음” 결과를 나타냄—은 예측 변수가 반응 변수를 예측하는 데 유용하지 않는다는 것이 될 것입니다. 그렇다면 대립 가설(Alternative hypothesis)은 예측 변수가 실제로 반응 변수를 예측하는 데 유용하다는 것이 됩니다.</p>
<p>과제는 이러한 주장들을 모수라는 용어로 표현해야 한다는 점입니다. 이들 가설 각각이 무엇을 의미하는지 생각해 보겠습니다. 만약 귀무 가설이 참이고 예측 변수가 반응 변수에 영향을 미치지 않다면, 이는 예측 변수 값이 무엇이든 반응 변수가 동일하게 유지됨을 의미합니다. 이것이 가능한 유일한 방법은 기울기 <span class="math inline">\(\beta_1\)</span>이 0인 경우입니다. 이것이 우리의 귀무 가설이 될 것입니다. 예측 변수가 실제로 유용하다면 예측 변수의 값이 반응 변수에 영향을 미치므로 기울기는 0이 아닙니다. 따라서 우리의 두 가설은 다음과 같습니다.</p>
<p>H0:β1=0 <span class="math display">\[
H_A:\beta_1≠0.
\]</span> 이 가설 세트는 올드 페이스풀 회귀에도 그대로 적용되어 기울기가 0인지 아닌지를 테스트하게 됩니다.</p>
</section>
<section id="유의-수준-설정" class="level3">
<h3 class="anchored" data-anchor-id="유의-수준-설정">유의 수준 설정</h3>
<p>다른 가설 검정과 마찬가지로, 유의 수준(Significance level) α는 제1종 오류(Type I error)를 범하는 것에 대한 본인의 감내 수준과 분야의 관례에 따라 설정하며 기본값은 <span class="math inline">\(\alpha=0.05\)</span>입니다. 본 예제에서는 기본값인 <span class="math inline">\(\alpha=0.05\)</span>를 사용하겠습니다.</p>
</section>
<section id="데이터-수집-및-요약" class="level3">
<h3 class="anchored" data-anchor-id="데이터-수집-및-요약">데이터 수집 및 요약</h3>
<p>이 특정 가설 검정을 위해 회귀 분석 결과—특히 기울기 추정치 <span class="math inline">\(\hat{\beta}_1\)</span>과 평균 제곱 오차 <span class="math inline">\(\hat{\sigma}^2\)</span>—와 표본 크기 n, 그리고 예측 변수의 분산 <span class="math inline">\(sx2\)</span>가 필요할 것입니다. 우리 예제의 경우, 기울기 추정치는 <span class="math inline">\(\hat{\beta}_1=10.7296\)</span>이고 MSE는 <span class="math inline">\(\hat{\sigma}^2=34.9755\)</span>임을 알고 있습니다. 표본 크기는 <span class="math inline">\(n=272\)</span>이며 예측 변수인 분출 시간의 분산은 <span class="math inline">\(sx2=1.3027\)</span>입니다.</p>
</section>
<section id="검정-통계량-계산" class="level3">
<h3 class="anchored" data-anchor-id="검정-통계량-계산">검정 통계량 계산</h3>
<p>이전의 각 가설 검정과 마찬가지로, 검정 통계량 계산 과정은 검정 통계량에 대한 일반 공식에서 시작합니다.</p>
<p>t=(표본 통계량 – 귀무 가설 값) / 표준 오차. 데이터, 가설, 그리고 표본 통계량에 대한 지식을 바탕으로 이들 각 성분을 채워 넣어야 합니다. 먼저 귀무 가설의 모수를 추정하는 표본 통계량을 찾아야 합니다. 회귀 분석의 경우 귀무 가설은 다음과 같았습니다.</p>
<p><span class="math display">\[
H_0:\beta_1=0.
\]</span> 따라서 <span class="math inline">\(\beta_1\)</span>을 추정하는 우리 데이터에서 계산된 표본 통계량이 필요합니다. 단순 선형 회귀의 기울기 <span class="math inline">\(\hat{\beta}_1\)</span>이 표본 통계량으로서 합리적인 선택임이 분명해 보입니다. 추가로 귀무 가설을 살펴보면 귀무 가설 값이 0임을 알 수 있습니다. 따라서 이 단계에서의 검정 통계량은 다음과 같습니다.</p>
<p><span class="math display">\[
t=\frac{\hat{\beta}_1-0}{\text{표준 오차}}.
\]</span> 이제 남은 것은 표본 통계량의 표준 오차(Standard error), 즉 <span class="math inline">\(s.e.(\hat{\beta}_1)\)</span>뿐입니다. 특정 조건 하에서—잠시 후에 논의하겠습니다—회귀 기울기 추정치 <span class="math inline">\(\hat{\beta}_1\)</span>은 정규 분포를 따르며, 구체적으로는 다음과 같다는 것이 알려져 있습니다.</p>
<p><span class="math display">\[
\hat{\beta}_1∼N(\beta_1, \hat{\sigma}^2 / ((n-1)s^2_{x})).
\]</span> 이는 <span class="math inline">\(\hat{\beta}_1\)</span>의 표준 오차가 <span class="math inline">\(s.e.(\hat{\beta}_1)=\sqrt{\hat{\sigma}^2 / ((n-1)s^2_{x})}\)</span>가 됨을 의미합니다. 여기서 <span class="math inline">\(\hat{\sigma}^2\)</span>는 회귀 분석의 평균 제곱 오차이고, n은 표본 크기이며, <span class="math inline">\(s_x^2\)</span>는 예측 변수의 표본 분산입니다. 따라서 이 가설 검정을 위한 검정 통계량은 다음과 같습니다.</p>
<p><span class="math display">\[
t=\hat{\beta}_1 / \sqrt{\hat{\sigma}^2 / ((n-1)s^2_{x})}.
\]</span> 올드 페이스풀 회귀의 경우, 검정 통계량의 여러 성분을 대입하면 다음과 같습니다.</p>
<p><span class="math display">\[
t=10.7296 / \sqrt{34.9755 / (271 \times 1.3027)} = 34.09.
\]</span> ### p-값 계산</p>
<p>다른 가설 검정과 마찬가지로, p-값을 계산하기 위해서는 대립 가설뿐만 아니라 검정 통계량이 어떤 분포를 따르는지 알아야 합니다. 회귀 추론 사례에서, 회귀 기울기 추정치 <span class="math inline">\(\hat{\beta}_1\)</span>이 정규 분포를 따른다면 검정 통계량은 자유도(Degrees of freedom)가 <span class="math inline">\(n-2\)</span>인 t-분포를 따르게 됩니다.</p>
<p>언제나 그렇듯, p-값 계산은 이전 테스트들과 유사한 논리에 따라 대립 가설에 의존합니다. 하지만 이 검정에서 우리의 초점은 항상 HA:β≠<span class="math inline">\(0\)</span>이므로, 관심 있는 p-값은 하나뿐입니다.</p>
<table class="caption-top table">
<thead>
<tr class="header">
<th>H_A</th>
<th>P-값</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>H_A:β1 ≠ 0</td>
<td>2 × P(t_n−2 ⩾ abs(t))</td>
</tr>
</tbody>
</table>
<p>어느 가설 검정과 마찬가지로 우려해야 할 가정이 있습니다. 이미 앞서 논의한 몇 가지 회귀 가정들을 알고 있습니다. 추론이 유효하려면 이들이 유지되어야 합니다. 그러나 지금 우리는 검정 통계량이 t-분포를 따르는 데 필요한 가정에 집중하고 있습니다. 핵심 가정은 회귀 기울기 추정치 <span class="math inline">\(\hat{\beta}_1\)</span>이 정규 분포를 따라야 한다는 것이라고 언급했습니다. 그렇다면 이것이 참이기 위해 필요한 것이 무엇인지 질문하는 것이 타당합니다. 이 경우 두 가지 조건 중 하나가 참이어야 합니다. 오차가 정규 분포에서 나왔거나, 표본 크기가 중심 극한 정리(Central limit theorem)가 적용될 만큼 충분히 커야 합니다(보통 <span class="math inline">\(n\ge 30\)</span>).</p>
<p>표본 크기가 충분히 큰지는 알 수 있지만, 오차가 정규 분포를 따르는지는 어떻게 알 수 있을까요? 이를 결정하기 위해 오차 대신 잔차를 사용할 수 있다는 것이 합리적입니다. 하지만 어떻게 진행해야 할까요? 데이터 표본이 정규 분포를 따르는지 확인하기 위한 공식적인 테스트들이 존재합니다. 그러나 이 책에서는 비공식적인 기법, 즉 잔차의 히스토그램을 살펴보는 것에 집중할 것입니다. 히스토그램이 대략 정규 분포를 따르는 것처럼 보이라면 이 가정이 충족된 것으로 간주할 것입니다.</p>
<p>p-값을 계산하기 위해 다시 R의 <code>pt</code> 함수를 활용합니다. 올드 페이스풀 예제에서 표본 크기는 분명히 30보다 크므로 중심 극한 정리가 유지될 것이며, 검정 통계량은 자유도가 <span class="math inline">\(272-2=270\)</span>인 t-분포를 따를 것입니다. 따라서 다음 R 코드를 사용하여 p-값이 8.08×<span class="math inline">\(10^-100\)</span>임을 알 수 있습니다.</p>
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb15"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb15-1"><a href="#cb15-1" aria-hidden="true" tabindex="-1"></a><span class="dv">2</span>  <span class="fu">pt</span>(<span class="at">q =</span> <span class="fl">34.09</span>, <span class="at">df =</span> <span class="dv">270</span>, <span class="at">lower.tail =</span> <span class="cn">FALSE</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</section>
<section id="결론" class="level3">
<h3 class="anchored" data-anchor-id="결론">결론</h3>
<p>결론 단계는 변하지 않았습니다. p-값이 유의 수준 α보다 작으면 귀무 가설을 기각합니다. 그렇지 않으면 귀무 가설 기각에 실패하게 됩니다. 올드 페이스풀 예제에서 p-값은 분명히 <span class="math inline">\(\alpha=0.05\)</span>보다 작으므로 귀무 가설을 기각하고 β1≠<span class="math inline">\(0\)</span>이라고 결론 내릴 것입니다. 따라서 분출 시간은 다음 분출까지의 대기 시간을 예측하는 데 정말로 도움이 됩니다.</p>
</section>
<section id="r에서의-회귀-추론" class="level3">
<h3 class="anchored" data-anchor-id="r에서의-회귀-추론">R에서의 회귀 추론</h3>
<p>이 가설 검정의 많은 부분을 수작업으로 할 수도 있지만, R은 이전에 본 함수를 통해 가설 검정의 전체 결과를 제공합니다. <code>summary</code> 함수에 <code>lm</code> 객체를 입력으로 주면 가설 검정의 전체 결과를 얻을 수 있습니다. 가설 검정 결과는 요약 정보의 <code>Coefficients</code> 섹션에서 볼 수 있습니다. slr로 저장된 올드 페이스풀 예제를 생각해 보겠습니다. 회귀 요약 정보에 접근하기 위해 <code>summary(slr)</code> 코드를 사용하면 다음과 같은 결과를 얻습니다.</p>
<pre class="text"><code>Call:
lm(formula = waiting ~ eruptions, data = faithful)

Residuals:
     Min       1Q   Median       3Q      Max
-12.0796  -4.4831   0.2122   3.9246  15.9719

Coefficients:
            Estimate Std. Error t value Pr(&gt;|t|)
(Intercept)  33.4744     1.1549   28.98   &lt;2e-16 
eruptions    10.7296     0.3148   34.09   &lt;2e-16 
---
Signif. codes:  0 '' 0.001 '' 0.01 '' 0.05 '.' 0.1 ' ' 1

Residual standard error: 5.914 on 270 degrees of freedom
Multiple R-squared:  0.8115,    Adjusted R-squared:  0.8108
F-statistic:  1162 on 1 and 270 DF,  p-value: &lt; 2.2e-16</code></pre>
<p>이 요약 정보의 <code>Coefficients</code> 섹션에는 <code>Estimate</code> 열에 저장된 회귀 기울기 및 절편 추정치, <code>Std. Error</code> 열의 기울기 및 절편에 대한 표준 오차, <code>t value</code> 아래의 검정 통계량, 그리고 <code>Pr(&gt;|t|)</code> 아래의 p-값을 포함하여 방대한 정보가 들어 있습니다. 마지막 열은 <code>Coefficients</code> 섹션 아래에 제공된 코드를 바탕으로 통계적으로 유의미한 변수—귀무 가설 H0:<span class="math inline">\(\betaj=0\)</span>을 기각하는 변수—를 식별할 수 있는 빠른 참조를 제공합니다.</p>
<p>올드 페이스풀 예제에서 이를 살펴보겠습니다. 우리는 특히 eruptions 변수의 기울기가 0인지 아니면 0이 아닌지에 관심이 있었습니다. <code>Coefficients</code> 섹션의 <code>eruptions</code> 행을 보면 회귀 기울기 추정치가 이전에 알았던 대로 <span class="math inline">\(\hat{\beta}_1=10.7296\)</span>임을 알 수 있습니다. 이 가설 검정을 수작업으로 진행한 결과 표준 오차가 <span class="math inline">\(s.e.(\hat{\beta}_1)=0.3148\)</span>이고 검정 통계량이 <span class="math inline">\(t=34.09\)</span>임을 알 수 있었습니다. 마지막으로 이전에 계산한 정확한 p-값은 없지만, 표에 따르면 2.2×<span class="math inline">\(10^-16\)</span>보다 작다는 것을 알 수 있습니다. 우리의 유의 수준이 이보다 작을 경우는 극히 드물 것이므로, 여전히 모수에 대한 결론을 도출할 수 있을 것입니다.</p>
</section>
</section>
<section id="회귀-모델의-성능-평가" class="level2">
<h2 class="anchored" data-anchor-id="회귀-모델의-성능-평가">회귀 모델의 성능 평가</h2>
<p>이제 예측 변수가 반응 변수를 모델링하는 데 유용한지 여부를 결정했으므로, 회귀에 대한 마지막 질문에 도달했습니다. “모델이 얼마나 좋은가?” 이는 사소해 보일 수 있지만 그렇지 않습니다. 비록 예측 변수가 유의미하고 H0:<span class="math inline">\(\beta_1=0\)</span>이라는 귀무 가설을 기각합니다 하더라도, 이것이 예측 변수가 좋은 회귀 모델을 만든다는 것을 의미하지는 않기 때문입니다.</p>
<p>우리 모델을 평가할 방법, 예측 변수가 얼마나 잘 작동하는지 이해하도록 돕는 방법이 필요합니다. 잔차는 회귀 모델의 예측값이 관측된 실제 상황과 얼마나 차이가 났는지를 나타내므로 좋은 시작점이 될 것으로 보입니다. 잔차를 평가할 때 우리는 그것들을 하나의 숫자로 요약하고 싶어 합니다. 잔차의 평균은 항상 0이라는 것을 알고 있으므로 적절한 요약치가 되지 못합니다. 대신 모든 잔차를 제곱하여 합산함으로써 잔차를 요약할 것입니다. 잔차를 제곱하면 모두 양수가 되며, 0에 가까운 값은 회귀 모델이 정확했음을 나타냅니다. 이 제곱된 잔차들을 모두 더하면 잔차 제곱합(Sum of Squared Residuals) 또는 SSR이 됩니다.</p>
<p><span class="math display">\[
SSR=∑_{i=1}^nei2.
\]</span> 단순 선형 회귀에서 <span class="math inline">\(\hat{\sigma}^2=SSE/(n-2)\)</span>이므로, 우리의 SSR은 평균 제곱 오차 <span class="math inline">\(\hat{\sigma}^2\)</span>와 직접 관련이 있습니다. 일반적으로 SSR이 0에 가까우면 모델이 데이터를 잘 적합시키고 있음을 의미합니다. SSR이 크면 모델이 데이터를 잘 적합시키지 못하고 있음을 의미합니다.</p>
<p>안타깝게도 이러한 해석에는 문제가 있습니다. 반응 변수에 존재하는 변동성의 양에 따라 달라진다는 것입니다. 제시된 다음 두 시뮬레이션 데이터셋을 살펴봐 주세요. 두 그래프를 볼 때, 오른쪽 회귀 모델이 관측값들이 선 주위에 더 빽빽하게 군집해 있어 반응 변수를 더 잘 예측할 것처럼 보입니다. 그러나 왼쪽 회귀의 SSR은 2421.9인 반면, 오른쪽 회귀의 SSR은 12050.5입니다.</p>
<p>왜 이런 결과가 나옵니까? 오른쪽 데이터셋의 반응 변수 분산(13516.02)이 왼쪽 데이터셋의 반응 변수 분산(36.29)보다 훨씬 크기 때문입니다. 전체 변동성과 SSR을 모두 고려하는 회귀 통계량이 필요합니다.</p>
<p>이 두 가지를 모두 고려하여 흔히 사용되는 통계량은 결정 계수(Coefficient of determination) 또는 <span class="math inline">\(R^2\)</span>입니다. <span class="math inline">\(R^2\)</span> 값은 회귀 모델에 의해 설명되는 반응 변수 전체 변동성의 백분율을 나타냅니다. <span class="math inline">\(R^2\)</span>는 백분율이므로 0과 1 사이로 범위가 제한되며, 값이 클수록 회귀 모델이 반응 변수의 변동성을 더 많이 설명하고 따라서 더 잘 작동하고 있음을 나타냅니다.</p>
<p><span class="math inline">\(R^2\)</span>의 공식은 다음과 같습니다.</p>
<p><span class="math display">\[
R^2=1-SSR/SST
\]</span> 여기서 SSR은 앞서 언급한 잔차 제곱합이고 SST는 전체 제곱합(Total sum of square)입니다. 전체 제곱합은 공식 SST=∑<span class="math inline">\(i=1n(yi-\bar{y})2\)</span>를 통해 계산하며, 여기서 <span class="math inline">\(\bar{y}\)</span>는 반응 변수의 평균입니다. SSR이 평균 제곱 오차와 연결되듯, SST는 반응 변수의 분산과 직접 연결됩니다. 따라서 이 정보를 사용하여 <span class="math inline">\(R^2\)</span> 공식을 다시 기술할 수 있습니다.</p>
<p><span class="math display">\[
R^2=1-((n-2)\hat{\sigma}^2) / ((n-1)s^2_{y}).
\]</span> 이 공식에서 <span class="math inline">\(\hat{\sigma}^2\)</span>는 평균 제곱 오차이고 <span class="math inline">\(sy2\)</span>는 반응 변수의 분산입니다. 올드 페이스풀 회귀에서 평균 제곱 오차는 <span class="math inline">\(\hat{\sigma}^2=34.9755\)</span>, 대기 시간 반응 변수의 분산은 <span class="math inline">\(sy2=184.8233\)</span>, 그리고 표본 크기는 <span class="math inline">\(n=272\)</span>임을 알고 있습니다. 이 정보를 사용하면 <span class="math inline">\(R^2\)</span> 값은 다음과 같습니다.</p>
<p><span class="math display">\[
R^2=1-(270×34.9755) / (271×184.8233)=0.8115.
\]</span> 따라서 분출 시간을 사용하여 다음 분출까지의 대기 시간을 예측하는 회귀 모델이 대기 시간 전체 변동성의 81.15%를 설명한다고 말할 수 있습니다.</p>
<p>단순 선형 회귀에서 결정 계수는 상관관계와 특별한 연관성을 갖습니다. 반응 변수 y와 예측 변수 x가 포함된 단순 선형 회귀의 <span class="math inline">\(R^2\)</span> 값은 <span class="math inline">\(R^2=rx,y_2\)</span>가 된다는 것이 밝혀졌습니다. 여기서 <span class="math inline">\(rx,y\)</span>는 상관관계와 같습니다. 올드 페이스풀 회귀에서도 이를 확인할 수 있는데, 분출 시간과 대기 시간 사이의 상관관계는 <span class="math inline">\(rx,y=0.9008\)</span>이고 이를 제곱하면 <span class="math inline">\(R^2=0.90082=0.8115\)</span>로 일치합니다.</p>
<p>회귀 가설 검정과 마찬가지로, R에서 <code>lm</code> 입력을 받는 <code>summary</code> 함수를 사용하여 <span class="math inline">\(R^2\)</span> 값을 찾을 수 있습니다. <span class="math inline">\(R^2\)</span>는 요약 정보의 <code>Coefficients</code> 섹션 아래 <code>Multiple R-squared</code> 부분에 저장되어 있습니다. slr로 저장된 올드 페이스풀 회귀의 요약 정보—<code>summary(slr)</code> 코드 사용—를 살펴보면 <code>Multiple R-squared</code> 섹션의 값이 우리가 계산한 <span class="math inline">\(R^2=0.8115\)</span> 값과 일치함을 쉽게 확인할 수 있습니다.</p>
<pre class="text"><code>Call:
lm(formula = waiting ~ eruptions, data = faithful)

Residuals:
     Min       1Q   Median       3Q      Max
-12.0796  -4.4831   0.2122   3.9246  15.9719

Coefficients:
            Estimate Std. Error t value Pr(&gt;|t|)
(Intercept)  33.4744     1.1549   28.98   &lt;2e-16 
eruptions    10.7296     0.3148   34.09   &lt;2e-16 
---
Signif. codes:  0 '' 0.001 '' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 5.914 on 270 degrees of freedom
Multiple R-squared:  0.8115,    Adjusted R-squared:  0.8108
F-statistic:  1162 on 1 and 270 DF,  p-value: &lt; 2.2e-16</code></pre>
</section>
<section id="연습-문제-2" class="level2">
<h2 class="anchored" data-anchor-id="연습-문제-2">연습 문제</h2>
<p>MASS 라이브러리에서 cabbages 데이터셋을 R로 로드해 주세요. 이 데이터셋은 양배추 머리 크기와 비타민 C 함량 사이의 관계를 살펴보겠습니다 [10,94].</p>
<ol start="7" type="1">
<li>머리 크기(HeadWt)를 사용하여 비타민 C 함량(VitC)을 예측하는 회귀를 실행해 주세요. 이 회귀에 대한 가정들이 충족될까요?</li>
<li>이 회귀의 추론을 바탕으로, 머리 무게가 양배추 머리의 비타민 C 함량을 예측할까요?</li>
<li>비타민 C 함량 전체 변동성의 몇 퍼센트가 회귀 모델에 의해 설명될까요?</li>
</ol>
<p>Ecdat 라이브러리에서 Cigar 데이터셋을 R로 로드해 주세요. 이 데이터셋은 미국 내 담배 가격과 판매량에 대한 조사입니다 [12,109].</p>
<ol start="10" type="1">
<li>담배 가격(price)을 사용하여 전체 판매량(sales)을 예측하는 회귀를 실행해 주세요. 이 회귀의 추론을 바탕으로, 담배 가격이 전체 판매량을 예측할까요?</li>
<li>이 회귀의 <span class="math inline">\(R^2\)</span>는 얼마입니까?</li>
<li>이 회귀에 대한 가정들이 충족될까요?</li>
</ol>
<p>DAAG 라이브러리에서 fruitohms 데이터셋을 로드해 주세요. 이 데이터셋은 즙 함량에 따른 키위 슬라이스의 전기 저항을 살펴보겠습니다 [23,110].</p>
<ol start="13" type="1">
<li>즙 백분율(juice)을 사용하여 전기 비저항(ohms)을 예측하는 회귀를 실행해 주세요. 이 회귀의 추론을 바탕으로, 즙이 비저항을 예측할까요?</li>
<li>이 회귀의 <span class="math inline">\(R^2\)</span>는 얼마입니까?</li>
<li>이 회귀에 대한 가정들이 충족될까요?</li>
</ol>
</section>
<section id="tidyverse와-함께-회귀-진단을-정리하기" class="level2">
<h2 class="anchored" data-anchor-id="tidyverse와-함께-회귀-진단을-정리하기">tidyverse와 함께 회귀 진단을 정리하기</h2>
<p><code>lm()</code>은 R의 기본 함수이므로 회귀 분석의 중심에는 계속 <code>lm()</code>이 있습니다. 다만 적합값과 잔차를 데이터 프레임으로 정리하면 그래프와 진단을 더 일관되게 수행할 수 있습니다.</p>
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb18"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb18-1"><a href="#cb18-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(tidyverse)</span>
<span id="cb18-2"><a href="#cb18-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb18-3"><a href="#cb18-3" aria-hidden="true" tabindex="-1"></a>slr <span class="ot">&lt;-</span> <span class="fu">lm</span>(waiting <span class="sc">~</span> eruptions, <span class="at">data =</span> faithful)</span>
<span id="cb18-4"><a href="#cb18-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb18-5"><a href="#cb18-5" aria-hidden="true" tabindex="-1"></a>regression_diagnostics <span class="ot">&lt;-</span> <span class="fu">tibble</span>(</span>
<span id="cb18-6"><a href="#cb18-6" aria-hidden="true" tabindex="-1"></a>  <span class="at">fitted =</span> <span class="fu">fitted</span>(slr),</span>
<span id="cb18-7"><a href="#cb18-7" aria-hidden="true" tabindex="-1"></a>  <span class="at">residual =</span> <span class="fu">resid</span>(slr),</span>
<span id="cb18-8"><a href="#cb18-8" aria-hidden="true" tabindex="-1"></a>  <span class="at">eruptions =</span> faithful<span class="sc">$</span>eruptions,</span>
<span id="cb18-9"><a href="#cb18-9" aria-hidden="true" tabindex="-1"></a>  <span class="at">waiting =</span> faithful<span class="sc">$</span>waiting</span>
<span id="cb18-10"><a href="#cb18-10" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb18-11"><a href="#cb18-11" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb18-12"><a href="#cb18-12" aria-hidden="true" tabindex="-1"></a>regression_diagnostics <span class="sc">|&gt;</span></span>
<span id="cb18-13"><a href="#cb18-13" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ggplot</span>(<span class="fu">aes</span>(<span class="at">x =</span> fitted, <span class="at">y =</span> residual)) <span class="sc">+</span></span>
<span id="cb18-14"><a href="#cb18-14" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_hline</span>(<span class="at">yintercept =</span> <span class="dv">0</span>, <span class="at">linetype =</span> <span class="st">"dashed"</span>) <span class="sc">+</span></span>
<span id="cb18-15"><a href="#cb18-15" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>(<span class="at">alpha =</span> <span class="fl">0.7</span>) <span class="sc">+</span></span>
<span id="cb18-16"><a href="#cb18-16" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(</span>
<span id="cb18-17"><a href="#cb18-17" aria-hidden="true" tabindex="-1"></a>    <span class="at">x =</span> <span class="st">"적합값"</span>,</span>
<span id="cb18-18"><a href="#cb18-18" aria-hidden="true" tabindex="-1"></a>    <span class="at">y =</span> <span class="st">"잔차"</span>,</span>
<span id="cb18-19"><a href="#cb18-19" aria-hidden="true" tabindex="-1"></a>    <span class="at">title =</span> <span class="st">"적합값 대비 잔차"</span></span>
<span id="cb18-20"><a href="#cb18-20" aria-hidden="true" tabindex="-1"></a>  )</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<p>예측도 같은 원칙으로 작성할 수 있습니다. 새 자료를 반드시 데이터 프레임 또는 tibble로 만들고, 열 이름을 회귀식의 예측 변수 이름과 일치시킵니다.</p>
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb19"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb19-1"><a href="#cb19-1" aria-hidden="true" tabindex="-1"></a>new_eruptions <span class="ot">&lt;-</span> <span class="fu">tibble</span>(<span class="at">eruptions =</span> <span class="fu">c</span>(<span class="fl">2.0</span>, <span class="fl">2.75</span>, <span class="fl">4.5</span>))</span>
<span id="cb19-2"><a href="#cb19-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb19-3"><a href="#cb19-3" aria-hidden="true" tabindex="-1"></a><span class="fu">predict</span>(</span>
<span id="cb19-4"><a href="#cb19-4" aria-hidden="true" tabindex="-1"></a>  <span class="at">object =</span> slr,</span>
<span id="cb19-5"><a href="#cb19-5" aria-hidden="true" tabindex="-1"></a>  <span class="at">newdata =</span> new_eruptions,</span>
<span id="cb19-6"><a href="#cb19-6" aria-hidden="true" tabindex="-1"></a>  <span class="at">interval =</span> <span class="st">"prediction"</span></span>
<span id="cb19-7"><a href="#cb19-7" aria-hidden="true" tabindex="-1"></a>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<p><code>interval = "prediction"</code>은 새 관측값 하나가 놓일 범위를 제시하고, <code>interval = "confidence"</code>는 평균 반응의 범위를 제시합니다. 두 구간은 질문이 다르므로 폭도 다릅니다. 회귀 분석에서 중요한 해석 습관은 기울기의 p-값만 읽지 않고, 산점도, 잔차, 외삽 여부, 예측 구간을 함께 확인하는 것입니다.</p>
</section>
<section id="결론-1" class="level2">
<h2 class="anchored" data-anchor-id="결론-1">결론</h2>
<p>회귀 분석은 예측 변수와 반응 변수 사이의 관계를 더 온전하게 이해하게 해줌으로써 상관관계 추론을 보완합니다. 데이터에 존재하는 무작위 오차에 대해 몇 가지 가정을 세움으로써 데이터를 잘 설명하는 직선을 추정할 수 있습니다. 이 직선을 통해 예측을 생성하고, 직선의 구성 요소에 대한 추론을 수행하며, 변동성의 어느 정도가 회귀선에 의해 설명되는지 이해할 수 있습니다. 이 모든 과정을 거치며 우리는 통계학에서 유용한 기법 중 하나인 선형 모델의 기초를 닦았습니다.</p>


</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
  window.document.addEventListener("DOMContentLoaded", function (event) {
    const icon = "";
    const anchorJS = new window.AnchorJS();
    anchorJS.options = {
      placement: 'right',
      icon: icon
    };
    anchorJS.add('.anchored');
    const isCodeAnnotation = (el) => {
      for (const clz of el.classList) {
        if (clz.startsWith('code-annotation-')) {                     
          return true;
        }
      }
      return false;
    }
    const onCopySuccess = function(e) {
      // button target
      const button = e.trigger;
      // don't keep focus
      button.blur();
      // flash "checked"
      button.classList.add('code-copy-button-checked');
      var currentTitle = button.getAttribute("title");
      button.setAttribute("title", "Copied!");
      let tooltip;
      if (window.bootstrap) {
        button.setAttribute("data-bs-toggle", "tooltip");
        button.setAttribute("data-bs-placement", "left");
        button.setAttribute("data-bs-title", "Copied!");
        tooltip = new bootstrap.Tooltip(button, 
          { trigger: "manual", 
            customClass: "code-copy-button-tooltip",
            offset: [0, -8]});
        tooltip.show();    
      }
      setTimeout(function() {
        if (tooltip) {
          tooltip.hide();
          button.removeAttribute("data-bs-title");
          button.removeAttribute("data-bs-toggle");
          button.removeAttribute("data-bs-placement");
        }
        button.setAttribute("title", currentTitle);
        button.classList.remove('code-copy-button-checked');
      }, 1000);
      // clear code selection
      e.clearSelection();
    }
    const getTextToCopy = function(trigger) {
      const outerScaffold = trigger.parentElement.cloneNode(true);
      const codeEl = outerScaffold.querySelector('code');
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
    const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
      text: getTextToCopy
    });
    clipboard.on('success', onCopySuccess);
    if (window.document.getElementById('quarto-embedded-source-code-modal')) {
      const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
        text: getTextToCopy,
        container: window.document.getElementById('quarto-embedded-source-code-modal')
      });
      clipboardModal.on('success', onCopySuccess);
    }
      var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
      var mailtoRegex = new RegExp(/^mailto:/);
        var filterRegex = new RegExp('/' + window.location.host + '/');
      var isInternal = (href) => {
          return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
      }
      // Inspect non-navigation links and adorn them if external
     var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
      for (var i=0; i<links.length; i++) {
        const link = links[i];
        if (!isInternal(link.href)) {
          // undo the damage that might have been done by quarto-nav.js in the case of
          // links that we want to consider external
          if (link.dataset.originalHref !== undefined) {
            link.href = link.dataset.originalHref;
          }
        }
      }
    function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
      const config = {
        allowHTML: true,
        maxWidth: 500,
        delay: 100,
        arrow: false,
        appendTo: function(el) {
            return el.parentElement;
        },
        interactive: true,
        interactiveBorder: 10,
        theme: 'quarto',
        placement: 'bottom-start',
      };
      if (contentFn) {
        config.content = contentFn;
      }
      if (onTriggerFn) {
        config.onTrigger = onTriggerFn;
      }
      if (onUntriggerFn) {
        config.onUntrigger = onUntriggerFn;
      }
      window.tippy(el, config); 
    }
    const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
    for (var i=0; i<noterefs.length; i++) {
      const ref = noterefs[i];
      tippyHover(ref, function() {
        // use id or data attribute instead here
        let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
        try { href = new URL(href).hash; } catch {}
        const id = href.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note) {
          return note.innerHTML;
        } else {
          return "";
        }
      });
    }
    const xrefs = window.document.querySelectorAll('a.quarto-xref');
    const processXRef = (id, note) => {
      // Strip column container classes
      const stripColumnClz = (el) => {
        el.classList.remove("page-full", "page-columns");
        if (el.children) {
          for (const child of el.children) {
            stripColumnClz(child);
          }
        }
      }
      stripColumnClz(note)
      if (id === null || id.startsWith('sec-')) {
        // Special case sections, only their first couple elements
        const container = document.createElement("div");
        if (note.children && note.children.length > 2) {
          container.appendChild(note.children[0].cloneNode(true));
          for (let i = 1; i < note.children.length; i++) {
            const child = note.children[i];
            if (child.tagName === "P" && child.innerText === "") {
              continue;
            } else {
              container.appendChild(child.cloneNode(true));
              break;
            }
          }
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(container);
          }
          return container.innerHTML
        } else {
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(note);
          }
          return note.innerHTML;
        }
      } else {
        // Remove any anchor links if they are present
        const anchorLink = note.querySelector('a.anchorjs-link');
        if (anchorLink) {
          anchorLink.remove();
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        if (note.classList.contains("callout")) {
          return note.outerHTML;
        } else {
          return note.innerHTML;
        }
      }
    }
    for (var i=0; i<xrefs.length; i++) {
      const xref = xrefs[i];
      tippyHover(xref, undefined, function(instance) {
        instance.disable();
        let url = xref.getAttribute('href');
        let hash = undefined; 
        if (url.startsWith('#')) {
          hash = url;
        } else {
          try { hash = new URL(url).hash; } catch {}
        }
        if (hash) {
          const id = hash.replace(/^#\/?/, "");
          const note = window.document.getElementById(id);
          if (note !== null) {
            try {
              const html = processXRef(id, note.cloneNode(true));
              instance.setContent(html);
            } finally {
              instance.enable();
              instance.show();
            }
          } else {
            // See if we can fetch this
            fetch(url.split('#')[0])
            .then(res => res.text())
            .then(html => {
              const parser = new DOMParser();
              const htmlDoc = parser.parseFromString(html, "text/html");
              const note = htmlDoc.getElementById(id);
              if (note !== null) {
                const html = processXRef(id, note);
                instance.setContent(html);
              } 
            }).finally(() => {
              instance.enable();
              instance.show();
            });
          }
        } else {
          // See if we can fetch a full url (with no hash to target)
          // This is a special case and we should probably do some content thinning / targeting
          fetch(url)
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.querySelector('main.content');
            if (note !== null) {
              // This should only happen for chapter cross references
              // (since there is no id in the URL)
              // remove the first header
              if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
                note.children[0].remove();
              }
              const html = processXRef(null, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      }, function(instance) {
      });
    }
        let selectedAnnoteEl;
        const selectorForAnnotation = ( cell, annotation) => {
          let cellAttr = 'data-code-cell="' + cell + '"';
          let lineAttr = 'data-code-annotation="' +  annotation + '"';
          const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
          return selector;
        }
        const selectCodeLines = (annoteEl) => {
          const doc = window.document;
          const targetCell = annoteEl.getAttribute("data-target-cell");
          const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
          const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
          const lines = annoteSpan.getAttribute("data-code-lines").split(",");
          const lineIds = lines.map((line) => {
            return targetCell + "-" + line;
          })
          let top = null;
          let height = null;
          let parent = null;
          if (lineIds.length > 0) {
              //compute the position of the single el (top and bottom and make a div)
              const el = window.document.getElementById(lineIds[0]);
              top = el.offsetTop;
              height = el.offsetHeight;
              parent = el.parentElement.parentElement;
            if (lineIds.length > 1) {
              const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
              const bottom = lastEl.offsetTop + lastEl.offsetHeight;
              height = bottom - top;
            }
            if (top !== null && height !== null && parent !== null) {
              // cook up a div (if necessary) and position it 
              let div = window.document.getElementById("code-annotation-line-highlight");
              if (div === null) {
                div = window.document.createElement("div");
                div.setAttribute("id", "code-annotation-line-highlight");
                div.style.position = 'absolute';
                parent.appendChild(div);
              }
              div.style.top = top - 2 + "px";
              div.style.height = height + 4 + "px";
              div.style.left = 0;
              let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
              if (gutterDiv === null) {
                gutterDiv = window.document.createElement("div");
                gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
                gutterDiv.style.position = 'absolute';
                const codeCell = window.document.getElementById(targetCell);
                const gutter = codeCell.querySelector('.code-annotation-gutter');
                gutter.appendChild(gutterDiv);
              }
              gutterDiv.style.top = top - 2 + "px";
              gutterDiv.style.height = height + 4 + "px";
            }
            selectedAnnoteEl = annoteEl;
          }
        };
        const unselectCodeLines = () => {
          const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
          elementsIds.forEach((elId) => {
            const div = window.document.getElementById(elId);
            if (div) {
              div.remove();
            }
          });
          selectedAnnoteEl = undefined;
        };
          // Handle positioning of the toggle
      window.addEventListener(
        "resize",
        throttle(() => {
          elRect = undefined;
          if (selectedAnnoteEl) {
            selectCodeLines(selectedAnnoteEl);
          }
        }, 10)
      );
      function throttle(fn, ms) {
      let throttle = false;
      let timer;
        return (...args) => {
          if(!throttle) { // first call gets through
              fn.apply(this, args);
              throttle = true;
          } else { // all the others get throttled
              if(timer) clearTimeout(timer); // cancel #2
              timer = setTimeout(() => {
                fn.apply(this, args);
                timer = throttle = false;
              }, ms);
          }
        };
      }
        // Attach click handler to the DT
        const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
        for (const annoteDlNode of annoteDls) {
          annoteDlNode.addEventListener('click', (event) => {
            const clickedEl = event.target;
            if (clickedEl !== selectedAnnoteEl) {
              unselectCodeLines();
              const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
              if (activeEl) {
                activeEl.classList.remove('code-annotation-active');
              }
              selectCodeLines(clickedEl);
              clickedEl.classList.add('code-annotation-active');
            } else {
              // Unselect the line
              unselectCodeLines();
              clickedEl.classList.remove('code-annotation-active');
            }
          });
        }
    const findCites = (el) => {
      const parentEl = el.parentElement;
      if (parentEl) {
        const cites = parentEl.dataset.cites;
        if (cites) {
          return {
            el,
            cites: cites.split(' ')
          };
        } else {
          return findCites(el.parentElement)
        }
      } else {
        return undefined;
      }
    };
    var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
    for (var i=0; i<bibliorefs.length; i++) {
      const ref = bibliorefs[i];
      const citeInfo = findCites(ref);
      if (citeInfo) {
        tippyHover(citeInfo.el, function() {
          var popup = window.document.createElement('div');
          citeInfo.cites.forEach(function(cite) {
            var citeDiv = window.document.createElement('div');
            citeDiv.classList.add('hanging-indent');
            citeDiv.classList.add('csl-entry');
            var biblioDiv = window.document.getElementById('ref-' + cite);
            if (biblioDiv) {
              citeDiv.innerHTML = biblioDiv.innerHTML;
            }
            popup.appendChild(citeDiv);
          });
          return popup.innerHTML;
        });
      }
    }
  });
  </script>
</div> <!-- /content -->




</body></html>