# 16

# Changepoint Detection

현대 세계에서 데이터는 연속적이고 빠른 속도로 흐르며, 과정의 변화는 단순한 이벤트가 아니라 지속적인 상태입니다. 심전도(ECG)나 신제품 출시에 따른 수익 증가와 같은 연속적인 신호 처리를 다룰 때, 기저 데이터 생성 과정의 변화는 불가피합니다. 변화점 탐지(Changepoint detection)는 시간이 지남에 따라 시스템의 동작에서 갑작스럽고 지속적인 변화를 식별하는 데 사용되는 엄격한 통계적 프레임워크입니다. 시계열의 이상치는 이전 기준선으로 빠르게 돌아가는 단기적인 스파이크인 반면, 변화점 탐지는 기저 데이터 생성 과정이 이동하여 새로운 정상 상태로 진입하는 지속적인 변화를 포착합니다.

변화점 탐지는 체계적인 변화를 식별할 수 있게 해주어 시장 동향, 장비 고장, 환자 건강 또는 전략적 비즈니스 결정의 변화에 대응할 수 있도록 합니다. 이 장에서는 후향적 연구 맥락에서 변화점 탐지를 논의합니다. 논의된 방법과 제시된 예제를 통해 관측된 데이터에서 변화점을 탐지하는 주요 접근 방식에 대해 배울 것입니다.

이 장은 다음과 같이 구성되어 있습니다.

- 16.1절: 변화점 탐지란 무엇인가?
- 16.2절: 가법적 계절성 및 추세를 위한 브레이크(BFAST)
- 16.3절: Pruned Exact Linear Time 방법
- 16.4절: 베이지안 변화점 탐지
- 16.5절: 방법 선택 가이드라인

구매 시 무료 PDF 사본 및 독점 추가 자료 포함

도서 구매 시 이 책의 DRM 프리 PDF 사본, Packt+ 라이브러리 7일 평가판(신용카드 불필요) 및 추가 독점 자료가 포함되어 있습니다. 서문의 '도서와 함께 제공되는 무료 혜택' 섹션을 참조하여 즉시 잠금을 해제하고 학습을 극대화하세요.

# 기술적 요구 사항

다음 코드를 사용하여 이 장에서 필요한 패키지를 로드해 보겠습니다.

```R
#install.packages("pacman")
library(pacman)
p_load("conflicted"
       ,"datasets"
       ,"tidyverse"
       ,"feasts"
       ,"patchwork"
       ,"bfast"
       ,"changepoint"
       ,"Rbeast" )

conflicts_prefer(
   strucchangeRcpp::boundary
  ,fabletools::accuracy
  ,fabletools::forecast
  ,fabletools::components
  ,dplyr::filter )
```

코드 파일은 다운로드하여 실습할 수 있도록 GitHub 저장소 <a href="https://github.com/PacktPublishing/Modern-Time-Series-Analysis-with-R.git" style="text-decoration: none;">https://github.com/PacktPublishing/Modern-Time-Series-Analysis-with-R.git</a>에서 제공됩니다.

# 16.1 변화점 탐지란 무엇인가?

시계열은 종종 구조적 단절이나 기저 패턴의 급격한 변화를 포함합니다. 평균, 분산 또는 추세와 같은 기본적인 통계적 속성에서 지속적인 이동이 발생할 때, 이러한 현상은 변화점에 기인합니다. 변화점은 서로 다른 두 가지 동작 세그먼트 사이의 경계를 정확히 찾아냅니다.

구조적 단절의 탐지는 프로세스 모니터링에 중점을 둔 모든 분야에서 관심 있는 주제입니다. 일부 응용 분야는 다음과 같습니다.

- GDP, 실업률 및 국가 부채와 같은 경제 시계열에서 구조적 단절 찾기
- 시장 변동성, 수익률 또는 거래량과 같은 금융 시계열에서 체제 변화 식별
- 뇌파(EEG), 심전도(ECG) 또는 혈압과 같은 생리학적 측정에서 전환 감지
- 통신 네트워크에서 이상 동작이나 부하 변화 발견
- 환경 모니터링에서 기후 패턴, 식생 지수 또는 수문 시스템의 변화 감지

변화점 탐지는 데이터세트에서 이벤트의 영향을 이해하고 해당 변화점을 고려하여 후속 분석 및 예측을 개선할 수 있는 기회를 제공합니다. 예를 들어 변화점을 탐지함으로써 예측 오류를 줄이고 의사 결정 과정을 손상시킬 수 있는 잘못된 통계적 추론을 피할 수 있습니다. 변화점 탐지는 개입 영향 측정(15장에서 다룸)과 다릅니다. 변화점 탐지에서는 변화에 기여하는 요소를 외부적인 것으로 간주하며, 분석은 본질적으로 후향적입니다. 반면, 인과적 영향 측정은 요소가 내부 비즈니스 전략이나 결정에서 비롯된다고 가정하며, 비즈니스는 성공을 주장하거나 전략을 잠재적으로 개선하기 위해 해당 전략의 영향을 이해하고자 합니다.

변화점 탐지 기법은 여러 강력한 방법론적 접근 방식을 제공합니다. 적합한 방법의 사용은 문제의 분석적 필요와 일치해야 합니다.

표 16.1은 이 장의 뒷부분에서 자세히 다루는 세 가지 변화점 탐지 방법에 대한 간략한 요약을 제공합니다.

| 기준               | 가법적 계절성 및 추세를 위한 브레이크(BFAST)                                                                        | Pruned exact linear time (PELT)                                                                             | 베이지안 접근 방식(BEAST)                                                                                   |
| ------------------ | ------------------------------------------------------------------------------------------------------------------- | ----------------------------------------------------------------------------------------------------------- | ----------------------------------------------------------------------------------------------------------- |
| 개요               | 데이터를 유의미한 단일 변화점에서 두 부분으로 분할한 다음 각 하위 세그먼트에서 프로세스를 반복하는 재귀적 접근 방식 | 비최적 점을 폐기하면서 모든 가능한 세그먼트에서 비용 함수(평균 또는 분산)를 최소화하는 정확한 검색 알고리즘 | 시스템에 대한 사전 신념을 통합하여 각각의 새로운 데이터 포인트로 변화점의 가능성을 업데이트하는 확률적 방법 |
| 적용 조건          | 세그먼트가 비교적 길고 변화점 수가 적을 때 잘 작동                                                                  | 과적합을 피하기 위해 사전 정의된 페널티 값(AIC 또는 BIC)이 필요함                                           | 적절한 사전 분포 선택이 필요함                                                                              |
| 적합성             | 계산 효율성으로 인해 매우 큰 데이터세트에 적합                                                                      | 다중 변화점의 정확한 수와 위치를 식별하는 데 이상적                                                         | 불확실성을 정량화하고 즉각적인 대응이 중요한 온라인(실시간) 탐지에 매우 적합                                |
| 일반적인 사용 사례 | 환경 모니터링, 토지 피복 변화 탐지, 위성 이미지 시계열의 계절적 변화                                                | 금융 및 공학, 시장 변동성의 체제 전환 식별, 센서 데이터의 구조적 단절                                       | 의료 및 사이버 보안, 심박수(ECG)의 실시간 모니터링, 네트워크 트래픽의 갑작스러운 급증 감지                  |

표 16.1: 변화점 탐지 방법 간의 비교

이러한 모든 방법은 계절성 및 비계절성 데이터에 모두 적용할 수 있습니다. 이 장에서는 비계절성 적용의 예로 `Nile` 데이터를 사용하고 계절성 적용을 위해 `AirPassengers` 데이터를 사용했습니다. 세 가지 방법 모두에 동일한 데이터를 사용하면 성능을 비교할 수도 있습니다.

다음으로 변화점 탐지를 위한 BFAST 방법을 논의하겠습니다.

# 16.2 가법적 계절성 및 추세를 위한 브레이크

Verbesselt 등이 (2010) 개발한 BFAST(Breaks for Additive Season and Trend) 프레임워크는 모든 반복에서 변화점을 확인하기 위해 데이터를 두 개의 세그먼트로 분할하므로 이진 분할과 유사합니다. 재귀 과정은 중지 기준을 충족할 때 종료됩니다. BFAST는 변화점을 탐지하는 직관적이고 계산적으로 효율적인 접근 방식 중 하나입니다.

BFAST에서 사용되는 핵심 도구는 이동 합계(MOSUM) 검정으로, 사전에 위치를 가정하지 않고 알 수 없는 수의 변화점을 탐지할 수 있게 해줍니다.

가법적 형태의 시계열 <span class="image placeholder" data-original-image-src="../Images/B21040_16_001.png" data-original-image-title="">B21040_16_001.png</span>은 다음과 같이 쓸 수 있음을 상기하십시오:

<span class="image placeholder" data-original-image-src="../Images/B21040_16_002.png" data-original-image-title="">B21040_16_002.png</span>

여기서,

- <span class="image placeholder" data-original-image-src="../Images/B21040_16_003.png" data-original-image-title="">B21040_16_003.png</span>는 추세 성분입니다.
- <span class="image placeholder" data-original-image-src="../Images/B21040_16_004.png" data-original-image-title="">B21040_16_004.png</span>는 계절 성분입니다.
- <span class="image placeholder" data-original-image-src="../Images/B21040_16_005.png" data-original-image-title="">B21040_16_005.png</span>는 나머지(또는 잔차) 성분입니다.

BFAST 구현에서 추세는 일반적으로 다음 방정식과 같이 조각별 선형 회귀로 모델링됩니다.

<span class="image placeholder" data-original-image-src="../Images/B21040_16_006.png" data-original-image-title="">B21040_16_006.png</span>

여기서,

- <span class="image placeholder" data-original-image-src="../Images/B21040_16_007.png" data-original-image-title="">B21040_16_007.png</span>은 알려지지 않은 변화점입니다.
- <span class="image placeholder" data-original-image-src="../Images/B21040_16_008.png" data-original-image-title="">B21040_16_008.png</span>은 체제별 회귀 계수입니다.

<span class="image placeholder" data-original-image-src="../Images/B21040_16_009.png" data-original-image-title="">B21040_16_009.png</span> 또는 <span class="image placeholder" data-original-image-src="../Images/B21040_16_010.png" data-original-image-title="">B21040_16_010.png</span>가 특정 시점에 변경되면 추세 단절이 발생합니다.

계절 성분은 매끄러운 주기적 곡선으로 모델링되며 종종 조화 회귀를 사용합니다.

<span class="image placeholder" data-original-image-src="../Images/B21040_16_011.png" data-original-image-title="">B21040_16_011.png</span>

여기서:

- <span class="image placeholder" data-original-image-src="../Images/B21040_16_012.png" data-original-image-title="">B21040_16_012.png</span>는 알려진 계절 주파수(월별 데이터의 경우 <span class="image placeholder" data-original-image-src="../Images/B21040_16_013.png" data-original-image-title="">B21040_16_013.png</span>)입니다.
- <span class="image placeholder" data-original-image-src="../Images/B21040_16_014.png" data-original-image-title="">B21040_16_014.png</span>는 고조파의 수입니다.

계절 성분은 알려진 주파수(연간 주기)를 가진 반복되는 파동의 조합으로 쓸 수 있습니다. 핵심 아이디어는 이러한 표현이 단기적인 노이즈에 반응하지 않고 규칙적인 패턴을 포착한다는 것입니다. 계절성의 구조적 단절은 계수 <span class="image placeholder" data-original-image-src="../Images/B21040_16_015.png" data-original-image-title="">B21040_16_015.png</span>의 변화에 해당합니다. 단순성을 위해 더미 변수를 사용하여 계절성을 모델링할 수도 있다는 점을 유의해야 합니다. 시계열에서 추세와 계절 성분을 추정하고 나면, 다음과 같이 관측된 데이터 <span class="image placeholder" data-original-image-src="../Images/B21040_16_016.png" data-original-image-title="">B21040_16_016.png</span>에서 빼서 나머지를 추출합니다.

<span class="image placeholder" data-original-image-src="../Images/B21040_16_017.png" data-original-image-title="">B21040_16_017.png</span>

모델이 안정적인 경우 이러한 나머지는 무작위 노이즈처럼 동작하고 <span class="image placeholder" data-original-image-src="../Images/B21040_16_018.png" data-original-image-title="">B21040_16_018.png</span> 주위에서 변동합니다. 구조적 변화가 발생하면 잔차는 체계적인 편향을 보이고 일정 기간 동안 대부분 양수이거나 대부분 음수일 경향이 있습니다. MOSUM 검정은 짧은 시간 창에 걸쳐 나머지를 집계하여 이러한 불안정성을 탐지합니다.

표현식 <span class="image placeholder" data-original-image-src="../Images/B21040_16_019.png" data-original-image-title="">B21040_16_019.png</span>는 회귀 모델의 잔차와 동일합니다. 이런 의미에서 식 (16.1)의 우변은 관측값과 해당 적합값의 차이로 해석될 수 있습니다. 적합값은 모델의 추세 및 계절 성분에 있는 매개변수의 최소자승법(OLS) 추정치를 사용하여 얻습니다. 결과적으로 BFAST에 사용된 MOSUM 통계량은 OLS 잔차로 계산되는 것으로 볼 수 있습니다. 이 절차는 문헌과 우리가 채택한 R 패키지에서 일반적으로 OLS 기반 MOSUM(OLS-MOSUM)으로 지칭됩니다.

이전 장에서 우리는 관측된 계열에서 나머지를 분리(또는 추정)하기 위해 STL 분해를 사용했습니다. BFAST 시나리오에서 그 방법을 사용할 수 있을까요? STL 분해가 하나의 옵션일 수 있습니다. 그러나 추세와 계절성을 명시적 모델로 표현함으로써 매개변수가 안정적으로 유지되는지 여부를 검정할 수 있습니다. 정상 추세와 계절성의 초기 정의는 나중에 프로세스에서 변화로 탐지되는 것을 강력하게 결정합니다. 이러한 모델 가정 없이는 이탈에 대한 검정을 수행할 수 없습니다.

MOSUM 검정은 미리 결정된 고정된 창 길이 <span class="image placeholder" data-original-image-src="../Images/B21040_16_020.png" data-original-image-title="">B21040_16_020.png</span>로 시작합니다. 그런 다음 각 지점 <span class="image placeholder" data-original-image-src="../Images/B21040_16_021.png" data-original-image-title="">B21040_16_021.png</span>에서 MOSUM은 다음과 같이 계산됩니다.

<span class="image placeholder" data-original-image-src="../Images/B21040_16_022.png" data-original-image-title="">B21040_16_022.png</span>

이 양은 창 크기에 걸쳐 값을 비교할 수 있도록 스케일링된 잔차의 국소 평균에 불과합니다. 변화가 없을 때 양수 및 음수 잔차가 상쇄되어 <span class="image placeholder" data-original-image-src="../Images/B21040_16_023.png" data-original-image-title="">B21040_16_023.png</span>가 <span class="image placeholder" data-original-image-src="../Images/B21040_16_024.png" data-original-image-title="">B21040_16_024.png</span>에 가깝게 유지됩니다.

변화가 탐지될 때 창의 잔차는 동일한 부호를 갖는 경향이 있어 <span class="image placeholder" data-original-image-src="../Images/B21040_16_025.png" data-original-image-title="">B21040_16_025.png</span>의 크기가 커집니다. 이렇게 하면 MOSUM이 미묘한 편차에서 가시적인 신호로 변환됩니다. 관측된 MOSUM 값이 비정상적으로 큰지 결정하기 위해 정상적인 무작위 변동 하에서 예상되는 것을 나타내는 참조 경계와 비교합니다. MOSUM 검정 통계량은 다음과 같이 정의됩니다.

<span class="image placeholder" data-original-image-src="../Images/B21040_16_026.png" data-original-image-title="">B21040_16_026.png</span>

<span class="image placeholder" data-original-image-src="../Images/B21040_16_027.png" data-original-image-title="">B21040_16_027.png</span>가 경계 아래에 머무르면 모델은 안정적인 것으로 간주됩니다. <span class="image placeholder" data-original-image-src="../Images/B21040_16_028.png" data-original-image-title="">B21040_16_028.png</span>가 경계를 초과하면 BFAST는 구조적 변화가 발생했다고 결론을 내립니다.

경계는 기저 프로세스가 변경되지 않은 경우 MOSUM이 취할 것으로 예상되는 값의 범위를 나타냅니다. 경계가 교차하는 시간은 단절의 위치에 대한 추정치를 제공합니다. 다음 두 절에서는 BFAST를 사용하여 각각 비계절성 및 계절성 계열의 변화점을 식별하는 방법을 볼 수 있습니다.

비계절성 데이터에 BFAST를 적용하는 방법을 살펴보겠습니다.

## 16.2.1 비계절성 데이터에 대한 BFAST 구현

이 예제에서는 datasets 패키지의 Nile 데이터를 사용합니다. 이 데이터는 `ts` 형식이며 1871년부터 1970년 사이의 과거 연간 나일강 유량 기록을 포함합니다. `bfast` 패키지의 `bfast()` 함수를 사용하여 BFAST 방법을 적용할 수 있습니다. 이 함수는 입력 데이터를 `ts` 형식으로 기대합니다.

연간 계열에서 비계절성 가법 분해를 강제하기 위해 `season = "none"`으로 설정하여 계절성 옵션을 비활성화합니다. 최소 세그먼트 길이로 전체 관측치의 <span class="image placeholder" data-original-image-src="../Images/B21040_16_029.png" data-original-image-title="">B21040_16_029.png</span>을 사용합니다(`bfast()` 함수에 인자 h 전달). 최소 세그먼트 길이를 선택하기 위한 엄격한 지침은 없지만 너무 작아서는 안 됩니다. 애플리케이션에서 적합한 숫자를 설정하려면 관측된 시계열의 도메인 지식과 맥락을 적용하십시오. 추세 성분(그리고 해당하는 경우 계절 성분)에서 변화점 추정에 허용되는 최대 반복 횟수를 제어하는 `max.iter = 10`을 설정합니다. 다음 코드 스니펫은 적용 방법과 모델에서 일부 정보를 추출하는 방법을 보여줍니다.

```R
bfast_nile <- bfast(Nile,
                    h = 0.15,
                    season = "none",
                    max.iter = 10)
## [1] "No seasonal model will be fitted!"
nile_bfast_magnitude <- bfast_nile$Magnitude

bfast_nile
```

적합된 모델 정보는 다음 출력에 제공됩니다.

```
TREND BREAKPOINTS
    Confidence intervals for breakpoints
    of optimal 2-segment partition:

Call:
confint.breakpointsfull(object = bp.Vt, het.err = FALSE)

Breakpoints at observation number:
  2.5 % breakpoints 97.5 %
1    26          28     31

Corresponding to breakdates:
  2.5 % breakpoints 97.5 %
1  1896        1898   1901

  SEASONAL BREAKPOINTS:  None
```

BFAST 방법에 의해 탐지된 변화점에서의 변화 크기는 다음과 같습니다.

```
nile_bfast_magnitude

# [1] -287.9431
```

아스완 댐이 건설된 연도인 <span class="image placeholder" data-original-image-src="../Images/B21040_16_030.png" data-original-image-title="">B21040_16_030.png</span>년인 28번째 관측치에서 변화점이 감지되었습니다. 변화의 크기는 <span class="image placeholder" data-original-image-src="../Images/B21040_16_031.png" data-original-image-title="">B21040_16_031.png</span>로, 평균 나일강 수량이 약 <span class="image placeholder" data-original-image-src="../Images/B21040_16_032.png" data-original-image-title="">B21040_16_032.png</span>(단위: <span class="image placeholder" data-original-image-src="../Images/B21040_16_033.png" data-original-image-title="">B21040_16_033.png</span> 리터) 영구적으로 감소했음을 나타냅니다.

다음 코드를 사용하여 탐지된 변화점과 함께 원본 데이터를 그려보겠습니다(`invisible()` 함수는 플롯팅 시 화면 정보를 억제합니다):

```R
invisible(plot(bfast_nile,
               type = c("trend"), main = ""))
```

그림 16.1은 수직선으로 탐지된 변화점의 위치를 보여줍니다.

<figure class="mediaobject">
 <span class="image placeholder" data-original-image-src="../Images/B21040_16_1.png" data-original-image-title="">Image 1</span> 
</figure>

그림 16.1: BFAST가 탐지한 연간 나일강 수량의 변화점

BFAST는 <span class="image placeholder" data-original-image-src="../Images/B21040_16_034.png" data-original-image-title="">B21040_16_034.png</span>에 변화점의 위치를 식별했으며, 그 주변에 <span class="image placeholder" data-original-image-src="../Images/B21040_16_035.png" data-original-image-title="">B21040_16_035.png</span> 신뢰 구간( <span class="image placeholder" data-original-image-src="../Images/B21040_16_036.png" data-original-image-title="">B21040_16_036.png</span> )이 있습니다. 이 방법은 이 비계절성 계열의 변화점에서 추세 단절을 식별했습니다.

다음 절에서는 BFAST 방법을 계절성 계열에 적용하여 변화점이 존재하는 경우 탐지합니다.

## 16.2.2 계절성 계열에 대한 BFAST 구현

<span class="image placeholder" data-original-image-src="../Images/B21040_16_037.png" data-original-image-title="">B21040_16_037.png</span>년부터 <span class="image placeholder" data-original-image-src="../Images/B21040_16_038.png" data-original-image-title="">B21040_16_038.png</span>년까지 국제선 탑승객의 월별 총합을 포함하는 잘 알려진 AirPassengers 계열을 사용하여 계절성 계열에서 변화점을 탐지하기 위해 BFAST를 적용하는 방법을 보여줍니다.

BFAST는 가법 모델을 가정하여 시계열을 분해하므로 이 데이터에 대한 모델의 적합성을 보장하기 위해 로그 변환이 필요합니다. 계절성 계열의 경우 전체 계절 주기를 최소 세그먼트 크기로 사용하는 것이 좋습니다. 이는 전체 관측치에 대한 데이터세트의 빈도 비율로 계산됩니다. 이 예제에서는 전체 관측치의 약 <span class="image placeholder" data-original-image-src="../Images/B21040_16_039.png" data-original-image-title="">B21040_16_039.png</span>( <span class="image placeholder" data-original-image-src="../Images/B21040_16_040.png" data-original-image-title="">B21040_16_040.png</span> )를 다룰 것입니다.

`season="harmonic"` 인자는 계절 성분에 대한 조화 회귀를 강제합니다. 최대 반복 횟수는 <span class="image placeholder" data-original-image-src="../Images/B21040_16_041.png" data-original-image-title="">B21040_16_041.png</span>으로 설정됩니다. 다음 코드는 `AirPassengers` 데이터의 로그에 BFAST를 구현합니다.

```R
bfast_ap <- bfast(log(AirPassengers),
                  h = round(frequency(AirPassengers)/
                            length(AirPassengers),3),
                  season = "harmonic",
                  max.iter = 10)

bfast_ap
```

이 방법은 다음 출력을 생성합니다.

```
  TREND BREAKPOINTS
     Confidence intervals for breakpoints
     of optimal 4-segment partition:

Call:
confint.breakpointsfull(object = bp.Vt, het.err = FALSE)

Breakpoints at observation number:
  2.5 % breakpoints 97.5 %
1    22          23     32
2    52          54     59
3   107         109    114

Corresponding to breakdates:
  2.5 %    breakpoints 97.5 %
1 1950(10) 1950(11)    1951(8)
2 1953(4)  1953(6)     1953(11)
3 1957(11) 1958(1)     1958(6)

  SEASONAL BREAKPOINTS:  None
```

추세에서 세 개의 변화점이 1950년 11월, 1953년 7월 및 1958년 1월에 감지되었습니다. 계절적 단절은 없었으며 이는 관측된 전체 기간 동안 계절 분포가 동일하게 유지되었음을 나타냅니다.

그림 16.2에 제시된 감지된 변화점의 위치를 시각화해 보겠습니다.

<figure class="mediaobject">
 <span class="image placeholder" data-original-image-src="../Images/B21040_16_2.png" data-original-image-title="">Image 2</span> 
</figure>

그림 16.2: BFAST에 의해 계절성 AirPassengers 데이터에서 탐지된 변화점

그림 16.2는 계절 성분(위에서 두 번째 패널)과 추세(위에서 세 번째 패널)의 변화점에 대한 시각적 정보를 제공합니다. 모델 출력과 플롯을 결합하면 BFAST 방법은 추세에서 통계적으로 유의미한 세 개의 변화점을 탐지했으며 계절 성분에서는 아무것도 탐지하지 못했습니다. 추가 연구를 통해 해당 시점을 중심으로 다음과 같은 중추적인 산업 발전이 확인되었습니다.

- 제트 여객기의 도입: 1952년 세계 최초의 상업용 제트 여객기인 De Havilland Comet의 데뷔는 더 빠른 속도와 부드러운 비행으로 항공에 혁명을 일으켰습니다. 초기 문제에도 불구하고 그 유산은 보잉 707(1958) 및 더글라스 DC-8(1959)과 같은 발전된 후속 모델을 가능하게 했습니다. 이 제트기들은 대서양 횡단 비행 시간을 14시간 이상에서 8시간 미만으로 단축하여 전례 없는 효율성과 승객의 편안함을 결합했습니다.
- 이코노미 클래스 확장: Pan Am과 같은 항공사는 저렴한 요금을 개척하여 더 많은 사람들이 항공 여행에 접근할 수 있도록 했습니다. 동시에 1958년 미국 연방 항공법은 안전 규정을 표준화하여 상업 항공에 대한 대중의 신뢰를 강화했습니다.
- 가압 캐빈 채택: 1950년대에 널리 구현된 이 기술을 통해 항공기가 난기류 기상 시스템 위로 순항할 수 있게 되어 승차감과 승객 경험이 크게 향상되었습니다.

BFAST 알고리즘은 계절성 데이터에 비계절성 모델을 강제함으로써 계절성 모델의 과적합을 피하는 옵션을 제공한다는 점에 유의할 가치가 있습니다. 이는 `season = "none"`으로 설정하여 달성할 수 있습니다. 계절성 계열에 대해서도 추세의 변화점을 탐지하기 위해 BFAST를 고려하려면 `bfast()` 함수에서 `season = "none"`을 설정하여 비계절성 모델을 강제할 수 있습니다.

BFAST 방법의 장단점을 살펴보겠습니다.

다음은 장점입니다.

- 계산적으로 효율적이어서 긴 시계열에 적합합니다.
- 직관적이고 비교적 구현하기 쉽습니다.
- 다중 변화점을 탐지할 수 있는 능력이 있습니다.
- 통합된 프레임워크에서 추세 및 계절성 변화를 모두 처리합니다.
- 잘 확립된 이론적 속성이 있습니다.

다음은 단점(제한 사항)입니다.

- 이 방법은 전역 최적해를 찾지 못할 수 있습니다.
- 변화점이 서로 가까울 때 성능이 저하됩니다.
- 이 방법은 이분산(분산이 변하는) 데이터에서 어려움을 겪을 수 있습니다.
- 노이즈가 많은 데이터로 변화점 수를 과대평가하는 경향이 있습니다.
- 최소 세그먼트 크기 매개변수의 사양이 필요합니다.

다음 절에서는 최적화를 통해 최적의 솔루션을 찾는 것을 보장하는 방법을 논의합니다.

# 16.3 Pruned Exact Linear Time 방법

Pruned Exact Linear Time (PELT) 알고리즘은 Killick 등이 (2012) 소개했습니다. 이 방법은 전역 검색을 통해 시계열에 변화점이 존재하는 경우 이를 찾는 것을 보장합니다. 이 방법은 비용 함수를 최소화하여 분할을 찾는 최적화 문제로 변화점 탐지를 처리합니다. 최적화 중 과적합을 피하기 위해 비용 함수는 변화점 수에 대해 모델에 페널티를 부과합니다.

PELT에 의해 최소화되는 비용 함수의 일반적인 형태는 다음과 같습니다.

<span class="image placeholder" data-original-image-src="../Images/B21040_16_042.png" data-original-image-title="">B21040_16_042.png</span>

여기서:

- <span class="image placeholder" data-original-image-src="../Images/B21040_16_043.png" data-original-image-title="">B21040_16_043.png</span>는 변화점의 수입니다.
- <span class="image placeholder" data-original-image-src="../Images/B21040_16_044.png" data-original-image-title="">B21040_16_044.png</span>는 변화점의 위치입니다.
- <span class="image placeholder" data-original-image-src="../Images/B21040_16_045.png" data-original-image-title="">B21040_16_045.png</span>는 세그먼트 <span class="image placeholder" data-original-image-src="../Images/B21040_16_046.png" data-original-image-title="">B21040_16_046.png</span>에 대한 비용입니다.
- <span class="image placeholder" data-original-image-src="../Images/B21040_16_047.png" data-original-image-title="">B21040_16_047.png</span>는 과적합을 방지하기 위한 페널티 매개변수입니다.

일반적인 구조를 채택함으로써 문제의 맥락에 따라 다양한 비용 함수를 사용할 수 있습니다. 실제로 사용되는 일반적인 비용 함수는 다음과 같습니다.

- 모수 분포를 위한 BIC, AIC 등과 같은 음의 로그 우도 기반 기준
- 평균 이동에 대한 잔차 제곱합
- 분산 변화에 대한 우도 기반 비용

PELT 프로세스는 초기화 단계로 시작하여 두 번째 단계에서 반복적인 재귀 방식으로 그럴듯한 변화점을 식별한 다음 정리(pruning) 단계에서 비최적 변화점을 버리고 마지막으로 중지 기준을 충족할 때 후보 변화점을 업데이트하거나 종료합니다. PELT 알고리즘의 핵심 구성 요소는 정리 단계입니다. 이 단계에서 비최적 변화점이 버려지며 이는 결과적으로 계산 복잡성을 줄여줍니다.

PELT 알고리즘의 세부 단계는 다음과 같습니다.

1. 초기화 단계: 초기 비용 함수 <span class="image placeholder" data-original-image-src="../Images/B21040_16_048.png" data-original-image-title="">B21040_16_048.png</span>와 시간 <span class="image placeholder" data-original-image-src="../Images/B21040_16_049.png" data-original-image-title="">B21040_16_049.png</span>까지의 후보 변화점 집합 <span class="image placeholder" data-original-image-src="../Images/B21040_16_050.png" data-original-image-title="">B21040_16_050.png</span>이 설정됩니다.

   <span class="image placeholder" data-original-image-src="../Images/B21040_16_051.png" data-original-image-title="">B21040_16_051.png</span>의 선택은 첫 번째 세그먼트 <span class="image placeholder" data-original-image-src="../Images/B21040_16_052.png" data-original-image-title="">B21040_16_052.png</span>가 평가될 때 첫 번째 세그먼트 비용 <span class="image placeholder" data-original-image-src="../Images/B21040_16_053.png" data-original-image-title="">B21040_16_053.png</span>이 올바른지 확인하기 위해 모델이 첫 번째 페널티를 상쇄하도록 보장합니다. <span class="image placeholder" data-original-image-src="../Images/B21040_16_054.png" data-original-image-title="">B21040_16_054.png</span>의 선택은 시간 <span class="image placeholder" data-original-image-src="../Images/B21040_16_055.png" data-original-image-title="">B21040_16_055.png</span> 이전에 변화점이 없었음을 보장합니다.

2. 반복적 재귀 단계: 각 시간 단계 <span class="image placeholder" data-original-image-src="../Images/B21040_16_056.png" data-original-image-title="">B21040_16_056.png</span>에 대해 다음 계산이 이루어집니다.
   - 최적 비용은 <span class="image placeholder" data-original-image-src="../Images/B21040_16_057.png" data-original-image-title="">B21040_16_057.png</span>를 통해 계산됩니다.
   - 비용 함수를 최적화하는 <span class="image placeholder" data-original-image-src="../Images/B21040_16_058.png" data-original-image-title="">B21040_16_058.png</span> 값은 최근의 변화점으로 간주되며 집합 <span class="image placeholder" data-original-image-src="../Images/B21040_16_059.png" data-original-image-title="">B21040_16_059.png</span>에 저장됩니다.

3. 정리(Pruning) 단계: 현재 집합 <span class="image placeholder" data-original-image-src="../Images/B21040_16_061.png" data-original-image-title="">B21040_16_061.png</span>의 모든 후보 세그먼트 <span class="image placeholder" data-original-image-src="../Images/B21040_16_060.png" data-original-image-title="">B21040_16_060.png</span>에서 다음과 같이 집합을 버리고 업데이트하여 최적의 세그먼트를 찾습니다.
   - 최적 <span class="image placeholder" data-original-image-src="../Images/B21040_16_062.png" data-original-image-title="">B21040_16_062.png</span>
   - <span class="image placeholder" data-original-image-src="../Images/B21040_16_063.png" data-original-image-title="">B21040_16_063.png</span> 업데이트

4. 종료: 모든 데이터 포인트 <span class="image placeholder" data-original-image-src="../Images/B21040_16_064.png" data-original-image-title="">B21040_16_064.png</span>가 처리되면 최적 파티션에서 변화점 위치를 검색하기 위해 <span class="image placeholder" data-original-image-src="../Images/B21040_16_065.png" data-original-image-title="">B21040_16_065.png</span>를 역추적합니다.

이제 Nile 데이터에 PELT를 적용하여 이 방법으로 몇 개의 변화점이 탐지되었는지 확인해 보겠습니다.

## 16.3.1 비계절성 데이터에 대한 PELT 구현

`changepoint` 패키지는 `cpt.meanvar()` 함수를 통해 PELT 구현을 제공합니다. 베이지안 정보 기준(BIC)을 비용 함수로 사용하고 전체 관측치의 <span class="image placeholder" data-original-image-src="../Images/B21040_16_066.png" data-original-image-title="">B21040_16_066.png</span>을 최소 세그먼트 길이로 사용합니다. `cpt.meanvar()` 함수는 평균과 분산 모두에서 변화점을 탐지할 수 있습니다.

다음 코드를 사용하여 비계절성 `Nile` 데이터에 PELT를 구현할 수 있습니다.

```R
pelt_nile <- cpt.meanvar(Nile,
                         method = "PELT",
                         penalty = "BIC",
                         minseglen = length(Nile)*0.15)
```

적합된 모델의 요약은 감지된 변화점에 대한 정보를 보여줍니다. 다음 출력은 PELT가 감지한 변화점을 보여줍니다.

```
> summary(pelt_nile)

Created Using changepoint version 2.2.4
Changepoint type      : Change in mean and variance
Method of analysis    : PELT
Test Statistic  : Normal
Type of penalty       : BIC with value, 13.81551
Minimum Segment Length : 15
Maximum no. of cpts   : Inf
Changepoint Locations : 28
```

PELT에 따르면 <span class="image placeholder" data-original-image-src="../Images/B21040_16_067.png" data-original-image-title="">B21040_16_067.png</span>번째 관측치에 하나의 변화점이 있으며 이는 <span class="image placeholder" data-original-image-src="../Images/B21040_16_068.png" data-original-image-title="">B21040_16_068.png</span>년입니다. 결과는 이전에 BFAST 방법에 의해 감지된 것과 동일합니다. 다음과 같이 PELT 모델 객체에서 감지된 변화점 전후의 평균 및 분산 변화를 추출할 수 있습니다.

```R
attributes(pelt_nile)$param.est

# $mean
# [1] 1097.7500  849.9722

# $variance
# [1] 17573.12 15352.92
```

PELT 방법은 탐지된 변화점 이후의 나일강 유량에서 평균( <span class="image placeholder" data-original-image-src="../Images/B21040_16_070.png" data-original-image-title="">B21040_16_070.png</span>에서 <span class="image placeholder" data-original-image-src="../Images/B21040_16_069.png" data-original-image-title="">B21040_16_069.png</span>로 감소)과 분산( <span class="image placeholder" data-original-image-src="../Images/B21040_16_072.png" data-original-image-title="">B21040_16_072.png</span>에서 <span class="image placeholder" data-original-image-src="../Images/B21040_16_071.png" data-original-image-title="">B21040_16_071.png</span>로 감소)의 감소를 추정했습니다. 평균 감소는 BFAST가 탐지한 것( <span class="image placeholder" data-original-image-src="../Images/B21040_16_074.png" data-original-image-title="">B21040_16_074.png</span> )에 비해 PELT( <span class="image placeholder" data-original-image-src="../Images/B21040_16_073.png" data-original-image-title="">B21040_16_073.png</span> )에서 더 낮습니다.

그림 16.3에 제시된 플롯에서 <span class="image placeholder" data-original-image-src="../Images/B21040_16_075.png" data-original-image-title="">B21040_16_075.png</span>의 감지된 변화점 전후의 수준 이동을 조사할 수 있습니다.

<figure class="mediaobject">
 <span class="image placeholder" data-original-image-src="../Images/B21040_16_3.png" data-original-image-title="">Image 3</span> 
</figure>

그림 16.3: 연간 나일강 유량 데이터에서 PELT 방법으로 탐지된 변화점

PELT의 플롯을 그림 16.1에서 BFAST에 의해 생성된 플롯과 비교하면 변화점 전후에 BFAST에서 탐지된 미묘한 상승 추세가 PELT 플롯에는 나타나지 않음을 알 수 있습니다.

다음으로 PELT를 동일한 계절성 계열에 적용하고 BFAST의 성능과 비교할 수 있습니다.

## 16.3.2 계절성 계열에 대한 PELT 구현

PELT는 변화점 사이의 데이터가 정상 분포에서 비롯된다는 기본적인 가정 하에 작동합니다. 따라서 변화점을 식별하기 위해 PELT를 적용하기 전에 관측된 계열이 정상이어야 합니다. `AirPassengers` 데이터는 추세와 계절성의 강력한 존재로 인해 비정상적입니다. 먼저 `AirPassengers` 계열에 로그를 취하고 STL 분해를 수행한 다음 나머지 성분을 추출합니다. 그런 다음 PELT를 적용하기 전에 KPSS 검정을 사용하여 나머지 성분이 정상인지 확인합니다. 다음 코드는 해당 작업을 수행하는 방법을 보여줍니다.

```R
ap_ts <- AirPassengers |>
  as_tsibble() |>
  mutate(log_passengers = log(value))

ap_decomp <- ap_ts |>
  model(stl_decomp = STL(
    log_passengers ~ trend(window = 13) +
      season(window = "periodic"))) |>
  components()

ap_remainder_kpss <- ap_decomp |>
  features(remainder, feasts::unitroot_kpss)

ap_remainder_kpss
```

KPSS 검정 결과는 다음 출력에 표시됩니다.

```
# A tibble: 1 × 3
  .model     kpss_stat kpss_pvalue
  <chr>          <dbl>       <dbl>
1 stl_decomp    0.0264         0.1
```

KPSS 검정은 큰 p-값( <span class="image placeholder" data-original-image-src="../Images/B21040_16_076.png" data-original-image-title="">B21040_16_076.png</span> )을 보고하여 나머지 계열이 정상임을 확인하므로 여기에 PELT를 적용할 수 있습니다. 나머지 계열의 ACF 및 PACF와 같은 시각적 보조 도구를 사용하여 정상성 조건을 조사할 수도 있습니다.

나머지 계열에 대한 PELT 구현에서 전체 계절 기간 내에서 검색을 허용하기 위해 최소 세그먼트 길이인 <span class="image placeholder" data-original-image-src="../Images/B21040_16_077.png" data-original-image-title="">B21040_16_077.png</span> 관측치(`minseglen=12`)를 적용하고 다음 코드에 제시된 대로 최적화 프로세스에서 BIC 최소화를 사용합니다.

```R
pelt_ap_remainder <- cpt.meanvar(
  ap_decomp$remainder,
  method = "PELT",
  penalty = "BIC",
  minseglen = 12)

summary(pelt_ap_remainder)
```

다음 출력은 PELT가 시계열을 세 개의 세그먼트로 분리하는 두 개의 최적 변화점을 감지했음을 보여줍니다.

```
Created Using changepoint version 2.2.4
Changepoint type      : Change in mean and variance
Method of analysis    : PELT
Test Statistic  : Normal
Type of penalty       : BIC with value, 14.90944
Minimum Segment Length : 12
Maximum no. of cpts   : Inf
Changepoint Locations : 62 109
```

그림 16.4는 나머지 계열에서 PELT가 탐지한 변화점의 위치를 나타냅니다.

<figure class="mediaobject">
 <span class="image placeholder" data-original-image-src="../Images/B21040_16_4.png" data-original-image-title="">Image 4</span> 
</figure>

그림 16.4: AirPassengers 계열에서 PELT에 의해 탐지된 변화점

모델 객체에서 각 세그먼트의 평균 및 분산과 변화점을 추출할 수 있습니다.

```R
pelt_ap_cp <- pelt_ap_remainder@cpts
pelt_ap_par <-pelt_ap_remainder@param.est
```

결과는 다음 출력에 제공되며 <span class="image placeholder" data-original-image-src="../Images/B21040_16_078.png" data-original-image-title="">B21040_16_078.png</span>은 마지막 기간입니다.

```
> pelt_ap_cp
[1]  62 109 144


> pelt_ap_par
$mean
[1] -0.001516690  0.002190884 -0.000916221

$variance
[1] 0.0012457391 0.0002361172 0.0009013271
```

BFAST와 달리 PELT는 모델 출력에 실제 연도-월 참조를 제공하지 않습니다. 그러나 다음과 같이 데이터를 필터링하여 쉽게 추출할 수 있습니다.

```R
pelt_ap_ref <- ap_ts |>
  left_join( ap_decomp |> select(index, remainder),
             by = "index") |>
  slice(pelt_ap_cp[1:2])

pelt_ap_ref
```

이렇게 하면 다음 출력과 같이 이러한 변경이 발생한 실제 시점이 제공됩니다.

```
# A tsibble: 2 x 4 [1M]
     index value log_passengers remainder
     <mth> <dbl>          <dbl>     <dbl>
1 1954 Feb   188           5.24   -0.0640
2 1958 Jan   340           5.83    0.0191
```

이러한 시간 참조는 BFAST 방법으로 탐지된 세 개의 변화점 중 두 개에 가깝습니다. 시각적 조사를 위해 그림 16.5에 제시된 원본 AirPassengers 계열에 변화점 위치를 가리키는 수직 파선과 함께 이 두 시점을 플롯해 보겠습니다.

<figure class="mediaobject">
 <span class="image placeholder" data-original-image-src="../Images/B21040_16_5.png" data-original-image-title="">Image 5</span> 
</figure>

그림 16.5: 나머지 계열에서 PELT 방법으로 변화점을 탐지한 AirPassengers 데이터

평균과 분산 모두에서 변화점을 찾는 대신 다음과 같이 PELT에서 결과 민감도를 평가하기 위해 다양한 옵션을 시도해 볼 수 있습니다.

- `cpt.mean()` 함수를 사용한 평균 전용 변경 테스트
- `cpt.var()` 함수를 사용한 분산 전용 변경 조사
- `minseglen` 인자 변경의 영향 평가

평균과 분산 모두에서 변화점을 찾는 대신 다음과 같이 PELT에서 결과 민감도를 평가하기 위해 다양한 옵션을 시도해 볼 수 있습니다.

- `cpt.mean()` 함수를 사용한 평균 전용 변경 테스트
- `cpt.var()` 함수를 사용한 분산 전용 변경 조사
- `minseglen` 인자 변경의 영향 평가

PELT 방법의 장점과 한계를 요약해 보겠습니다.

다음은 장점입니다.

- 지정된 비용 함수 하에서 최적의 분할을 찾는 것이 보장됩니다.
- 널리 사용되는 많은 비용 함수에 대해 선형적인 계산 복잡도를 갖습니다.
- 평균과 분산의 변화를 감지할 수 있는 유연한 프레임워크를 가지고 있습니다.
- 잘 정의된 통계적 특성을 갖춘 강력한 이론적 기반을 가지고 있습니다.
- 최적의 변화점 수를 자동으로 결정합니다.

다음은 한계점입니다.

- 패널티 매개변수(BIC와 같은 정보 기준 등)의 지정이 필요합니다.
- 선택한 비용 함수에 대해 모델 가정을 신중하게 고려해야 합니다.
- 모델 설정 오류에 민감합니다.
- 자기상관성이 강한 시계열에서는 제대로 작동하지 않을 수 있습니다.

지금까지 비계절성 및 계절성 계열 모두에 적용할 수 있는 빈도주의(frequentist) 기반의 두 가지 방법인 BFAST와 PELT에 대해 다루었습니다. 그러나 이러한 분해 기반 방법은 추세와 계절성의 복잡한 상호 작용에서 비정상성이 발생할 때 눈에 띄는 한계가 있습니다. 예를 들어 복잡한 추세와 계절성을 가진 계절성 데이터는 정상적인 나머지를 얻기 위해 적절한 차분이 필요할 수 있습니다. BFAST와 마찬가지로 PELT 방법도 최소 세그먼트 길이(`minseglen`) 지정에 민감합니다. 이 예에서 `minseglen = 2`를 사용했다면 추가 변화점이 탐지되었을 것입니다. 이러한 한계로 인해 대안적인 접근 방식을 모색해야 합니다. 다음 절에서는 베이지안 기반 변화점 탐지 방법에 대해 논의합니다.

# 16.4 베이지안 변화점 탐지

베이지안 변화점 탐지 접근 방식은 변화점의 수와 위치에 대한 사전 신념을 지정하는 것으로 시작합니다. 이 신념은 관측된 데이터를 사용하여 업데이트됩니다. 이 과정은 변화점 구성에 대한 불확실성을 정량화하는 사후 분포를 생성합니다.

일반적으로 점 추정치를 생성하는 빈도주의 방법과 달리, 베이지안 방법은 전체 사후 분포를 제공하여 모든 매개변수에 대한 강력한 불확실성 정량화를 가능하게 합니다.

베이지안 프레임워크에서 우리는 관측된 시계열 <span class="image placeholder" data-original-image-src="../Images/B21040_16_079.png" data-original-image-title="">B21040_16_079.png</span>에서 기저 데이터 생성 과정이 변화하는 지점을 식별하고자 합니다. <span class="image placeholder" data-original-image-src="../Images/B21040_16_080.png" data-original-image-title="">B21040_16_080.png</span>를 <span class="image placeholder" data-original-image-src="../Images/B21040_16_081.png" data-original-image-title="">B21040_16_081.png</span>개의 변화점 위치 벡터라고 합시다. 여기서 <span class="image placeholder" data-original-image-src="../Images/B21040_16_082.png" data-original-image-title="">B21040_16_082.png</span>입니다.

이 접근 방식은 프로세스를 시작하기 위해 다음 매개변수에 대한 지정이 필요합니다.

- 변화점의 수에 대한 사전 분포 <span class="image placeholder" data-original-image-src="../Images/B21040_16_083.png" data-original-image-title="">B21040_16_083.png</span>
- 주어진 수에 대한 변화점의 위치에 대한 사전 분포 <span class="image placeholder" data-original-image-src="../Images/B21040_16_084.png" data-original-image-title="">B21040_16_084.png</span>
- 매개변수 <span class="image placeholder" data-original-image-src="../Images/B21040_16_086.png" data-original-image-title="">B21040_16_086.png</span>를 사용해 데이터 생성 프로세스를 설명하는 우도 모델 <span class="image placeholder" data-original-image-src="../Images/B21040_16_085.png" data-original-image-title="">B21040_16_085.png</span>
- 모델 매개변수에 대한 사전 분포 <span class="image placeholder" data-original-image-src="../Images/B21040_16_087.png" data-original-image-title="">B21040_16_087.png</span>

베이지안 추론은 다음 사후 분포를 계산하여 진행됩니다.

<span class="image placeholder" data-original-image-src="../Images/B21040_16_088.png" data-original-image-title="">B21040_16_088.png</span>

이 사후 분포는 관측된 데이터가 주어졌을 때 변화점 구성 및 모델 매개변수에 대해 사용 가능한 모든 정보를 요약합니다.

베이지안 추론에서 사후 분포는 다양한 방법을 사용하여 계산될 수 있습니다. 사후 분포의 분석적 해법이 단순하지 않을 때, 추론 과정은 마르코프 체인 몬테카를로(MCMC) 샘플링으로 알려진 수치적 매개변수 추정 알고리즘에 의존합니다. 알고리즘은 다음 단계로 구성됩니다.

1. 매개변수 <span class="image placeholder" data-original-image-src="../Images/B21040_16_089.png" data-original-image-title="">B21040_16_089.png</span>의 초기 추정치로 시작하여 체인을 초기화합니다.

2. 다음 과정을 반복합니다.
   - 새로운 매개변수 값 <span class="image placeholder" data-original-image-src="../Images/B21040_16_090.png" data-original-image-title="">B21040_16_090.png</span>를 제안합니다.
   - <span class="image placeholder" data-original-image-src="../Images/B21040_16_091.png" data-original-image-title="">B21040_16_091.png</span>을 제안 분포로 사용하여 수락 확률 <span class="image placeholder" data-original-image-src="../Images/B21040_16_092.png" data-original-image-title="">B21040_16_092.png</span>를 계산합니다.

   <span class="image placeholder" data-original-image-src="../Images/B21040_16_093.png" data-original-image-title="">B21040_16_093.png</span>
   - 균등 분포에서 추출한 난수 <span class="image placeholder" data-original-image-src="../Images/B21040_16_096.png" data-original-image-title="">B21040_16_096.png</span>와 <span class="image placeholder" data-original-image-src="../Images/B21040_16_095.png" data-original-image-title="">B21040_16_095.png</span>를 비교하여 <span class="image placeholder" data-original-image-src="../Images/B21040_16_094.png" data-original-image-title="">B21040_16_094.png</span>를 수락하거나 거부합니다. 만약 <span class="image placeholder" data-original-image-src="../Images/B21040_16_097.png" data-original-image-title="">B21040_16_097.png</span>라면, <span class="image placeholder" data-original-image-src="../Images/B21040_16_098.png" data-original-image-title="">B21040_16_098.png</span>를 <span class="image placeholder" data-original-image-src="../Images/B21040_16_099.png" data-original-image-title="">B21040_16_099.png</span>로 설정합니다.

3. 정상 분포가 사후 분포인 마르코프 체인을 구축하기 위해 여러 번 반복합니다.

4. (번인 기간 이후) 체인 샘플을 사용하여 사후 평균, 분산 또는 신뢰 구간과 같은 수량을 추정함으로써 매개변수를 추정합니다.

MCMC에 대한 자세한 내용은 베이지안 추론에 관한 표준 교과서에서 찾을 수 있습니다.

Bayesian Estimation of Abrupt changes, Seasonal variation, and Trend (BEAST)는 다중 구성 요소가 있는 복잡한 시계열을 처리하는 베이지안 방법 기반의 변화점 탐지 프레임워크입니다. 이 방법은 `Rbeast` 패키지(Zhao 등, 2019)에 구현되어 있습니다. BFAST와 마찬가지로 BEAST는 구성 요소가 다음과 같이 독립적으로 구조적 변화를 겪을 수 있는 시계열의 가법 분해를 사용합니다.

- 추세 성분 <span class="image placeholder" data-original-image-src="../Images/B21040_16_100.png" data-original-image-title="">B21040_16_100.png</span>는 수준과 기울기 모두에서 가능한 변화점을 갖는 조각별 선형 함수로 모델링됩니다.
- 계절 성분 <span class="image placeholder" data-original-image-src="../Images/B21040_16_101.png" data-original-image-title="">B21040_16_101.png</span>는 진폭과 위상이 변할 수 있는 주기적 함수로 모델링됩니다.
- 잡음 성분 <span class="image placeholder" data-original-image-src="../Images/B21040_16_102.png" data-original-image-title="">B21040_16_102.png</span>는 잠재적으로 분산이 변하는 가우스 분포를 따르는 것으로 일반적으로 가정됩니다.

BEAST 모델은 각 구성 요소에서 알 수 없는 수의 변화점을 허용하여 시계열 분해 및 변화점 탐지를 위한 유연한 프레임워크를 제공합니다.

BEAST 알고리즘의 주요 단계는 다음과 같습니다.

1. 초기화: 추세 및 계절 성분의 변화점 수와 위치에 대한 초깃값을 설정합니다.
2. MCMC 샘플링: 일련의 이동 유형을 통해 모델 구성을 반복적으로 업데이트합니다. 예를 들어 새로운 변화점을 추가하거나 기존 변화점을 제거합니다.
3. 사후 추정: 번인 기간 후 MCMC 샘플을 사용하여 변화점 수, 위치 및 모델 매개변수에 대한 사후 분포를 근사화합니다.

이 알고리즘은 베이지안 프레임워크를 통해 모델 복잡성과 데이터 적합도의 균형을 자동으로 맞추므로 과적합을 제어하기 위한 명시적인 페널티 항이나 교차 검증 절차가 필요하지 않습니다.

다음 하위 절에서 BEAST 방법의 구현을 살펴보겠습니다.

## 16.4.1 비계절성 계열에 대한 BEAST 구현

`Rbeast` 패키지의 `beast()` 함수가 알고리즘을 수행합니다. 방법론적 일관성을 유지하기 위해 모델 사후 확률 계산 및 MCMC 샘플링에 대한 기본 설정을 사용합니다. 추세 성분 분석은 `tcp.minmax` 매개변수를 사용하여 <span class="image placeholder" data-original-image-src="../Images/B21040_16_103.png" data-original-image-title="">B21040_16_103.png</span>에서 <span class="image placeholder" data-original-image-src="../Images/B21040_16_104.png" data-original-image-title="">B21040_16_104.png</span>개의 잠재적 변화점 사이에서 테스트하도록 제한되었습니다. 비계절성 데이터의 경우 season 인자를 none으로 설정해야 합니다.

`Nile` 데이터에 BEAST 알고리즘을 적용하고 다음 코드를 사용하여 중요한 정보를 추출합니다.

```R
beast_nile <- beast(Nile, season = "none",
                    tcp.minmax = c(0, 10))

beast_nile_trend_cp <- tibble(
  location = beast_nile$trend$cp,
  prob = beast_nile$trend$cpPr,
  ci_lower = beast_nile$trend$cpCI[,1],
  ci_upper = beast_nile$trend$cpCI[,2],
  magnitude_change = beast_nile$trend$cpAbruptChange ) |>
  na.omit()

beast_nile_trend_cp
```

다음 출력의 요약은 변화점의 연도(위치), 확률, 신뢰 구간 및 변화의 크기를 보여줍니다.

```
# A tibble: 9 × 5
  location   prob ci_lower ci_upper magnitude_change
     <dbl>  <dbl>    <dbl>    <dbl>            <dbl>
1     1899 0.968     1896.    1901.         -175.
2     1954 0.110     1950.    1957.            5.00
3     1966 0.0733    1962.    1968.           -2.77
4     1946 0.0725    1937.    1951.            2.28
5     1916 0.0644    1907.    1922.            1.61
6     1890 0.0350    1883.    1894.            1.65
7     1929 0.0349    1922.    1937.            0.559
8     1877 0.0345    1874.    1883.           -0.157
9     1961 0.0337    1956.    1964.            0.241
```

요약은 최대 <span class="image placeholder" data-original-image-src="../Images/B21040_16_105.png" data-original-image-title="">B21040_16_105.png</span>개의 변화점에 대해 생성됩니다. BEAST에 따르면 통계적으로 의미 있는 변화점은 <span class="image placeholder" data-original-image-src="../Images/B21040_16_106.png" data-original-image-title="">B21040_16_106.png</span>년(prob=<span class="image placeholder" data-original-image-src="../Images/B21040_16_107.png" data-original-image-title="">B21040_16_107.png</span>) 하나만 감지되었으며 변화의 크기는 <span class="image placeholder" data-original-image-src="../Images/B21040_16_108.png" data-original-image-title="">B21040_16_108.png</span>입니다. BEAST에 의해 추정된 변화의 크기는 동일한 데이터에 대해 BFAST와 PELT가 측정한 것과 상당히 다릅니다.

적합된 BEAST 객체에서 생성된 통찰력 있는 플롯이 그림 16.6에 제시되어 있습니다.

<figure class="mediaobject">
 <span class="image placeholder" data-original-image-src="../Images/B21040_16_6.png" data-original-image-title="">Image 6</span> 
</figure>

그림 16.6: 나일강 데이터에서 BEAST가 감지한 변화점

그림 16.6의 시각화는 다음과 같은 몇 가지 흥미로운 발견을 드러냅니다.

- 추세 성분: 녹색 추세선과 파선 수직 변화점 마커(관측된 데이터 포인트에 겹쳐짐)는 유의미한 변화점 연도로 <span class="image placeholder" data-original-image-src="../Images/B21040_16_109.png" data-original-image-title="">B21040_16_109.png</span>년을 정확히 지적하며 이는 BFAST 및 PELT 결과와 일치합니다. 베이지안 방법으로서 BEAST는 변화점을 모델 매개변수로 취급하고 단일 결정론적 변화점을 식별하는 대신 사후 확률 분포를 추정합니다. 이 접근 방식은 변화점 탐지에서 관련된 불확실성을 제공합니다. <span class="image placeholder" data-original-image-src="../Images/B21040_16_110.png" data-original-image-title="">B21040_16_110.png</span>년에 식별된 변화점의 경우 <span class="image placeholder" data-original-image-src="../Images/B21040_16_111.png" data-original-image-title="">B21040_16_111.png</span> 신뢰 구간이 <span class="image placeholder" data-original-image-src="../Images/B21040_16_112.png" data-original-image-title="">B21040_16_112.png</span>년 6월에서 <span class="image placeholder" data-original-image-src="../Images/B21040_16_113.png" data-original-image-title="">B21040_16_113.png</span>년 4월까지 걸쳐 있습니다.
- 추세의 변화점 확률: `Pr(tcp)` 패널은 <span class="image placeholder" data-original-image-src="../Images/B21040_16_114.png" data-original-image-title="">B21040_16_114.png</span>에 뚜렷한 확률 정점을 보여줍니다.
- 기울기 방향: `slpSign` 패널은 기울기 방향 확률을 나타내며 양수는 빨간색, 음수는 파란색, 중립(추세 변화 없음)은 녹색입니다.

이제 계절성 AirPassengers 데이터에 BEAST 방법을 적용해 보겠습니다.

## 16.4.2 계절성 데이터에 대한 BEAST 구현

계절성 계열에서 BEAST를 설명하기 위해 AirPassengers 데이터의 로그에 알고리즘을 적용합니다. 승수적 계절성 패턴을 가법적으로 변환하기 위해 로그 변환이 적용됩니다. `season="harmonic"` 인자는 알고리즘이 계절 패턴의 변화점을 탐지할 수 있게 해줍니다. 다음 코드를 사용하여 방법을 적용하고 모델 객체에서 중요한 정보를 추출할 수 있습니다.

```R
beast_ap <- beast(log(AirPassengers),
                  season = "harmonic",
                  tcp.minmax = c(0, 10))

# 추세의 변화점
beast_ap_trend_cp <- tibble(
  location = beast_ap$trend$cp,
  prob = beast_ap$trend$cpPr,
  ci_lower = beast_ap$trend$cpCI[,1],
  ci_upper = beast_ap$trend$cpCI[,2],
  magnitude_change = beast_ap$trend$cpAbruptChange
) |>
  na.omit()

# 계절성의 변화점
beast_ap_seas_cp <- tibble(
  location = beast_ap$season$cp,
  prob = beast_ap$season$cpPr,
  ci_lower = beast_ap$season$cpCI[,1],
  ci_upper = beast_ap$season$cpCI[,2],
  magnitude_change = beast_ap$season$cpAbruptChange
) |>
  na.omit()
```

BEAST 방법으로 생성된 그림 16.7에 제시된 플롯을 살펴보겠습니다.

```R
par(mar = c(2, 2, 1, 1), cex=0.8)
plot(beast_ap, main = "")
```

<figure class="mediaobject">
 <span class="image placeholder" data-original-image-src="../Images/B21040_16_7.png" data-original-image-title="">Image 7</span> 
</figure>

그림 16.7: AirPassengers 데이터의 추세 및 계절적 변화점에 대한 베이지안 추정

플롯에서 BEAST가 추세에서 세 개의 변화점을 식별하고 계절 성분에서 하나의 변화점을 식별했음을 알 수 있습니다. BFAST나 PELT 모두 동일한 데이터에 대해 계절성 변화점을 감지하지 못했음을 상기해 보세요. 다음 출력에서 추세 변화점의 정확한 위치를 얻을 수 있습니다.

```
> beast_ap_trend_cp

# A tibble: 6 × 5
  location   prob ci_lower ci_upper magnitude_change
     <dbl>  <dbl>    <dbl>    <dbl>            <dbl>
1    1958  0.979     1958.    1958.          -0.0412
2    1953. 0.969     1953.    1954.          -0.0353
3    1950. 0.798     1950.    1951.           0.0373
4    1956. 0.127     1956.    1957.           0.0145
5    1955. 0.0881    1954.    1955.           0.0135
6    1952. 0.0297    1952.    1952.           0.0121
```

계절 패턴에서 감지된 변화점은 다음 출력에 제시되어 있습니다.

```
> beast_ap_seas_cp

# A tibble: 2 × 5
  location  prob ci_lower ci_upper magnitude_change
     <dbl> <dbl>    <dbl>    <dbl>            <dbl>
1    1954. 0.539    1953.    1954.         -0.00756
2    1953. 0.259    1952.    1953.         -0.0886
```

수치 출력에서 더 많은 변화점이 탐지되었음을 알 수 있습니다. 그러나 <span class="image placeholder" data-original-image-src="../Images/B21040_16_115.png" data-original-image-title="">B21040_16_115.png</span>보다 높은 확률을 갖는 변화점만이 유의미한 것으로 간주되어 플롯에 포함됩니다.

다음은 BEAST 알고리즘의 장점과 한계입니다.

다음은 장점입니다.

- 변화점 위치에 대한 전체 사후 분포를 제공하여 불확실성을 정량화합니다.
- 변화점의 빈도나 위치에 대한 사전 지식을 자연스럽게 통합합니다.
- 통합 프레임워크에서 여러 유형의 변경 사항(추세 및 계절)을 처리합니다.
- 빈도주의적 방법에 비해 튜닝 매개변수에 덜 민감합니다.

다음은 한계점입니다.

- 계산 집약적이며 특히 MCMC 기반 방법의 경우 더욱 그렇습니다.
- 사전 분포의 지정이 필요합니다.
- 다중 변화점 유형에 대해 모델 복잡성이 빠르게 증가합니다.
- 단순한 방법에 비해 해석이 더 어려울 수 있습니다.
- 구현을 위해 베이지안 통계에 대한 전문 지식이 필요할 수 있습니다.

지금까지 비계절성 및 계절성 데이터세트에 모두 적용되는 세 가지 변화점 탐지 방법과 그 장단점에 대해 배웠습니다. 한 방법이 다른 방법보다 더 적합한 상황이 있을까요? 다음 절의 가이드라인은 비즈니스 문제에 적합한 방법을 식별하는 데 도움이 될 것입니다.

# 16.5 방법 선택 가이드라인

실제 응용 분야에서 변화점 탐지 방법을 선택할 때 장단점 이상의 몇 가지 요소를 고려해야 합니다. 이들은 요구 사항에 따라 여러분을 안내하기 위해 세 가지 주요 범주로 요약 및 그룹화되었습니다.

첫 번째는 데이터 특성과 관련이 있습니다.

- 데이터 크기: 매우 큰 데이터세트의 경우 계산 효율성 때문에 이진 분할이 선호될 수 있습니다.
- 노이즈 수준: 베이지안 방법은 확률적 특성으로 인해 노이즈가 많은 데이터에서 종종 더 나은 성능을 발휘합니다.
- 변화점 빈도: PELT는 수많은 변화점을 탐지하는 데 매우 적합합니다.
- 변화점 크기: 더 작은 이동은 PELT 또는 베이지안 접근 방식에 의해 더 잘 감지될 수 있습니다.

다음은 분석 목표입니다.

- 계산 효율성: 이진 분할이 빠르며 그 다음이 PELT이고 베이지안 방법이 뒤를 잇습니다.
- 이론적 보장: PELT는 비용 모델 하에서 최적성 보장을 제공합니다.
- 불확실성 정량화: 베이지안 방법은 불확실성 추정치가 필요할 때 뛰어납니다.
- 온라인 감지: 수정된 베이지안 접근 방식은 스트리밍 데이터의 변화점 탐지에 특히 적합합니다.

마지막 그룹은 구현 복잡성입니다.

- 필요한 기술적 전문성: 이진 분할이 간단한 반면 베이지안 방법은 일반적으로 고급 통계 및 컴퓨팅 기술이 필요합니다.
- 매개변수 조정: 베이지안 방법은 일반적으로 PELT 및 BFAST보다 더 넓은 범위의 매개변수 조정이 필요합니다.

# 요약

변화점 탐지는 시계열 분석의 중요한 구성 요소로서 후속 분석 및 예측에 상당한 영향을 미칠 수 있는 구조적 단절을 식별할 수 있게 해줍니다. 이 장에서는 BFAST, PELT 및 BEAST의 세 가지 방법과 함께 이들의 고유한 강점과 한계를 탐구했습니다.

이진 분할(BFAST)은 많은 애플리케이션에 적합한 효율적이고 직관적인 접근 방식을 제공하며, 특히 계산 리소스가 제한되어 있거나 매우 긴 시계열을 다룰 때 유용합니다. PELT는 합리적인 계산 효율성을 유지하면서 최적의 분할 보장을 제공하여 높은 정밀도가 필요한 응용 분야에 탁월한 선택이 됩니다. 베이지안 변화점 탐지는 불확실성을 정량화하고 사전 지식을 통합하는 데 뛰어나 계산 복잡성이 증가하는 대신 더 풍부한 통찰력을 제공합니다.

실제에서 이러한 방법을 적용할 때 데이터세트의 특정 특성, 분석 목표 및 사용 가능한 계산 리소스를 신중하게 고려해야 합니다. 단일 방법에 의존하는 것보다 여러 접근 방식을 사용하고 그 결과를 비교하는 것이 종종 더 강력한 통찰력을 제공할 수 있습니다.

도메인 전반에 걸쳐 시계열 데이터의 양과 중요성이 계속 증가함에 따라 변화점 탐지는 구조적 변화를 이해하고 예측 정확도를 향상시키며 복잡한 시스템의 기본 역학에 대한 통찰력을 얻기 위한 필수적인 도구로 남아 있을 것입니다.

추세 및 계절 성분이 뚜렷한 시계열의 경우 탐지된 변화점의 의미 있는 해석을 위해 도메인 전문 지식이 필수적이 됩니다. 맥락적 이해 없이 맹목적으로 방법을 적용하면 복잡한 시간적 패턴에 직면할 때 모호하거나 오해의 소지가 있는 결과가 발생할 수 있습니다.

이러한 중요한 알림을 염두에 두고 책의 마지막 장으로 넘어가 보겠습니다. 이 장에서는 비즈니스에서 흔히 발생하는 상황인 시계열에서 이상치를 탐지하는 방법과 결측값을 대치하는 방법을 배우게 됩니다.

# 추가 읽을거리

- Killick, R., Fearnhead, P., & Eckley, I. A. (2012). _Optimal detection of changepoints with a linear computational cost. Journal of the American Statistical Association_, 107(500), 1590–1598.
- Verbesselt, J., Hyndman, R., Newnham, G., & Culvenor, D. (2010). _Detecting trend and seasonal changes in satellite image time series. Remote Sensing of Environment_, 114(1), 106–115.
- Zhao, K., Wulder, M. A., Hu, T., Bright, R., Wu, Q., Qin, H., Li, Y., Toman, E., Mallick, B., 창, X., et al. (2019). _Detecting change-point, trend, and seasonality in satellite time series data to track abrupt changes and nonlinear dynamics: A Bayesian ensemble algorithm. Remote Sensing of Environment_, 232, 111181.

# Discord 커뮤니티에 가입하세요

커뮤니티의 Discord 공간에 참여하여 저자 및 다른 독자들과 토론하세요.

<a href="https://discord.gg/G4YmB6DQvf" style="text-decoration: none;">https://discord.gg/G4YmB6DQvf</a>

<span class="image placeholder" data-original-image-src="../Images/B21040_16_8.png" data-original-image-title="">Image</span>
