# 환영합니다 {.unnumbered}

이 웹사이트는 **"R for Data Science"** 2판의 웹사이트입니다.
이 책은 R을 사용하여 데이터 과학을 수행하는 방법을 가르쳐줍니다. 데이터를 R로 가져오고, 유용한 구조로 만들고, 변환하고 시각화하는 방법을 배우게 됩니다.

이 책에서는 데이터 과학을 위한 실무 기술을 찾을 수 있습니다.
화학자가 시험관을 닦고 실험실을 채우는 방법을 배우는 것처럼, 데이터를 정리하고 플롯을 그리는 방법은 물론 그 밖의 여러 가지를 배우게 됩니다.
이러한 기술들은 데이터 과학을 가능하게 하는 핵심이며, 여기에서 R을 사용하여 이러한 각 작업을 수행하는 모범 사례를 찾을 수 있습니다.
그래픽 문법(grammar of graphics), 리터러트 프로그래밍(literate programming), 재현 가능한 연구(reproducible research)를 사용하여 시간을 절약하는 방법을 배울 것입니다.
또한 데이터를 다듬고, 시각화하고, 탐색할 때 발견을 촉진하기 위해 인지적 자원(cognitive resources)을 관리하는 방법도 배우게 됩니다.

이 웹사이트는 항상 무료이며, [CC BY-NC-ND 3.0](https://creativecommons.org/licenses/by-nc-nd/3.0/us/) 라이선스에 따라 배포됩니다.
책의 실물 버전을 원하신다면, [Amazon](https://www.amazon.com/dp/1492097403?&tag=hadlwick-20)에서 주문하실 수 있습니다.
무료로 책을 읽고 감사의 뜻을 전하고 싶으시다면, [Kākāpō Recovery](https://www.doc.govt.nz/kakapo-donate)에 기부해 주시기 바랍니다. R4DS 표지에 등장하는 [카카포(kākāpō)](https://www.youtube.com/watch?v=9T1vfsHYiKY)는 뉴질랜드 토착종으로 심각한 멸종 위기에 처한 앵무새이며, 현재 단 244마리만 남아 있습니다.

다른 언어를 사용하신다면, 1판의 무료 번역본에 관심이 있으실 수 있습니다.

-   [스페인어(Spanish)](http://es.r4ds.hadley.nz)
-   [이탈리아어(Italian)](https://it.r4ds.hadley.nz)
-   [튀르키예어(Turkish)](https://tr.r4ds.hadley.nz)
-   [포르투갈어(Portuguese)](https://pt.r4ds.hadley.nz)

그리고 2판:

-   [스페인어(Spanish)](https://davidrsch.github.io/r4ds-es/)
-   [베트남어(Vietnamese)](https://vn.r4ds.hadley.nz/)

책의 연습 문제에 대한 권장 해답은 <https://mine-cetinkaya-rundel.github.io/r4ds-solutions>에서 찾으실 수 있습니다.

R4DS는 [기여자 행동 강령(Contributor Code of Conduct)](https://contributor-covenant.org/version/2/0/CODE_OF_CONDUCT.html)을 사용함을 유의하시기 바랍니다.
이 책에 기여함으로써 귀하는 해당 약관을 준수하는 데 동의하게 됩니다.
