# 2판 서문 (Preface to the second edition) {.unnumbered}

"R for Data Science" 2판에 오신 것을 환영합니다!
이번 판은 1판의 대대적인 개정판으로, 더 이상 유용하지 않다고 생각되는 내용을 삭제하고, 1판에 포함되었으면 했던 내용을 추가했으며, 전반적으로 텍스트와 코드를 업데이트하여 모범 사례의 변화를 반영했습니다.
또한 저명한 데이터 과학 교육자이자 Posit(구 RStudio)의 동료인 Mine Çetinkaya-Rundel을 새로운 공동 저자로 맞이하게 되어 매우 기쁩니다.

가장 큰 변경 사항을 간략히 요약하면 다음과 같습니다.

-   책의 첫 번째 부분은 "전체 과정(Whole game)"으로 이름이 변경되었습니다.
    이 섹션의 목표는 세부 사항을 살펴보기 전에 데이터 과학의 "전체 과정"에 대한 개략적인 세부 사항을 제공하는 것입니다.

-   책의 두 번째 부분은 "시각화(Visualize)"입니다.
    이 부분에서는 1판에 비해 데이터 시각화 도구와 모범 사례를 더 깊이 있게 다룹니다.
    모든 세부 사항을 얻을 수 있는 가장 좋은 곳은 여전히 [ggplot2 book](http://ggplot2-book.org/)이지만, 이제 R4DS에서 가장 중요한 기술을 더 많이 다룹니다.

-   책의 세 번째 부분은 이제 "변환(Transform)"이라고 불리며 숫자, 논리형 벡터(logical vectors), 결측값(missing values)에 대한 새로운 장이 추가되었습니다.
    이것들은 이전에 데이터 변환 장의 일부였지만 모든 세부 사항을 다루기 위해 훨씬 더 많은 공간이 필요했습니다.

-   책의 네 번째 부분은 "가져오기(Import)"입니다.
    일반 텍스트 파일(flat text files)을 읽는 것을 넘어 스프레드시트(spreadsheets) 작업, 데이터베이스에서 데이터 가져오기, 빅 데이터 작업, 계층적 데이터 직사각형화(rectangling hierarchical data), 웹 사이트에서 데이터 스크래핑 등을 다루는 새로운 장들로 구성되었습니다.

-   "프로그램(Program)" 부분은 그대로 유지되지만 상위 함수 작성(function writing) 및 반복(iteration)의 가장 중요한 부분에 초점을 맞추도록 위에서 아래로 다시 작성되었습니다.
    지난 몇 년 동안 이것이 훨씬 쉽고 중요해졌기 때문에 함수 작성에는 tidyverse 함수를 래핑하는 방법(tidy evaluation의 문제 처리)에 대한 세부 사항이 포함됩니다.
    야생에서 얻은(wild-caught) R 코드에서 볼 가능성이 높은 중요한 기본 R 함수(base R functions)에 대한 새로운 장을 추가했습니다.

-   모델링(modeling) 부분은 삭제되었습니다.
    모델링을 제대로 다루기 위한 충분한 공간이 없었고, 이제 훨씬 더 나은 리소스를 사용할 수 있습니다.
    일반적으로 [tidymodels](https://www.tidymodels.org/) 패키지를 사용하고 Max Kuhn과 Julia Silge가 작성한 [Tidy Modeling with R](https://www.tmwr.org/)을 읽는 것을 권장합니다.

-   "소통(Communicate)" 부분은 유지되지만 R Markdown 대신 [Quarto](https://quarto.org/)를 특징으로 하도록 철저히 업데이트되었습니다.
    이 책의 이번 판은 Quarto로 작성되었으며 분명히 미래의 도구입니다.
