{
  "hash": "43f1876e653b935e6ec70cb0843e5ab0",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: \"구간 추정의 개념\"\n---\n\n> 지금까지 다룬 통계적 추론(statistical inference) 논의에서는 주로 가설 검정(hypothesis tests)에만 초점을 맞추었습니다. 더불어 표본으로부터 통계량을 계산할 때, 모집단 모수(population parameters)를 추정하기 위해 단일 수치만을 도출하는 데 집중했습니다. 그러나 모수에 대한 추정 방식 중에는 '타당해 보이는 값들의 범위(구간, interval)' 전체를 제시하는 강력한 방법론들이 존재합니다. 본 장에서는 이러한 구간 추정(interval estimates)의 필요성과 그 정확한 해석 방법에 대해 다루겠습니다.\n\n## 점 및 구간 추정값\n\n통계학에서는 알 수 없는 모집단 모수를 추정하기 위해 표본 통계량(sample statistics)을 계산합니다. 지금까지 우리가 살펴본 것은 점 추정값(point estimates)입니다. 점 추정값은 대응하는 모집단 모수를 추정하기 위해 사용하는 단 하나의 수치입니다. 예를 들어 표본 평균 $\\bar{x}$는 모집단 평균 $\\mu$에 대한 점 추정값이고, 표본 분산 $s^2$은 모집단 분산 $\\sigma^2$에 대한 점 추정값이며, 표본 비율 $\\hat{p}$은 모집단 비율 $p$에 대한 점 추정값입니다. 이 모든 점 추정값들은 모집단 모수의 실제 값에 대한 우리의 '최선의 단일 추측치'를 나타냅니다.\n\n점 추정값이나 표본 통계량은 유용한 정보를 제공하지만, 무작위 추출의 본질상 표본을 새로 뽑을 때마다 그 값이 달라질 수밖에 없습니다. 여러 번 표본을 수집한다면, 모집단 모수로 타당해 보이는 다양한 값들의 무더기를 얻게 될 것입니다. 따라서 특정한 상황에서는 단일 수치보다 '타당한 값들의 범위'를 통째로 추정값으로 제시하는 것이 훨씬 합리적입니다. 구간 추정값(interval estimate)이 바로 이러한 역할을 수행합니다. 구간 추정값이란 알려지지 않은 모집단 모수가 포함될 것으로 기대되는 값들의 구간을 의미합니다. 선거 예측이나 정치 여론 조사에서 지지율 우위가 단일 숫자가 아닌 특정 범위(구간)로 명시되는 것을 자주 접해보셨을 텐데, 이것이 바로 구간 추정의 대표적인 예입니다.\n\n실무에서 구간 추정값은 보통 '점 추정값 $\\pm$ 오차 한계(margin of error)'의 형태로 보고됩니다. 오차 한계는 점 추정값이 얼마나 정밀한지를 보여주는 지표로, 통제할 수 없는 표본 추출의 우연성 때문에 추정값에 발생할 수 있는 변동성의 최대 허용치를 나타냅니다.\n\n예를 들어 2017년 버지니아 주지사 선거를 앞두고 퀴니피액 대학교(Quinnipiac University)가 실시한 여론조사에서, 민주당 랠프 노덤(Ralph Northam) 후보가 공화당 에드 길레스피(Ed Gillespie) 후보를 '9포인트 $\\pm$ 3.7포인트' 차이로 앞서고 있다는 결과가 발표되었습니다. 이 경우 지지율 격차에 대한 점 추정값은 9포인트이고 오차 한계는 3.7포인트입니다. 이는 노덤 후보가 실제로는 $9 - 3.7 = 5.3$포인트에서 $9 + 3.7 = 12.7$포인트 사이의 격차로 앞서고 있다고 보는 것이 통계적으로 타당하다는 뜻입니다.\n\n이상적인 상황에서 오차 한계는 우리가 모집단 모수의 추정 범위를 얼마나 확신할 수 있는지 직관적으로 알려줍니다. 만약 점 추정값이 6으로 같지만 오차 한계가 각각 다른 두 구간 추정값, $6 \\pm 2$와 $6 \\pm 4$가 있다고 상상해 보십시오. 첫 번째 구간은 모수의 타당한 범위가 4에서 8까지임을 의미하고, 두 번째는 2에서 10까지임을 의미합니다. 첫 번째 구간의 범위가 훨씬 좁고 구체적이므로, 우리는 첫 번째 추정 결과를 더 신뢰하는 경향이 있습니다. 그러나 오차 한계의 크기는 단순히 데이터 자체의 변동성뿐만 아니라 표본의 크기, 그리고 중요하게는 '우리가 설정한 구간이 맞을 확률' 등 여러 복합적인 요인에 의해 결정됩니다.\n\n## 구간이 \"옳을\" 때\n\n구간 추정값을 정의할 때, 우리는 이 구간이 확률적으로 어떤 의미를 갖는지 명확히 하고 싶어 합니다. 이상적인 해석은 \"이 구간이 모수를 정확히 맞출 확률이 얼마인가?\"일 것입니다. 그렇다면 통계학에서 구간이 '옳다(맞다)'는 것은 도대체 무엇을 의미하며, 현실에서 우리가 그것을 확인할 수 있을까요?\n\n우리가 모수와 구간에 대해 알고 있는 근본적인 전제로 돌아가 보겠습니다. 고전 통계학(빈도주의, frequentist) 패러다임에서 모집단 모수는 비록 우리가 알 수는 없지만 '고정된 단일 상수'입니다. 즉, 현실 세계에서 모수는 여러 타당한 값들을 가지는 것이 아니라 오직 하나의 진짜 값(true value)만을 가집니다. 반면 우리가 계산하는 구간 추정값은 수집된 표본 데이터로부터 산출되므로, 표본이 바뀔 때마다 그 위치와 너비가 달라지는 '확률 변수(random variable)'입니다.\n\n우리는 이 변동하는 구간 추정값이 모수의 고정된 참값을 덮을 때(포함할 때), 해당 구간이 '옳다'고 정의합니다. 물론 현실에서는 모수의 참값을 결코 알 수 없으므로, 특정 표본에서 계산된 단일 구간이 진짜로 옳은지 틀린지 확인하는 것은 불가능합니다. 따라서 우리는 특정한 하나의 구간에 집착하는 대신, '이러한 방식으로 구간을 계산했을 때 그 구간이 참값을 덮을 확률'이라는 관점에서 접근해야 합니다. 즉, 우리의 구간 산출 방식이 얼마나 믿을 만한지, 그 정확성에 대해 '얼마나 확신하는지(confident)'를 수치화해야 합니다.\n\n## 신뢰 구간\n\n이제 '구간이 옳다'는 것의 정의를 내렸으므로, 그 '옳을 확률'과 직접적으로 연결되는 구간 추정값을 만들어야 합니다. 신뢰 구간(confidence intervals)은 데이터로부터 산출된 모수의 타당한 범위로, 그 확률론적 해석이 '구간 산출 방식이 모수의 참값을 덮어낼 확률'과 수학적으로 직결되는 특별한 구간 추정값입니다. \n\n표본으로부터 계산된 신뢰 구간은 사전에 약속된 특정 비율만큼 모집단 모수의 참값을 포함하도록 설계됩니다. 예를 들어 80% 신뢰 구간을 산출하는 방식은 80%의 확률로 모수의 참값을 덮어냅니다. 95% 신뢰 구간은 95%의 확률로 참값을 덮어냅니다. 일반화하자면, 우리가 무수히 많은 표본을 반복 추출하여 각각으로부터 $(1-\\alpha) \\times 100\\%$ 신뢰 구간을 계산한다면, 그 무수한 구간들 중 정확히 $(1-\\alpha) \\times 100\\%$가 모수의 참값을 포함하게 됩니다. 이 $(1-\\alpha) \\times 100\\%$라는 사전에 정해진 포함 비율(구간 산출 방식이 옳을 확률)을 바로 신뢰 수준(confidence level)이라고 부릅니다.\n\n이해를 돕기 위해 예외적으로 모수의 참값을 이미 알고 있는 시뮬레이션 상황을 가정해 보겠습니다. 공정한 동전(앞면이 나올 참 확률 $p=0.5$)을 100번 던진 뒤, 그 결과를 바탕으로 $p$에 대한 95% 신뢰 구간을 생성한다고 가정해 보십시오. 데이터를 새로 수집하여 신뢰 구간을 생성하는 이 동일한 과정을 총 100번 반복합니다. 95% 신뢰 구간 방식은 95%의 확률로 '옳게' 설계되었으므로, 우리가 생성한 100개의 각기 다른 구간들 중 대략 95개 정도가 $p=0.5$라는 참값을 성공적으로 덮고(포함하고) 있는 것을 확인할 수 있을 것입니다.\n\n## 신뢰 구간 생성하기\n\n일반적으로 모수에 대한 신뢰 구간은 앞서 언급한 바와 같이 다음과 같은 기본 형태를 띱니다.\n\n$$\n\\text{점 추정값} \\pm \\text{오차 한계}\n$$\n\n신뢰 구간의 정확한 수학적 형태는 추정하고자 하는 모수가 무엇인지에 따라 조금씩 달라집니다. 하지만 신뢰 구간을 도출하는 과정과 그것이 어떻게 '옳을 확률'과 연결되는지에 대한 기본 논리는 동일합니다. 여기서는 대표적인 모집단 비율 $p$에 대한 신뢰 구간을 도출하는 과정을 통해 그 원리를 살펴보겠습니다.\n\n우리가 산출하는 신뢰 구간이 $(1-\\alpha) \\times 100\\%$의 확률로 참값을 포함(옳음)하려면, 표본으로부터 계산될 하한(Lower bound)과 상한(Upper bound)이 다음 조건을 만족해야 합니다.\n\n$$\nP(\\text{하한} < p < \\text{상한}) = 1-\\alpha\n$$\n\n이를 유도하기 위해 이전 장에서 다루었던 표준 정규분포(Standard Normal distribution)를 활용해 보겠습니다. 표준 정규분포 곡선 아래의 면적 중 중앙의 $(1-\\alpha)$만큼을 차지하게 만드는 대칭적인 경계값 $-z^*$와 $z^*$를 찾을 수 있습니다.\n\n$$\nP(-z^* < N(0,1) < z^*) = 1-\\alpha\n$$\n\n이 $z^*$ 값을 우리는 임계값(critical value)이라고 부릅니다. 이제 우리가 추정하려는 모집단 비율 $p$를 이 표준 정규분포와 수학적으로 연결할 수만 있다면 구간을 완성할 수 있습니다. 기억을 되살려 보면, 표본 비율, 모집단 비율, 그리고 정규분포를 이어주는 강력한 이론이 있었습니다. 바로 중심극한정리(Central limit theorem)입니다. 표본 크기 $n$이 충분히 크다면 표본 비율 $\\hat{p}$은 다음과 같은 정규분포를 따릅니다.\n\n$$\n\\hat{p} \\sim N\\left(p, \\text{s.e.}(\\hat{p})^2\\right)\n$$\n\n가설 검정에서 보았듯이, 여기서 평균 $p$를 빼고 표준 오차 $\\text{s.e.}(\\hat{p})$로 나누면 이를 표준 정규분포로 변환할 수 있습니다.\n\n$$\n\\frac{\\hat{p}-p}{\\text{s.e.}(\\hat{p})} \\sim N(0,1)\n$$\n\n이제 처음 작성했던 표준 정규분포 확률 식 $P(-z^* < N(0,1) < z^*) = 1-\\alpha$로 돌아가 보겠습니다. $N(0,1)$ 자리에 위에서 구한 $\\frac{\\hat{p}-p}{\\text{s.e.}(\\hat{p})}$를 그대로 대입하면 식은 다음과 같이 변합니다.\n\n$$\nP\\left(-z^* < \\frac{\\hat{p}-p}{\\text{s.e.}(\\hat{p})} < z^*\\right) = 1-\\alpha\n$$\n\n이제 $1-\\alpha$라는 확률을 보장하는 부등식 한가운데에 미지의 모집단 모수 $p$가 자리 잡게 되었습니다. 하한과 상한을 구하기 위해 부등식을 조작하여 가운데에 $p$만 남겨 보겠습니다.\n\n$$\n\\begin{aligned}\nP\\left(-z^* < \\frac{\\hat{p}-p}{\\text{s.e.}(\\hat{p})} < z^*\\right) &= 1-\\alpha \\\\\nP\\left(-z^* \\cdot \\text{s.e.}(\\hat{p}) < \\hat{p}-p < z^* \\cdot \\text{s.e.}(\\hat{p})\\right) &= 1-\\alpha \\\\\nP\\left(-\\hat{p} - z^* \\cdot \\text{s.e.}(\\hat{p}) < -p < -\\hat{p} + z^* \\cdot \\text{s.e.}(\\hat{p})\\right) &= 1-\\alpha \\\\\nP\\left(\\hat{p} - z^* \\cdot \\text{s.e.}(\\hat{p}) < p < \\hat{p} + z^* \\cdot \\text{s.e.}(\\hat{p})\\right) &= 1-\\alpha\n\\end{aligned}\n$$\n\n마지막 단계에서 부등식 전체에 $-1$을 곱하면 부등호 방향이 뒤집히므로, 이를 작은 값이 왼쪽에 오도록 다시 쓰면 위와 같은 최종 형태가 됩니다.\n\n이렇게 해서 우리는 하한이 $\\hat{p} - z^* \\cdot \\text{s.e.}(\\hat{p})$이고 상한이 $\\hat{p} + z^* \\cdot \\text{s.e.}(\\hat{p})$인 구간을 얻어냈습니다. 이 구간의 양 끝값은 표본 데이터($\\hat{p}$)로부터 계산되므로 표본에 따라 변하는 확률 변수입니다. 그리고 이 구간 산출 방식은 정확히 $(1-\\alpha) \\times 100\\%$의 확률로 참값 $p$를 포함하게 됩니다. 결론적으로, 모집단 비율 $p$에 대한 $(1-\\alpha) \\times 100\\%$ 신뢰 구간의 공식은 다음과 같습니다.\n\n$$\n\\left(\\hat{p} - z^* \\cdot \\text{s.e.}(\\hat{p}), \\;\\; \\hat{p} + z^* \\cdot \\text{s.e.}(\\hat{p})\\right)\n$$\n\n공식을 보면 신뢰 구간을 계산하기 위해 세 가지 요소가 필요함을 알 수 있습니다. 표본 비율 $\\hat{p}$, 표준 오차 $\\text{s.e.}(\\hat{p})$, 그리고 임계값 $z^*$입니다. 표본 비율은 수집한 데이터에서 직접 계산합니다. 표준 오차를 계산하는 구체적인 공식은 향후 장들에서 다룰 예정이며, 당분간은 문제에서 값이 주어질 것입니다. 남은 것은 임계값 $z^*$를 구하는 방법입니다. $z^*$는 우리가 원하는 신뢰 수준(얼마나 확신하고 싶은지)에 따라 다음 조건을 만족하도록 선택됩니다.\n\n$$\nP(-z^* < N(0,1) < z^*) = 1-\\alpha\n$$\n\n이 정의대로라면 $z^*$를 찾기 위해 양쪽 꼬리의 확률을 동시에 고려해야 하므로 다소 번거롭습니다. 하지만 정규분포가 완벽히 대칭이라는 사실을 이용하면, 위 조건은 다음 조건과 수학적으로 완전히 동일해집니다.\n\n$$\nP(N(0,1) < z^*) = 1 - \\alpha/2\n$$\n\n이 단순화된 식을 이용하면 누적 확률 하나만 조회하여 쉽게 $z^*$를 찾을 수 있습니다. 실제 상황에 적용해 보겠습니다. $p$에 대한 95\\% 신뢰 구간을 구하고 싶다고 합시다. $(1-\\alpha) \\times 100\\% = 95\\%$이므로 $\\alpha = 0.05$가 됩니다. 이를 식에 대입하면 다음과 같습니다.\n\n$$\nP(N(0,1) < z^*) = 1 - 0.05/2 = 0.975\n$$\n\n이 임계값 $z^*$를 구하기 위해 우리는 R과 같은 통계 소프트웨어를 활용합니다. 특정 누적 확률에 해당하는 정규분포의 분위수(Quantile)를 찾을 때는 `qnorm` 함수를 사용합니다.\n\n```r\nqnorm(p, mean, sd)\n```\n\n이 함수는 누적 확률이 `p`가 되는 지점의 분위수 $z^*$를 반환합니다. 95% 신뢰 구간에 필요한 $z^*$를 찾으려면 다음 코드를 실행합니다.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nqnorm(p = 0.975, mean = 0, sd = 1)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 1.959964\n```\n\n\n:::\n:::\n\n\nR은 1.959964라는 값을 반환하며, 우리는 이 값을 반올림하여 1.96으로 사용하는 경우가 많습니다.\n\n실제 연구 사례를 통해 이 과정을 완성해 보겠습니다. 1996년 미국 종합 사회 조사(General Social Survey)에서 96명을 무작위로 추출하여 직업 만족 여부를 물었습니다. 79명이 만족한다고 응답했으므로, 표본 비율은 $\\hat{p} = 79/96 \\approx 0.8229$입니다. 전체 미국인 중 직업에 만족하는 사람들의 참 비율 $p$에 대해 90\\% 신뢰 구간($\\alpha=0.1$)을 생성하고자 합니다.\n\n첫 번째 단계로, 누적 확률이 $1 - 0.1/2 = 0.95$가 되는 임계값 $z^*$를 찾습니다.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nqnorm(p = 0.95, mean = 0, sd = 1)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 1.644854\n```\n\n\n:::\n:::\n\n\n계산 결과 $z^* \\approx 1.644854$(보통 1.645로 사용)를 얻습니다. 이 데이터의 표준 오차는 $\\text{s.e.}(\\hat{p}) = 0.039$로 주어졌다고 가정합시다. 모든 정보를 공식에 대입하면 90\\% 신뢰 구간은 다음과 같이 계산됩니다.\n\n$$\n(0.8229 - 1.645 \\times 0.039, \\; 0.8229 + 1.645 \\times 0.039) = (0.7587, \\; 0.8871)\n$$\n\n## 신뢰 구간 해석하기\n\n신뢰 구간을 성공적으로 계산했다면, 남은 것은 그 의미를 올바르게 해석하는 것입니다. 앞서 우리는 구간이 '옳다'는 개념을 확률적으로 정의했습니다. 일반적으로 어떤 모수에 대해 $(1-\\alpha) \\times 100\\%$ 신뢰 구간을 산출했다면, 이는 '우리가 방금 계산한 이 구체적인 구간이 모수의 참값을 포함하고 있을 것이라고 $(1-\\alpha) \\times 100\\%$만큼 확신한다(confident)'는 뜻입니다.\n\n방금 구한 미국인 직업 만족도 비율에 대한 90\\% 신뢰 구간 $(0.7587, 0.8871)$을 예로 들어 해석해 보겠습니다. 우리는 이 결과를 \"구간 (0.7587, 0.8871)이 자신의 직업에 만족하는 전체 미국인의 참 비율 $p$를 포함하고 있다는 것에 대해 90\\% 확신합니다\"라고 명확히 서술해야 합니다.\n\n$p$-값과 마찬가지로, 신뢰 구간에도 실무자들이 흔히 저지르는 치명적인 오역들이 존재합니다. 통계적 엄밀성을 지키기 위해, 자주 등장하는 잘못된 해석들을 짚어보고 왜 틀렸는지 분명히 하겠습니다.\n\n- 오류 1: \"참 모수 값이 이 구간(0.7587 ~ 0.8871) 안에 존재할 확률이 90\\%이다.\"\n  - 이유: 매우 흔한 착각입니다. 모수 $p$는 이미 세상에 고정되어 있는 단일 상수이며 주사위처럼 확률적으로 변하지 않습니다. 특정 구간(숫자)이 주어졌을 때 모수가 그 안에 있거나(확률 100%) 없거나(확률 0%) 둘 중 하나일 뿐입니다. '90\\%의 확률'은 모수가 아니라 우리의 '구간 산출 방식(표본 추출 과정)'에 부여되는 것입니다.\n\n- 오류 2: \"모수 값이 제시된 구간과 일치할 것이라고 90\\% 확신한다.\"\n  - 이유: 모수는 특정한 '하나의 값'이며, 범위 형태인 구간과 '같을(Equal)' 수는 없습니다. 모수는 구간 안에 '포함'되는 것입니다.\n\n- 오류 3: \"전체 모집단 개인 중 90%가 이 구간 안의 값을 가진다.\"\n  - 이유: 신뢰 구간은 모집단에 속한 '개인들의 분포'를 나타내는 것이 아니라, 전체를 요약하는 '단 하나의 모집단 모수(전체 평균이나 비율)'가 어디쯤 있을지 추정하는 도구입니다.\n\n- 오류 4: \"앞으로 표본 통계량을 다시 계산하면 90%의 경우 이 구간(0.7587 ~ 0.8871) 안에 들어올 것이다.\"\n  - 이유: 미래에 추출될 표본 통계량의 변동 범위를 예측하는 것은 '예측 구간(prediction interval)'의 역할입니다. 신뢰 구간은 '참 모수'의 위치를 추정하기 위한 것입니다.\n\n## 연습 문제\n\n2016년 퓨 리서치 센터(Pew Research Center)는 미국인들을 대상으로 반대 정당에 대한 의견을 묻는 설문 조사를 실시했습니다. 조사 결과 응답자의 45%가 상대 정당에 대해 \"우호적이지 않은(Unfavorable)\" 견해를 가지고 있었으며, 이 표본 비율에 대한 표준 오차는 $\\text{s.e.}(\\hat{p}) = 0.007$이었습니다.\n\n1. 전체 미국인 비율 $p$에 대한 90% 신뢰 구간을 계산하고, 그 결과를 올바른 형식으로 해석하십시오.\n\n2. $p$에 대한 95% 신뢰 구간을 계산하고 해석하십시오.\n\n3. $p$에 대한 99% 신뢰 구간을 계산하고 해석하십시오.\n\n4. $p$에 대한 99.5% 신뢰 구간을 계산하고 해석하십시오.\n\n2019년 퓨 리서치 센터는 미국인들을 대상으로 \"화석 연료 생산 확대보다 재생 에너지원 개발에 집중하는 것이 더 중요한 국가적 우선순위인가?\"라고 묻는 조사를 진행했습니다. 그 결과 77%가 그렇다고 응답했으며, 표준 오차는 $\\text{s.e.}(\\hat{p}) = 0.007$이었습니다.\n\n5. 이 견해를 가진 미국인의 참 비율 $p$에 대한 80% 신뢰 구간을 구하고 해석하십시오.\n\n6. $p$에 대한 90% 신뢰 구간을 구하고 해석하십시오.\n\n7. $p$에 대한 95% 신뢰 구간을 구하고 해석하십시오.\n\n## 신뢰 구간을 보고할 때 함께 말해야 할 것\n\n신뢰 구간(confidence interval)은 결론을 단 하나의 불확실한 숫자로 고정하지 않고, 표본 추출에 따른 내재적 변동성을 정직하게 반영하여 '타당한 값들의 범위'를 통째로 제시하는 도구입니다. 그러나 단순히 숫자 두 개로 이루어진 구간만 덩그러니 제시하면 정보로서의 가치가 떨어집니다. 어떤 모수를 추정하기 위한 구간인지, 신뢰 수준은 얼마로 설정했는지, 어떤 표본 통계량과 표준 오차를 기반으로 산출했는지를 반드시 함께 명시해야 합니다.\n\n전문적인 통계 분석 보고서는 보통 다음의 구조를 따릅니다.\n\n1. 목표 명시: 추정하고자 하는 모집단 모수(전체 유권자의 참 지지율)가 무엇인지 명확히 밝힙니다.\n\n2. 방법론 요약: 사용한 표본 통계량과 표준 오차, 그리고 적용된 정규 근사 등의 방법론적 근거를 간략히 설명합니다.\n\n3. 결과 제시: 사전에 설정한 신뢰 수준과 계산된 신뢰 구간을 명확하게 제시합니다.\n\n4. 맥락적 해석: 연구나 비즈니스 맥락에서 그 구간이 허용하는 타당한 결론과, 오역으로 이어질 수 있는 잘못된 결론을 주의 깊게 분리하여 서술합니다.\n\n예를 들어, 어느 대도시에 도입될 새로운 모빌리티 정책의 찬성 비율에 대한 95% 신뢰 구간이 47%에서 53%(0.47 ~ 0.53)로 나타났다고 가정해 봅시다. 이 경우 구간 내에 50% 미만의 값이 포함되어 있으므로, 단순히 과반이 찬성한다고 단정 짓기에는 증거가 불충분합니다. 반대로 신뢰 구간 전체가 50%를 훌쩍 넘는다면, 이는 단일 점 추정값(찬성 55%) 하나를 제시할 때보다 훨씬 강력하고 설득력 있는 정책 추진 근거가 됩니다. 신뢰 구간의 진정한 힘은 불확실성을 감추는 데 있는 것이 아니라, 그 불확실성의 크기를 과학적으로 수치화하여 투명하게 드러내는 데 있습니다.\n\n## R을 활용한 실습: 신뢰 구간 계산\n\nR을 활용하여 비율에 대한 신뢰 구간을 계산하는 방법을 알아보겠습니다. 앞서 다룬 1996년 미국 종합 사회 조사(General Social Survey) 예제를 R 코드로 구현해 보겠습니다.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# 1. 수동으로 신뢰 구간 계산하기\nn <- 96           # 표본 크기\nx <- 79           # 만족한다고 응답한 사람 수\np_hat <- x / n    # 표본 비율\nalpha <- 0.1      # 유의 수준 (90% 신뢰 수준)\n\n# 임계값 z* 계산\nz_star <- qnorm(1 - alpha / 2)\n\n# 표준 오차(SE) 계산 (비율의 표준 오차 공식 사용)\nse <- sqrt(p_hat * (1 - p_hat) / n)\n\n# 오차 한계(Margin of Error) 계산\nmargin_of_error <- z_star * se\n\n# 신뢰 구간 하한과 상한\nlower_bound <- p_hat - margin_of_error\nupper_bound <- p_hat + margin_of_error\n\ncat(\"90% 신뢰 구간: (\", round(lower_bound, 4), \", \", round(upper_bound, 4), \")\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n90% 신뢰 구간: ( 0.7588 ,  0.887 )\n```\n\n\n:::\n:::\n\n\n위 코드는 수식을 그대로 코드로 옮긴 것입니다. R에서는 `prop.test()` 함수를 사용하여 더 간단하게 비율에 대한 신뢰 구간과 가설 검정을 동시에 수행할 수 있습니다.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# 2. prop.test() 함수를 활용한 신뢰 구간 계산\nresult <- prop.test(x = 79, n = 96, conf.level = 0.90, correct = FALSE)\nresult$conf.int\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 0.7502477 0.8778831\nattr(,\"conf.level\")\n[1] 0.9\n```\n\n\n:::\n:::\n\n\n`prop.test()`의 출력 결과에 포함된 `conf.int` 속성을 통해 90% 신뢰 구간을 쉽게 확인할 수 있습니다. `correct = FALSE`는 연속성 수정(Yates' continuity correction)을 적용하지 않음을 의미합니다.\n\n다만 한 가지 주의할 점이 있습니다. `prop.test()`는 위에서 손으로 계산한 발드(Wald) 구간이 아니라 윌슨 점수(Wilson score) 구간을 계산합니다. 따라서 `correct = FALSE`를 지정해도 수동 계산 결과와 정확히 일치하지 않으며, 이 예제에서는 $(0.7502, 0.8779)$가 출력되어 수동 계산값 $(0.7587, 0.8871)$과 소수 둘째 자리부터 차이가 납니다. `correct` 인자는 연속성 수정만 제거할 뿐 계산 방식을 발드 구간으로 바꾸지는 않습니다. 두 구간의 차이는 $\\hat{p}$이 0.5에서 멀수록, 그리고 표본이 작을수록 커집니다.\n",
    "supporting": [],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}