{
  "hash": "2fffb802ef6a74b164904097e97889a2",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: \"통계적 추론\"\n---\n\n> 2025-2026년 현재, 생성형 AI(Generative AI)가 쏟아내는 텍스트 로그나 수백만 건의 사용자 상호작용(interaction) 데이터를 다루는 현대의 실무 환경에서는 데이터 세트가 매우 방대하고 복잡합니다. 수십만 개의 관측값(observation)을 손으로 직접 계산하여 추론하는 것은 사실상 불가능에 가깝습니다. 다행히도 R 통계 소프트웨어는 탐색적 데이터 분석(exploratory data analysis)과 시각화 도구를 제공할 뿐만 아니라, 우리가 논의한 모든 가설 검정과 신뢰 구간에 대해 확률과 $p$-값($p$-value)을 눈 깜짝할 사이에 계산해 줍니다. \n\n## 올바른 검정 선택하기\n\n가설 검정을 수행할 때 가장 중요한 첫 단추는 '어떤 검정 기법을 사용할 것인가'를 정확히 판단하는 일입니다. 이를 결정하기 위해서는 분석하고자 하는 반응 변수(response)와 표본(sample)의 특성을 파악해야 하며, 이는 다음 세 가지 질문으로 압축됩니다.\n\n1. 우리의 반응 변수가 범주형(categorical)입니까, 아니면 양적(quantitative) 데이터입니까?\n2. 분석하려는 데이터에 하나 또는 두 개의 표본이 존재합니까?\n3. 표본이 두 개인 경우, 두 표본이 서로 철저히 독립적입니까(independent)? 즉, 표본 사이에 교집합이나 짝지어진 연결 고리가 존재합니까?\n\n이 질문들을 하나씩 짚어보겠습니다. 먼저 반응 변수의 성격부터 살펴보아야 합니다. 범주형 반응 변수를 다룰 때는 비율에 관한 검정인 단일 표본 비율 검정과 두 표본 비율 검정을 사용합니다. 반면 연속적인 양적 반응 변수를 분석할 때는 평균에 관한 검정인 단일 표본 $t$-검정(t-test), 두 표본 $t$-검정, 그리고 대응 $t$-검정(paired $t$-test)을 활용합니다.\n\n둘째, 데이터에 포함된 표본의 개수를 확인합니다. 명칭에서 알 수 있듯 두 표본 비율 검정, 평균에 대한 두 표본 $t$-검정, 평균에 대한 대응 $t$-검정은 모두 두 개의 표본 그룹을 비교합니다. 반면 단일 표본 비율 검정과 평균에 대한 단일 표본 $t$-검정은 오직 하나의 데이터 표본만을 대상으로 합니다.\n\n마지막으로, 두 개의 표본을 다룰 때는 표본 간의 독립성을 반드시 고려해야 합니다. 앞서 언급한 두 표본 검정 중 '대응 $t$-검정'만이 유일하게 독립성을 전제하지 않습니다. 이 검정에서는 동일한 피험자가 두 가지 처치를 모두 경험하는 등 두 표본 사이에 명백한 중복이나 직접적인 연결 고리가 존재합니다. 이 질문들의 흐름을 따라가다 보면 주어진 상황에 가장 알맞은 검정 방법을 자연스럽게 도출할 수 있습니다.\n\n## 비율에 대한 추론\n\n우리는 비율을 다루는 두 가지 가설 검정을 학습했습니다. 단일 표본 비율 검정은 단일 모집단 비율(population proportion)이 특정 기준값과 같은지 검정하는 기법입니다. 반면 두 표본 비율 검정은 두 집단의 모집단 비율이 서로 동일한지, 아니면 차이가 있는지 확인하는 데 쓰입니다. 신뢰 구간 역시 이와 완벽히 짝을 이룹니다. 모집단 비율 p에 대한 $(1-\\alpha)$ 100% 신뢰 구간은 단일 집단의 비율을 추정하며, $p_1-p_2$에 대한 $(1-\\alpha)$ 100% 신뢰 구간은 두 집단의 비율 차이가 가질 수 있는 타당한 값의 범위를 제시합니다.\n\n결과적으로 우리는 비율 추론을 위해 총 4가지(2개의 검정과 2개의 신뢰 구간) 선택지를 지니고 있습니다. 다행히 R에서는 이 모든 추론을 단 하나의 함수인 `prop.test`로 통합하여 간결하게 처리할 수 있습니다. 단일 표본을 분석하느냐, 두 표본을 분석하느냐에 따라 함수에 입력하는 코드 구조만 약간 바뀔 뿐입니다. 먼저 단일 표본 비율 검정부터 살펴보겠습니다.\n\n### 단일 비율에 대한 추론\n\n단일 표본 비율 검정 시 `prop.test` 함수는 다섯 개의 인자(argument)를 입력받습니다. 표본 내 성공 횟수 `x`, 전체 표본 크기 `n`, 귀무 가설(null hypothesis)의 기준값 `p`, 대립 가설(alternative hypothesis)의 방향을 정하는 `alternative`, 그리고 연속성 수정(continuity correction) 적용 여부를 묻는 `correct`입니다.\n\n```r\nprop.test(x = x, n = n, p = p, alternative = alternative, correct = correct)\n```\n\n이 함수를 다룰 때 두 가지 주의할 점이 있습니다. 첫째, `correct` 인자는 연속성 수정을 적용할지 결정하는 TRUE/FALSE 논리값입니다. 표본이 작을 때 중심 극한 정리(central limit theorem)의 근사를 돕기 위해 간혹 사용되지만, 현대 통계 분석에서는 이 보정이 과도하여 결과를 왜곡할 위험이 있다고 평가합니다. 따라서 우리는 모든 실습에서 이 옵션을 `FALSE`로 설정하겠습니다. 둘째, `alternative` 인자는 세 가지 대립 가설 형태에 맞추어 다음 중 하나를 선택해야 합니다.\n\n| $H_A$ | R-코드 |\n| --- | --- |\n| $H_A:\\rho < p_0$ | alternative = \"less\" |\n| $H_A:\\rho > p_0$ | alternative = \"greater\" |\n| $H_A:\\rho \\neq p_0$ | alternative = \"two.sided\" |\n\n이전 장에서 단일 표본 비율 검정의 단계를 학습할 때 다루었던 예제를 R로 구현해 보겠습니다. 우리는 스위트 브라이어 칼리지(Sweet Briar College)의 동문 자녀(legacy) 학생 비율이 전국 평균인 14\\%와 통계적으로 다른지 궁금했습니다. 이를 확인하고자 79명의 학생 표본을 조사했고, 그중 12명이 동문 자녀임을 확인했습니다. 이때 설정한 가설은 다음과 같습니다.\n\n$$\n\\begin{aligned}\nH_0: \\rho = 0.14\nH_A: \\rho \\neq 0.14\n\\end{aligned}\n$$\n\n이 검정을 R에서 수행하려면 성공 횟수 $x=12$, 표본 크기 $n=79$, 귀무 값 $p=0.14$, 그리고 대립 가설 `alternative = \"two.sided\"`가 필요합니다. 실무에서는 자동화된 데이터 파이프라인에서 추출한 csv 파일을 R로 불러온 뒤 `table` 함수를 이용해 성공 횟수를 동적으로 집계하는 방식이 흔히 쓰입니다. 여기서는 직접 값을 입력하여 검정을 수행해 보겠습니다.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nprop.test(\n  x = 12,\n  n = 79,\n  p = 0.14,\n  alternative = \"two.sided\",\n  correct = FALSE\n)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n\t1-sample proportions test without continuity correction\n\ndata:  12 out of 79, null probability 0.14\nX-squared = 0.092897, df = 1, p-value = 0.7605\nalternative hypothesis: true p is not equal to 0.14\n95 percent confidence interval:\n 0.08908268 0.24699854\nsample estimates:\n        p \n0.1518987 \n```\n\n\n:::\n:::\n\n\n명령을 실행하면 R은 가설 검정과 관련된 상세한 결과 보고서를 출력합니다.\n\n출력 결과에는 분석가에게 유용한 통계적 단서들이 가득합니다. 가장 먼저 눈에 띄는 값은 `X-squared`인데, 이는 우리가 익숙한 z-검정 통계량(test statistic)을 제곱한 값입니다. 만약 손으로 직접 검정 통계량 $z$를 계산했다면, $\\hat{p}=0.1519$가 귀무값 0.14보다 크므로 $X-squared$의 양의 제곱근인 $+0.0929=0.3048$을 얻었을 것입니다. `prop.test`가 굳이 검정 통계량의 제곱을 출력하는 이유는, 이 함수가 더 복잡한 통계 모델인 '카이제곱 검정(chi-squared test)'의 논리를 내부적으로 차용하고 있기 때문입니다. 사실 $z^2$은 자유도가 1인 카이제곱 분포를 따르므로 두 검정은 본질적으로 동일한 결과를 냅니다.\n\n다음으로 산출된 `$p$-value`는 0.7605입니다. 이는 실무에서 통용되는 그 어떤 유의 수준(significance level) 기준선(0.05)보다도 아득히 높은 수치입니다. 따라서 귀무 가설을 기각할 수 없으며, 앞서 손으로 단계별 계산을 수행했을 때 도출한 결론과 완벽하게 일치합니다.\n\nR의 출력 결과 하단을 유심히 살펴보면, 가설 검정 결과와 짝을 이루는 p에 대한 95% 신뢰 구간이 보너스처럼 제공됩니다. 만약 연구 목적상 90\\%나 99\\%처럼 다른 신뢰 수준이 필요하다면 어떻게 해야 할까요? `prop.test` 함수에는 `conf.level`이라는 추가 인자가 준비되어 있어 원하는 신뢰 수준을 자유롭게 지정할 수 있습니다.\n\n```r\nprop.test(x = x, n = n, p = p, alternative = alternative, correct = correct, conf.level = conf.level)\n```\n\n이 `conf.level`의 기본값은 0.95입니다. 만약 90\\% 신뢰 구간이 필요하다면 `conf.level=0.9`로, 99\\%가 필요하다면 `conf.level=0.99`로 명시하기만 하면 됩니다. 앞선 예제에서 p에 대한 99\\% 신뢰 구간을 도출하기 위해 코드를 수정하면 $(0.07538655, 0.28235191)$이라는 구간을 새롭게 얻을 수 있습니다. 여기서 반드시 명심해야 할 핵심 규칙이 하나 있습니다. 단일 표본 분석 시 R이 '정상적인' 양방향 신뢰 구간을 반환하게 하려면, `alternative` 옵션을 반드시 `\"two.sided\"`로 설정해야 합니다. 만약 이를 지키지 않으면 R은 대립 가설의 방향성에 맞추어 한쪽이 무한대(또는 0)로 열려 있는 잘못된 한쪽 꼬리 구간을 반환할 것입니다.\n\n### 두 비율에 대한 추론\n\n단일 표본을 넘어 이제 두 표본의 경우를 살펴보겠습니다. 앞서 `prop.test` 함수가 두 표본 검정에도 동일하게 쓰인다고 언급했는데, 실제 코드 구조도 놀라울 만큼 흡사합니다. 두 표본을 비교할 때 필요한 인자는 두 집단 각각의 성공 횟수를 담은 `x`, 두 집단의 표본 크기를 담은 `n`, 대립 가설 `alternative`, 연속성 수정 `correct`, 그리고 신뢰 수준 `conf.level`입니다.\n\n```r\nprop.test(x = x, n = n, alternative = alternative, correct = correct, conf.level = conf.level)\n```\n\n가장 큰 변화는 `x`와 `n`에 입력하는 데이터의 형태입니다. 단일 표본일 때는 하나의 숫자만 입력했지만, 지금은 두 집단을 다루므로 `x`와 `n` 모두에 두 개의 숫자가 묶인 벡터(vector) 구조를 전달해야 합니다. 이때 `x`에 입력한 성공 횟수의 순서와 `n`에 입력한 표본 크기의 순서가 반드시 일치해야 합니다. 또한, 이 순서는 대립 가설 옵션에도 직접적인 영향을 미칩니다. 예를 들어 `\"greater\"` 옵션은 $H_A:\\rho_1 > \\rho_2$를 의미하는데, 여기서 첫 번째 집단 $\\rho_1$은 오직 `x`와 `n` 벡터의 '첫 번째 자리'에 입력된 데이터로만 결정됩니다. 순서가 뒤바뀌면 분석 결과의 부호가 완전히 반전되므로 각별히 주의해야 합니다.\n\n실습을 위해 퓨 리서치 그룹(pew research group)의 밀레니얼 세대(millennial)와 x세대(generation x) 비교 설문 데이터를 다시 불러오겠습니다. 연구진은 두 세대에게 미국이 우주 탐사 분야에서 선도적인 위치를 지키는 것이 필수적인지 물었습니다. 밀레니얼 세대 667명 중 467명이 \"그렇다\"고 답했고, x세대 558명 중 407명 역시 긍정했습니다. 우리는 이 두 세대 간 응답 비율의 차이가 통계적으로 유의미한지 검증하고자 합니다. 가설은 다음과 같이 설정됩니다.\n\n$$\n\\begin{aligned}\nH_0: &\\rho_{\\text{Millenial}}-\\rho_{\\text{Gen}}X = 0\\\\\nH_A: &\\rho_{\\text{Millenial}}-\\rho_{\\text{Gen}}X \\neq 0\n\\end{aligned}\n$$\n\n이에 따라 성공 횟수 벡터는 $x=c(467,407)$로, 표본 크기 벡터는 $n=c(667,558)$로 구성됩니다. 이를 R 코드로 조합하면 아래와 같습니다.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nprop.test(\n  x = c(467, 407),\n  n = c(667, 558),\n  alternative = \"two.sided\",\n  correct = FALSE\n)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n\t2-sample test for equality of proportions without continuity correction\n\ndata:  c(467, 407) out of c(667, 558)\nX-squared = 1.2707, df = 1, p-value = 0.2596\nalternative hypothesis: two.sided\n95 percent confidence interval:\n -0.07991559  0.02143408\nsample estimates:\n   prop 1    prop 2 \n0.7001499 0.7293907 \n```\n\n\n:::\n:::\n\n\n코드를 실행하면 다음과 같은 결과가 출력됩니다. 앞서 설명했듯 실제 z-검정 통계량은 출력된 `X-squared` 값의 제곱근을 취한 뒤, $\\hat{p}_1$과 $\\hat{p}_2$의 대소 관계에 따라 부호를 결정합니다. 이 데이터에서는 $\\hat{p}_1 < \\hat{p}_2$이므로, 음의 제곱근인 $-1.2707 = -1.127$이 검정 통계량이 됩니다. 최종 산출된 $p$-값은 0.2596으로 0.05 유의 수준을 훌쩍 넘기므로, 귀무 가설을 기각할 충분한 통계적 근거를 찾지 못했습니다.\n\n\n단일 표본 때와 마찬가지로 `conf.level`을 조정하여 $p_1-p_2$에 대한 신뢰 구간을 자유롭게 변경할 수 있습니다. 예를 들어 $p_{Millenial}-p_{GenX}$에 대한 90\\% 신뢰 구간이 필요하다면 코드 인자에 `conf.level=0.9`를 추가하기만 하면 됩니다. 그 결과 $(-0.07176842, 0.01328690)$이라는 구간을 손쉽게 얻을 수 있습니다.\n\n### 연습 문제\n\n1. 성별에 따라 왼손잡이 비율이 다른지 알아보고자 설문 조사를 진행했습니다. 조사 결과 여성 117명 중 7명, 남성 118명 중 10명이 왼손잡이였습니다. 유의 수준 $\\alpha=0.1$ 하에서 $H_A:p_F - p_M \\neq 0$인 가설 검정을 수행하고, $p_F - p_M$에 대한 87% 신뢰 구간을 산출해 보십시오.\n\n2. 2018년 퓨 리서치 그룹이 미국인 1,500명을 조사한 결과, 705명이 중국에 대해 부정적인 인식을 가진 것으로 나타났습니다. 유의 수준 $\\alpha=0.05$ 하에서 $H_A:p<0.5$인 가설 검정을 진행하고, p에 대한 93% 신뢰 구간을 도출해 보십시오.\n\n3. 1987년의 한 사회학 연구에 따르면, 대학 진학 경험이 있는 기혼 여성 212명 중 171명의 남편도 대학에 진학했습니다. 반면 대학 진학 경험이 없는 아내 541명 중에서는 124명의 남편만이 대학에 진학했습니다. 유의 수준 $\\alpha=0.05$ 하에서 $H_A:p_{WifeCollege}-p_{WifeNone}>0$ 가설 검정을 수행해 주십시오. 덧붙여 $p_{WifeCollege}-p_{WifeNone}$에 대한 98% 신뢰 구간도 산출해 보십시오.\n\n4. 앞선 설문 조사 데이터에서 기혼 여성 753명 중 428명이 경제 활동에 적극적으로 참여하고 있음을 파악했습니다. 유의 수준 $\\alpha=0.01$ 하에서 $H_A:p>0.5$ 가설 검정을 수행하고, 모집단 비율 p에 대한 84% 신뢰 구간을 구해 보십시오.\n\n## 평균에 대한 추론\n\n비율 검정과 더불어, 우리는 모집단 평균과 관련된 단일 표본 $t$-검정, 두 표본 $t$-검정, 그리고 대응표본 $t$-검정이라는 핵심 추론 기법들을 마스터했습니다. 비율 검정 시 `prop.test` 하나로 모든 변형을 포괄했던 것처럼, 평균과 관련된 모든 추론 역시 R의 `t.test`라는 단일 함수로 우아하게 해결할 수 있습니다. 각 검정 상황에 맞추어 `t.test` 함수의 코드를 어떻게 변형하여 적용하는지 체계적으로 살펴보겠습니다.\n\n### 단일 평균에 대한 추론\n\n평균에 대한 단일 표본 $t$-검정 상황에서 `t.test` 함수는 세 가지 필수 인자를 요구합니다. 분석할 원시 데이터가 담긴 표본 벡터 `x`, 귀무 가설이 주장하는 수치인 `mu`, 그리고 대립 가설의 논리적 방향성을 지시하는 `alternative`입니다.\n\n```r\nt.test(x = x, mu = mu, alternative = alternative)\n```\n\n여기서 `x`는 엑셀 파일 등에서 데이터 프레임(data frame) 형태로 불러온 특정 열(column)이거나 R 콘솔에 직접 입력한 숫자 벡터입니다. `mu`는 `prop.test`의 `p` 인자와 같은 역할을 하며 귀무 가설의 기준점을 정의합니다. 마지막으로 `alternative` 인자는 비율 검정과 완벽하게 동일한 규칙을 따릅니다.\n\n| $H_A$ | R-코드 |\n| --- | --- |\n| $H_A:\\mu < \\mu 0$ | alternative = \"less\" |\n| $H_A:\\mu > \\mu 0$ | alternative = \"greater\" |\n| $H_A:\\mu \\neq \\mu 0$ | alternative = \"two.sided\" |\n\n이해를 돕기 위해 비디오 슬롯 머신(video slot machine)의 환수율을 분석했던 예제로 되돌아가 보겠습니다. 우리는 기계의 평균 지불금(payout)이 이론상 지불금인 13.13달러보다 통계적으로 적거나 같은지 검증하고자 했습니다. 해당 실측 데이터는 DAAG 라이브러리의 `vlt` 데이터 세트에 저장되어 있으며, 345회 게임의 개별 지불 금액은 `prize` 변수에 기록되어 있습니다. 이를 R로 검정하는 코드는 매우 직관적입니다.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(DAAG)\ndata(vlt, package = \"DAAG\")\n\nt.test(\n  x = vlt$prize,\n  mu = 13.13,\n  alternative = \"less\"\n)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n\tOne Sample t-test\n\ndata:  vlt$prize\nt = -90.718, df = 344, p-value < 2.2e-16\nalternative hypothesis: true mean is less than 13.13\n95 percent confidence interval:\n      -Inf 0.8989483\nsample estimates:\nmean of x \n0.6724638 \n```\n\n\n:::\n:::\n\n\n코드를 실행하면 R은 단일 표본 $t$-검정에 관한 포괄적인 분석 보고서를 반환합니다. 출력된 `t` 값은 우리가 익숙한 공식을 손으로 풀어 계산했을 때 나오는 검정 통계량과 정확히 일치합니다. `df`는 이 검정 모델의 자유도(degrees of freedom)이며 표본 크기에서 1을 뺀 값($n-1$)으로 계산되었습니다. 계산된 `$p$-value`는 매우 극단적으로 작게 산출되어 이론적 지불금을 하회한다는 대립 가설을 강력히 뒷받침합니다.\n\n가설 검정과 함께 `t.test` 함수는 기본적으로 모평균 μ에 대한 95% 신뢰 구간을 계산하여 출력해 줍니다. 만약 분석 보고서의 요구 사항에 따라 95%가 아닌 다른 신뢰 수준이 필요하다면, 앞서 배운 `conf.level` 인자를 코드에 슬쩍 추가해 주기만 하면 됩니다.\n\n```r\nt.test(x = x, mu = 0, alternative = alternative, conf.level = conf.level)\n```\n\n여기서도 잊지 말아야 할 철칙이 있습니다. 우리가 익히 아는 양방향 신뢰 구간을 획득하려면, 분석의 주 목적이 한쪽 꼬리 가설 검정이었다 하더라도 구간 추정 시에는 `alternative = \"two.sided\"`로 명시해야 합니다. 만약 기계의 실제 평균 지불금에 대한 99% 신뢰 구간을 엄밀하게 도출하고 싶다면 아래와 같이 코드를 수정해야 하며, 그 결과 $(0.3167728, 1.0281548)$이라는 견고한 신뢰 구간을 획득하게 됩니다.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nt.test(\n  x = vlt$prize,\n  mu = 13.13,\n  alternative = \"two.sided\",\n  conf.level = 0.99\n)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n\tOne Sample t-test\n\ndata:  vlt$prize\nt = -90.718, df = 344, p-value < 2.2e-16\nalternative hypothesis: true mean is not equal to 13.13\n99 percent confidence interval:\n 0.3167728 1.0281548\nsample estimates:\nmean of x \n0.6724638 \n```\n\n\n:::\n:::\n\n\n### 두 평균에 대한 추론\n\n평균에 대한 두 표본 $t$-검정의 핵심 목표는 두 집단의 모집단 평균 간에 통계적으로 유의미한 차이가 존재하는지 판별하는 것입니다. R에서는 단일 표본 `t.test` 코드에 몇 가지 인자를 영리하게 덧붙이는 것만으로 이 복잡한 검정을 즉각 수행할 수 있습니다. 추가되는 핵심 인자는 두 번째 집단의 데이터를 담을 벡터 `y`, 귀무값 0의 생략(두 표본 검정에서는 차이가 0이라는 점이 기본값이므로), 그리고 두 집단의 분산(variance) 동일성 여부를 R 엔진에 알려주는 `var.equal` (TRUE/FALSE) 논리 인자입니다. \n\n```r\nt.test(x = x, y = y, alternative = alternative, var.equal = var_equal)\n```\n\n구체적인 응용을 위해 사회 심리학 분야의 동조(conformity) 실험 데이터를 다시 불러오겠습니다. 해당 데이터는 carData 라이브러리의 `Moore` 데이터 세트에 잘 정돈되어 있습니다 [48,59]. 우리는 지위가 높은 파트너(high status)가 지위가 낮은 파트너(low status)보다 상대방으로부터 더 강한 동조를 끌어내는지 양적 데이터로 검정하고자 했습니다. 가설은 $H_0:\\mu_{High}-\\mu_{Low}=0$ 대 $H_A:\\mu_{High}-\\mu_{Low}>0$입니다. 사전에 분산 비율 $s_1^2/s_2^2 = 27.855/19.087 = 1.459$를 확인하여 분산이 대체로 유사하다(등분산)는 결론을 내렸으므로, `var.equal = TRUE` 인자를 당당히 활성화할 수 있습니다.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(carData)\ndata(Moore, package = \"carData\")\n\nt.test(\n  x = Moore$conformity[Moore$partner.status == \"high\"],\n  y = Moore$conformity[Moore$partner.status == \"low\"],\n  alternative = \"greater\",\n  var.equal = TRUE\n)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n\tTwo Sample t-test\n\ndata:  Moore$conformity[Moore$partner.status == \"high\"] and Moore$conformity[Moore$partner.status == \"low\"]\nt = 2.957, df = 43, p-value = 0.002515\nalternative hypothesis: true difference in means is greater than 0\n95 percent confidence interval:\n 1.839379      Inf\nsample estimates:\nmean of x mean of y \n14.217391  9.954545 \n```\n\n\n:::\n:::\n\n\nR 엔진은 즉각 연산을 수행하고, 단일 표본 때와 유사한 구조의 명쾌한 결과 보고서를 터미널에 출력합니다. 산출된 검정 통계량 2.957과 $p$-값 0.002515를 확인해 보십시오. 이 수치들은 복잡한 공식을 이용해 손으로 계산했던 과거의 결괏값과 한 치의 오차도 없이 완벽히 들어맞습니다.\n\n이 함수 역시 95% 신뢰 구간을 덤으로 제공하지만, 단방향 가설(`alternative=\"greater\"`)로 인해 상한선이 무한대(Inf)로 열려 있는 것을 볼 수 있습니다. 온전한 양방향 신뢰 구간을 원한다면 인자를 `alternative = \"two.sided\"`로 교체하고 원하는 `conf.level`을 명시하면 됩니다. 만약 $\\mu_{High}-\\mu_{Low}$에 대한 98\\% 신뢰 구간을 추출하고 싶다면 해당 인자들을 조합하여 코드를 실행하고, 결과로 $(0.7795, 7.7462)$를 얻을 수 있습니다.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nt.test(\n  x = Moore$conformity[Moore$partner.status == \"high\"],\n  y = Moore$conformity[Moore$partner.status == \"low\"],\n  alternative = \"two.sided\",\n  var.equal = TRUE,\n  conf.level = 0.98\n)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n\tTwo Sample t-test\n\ndata:  Moore$conformity[Moore$partner.status == \"high\"] and Moore$conformity[Moore$partner.status == \"low\"]\nt = 2.957, df = 43, p-value = 0.005029\nalternative hypothesis: true difference in means is not equal to 0\n98 percent confidence interval:\n 0.7795282 7.7461635\nsample estimates:\nmean of x mean of y \n14.217391  9.954545 \n```\n\n\n:::\n:::\n\n\n### 평균에 대한 대응 추론\n\n우리가 정복해야 할 마지막 추론의 봉우리는 평균에 대한 대응 추론(Paired inference)입니다. 이 기법은 분석 데이터가 서로 긴밀하게 짝지어져 있어(paired data) 표본 간 독립성 가정이 근본적으로 깨질 때 사용됩니다. 환자의 투약 전후 상태 비교처럼 피험자가 두 집단에 중복해서 등장하거나, 오차를 줄이기 위해 의도적으로 조건이 유사한 대상을 쌍으로 매칭시킨 경우가 이에 해당합니다.\n\n놀랍게도 `t.test` 함수 하나로 이 특수한 시나리오까지 완벽히 커버할 수 있습니다. 두 표본 벡터 `x`와 `y`, 그리고 `alternative` 옵션을 준비하는 것까지는 독립 표본 때와 동일합니다. 하지만 R이 이 데이터를 무턱대고 독립적인 두 표본으로 취급하지 못하도록, 분석의 성격을 확실히 규정짓는 `paired = TRUE` 인자를 반드시 선언해야 합니다.\n\n```r\nt.test(x = x, y = y, alternative = alternative, paired = TRUE)\n```\n\n대응 $t$-검정을 수행할 때 가장 치명적이고 흔한 실수는 `x`와 `y` 벡터의 데이터 정렬 순서가 어긋나는 것입니다. 두 벡터는 완벽히 1:1로 매칭되는 쌍이어야 하므로, 벡터의 길이가 반드시 같아야 하고 배열 순서상 동일한 인덱스에 위치한 데이터가 서로 정확히 짝을 이루어야 합니다. 만약 이 전제 조건이 무너지면 R은 오류 메시지를 뱉어내거나, 아무 경고 없이 완전히 왜곡된 엉터리 결괏값을 반환할 위험이 큽니다. \n\n기네스 양조장의 통계학자 고셋(Student)이 분석했던 역사적인 수면 연장 데이터 예시를 R 코드로 구현해 보겠습니다 [17]. 이 데이터는 R 기초 패키지의 `sleep` 데이터 세트에 고스란히 담겨 있습니다. 우리는 덱스트로(Dextro)와 레보(Laevo)라는 두 수면제 간 약효 차이가 실재하는지 파악하고자 양측 검정($H_0:\\mu_{D}=0$ 대 $H_A:\\mu_D \\neq 0$)을 기획했습니다. \n\n\n::: {.cell}\n\n```{.r .cell-code}\nt.test(\n  x = sleep$extra[sleep$group == 1],\n  y = sleep$extra[sleep$group == 2],\n  alternative = \"two.sided\",\n  paired = TRUE\n)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n\tPaired t-test\n\ndata:  sleep$extra[sleep$group == 1] and sleep$extra[sleep$group == 2]\nt = -4.0621, df = 9, p-value = 0.002833\nalternative hypothesis: true mean difference is not equal to 0\n95 percent confidence interval:\n -2.4598858 -0.7001142\nsample estimates:\nmean difference \n          -1.58 \n```\n\n\n:::\n:::\n\n\n결과 창에는 \"Paired t-test\"라는 타이틀과 함께 검정 통계량 t, 자유도 df, 그리고 $p$-값이 깔끔하게 정돈되어 출력됩니다. 이 결과 역시 과거 우리가 계산기를 두드려가며 도출했던 수작업 결과와 놀랍도록 일치합니다.\n\n가설 검정 수치와 더불어, 출력 화면 하단에는 쌍을 이룬 차이의 모평균 $\\mu_{D}$에 대한 95\\% 신뢰 구간이 당당히 자리 잡고 있습니다. 이 역시 `conf.level` 인자를 삽입하여 손쉽게 조작할 수 있습니다. 만약 $\\mu_{D}$에 대한 90\\% 신뢰 구간이 절실하다면 다음 코드를 실행하여 $(-2.2930053, -0.8669947)$이라는 정밀한 구간을 획득하십시오.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nt.test(\n  x = sleep$extra[sleep$group == 1],\n  y = sleep$extra[sleep$group == 2],\n  alternative = \"two.sided\",\n  paired = TRUE,\n  conf.level = 0.9\n)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n\tPaired t-test\n\ndata:  sleep$extra[sleep$group == 1] and sleep$extra[sleep$group == 2]\nt = -4.0621, df = 9, p-value = 0.002833\nalternative hypothesis: true mean difference is not equal to 0\n90 percent confidence interval:\n -2.2930053 -0.8669947\nsample estimates:\nmean difference \n          -1.58 \n```\n\n\n:::\n:::\n\n\n### 연습 문제\n\n5. MASS 라이브러리의 DDT 데이터 세트를 활용하여, 해당 샘플들의 DDT 수치가 유의 수준 $\\alpha=0.01$ 하에서 3 ppm 기준치를 초과하는지 엄밀히 검정하고 99% 신뢰 구간을 도출해 보십시오.\n\n6. DAAG 라이브러리의 `monica` 데이터 세트는 심장 마비 환자들의 코호트 관찰 데이터를 담고 있습니다. 유의 수준 $\\alpha=0.05$ 하에서 심혈관 질환 최초 발병 연령(age)이 남성(sex) 그룹에서 여성 그룹보다 더 이른(낮은) 경향을 띠는지 통계적으로 검증하십시오. 추가로 90% 신뢰 구간도 산출해 보십시오.\n\n7. `boot` 라이브러리의 `cd4` 데이터 세트는 HIV 양성 환자들의 면역 체계를 임상 시험 초기(baseline)와 신약 복용 1년 후(oneyear)에 각각 추적 관찰한 기록입니다. 신약 복용 후 환자들의 모집단 평균 CD4 수치가 1년 전과 비교하여 유의미하게 감소했는지 대응표본 검정으로 확인하고, 60% 신뢰 구간을 시범적으로 도출해 보십시오.\n\n8. carData 라이브러리의 `Guyer` 데이터 세트는 집단의 의사결정 방식(공개 투표 vs 익명 투표)이 집단 구성원 간의 협력(cooperation)에 미치는 영향을 기록했습니다. 두 투표 시스템(condition) 하에서 협력적 결정의 모집단 평균이 동일한지 상이한지 양측 검정으로 파악하고, $\\mu_{Anon}-\\mu_{Pub}$에 대한 97% 신뢰 구간을 산출해 보십시오.\n\n9. DAAG 라이브러리의 `pair65` 데이터 세트는 물리적 가열 처리 유무가 고무줄의 신축성(동일한 무게를 매달았을 때 늘어난 길이)에 미치는 영향을 실험한 자료입니다. 고무줄들은 초기 탄성 계수가 유사한 개체들끼리 한 쌍으로 묶여 각각 가열 처리(heated)와 상온 유지(ambient) 처리를 받았습니다. 두 그룹 간 모집단 평균 신축성에 유의미한 차이가 있는지 정밀 검정해 보십시오.\n\n## 추론 결과를 재사용 가능한 객체로 다루기\n\nR이 제공하는 검정 함수들의 진정한 강력함은 결과를 단순히 화면에 텍스트로 뿌려주는 데 그치지 않고, 그 결과 전체를 메모리상에 '구조화된 객체(Object)' 형태로 저장할 수 있다는 데 있습니다. 대규모 데이터를 처리하는 현대의 자동화 파이프라인이나 AI 기반 데이터 리포팅 시스템에서는 검정 결과를 객체로 저장한 뒤, 필요한 $p$-값이나 신뢰 구간 수치만 스크립트로 쏙쏙 뽑아 쓰는 방식이 필수적입니다. 이 방식은 인간의 수작업 복사-붙여넣기 과정에서 필연적으로 발생하는 오타를 원천 차단합니다.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nprop_result <- prop.test(\n  x = 12,\n  n = 79,\n  p = 0.14,\n  alternative = \"two.sided\",\n  correct = FALSE,\n  conf.level = 0.95\n)\n\nprop_result$p.value\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 0.7605259\n```\n\n\n:::\n\n```{.r .cell-code}\nprop_result$estimate\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n        p \n0.1518987 \n```\n\n\n:::\n\n```{.r .cell-code}\nprop_result$conf.int\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 0.08908268 0.24699854\nattr(,\"conf.level\")\n[1] 0.95\n```\n\n\n:::\n:::\n\n\n`t.test()` 함수의 반환값 역시 동일한 문법으로 다룰 수 있습니다. 이러한 코딩 습관은 수십 개의 변수를 순회하며 검정을 반복해야 하는 시뮬레이션 연구에서 빛을 발합니다. $p$-값을 리포트에 손으로 하드코딩해 두면 나중에 원본 데이터가 업데이트되었을 때 문서의 수치가 과거 상태로 방치되는 심각한 재현성(Reproducibility) 위기가 발생합니다. 반면, 객체에서 값을 동적으로 추출하여 R Markdown 등에 연결해 두면, 데이터-분석 코드-최종 리포트 사이의 단단한 연결 고리가 영구히 유지됩니다.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nt_result <- t.test(\n  x = sleep$extra[sleep$group == 1],\n  y = sleep$extra[sleep$group == 2],\n  paired = TRUE,\n  alternative = \"two.sided\",\n  conf.level = 0.90\n)\n\nt_result$p.value\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 0.00283289\n```\n\n\n:::\n\n```{.r .cell-code}\nt_result$conf.int\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] -2.2930053 -0.8669947\nattr(,\"conf.level\")\n[1] 0.9\n```\n\n\n:::\n:::\n\n\n수많은 집단이나 피처(feature)에 대해 동일한 검정 로직을 반복 적용해야 한다면, 무작정 코드를 짜기보다 먼저 데이터 구조를 정갈하게 전처리(tidy)해야 합니다. 어떤 변수 간의 비교가 실제 비즈니스나 연구 질문에 정확히 부합하는지 전략적으로 결정한 뒤에야 반복 루프를 작성하십시오. 기계적으로 검정을 남발하는 자동화 능력보다 훨씬 중요한 통계학자의 덕목은, 불필요하고 무의미한 다중 비교(multiple comparisons)를 억제하는 정교한 실험 설계 능력을 갖추는 것입니다.\n",
    "supporting": [],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}