<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.10.18">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>단일 모수(Single parameter)에 대한 가설 검정 – R과 데이터 분석 입문</title>
<style>
/* Default styles provided by pandoc.
** See https://pandoc.org/MANUAL.html#variables-for-html for config info.
*/
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: 1.5em;}
div.column{flex: auto;}
@media screen {
div.columns{gap: min(4vw, 1.5em);}
div.column{overflow-x: auto;}
}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
html { -webkit-text-size-adjust: 100%; }
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="../../site_libs/quarto-nav/quarto-nav.js"></script>
<script src="../../site_libs/quarto-nav/headroom.min.js"></script>
<script src="../../site_libs/clipboard/clipboard.min.js"></script>
<script src="../../site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="../../site_libs/quarto-search/fuse.min.js"></script>
<script src="../../site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="../../">
<script src="../../site_libs/quarto-html/quarto.js" type="module"></script>
<script src="../../site_libs/quarto-html/tabsets/tabsets.js" type="module"></script>
<script src="../../site_libs/quarto-html/popper.min.js"></script>
<script src="../../site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="../../site_libs/quarto-html/anchor.min.js"></script>
<link href="../../site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="../../site_libs/quarto-html/quarto-syntax-highlighting-64a204ab8560d761af7679ceaba22944.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="../../site_libs/bootstrap/bootstrap.min.js"></script>
<link href="../../site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="../../site_libs/bootstrap/bootstrap-d55203e86ba1a699a1ae3c3642d34712.min.css" rel="stylesheet" append-hash="true" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "sidebar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "start",
  "type": "textbox",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>

  <script src="https://cdnjs.cloudflare.com/polyfill/v3/polyfill.min.js?features=es6"></script>
  <script defer="" src="https://cdn.jsdelivr.net/npm/mathjax@4/tex-chtml.js" type="text/javascript"></script>

<script type="text/javascript">
const typesetMath = (el) => {
  if (window.MathJax) {
    // MathJax Typeset
    window.MathJax.typeset([el]);
  } else if (window.katex) {
    // KaTeX Render
    var mathElements = el.getElementsByClassName("math");
    var macros = [];
    for (var i = 0; i < mathElements.length; i++) {
      var texText = mathElements[i].firstChild;
      if (mathElements[i].tagName == "SPAN" && texText && texText.data) {
        window.katex.render(texText.data, mathElements[i], {
          displayMode: mathElements[i].classList.contains('display'),
          throwOnError: false,
          macros: macros,
          fleqn: false
        });
      }
    }
  }
}
window.Quarto = {
  typesetMath
};
</script>

<meta property="og:title" content="단일 모수(Single parameter)에 대한 가설 검정 – R과 데이터 분석 입문">
<meta property="og:description" content="">
<meta property="og:site_name" content="R과 데이터 분석 입문">
<meta name="twitter:title" content="단일 모수(Single parameter)에 대한 가설 검정 – R과 데이터 분석 입문">
<meta name="twitter:description" content="">
<meta name="twitter:card" content="summary">
</head>

<body class="nav-sidebar docked quarto-light">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
  <nav class="quarto-secondary-nav">
    <div class="container-fluid d-flex">
      <button type="button" class="quarto-btn-toggle btn" data-bs-toggle="collapse" role="button" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
        <i class="bi bi-layout-text-sidebar-reverse"></i>
      </button>
        <nav class="quarto-page-breadcrumbs" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item">
      R과 데이터 분석 입문
      </li></ol></nav>
        <a class="flex-grow-1" role="navigation" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">      
        </a>
      <button type="button" class="btn quarto-search-button" aria-label="Search" onclick="window.quartoOpenSearch();">
        <i class="bi bi-search"></i>
      </button>
    </div>
  </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article">
<!-- sidebar -->
  <nav id="quarto-sidebar" class="sidebar collapse collapse-horizontal quarto-sidebar-collapse-item sidebar-navigation docked overflow-auto">
    <div class="pt-lg-2 mt-2 text-left sidebar-header">
    <div class="sidebar-title mb-0 py-0">
      <a href="../../">R과 데이터 분석 입문</a> 
        <div class="sidebar-tools-main">
  <a href="" class="quarto-reader-toggle quarto-navigation-tool px-1" onclick="window.quartoToggleReader(); return false;" title="Toggle reader mode">
  <div class="quarto-reader-toggle-btn">
  <i class="bi"></i>
  </div>
</a>
</div>
    </div>
      </div>
        <div class="mt-2 flex-shrink-0 align-items-center">
        <div class="sidebar-search">
        <div id="quarto-search" class="" title="Search"></div>
        </div>
        </div>
    <div class="sidebar-menu-container"> 
    <ul class="list-unstyled mt-1">
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">R 언어</span></a>
  </div>
</li>
    </ul>
    </div>
</nav>
<div id="quarto-sidebar-glass" class="quarto-sidebar-collapse-item" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item"></div>
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">On this page</h2>
   
  <ul>
  <li><a href="#비율에-대한-일표본-검정" id="toc-비율에-대한-일표본-검정" class="nav-link active" data-scroll-target="#비율에-대한-일표본-검정"><span class="header-section-number">1</span> 비율에 대한 일표본 검정</a>
  <ul class="collapse">
  <li><a href="#단계-가설-설정" id="toc-단계-가설-설정" class="nav-link" data-scroll-target="#단계-가설-설정"><span class="header-section-number">1.1</span> 1단계: 가설 설정</a></li>
  <li><a href="#단계-유의-수준-설정" id="toc-단계-유의-수준-설정" class="nav-link" data-scroll-target="#단계-유의-수준-설정"><span class="header-section-number">1.2</span> 2단계: 유의 수준 설정</a></li>
  <li><a href="#단계-데이터-수집-및-요약" id="toc-단계-데이터-수집-및-요약" class="nav-link" data-scroll-target="#단계-데이터-수집-및-요약"><span class="header-section-number">1.3</span> 3단계: 데이터 수집 및 요약</a></li>
  <li><a href="#단계-검정-통계량-계산" id="toc-단계-검정-통계량-계산" class="nav-link" data-scroll-target="#단계-검정-통계량-계산"><span class="header-section-number">1.4</span> 4단계: 검정 통계량 계산</a></li>
  <li><a href="#단계-p-값-계산" id="toc-단계-p-값-계산" class="nav-link" data-scroll-target="#단계-p-값-계산"><span class="header-section-number">1.5</span> 5단계: <span class="math inline">\(p\)</span>-값 계산</a></li>
  <li><a href="#단계-결론-도출" id="toc-단계-결론-도출" class="nav-link" data-scroll-target="#단계-결론-도출"><span class="header-section-number">1.6</span> 6단계: 결론 도출</a></li>
  <li><a href="#연습-문제" id="toc-연습-문제" class="nav-link" data-scroll-target="#연습-문제"><span class="header-section-number">1.7</span> 연습 문제</a></li>
  </ul></li>
  <li><a href="#평균에-대한-일표본-t-검정" id="toc-평균에-대한-일표본-t-검정" class="nav-link" data-scroll-target="#평균에-대한-일표본-t-검정"><span class="header-section-number">2</span> 평균에 대한 일표본 <span class="math inline">\(t\)</span>-검정</a>
  <ul class="collapse">
  <li><a href="#단계-가설-설정-1" id="toc-단계-가설-설정-1" class="nav-link" data-scroll-target="#단계-가설-설정-1"><span class="header-section-number">2.1</span> 1단계: 가설 설정</a></li>
  <li><a href="#단계-유의-수준-설정-1" id="toc-단계-유의-수준-설정-1" class="nav-link" data-scroll-target="#단계-유의-수준-설정-1"><span class="header-section-number">2.2</span> 2단계: 유의 수준 설정</a></li>
  <li><a href="#단계-데이터-수집-및-요약-1" id="toc-단계-데이터-수집-및-요약-1" class="nav-link" data-scroll-target="#단계-데이터-수집-및-요약-1"><span class="header-section-number">2.3</span> 3단계: 데이터 수집 및 요약</a></li>
  <li><a href="#단계-검정-통계량-계산-1" id="toc-단계-검정-통계량-계산-1" class="nav-link" data-scroll-target="#단계-검정-통계량-계산-1"><span class="header-section-number">2.4</span> 4단계: 검정 통계량 계산</a></li>
  <li><a href="#단계-p-값-계산-1" id="toc-단계-p-값-계산-1" class="nav-link" data-scroll-target="#단계-p-값-계산-1"><span class="header-section-number">2.5</span> 5단계: <span class="math inline">\(p\)</span>-값 계산</a></li>
  <li><a href="#단계-결론-도출-1" id="toc-단계-결론-도출-1" class="nav-link" data-scroll-target="#단계-결론-도출-1"><span class="header-section-number">2.6</span> 6단계: 결론 도출</a></li>
  <li><a href="#연습-문제-1" id="toc-연습-문제-1" class="nav-link" data-scroll-target="#연습-문제-1"><span class="header-section-number">2.7</span> 연습 문제</a></li>
  </ul></li>
  <li><a href="#단일-모수-검정에서-효과-크기를-함께-보기" id="toc-단일-모수-검정에서-효과-크기를-함께-보기" class="nav-link" data-scroll-target="#단일-모수-검정에서-효과-크기를-함께-보기"><span class="header-section-number">3</span> 단일 모수 검정에서 효과 크기를 함께 보기</a></li>
  <li><a href="#결론" id="toc-결론" class="nav-link" data-scroll-target="#결론"><span class="header-section-number">4</span> 결론</a></li>
  </ul>
</nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">단일 모수(Single parameter)에 대한 가설 검정</h1>
</div>



<div class="quarto-title-meta">

    
  
    
  </div>
  


</header>


<blockquote class="blockquote">
<p>지난 몇 장에 걸쳐 우리는 가설 검정과 신뢰 구간(confidence interval)의 핵심 원리를 다루며 통계적 추론(statistical inference)을 위한 이론적 토대를 마련했습니다. 이 장에서는 이전 장들에서 미처 다루지 못했던 세부 계산 과정들을 채워가며, 가설 검정의 전체 과정을 실무적으로 살펴보겠습니다. 특히 이번 장에서는 일표본 검정(one-sample test)에 집중합니다. 일표본 가설 검정은 오직 하나의 모수(parameter)와 관련된 질문에 답하기 위해 사용됩니다. 예를 들어, 주어진 동전이 완벽히 공정한가(즉 <span class="math inline">\(p=0.5\)</span>인가) 하는 문제들이 이에 해당합니다.</p>
</blockquote>
<p>데이터 분석은 논리적 과학인 동시에 직관이 필요한 예술적 과정이기도 합니다. 그러나 가설 검정만큼은 어떤 상황에서든 정해진 단계를 엄격히 밟아나가는 매우 체계적인 절차입니다. 표준적인 가설 검정은 다음의 6단계를 거치며, 본 장은 물론 향후 여러 장에서 새로운 검정 기법을 배울 때마다 이 틀을 동일하게 적용할 것입니다.</p>
<ol type="1">
<li>가설 설정</li>
<li>유의 수준 설정</li>
<li>데이터 수집 및 요약</li>
<li>검정 통계량 계산</li>
<li><span class="math inline">\(p\)</span>-값 계산</li>
<li>결론 도출</li>
</ol>
<p>이번 장에서 다룰 일표본 검정에는 ’모집단 비율 <span class="math inline">\(p\)</span>에 대한 일표본 검정’과 ’모집단 평균 <span class="math inline">\(\mu\)</span>에 대한 일표본 검정’이 포함됩니다. 먼저 우리에게 조금 더 익숙한 비율 검정부터 시작하겠습니다.</p>
<section id="비율에-대한-일표본-검정" class="level2" data-number="1">
<h2 data-number="1" class="anchored" data-anchor-id="비율에-대한-일표본-검정"><span class="header-section-number">1</span> 비율에 대한 일표본 검정</h2>
<p>비율에 대한 일표본 검정은 관심 있는 모집단의 비율이 특정 기준값과 같은지, 혹은 다른지를 판단하기 위해 사용되는 가설 검정입니다. 이 검정은 ’비율’을 다루기 때문에 응답 변수가 범주형(categorical response, 찬성/반대, 성공/실패)일 때만 사용할 수 있습니다. 이를 통해 동전이나 주사위가 공정한지, 특정 정책에 찬성하는 유권자가 절반을 넘는지 등 다양한 사회적 질문에 통계적으로 답할 수 있습니다.</p>
<p>가설 검정의 6단계를 구체적인 예시와 함께 짚어보겠습니다.</p>
<p>미국 대학 입시에서 동문 자녀(legacy students)는 종종 주요 고려 요소가 됩니다. 전국적으로 전체 대학생의 약 14%가 동문 자녀 전형으로 입학한다고 알려져 있습니다. 스위트 브라이어 대학(Sweet Briar College)의 동문 자녀 학생 비율이 이 전국 평균(14%)과 유의미하게 다른지 검증해 보고자 합니다. 우리의 응답 데이터는 학생이 동문 자녀인지 아닌지를 나타내는 ’범주형’이며, 분석 대상 그룹이 하나뿐이므로 비율에 대한 일표본 검정이 적합합니다.</p>
<section id="단계-가설-설정" class="level3" data-number="1.1">
<h3 data-number="1.1" class="anchored" data-anchor-id="단계-가설-설정"><span class="header-section-number">1.1</span> 1단계: 가설 설정</h3>
<p>가설 설정 단계에서는 분석하고자 하는 모수와 그 모수가 특정 기준값과 맺는 관계를 수식으로 명확히 선언해야 합니다. 귀무 가설(null hypothesis)은 ‘현재 상태(status quo)’ 또는 ’데이터에 아무런 특별한 변화나 차이가 없다’는 기본 가정을 나타내며 주로 <span class="math inline">\(H_0 : p = p_0\)</span>의 형태를 띱니다. 대립 가설(alternative hypothesis)은 귀무 가설과 모순되는 주장으로, 연구자의 관심 방향에 따라 다음 세 가지 중 하나로 설정됩니다: 단측 검정인 <span class="math inline">\(H_A : p &gt; p_0\)</span> 또는 <span class="math inline">\(H_A : p &lt; p_0\)</span>, 양측 검정인 <span class="math inline">\(H_A : p \neq p_0\)</span>.</p>
<p>우리의 예시에서는 스위트 브라이어 대학의 참 동문 자녀 비율이 0.14(14%)와 ‘같은지’ 혹은 ’다른지’를 확인하고자 하므로 양측 검정 가설을 설정합니다.</p>
<p><span class="math display">\[
\begin{aligned}
H_0 &amp;: p = 0.14 \\
H_A &amp;: p \neq 0.14
\end{aligned}
\]</span></p>
</section>
<section id="단계-유의-수준-설정" class="level3" data-number="1.2">
<h3 data-number="1.2" class="anchored" data-anchor-id="단계-유의-수준-설정"><span class="header-section-number">1.2</span> 2단계: 유의 수준 설정</h3>
<p>유의 수준(significance level) <span class="math inline">\(\alpha\)</span>는 가설 검정의 최종 결론을 판가름하는 기준선이자, 귀무 가설을 기각하기 위한 ’합리적인 의심’의 허들입니다. <span class="math inline">\(\alpha\)</span>를 낮게 설정하면 증거가 매우 강력해야만 귀무 가설을 기각할 수 있고, <span class="math inline">\(\alpha\)</span>가 높으면 상대적으로 쉽게 기각할 수 있습니다. 유의 수준은 귀무 가설이 실제로 참임에도 불구하고 실수로 기각해 버리는 제1종 오류(Type I error)를 범할 최대 허용 확률입니다. 학문 분야에 따라 기준이 다를 수 있으나, 일반적으로는 <span class="math inline">\(\alpha = 0.05\)</span>를 널리 사용합니다.</p>
<p>중요한 점은 유의 수준 <span class="math inline">\(\alpha\)</span>를 데이터 수집이나 분석을 시작하기 ‘전에’ 미리 확정해야 한다는 것입니다. 데이터를 먼저 들여다본 뒤 결과가 유의미하게 나오도록 <span class="math inline">\(\alpha\)</span>를 사후에 조정하는 행위는 심각한 연구 부정행위(p-hacking)에 해당하며 분석의 신뢰성을 완전히 무너뜨립니다. 이를 막기 위해 여러 분야에서는 분석 계획과 임계값을 실험 전에 공개 등록하는 사전 등록(preregistration) 제도를 운영합니다. 스위트 브라이어 대학 예시에서는 1종 오류가 초래할 특별히 치명적인 비용이 없으므로 표준적인 <span class="math inline">\(\alpha = 0.05\)</span>를 사용하겠습니다.</p>
</section>
<section id="단계-데이터-수집-및-요약" class="level3" data-number="1.3">
<h3 data-number="1.3" class="anchored" data-anchor-id="단계-데이터-수집-및-요약"><span class="header-section-number">1.3</span> 3단계: 데이터 수집 및 요약</h3>
<p>실제 데이터 수집 과정은 통계학의 범위를 넘어서는 연구 방법론의 영역이지만, 수집된 데이터를 적절히 요약하는 것은 분석의 핵심입니다. 비율에 대한 일표본 검정을 위해서는 두 가지 핵심 요약치가 필요합니다. 첫째는 관측된 표본 비율(sample proportion) <span class="math inline">\(\hat{p}\)</span>로, 이는 귀무 가설 기준값 <span class="math inline">\(p_0\)</span>에서 실제로 얼마나 벗어나 있는지 보여줍니다. 둘째는 표본 크기(sample size) <span class="math inline">\(n\)</span>입니다. 표본 크기는 검정 통계량 계산의 분모 역할을 하는 표준 오차(standard error)를 결정짓는 핵심 요소이기 때문입니다.</p>
<p>이 예시에서는 스위트 브라이어 대학 학생 79명의 데이터를 임의 추출하여 조사한 결과, 12명이 동문 자녀임이 확인되었습니다. 따라서 표본 크기는 <span class="math inline">\(n=79\)</span>이고 표본 비율은 <span class="math inline">\(\hat{p} = 12 / 79 \approx 0.1519\)</span>입니다.</p>
</section>
<section id="단계-검정-통계량-계산" class="level3" data-number="1.4">
<h3 data-number="1.4" class="anchored" data-anchor-id="단계-검정-통계량-계산"><span class="header-section-number">1.4</span> 4단계: 검정 통계량 계산</h3>
<p>지난 장에서 살펴보았듯, 검정 통계량(test statistic)은 관측된 표본 통계량이 귀무 가설 기준값으로부터 ‘표준 오차의 몇 배만큼’ 떨어져 있는지를 계산한 척도입니다.</p>
<p><span class="math display">\[
z = \frac{\text{표본 통계량} - \text{귀무 가설 값}}{\text{표준 오차}}
\]</span></p>
<p>비율 일표본 검정에서 표본 통계량은 <span class="math inline">\(\hat{p}\)</span>이고 귀무 가설 값은 <span class="math inline">\(p_0\)</span>입니다. 표준 정규분포와 직접 비교하는 통계량이므로 관례에 따라 <span class="math inline">\(z\)</span>로 표기합니다. 이를 대입하면 다음과 같습니다.</p>
<p><span class="math display">\[
z = \frac{\hat{p} - p_0}{\text{s.e.}(\hat{p})}
\]</span></p>
<p>문제는 표본 비율의 표준 오차 <span class="math inline">\(\text{s.e.}(\hat{p})\)</span>를 구하는 공식이 다음과 같다는 점입니다.</p>
<p><span class="math display">\[
\text{s.e.}(\hat{p}) = \sqrt{\frac{p(1-p)}{n}}
\]</span></p>
<p>여기서 <span class="math inline">\(p\)</span>는 모집단 참 비율인데, 우리는 그 진짜 값을 모릅니다. 이것이 미지수라면 표준 오차를 계산할 수 없어 분석이 벽에 부딪힌 것처럼 보입니다. 다행히 가설 검정의 기본 전제가 해결책을 제시해 줍니다. 우리는 반증되기 전까지는 ’귀무 가설이 완벽하게 참(<span class="math inline">\(p = p_0\)</span>)’이라고 굳게 가정하고 계산을 진행합니다. 따라서 미지의 참값 <span class="math inline">\(p\)</span> 자리에 귀무 가설 값 <span class="math inline">\(p_0\)</span>를 과감하게 대입할 수 있습니다.</p>
<p><span class="math display">\[
\text{s.e.}(\hat{p}) = \sqrt{\frac{p_0(1-p_0)}{n}}
\]</span></p>
<p>모든 요소를 종합하면 비율 일표본 검정의 최종 검정 통계량 공식은 다음과 같습니다.</p>
<p><span class="math display">\[
z = \frac{\hat{p} - p_0}{\sqrt{\frac{p_0(1-p_0)}{n}}}
\]</span></p>
<p>스위트 브라이어 예시의 데이터(<span class="math inline">\(p_0=0.14\)</span>, <span class="math inline">\(\hat{p}=0.1519\)</span>, <span class="math inline">\(n=79\)</span>)를 공식에 대입하여 계산해 보겠습니다.</p>
<p><span class="math display">\[
z = \frac{0.1519 - 0.14}{\sqrt{\frac{0.14(1-0.14)}{79}}} \approx 0.3048
\]</span></p>
</section>
<section id="단계-p-값-계산" class="level3" data-number="1.5">
<h3 data-number="1.5" class="anchored" data-anchor-id="단계-p-값-계산"><span class="header-section-number">1.5</span> 5단계: <span class="math inline">\(p\)</span>-값 계산</h3>
<p>검정 통계량을 확보했으니 이제 <span class="math inline">\(p\)</span>-값을 계산할 차례입니다. <span class="math inline">\(p\)</span>-값은 ’귀무 가설이 참이라고 가정할 때, 관측된 것 이상으로 극단적인 데이터가 나올 확률’을 뜻하며, ’더 극단적’이라는 방향의 정의는 오로지 대립 가설(<span class="math inline">\(H_A\)</span>)의 형태에 따라 결정됩니다. 이전 장에서 도출한 바와 같이, 중심극한정리에 의해 표본 비율은 정규분포를 따르므로 표준화된 검정 통계량 <span class="math inline">\(z\)</span>를 표준 정규분포(<span class="math inline">\(N(0,1)\)</span>)에 적용하여 <span class="math inline">\(p\)</span>-값을 구할 수 있습니다.</p>
<table class="caption-top table">
<thead>
<tr class="header">
<th>대립 가설(<span class="math inline">\(H_A\)</span>)</th>
<th><span class="math inline">\(p\)</span>-값 공식</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td><span class="math inline">\(H_A : p &lt; p_0\)</span></td>
<td><span class="math inline">\(P(N(0,1) \le z)\)</span></td>
</tr>
<tr class="even">
<td><span class="math inline">\(H_A : p &gt; p_0\)</span></td>
<td><span class="math inline">\(P(N(0,1) \ge z)\)</span></td>
</tr>
<tr class="odd">
<td><span class="math inline">\(H_A : p \neq p_0\)</span></td>
<td><span class="math inline">\(2 \times P(N(0,1) \ge \vert z \vert)\)</span></td>
</tr>
</tbody>
</table>
<p>이 공식들이 수학적으로 유효하려면 표본 크기 <span class="math inline">\(n\)</span>이 충분히 커서 중심극한정리가 작동해야 합니다. 비율 검정에서 표본이 충분히 크다고 판단하는 경험적 기준은 (1) 표본 크기가 최소 30 이상이고, (2) 귀무 가설 기준 기대 성공 횟수(<span class="math inline">\(np_0\)</span>)와 기대 실패 횟수(<span class="math inline">\(n(1-p_0)\)</span>)가 각각 최소 10회 이상이어야 한다는 것입니다. 검정에서는 표준 오차에 <span class="math inline">\(p_0\)</span>를 대입하므로 이 조건도 <span class="math inline">\(p_0\)</span>를 기준으로 확인하며, 신뢰 구간에서는 <span class="math inline">\(\hat{p}\)</span>을 기준으로 확인한다는 점을 구별해 두십시오. 이 조건이 충족되면 표준 정규분포를 안심하고 사용할 수 있습니다.</p>
<p>R에서는 <code>pnorm</code> 함수를 통해 정규분포 확률을 계산합니다. 우리의 대립 가설은 <span class="math inline">\(H_A : p \neq 0.14\)</span>이므로 양측 검정 공식을 사용합니다. 검정 통계량 <span class="math inline">\(z = 0.3048\)</span>이므로, <span class="math inline">\(p\)</span>-값은 <span class="math inline">\(2 \times P(N(0,1) &gt; \vert 0.3048 \vert)\)</span>가 됩니다.</p>
<p>먼저 단측 확률을 R로 계산합니다.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb1"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="fu">pnorm</span>(<span class="at">q =</span> <span class="fl">0.3048</span>, <span class="at">mean =</span> <span class="dv">0</span>, <span class="at">sd =</span> <span class="dv">1</span>, <span class="at">lower.tail =</span> <span class="cn">FALSE</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0.3802592</code></pre>
</div>
</div>
<p>이 코드는 <span class="math inline">\(0.3802592\)</span>를 반환합니다. 따라서 최종 <span class="math inline">\(p\)</span>-값은 이 값을 두 배 한 <span class="math inline">\(2 \times 0.3802592 \approx 0.7605\)</span>가 됩니다.</p>
</section>
<section id="단계-결론-도출" class="level3" data-number="1.6">
<h3 data-number="1.6" class="anchored" data-anchor-id="단계-결론-도출"><span class="header-section-number">1.6</span> 6단계: 결론 도출</h3>
<p>가설 검정의 최종 결론은 항상 다음 세 가지 요소를 포함해야 합니다.</p>
<ol type="1">
<li>정당화(Justification): <span class="math inline">\(p\)</span>-값과 유의 수준 <span class="math inline">\(\alpha\)</span>의 명시적 비교</li>
<li>통계적 결과(Result): ‘귀무 가설 기각’ 또는 ‘기각 실패’ 선언</li>
<li>맥락(Context): 통계적 결과가 현실의 연구 질문에 대해 가지는 구체적 의미</li>
</ol>
<p>주의할 점은, 귀무 가설을 기각하는 데 실패했다고 해서 귀무 가설이 ’완벽한 참’이라고 선언할 수는 없다는 것입니다. 단지 귀무 가설이 ’여전히 타당하다(plausible)’고 조심스럽게 결론 내릴 뿐입니다.</p>
<p>스위트 브라이어 대학 예시의 결론을 작성해 보겠습니다. 계산된 <span class="math inline">\(p\)</span>-값 <span class="math inline">\(0.7605\)</span>는 설정된 유의 수준 <span class="math inline">\(\alpha=0.05\)</span>보다 훨씬 큽니다(정당화). 따라서 귀무 가설 기각에 실패합니다(통계적 결과). 이는 스위트 브라이어 대학의 참 동문 자녀 학생 비율이 전국 평균인 14%와 다르다고 볼 충분한 증거가 없으며, 14%와 같다는 주장이 타당함을 의미합니다(맥락).</p>
<p>전체 가설 검정 절차를 또 다른 예시로 신속히 복습해 보겠습니다. 2016년 3월 퓨 리서치(Pew Research) 여론조사 결과, 미국인의 57%가 연방 정부에 불만을 품고 있었습니다. 2017년 12월 후속 조사에서는 1503명의 표본 중 826명이 불만을 표시했습니다. 2017년에 정부에 불만을 느끼는 미국인의 참 비율이 이전 조사(57%)보다 ’감소’했는지 검정하고자 합니다.</p>
<ol type="1">
<li>가설 설정: <span class="math inline">\(H_0 : p = 0.57\)</span>, <span class="math inline">\(H_A : p &lt; 0.57\)</span></li>
<li>유의 수준: <span class="math inline">\(\alpha = 0.05\)</span></li>
<li>데이터 요약: 표본 비율 <span class="math inline">\(\hat{p} = 826/1503 \approx 0.5496\)</span>, 표본 크기 <span class="math inline">\(n = 1503\)</span></li>
<li>검정 통계량: <span class="math inline">\(z = \frac{\hat{p} - 0.57}{\sqrt{\frac{0.57 \times 0.43}{1503}}} \approx -1.600\)</span></li>
<li><span class="math inline">\(p\)</span>-값 계산: 단측 검정이므로 <span class="math inline">\(p\text{-값} = P(N(0,1) &lt; -1.600)\)</span></li>
</ol>
<p>여기서 <span class="math inline">\(\hat{p}\)</span>은 반올림하지 않은 원값 <span class="math inline">\(826/1503\)</span>을 그대로 대입해야 합니다. 반올림한 0.549를 쓰면 검정 통계량이 <span class="math inline">\(-1.644\)</span>로 계산되어 결론이 뒤바뀔 만큼 경계선에 가까워지므로, 중간 반올림은 피하는 것이 원칙입니다.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb3"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb3-1"><a href="#cb3-1" aria-hidden="true" tabindex="-1"></a>p_hat <span class="ot">&lt;-</span> <span class="dv">826</span> <span class="sc">/</span> <span class="dv">1503</span></span>
<span id="cb3-2"><a href="#cb3-2" aria-hidden="true" tabindex="-1"></a>z <span class="ot">&lt;-</span> (p_hat <span class="sc">-</span> <span class="fl">0.57</span>) <span class="sc">/</span> <span class="fu">sqrt</span>(<span class="fl">0.57</span> <span class="sc">*</span> <span class="fl">0.43</span> <span class="sc">/</span> <span class="dv">1503</span>)</span>
<span id="cb3-3"><a href="#cb3-3" aria-hidden="true" tabindex="-1"></a><span class="fu">pnorm</span>(<span class="at">q =</span> z, <span class="at">mean =</span> <span class="dv">0</span>, <span class="at">sd =</span> <span class="dv">1</span>, <span class="at">lower.tail =</span> <span class="cn">TRUE</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0.05479574</code></pre>
</div>
</div>
<p>계산 결과 <span class="math inline">\(p\)</span>-값은 약 <span class="math inline">\(0.0548\)</span>입니다.</p>
<ol start="6" type="1">
<li>결론: <span class="math inline">\(p\)</span>-값이 <span class="math inline">\(\alpha=0.05\)</span>보다 크므로 귀무 가설 기각에 실패합니다. 따라서 연방 정부에 불만을 품은 미국인 비율이 감소했다는 통계적으로 유의한 증거가 부족하며, 이전 수준인 57%가 유지되고 있다고 보는 것이 타당합니다.</li>
</ol>
<p>실무에서 이 번거로운 수작업은 R의 <code>prop.test</code> 함수 하나로 간편하게 처리할 수 있습니다. 자세한 함수 사용법은 17장에서 다루겠습니다.</p>
</section>
<section id="연습-문제" class="level3" data-number="1.7">
<h3 data-number="1.7" class="anchored" data-anchor-id="연습-문제"><span class="header-section-number">1.7</span> 연습 문제</h3>
<p>2014년 퓨 리서치 연구에 따르면 미국인의 68%가 모든 아동의 백신 접종 의무화에 찬성했습니다. 2017년, 백신 관련 대중의 인식이 변함에 따라 이 비율이 ’증가’했는지 검증하고자 합니다.</p>
<ol type="1">
<li><p>이 상황을 검정하기 위한 귀무 가설과 대립 가설을 설정하십시오.</p></li>
<li><p>2017년 조사에서 1549명 중 1270명이 찬성했습니다. 표본 비율을 계산하십시오.</p></li>
<li><p>귀무 가설과 데이터를 바탕으로 검정 통계량을 계산하십시오.</p></li>
<li><p>대립 가설의 방향에 맞는 <span class="math inline">\(p\)</span>-값을 도출하십시오.</p></li>
<li><p><span class="math inline">\(\alpha=0.05\)</span>일 때 어떤 최종 결론을 내릴 수 있습니까?</p></li>
</ol>
<p>일반적으로 전체 이메일 트래픽의 약 50%가 스팸으로 분류된다고 알려져 있습니다. 최근 이 비율에 어떤 ’변화(증가든 감소든)’가 생겼는지 검증하고 싶습니다.</p>
<ol start="6" type="1">
<li><p>귀무 가설과 대립 가설을 수식으로 표현하십시오.</p></li>
<li><p>276통의 샘플 이메일을 조사한 결과 122통이 스팸이었습니다. 표본 비율은 얼마입니까?</p></li>
<li><p>검정 통계량을 계산하십시오.</p></li>
<li><p><span class="math inline">\(p\)</span>-값을 구하십시오.</p></li>
<li><p><span class="math inline">\(\alpha=0.1\)</span>로 설정할 때, 어떤 결론을 내리시겠습니까?</p></li>
</ol>
<p>2011년 조사에서 미국인의 79%가 지난 1년간 최소 한 권의 책을 읽었다고 답했습니다. 2019년 조사에서는 1502명 중 1082명이 그렇다고 답했습니다.</p>
<ol start="11" type="1">
<li>2019년의 독서 인구 비율이 과거 기준인 79%에서 ’감소’했는지 <span class="math inline">\(\alpha=0.05\)</span> 수준에서 6단계를 거쳐 직접 가설 검정을 수행해 보십시오.</li>
</ol>
</section>
</section>
<section id="평균에-대한-일표본-t-검정" class="level2" data-number="2">
<h2 data-number="2" class="anchored" data-anchor-id="평균에-대한-일표본-t-검정"><span class="header-section-number">2</span> 평균에 대한 일표본 <span class="math inline">\(t\)</span>-검정</h2>
<p>비율에 대한 검정을 충분히 익혔으니, 이제 단일 평균(Mean)에 대한 가설 검정으로 넘어가겠습니다. 평균에 대한 일표본 <span class="math inline">\(t\)</span>-검정은 연속형 혹은 수치형 응답(Quantitative response) 데이터가 주어졌을 때, 모집단의 참 평균이 특정 기준값과 다른지 검증하는 도구입니다. 검정 절차 자체는 비율 검정에서 배운 동일한 6단계를 그대로 따릅니다.</p>
<p>새로운 예시를 통해 단계를 밟아보겠습니다. 빈 칸, 바(Bar), 더블 바, 트리플 바, 더블 다이아몬드, 체리, 7 등 7가지 결과를 가진 카지노의 비디오 슬롯 머신이 있습니다. 이 머신의 이론적인 실제 1회 평균 지급액은 <span class="math inline">\(\$13.13\)</span>으로 설계되어야 합법입니다.</p>
<section id="단계-가설-설정-1" class="level3" data-number="2.1">
<h3 data-number="2.1" class="anchored" data-anchor-id="단계-가설-설정-1"><span class="header-section-number">2.1</span> 1단계: 가설 설정</h3>
<p>이전과 마찬가지로 모수와 기준값의 관계를 설정합니다. 이번 검정의 관심 모수는 비율 <span class="math inline">\(p\)</span>가 아니라 모집단 평균 <span class="math inline">\(\mu\)</span>입니다. 귀무 가설은 머신이 설계대로 정상 작동한다는 기본 가정을 뜻하므로 <span class="math inline">\(H_0 : \mu = \mu_0\)</span>가 됩니다. 대립 가설은 조작을 의심하는 방향에 따라 <span class="math inline">\(H_A : \mu &gt; \mu_0\)</span>, <span class="math inline">\(H_A : \mu &lt; \mu_0\)</span>, <span class="math inline">\(H_A : \mu \neq \mu_0\)</span> 중 하나가 됩니다.</p>
<p>우리는 카지노 측이 슬롯 머신을 조작하여 평균 지급액을 이론적 가치(<span class="math inline">\(\$13.13\)</span>)보다 ‘더 적게’ 나오도록 만들었는지 의심하고 있습니다. 따라서 가설은 다음과 같습니다.</p>
<p><span class="math display">\[
\begin{aligned}
H_0 &amp;: \mu = 13.13 \\
H_A &amp;: \mu &lt; 13.13
\end{aligned}
\]</span></p>
</section>
<section id="단계-유의-수준-설정-1" class="level3" data-number="2.2">
<h3 data-number="2.2" class="anchored" data-anchor-id="단계-유의-수준-설정-1"><span class="header-section-number">2.2</span> 2단계: 유의 수준 설정</h3>
<p><span class="math inline">\(\alpha\)</span> 설정 기준은 앞서 충분히 논의했으므로 반복하지 않겠습니다. 데이터 수집 전 사전 설정 원칙에 따라 표준 유의 수준인 <span class="math inline">\(\alpha=0.05\)</span>를 채택하겠습니다.</p>
</section>
<section id="단계-데이터-수집-및-요약-1" class="level3" data-number="2.3">
<h3 data-number="2.3" class="anchored" data-anchor-id="단계-데이터-수집-및-요약-1"><span class="header-section-number">2.3</span> 3단계: 데이터 수집 및 요약</h3>
<p>비율 검정과 마찬가지로 표본 크기 <span class="math inline">\(n\)</span>이 필수적입니다. 더불어 모집단 평균 <span class="math inline">\(\mu\)</span>를 추정하기 위한 표본 평균 <span class="math inline">\(\bar{x}\)</span>가 필요합니다. 비율 검정과 결정적으로 다른 점은 데이터의 흩어짐(변동성)을 나타내는 표본 분산 <span class="math inline">\(s^2\)</span> 또는 표본 표준편차 <span class="math inline">\(s\)</span>를 반드시 계산해야 한다는 점입니다.</p>
<p>카지노 감독관이 해당 슬롯 머신에서 <span class="math inline">\(345\)</span>게임을 직접 플레이한 결과(표본 크기 <span class="math inline">\(n=345\)</span>), 표본 평균 지급액은 <span class="math inline">\(\bar{x} = 0.672\)</span>달러였고, 표본 표준편차는 <span class="math inline">\(s = 2.551\)</span>이었습니다. (실제 데이터 요약치입니다.)</p>
</section>
<section id="단계-검정-통계량-계산-1" class="level3" data-number="2.4">
<h3 data-number="2.4" class="anchored" data-anchor-id="단계-검정-통계량-계산-1"><span class="header-section-number">2.4</span> 4단계: 검정 통계량 계산</h3>
<p>검정 통계량 <span class="math inline">\(t\)</span>의 기본 공식은 변하지 않습니다.</p>
<p><span class="math display">\[
t = \frac{\text{표본 통계량} - \text{귀무 가설 값}}{\text{표준 오차}}
\]</span></p>
<p>여기서 표본 통계량은 표본 평균 <span class="math inline">\(\bar{x}\)</span>이고 귀무 가설 값은 <span class="math inline">\(\mu_0\)</span>입니다. 표본 평균의 표준 오차는 분산의 기본 성질에 의해 다음과 같으며, 중심극한정리는 이와 별개로 <span class="math inline">\(\bar{x}\)</span>의 분포가 정규분포로 근사됨을 보장합니다.</p>
<p><span class="math display">\[
\text{s.e.}(\bar{x}) = \frac{\sigma}{\sqrt{n}}
\]</span></p>
<p>여기서 <span class="math inline">\(\sigma\)</span>는 전체 모집단의 진짜 표준편차입니다. 이 식들을 결합하면 초기 검정 통계량 형태가 나옵니다.</p>
<p><span class="math display">\[
t = \frac{\bar{x} - \mu_0}{\sigma / \sqrt{n}}
\]</span></p>
<p>이 공식에는 치명적인 모순이 숨어 있습니다. 우리는 모집단 평균 <span class="math inline">\(\mu\)</span>도 모르는 마당에 모집단 표준편차 <span class="math inline">\(\sigma\)</span>를 알 길이 전혀 없습니다. 비율 검정에서는 귀무 가설(<span class="math inline">\(p=p_0\)</span>)을 가정하여 이 문제를 우회할 수 있었지만, 평균 검정에서는 <span class="math inline">\(\mu=\mu_0\)</span>라고 가정한다고 해서 흩어짐을 나타내는 <span class="math inline">\(\sigma\)</span> 값을 알 수 있는 것은 아닙니다.</p>
<p>이 난관을 돌파하는 방법은 미지의 모수 <span class="math inline">\(\sigma\)</span> 자리에, 표본에서 직접 계산한 표본 표준편차 <span class="math inline">\(s\)</span>를 대신 대입하는 것입니다. 이렇게 수정된 최종 검정 통계량 공식은 다음과 같습니다.</p>
<p><span class="math display">\[
t = \frac{\bar{x} - \mu_0}{s / \sqrt{n}}
\]</span></p>
<p>슬롯 머신 데이터(<span class="math inline">\(\mu_0 = 13.13\)</span>, <span class="math inline">\(\bar{x} = 0.672\)</span>, <span class="math inline">\(s = 2.551\)</span>, <span class="math inline">\(n = 345\)</span>)를 대입하여 계산해 보겠습니다.</p>
<p><span class="math display">\[
t = \frac{0.672 - 13.13}{2.551 / \sqrt{345}} \approx -90.7084
\]</span></p>
</section>
<section id="단계-p-값-계산-1" class="level3" data-number="2.5">
<h3 data-number="2.5" class="anchored" data-anchor-id="단계-p-값-계산-1"><span class="header-section-number">2.5</span> 5단계: <span class="math inline">\(p\)</span>-값 계산</h3>
<p><span class="math inline">\(p\)</span>-값을 구하려면 우리가 계산한 검정 통계량 <span class="math inline">\(t\)</span>가 정확히 어떤 확률 분포(probability distribution)를 따르는지 알아야 합니다. 모집단이 정규분포이거나 표본이 충분히 크다는 전제 아래, 이론적으로 분모에 참 표준편차 <span class="math inline">\(\sigma\)</span>를 사용했다면 검정 통계량은 표준 정규분포 <span class="math inline">\(N(0,1)\)</span>을 따릅니다.</p>
<p>하지만 우리는 미지의 <span class="math inline">\(\sigma\)</span> 대신 표본 데이터로부터 추정한 <span class="math inline">\(s\)</span>를 땜질하듯 집어넣었습니다. 추정치 <span class="math inline">\(s\)</span> 자체에도 불확실성이 내재되어 있으므로, 우리의 검정 통계량은 꼬리 부분이 더 두꺼워져 표준 정규분포를 엄밀하게 따르지 않게 됩니다. 바로 이 지점에서 통계학의 위대한 발견 중 하나인 <span class="math inline">\(t\)</span>-분포(t-distribution)가 등장합니다.</p>
<section id="잠시-쉬어가기-t-분포" class="level4" data-number="2.5.1">
<h4 data-number="2.5.1" class="anchored" data-anchor-id="잠시-쉬어가기-t-분포"><span class="header-section-number">2.5.1</span> 잠시 쉬어가기: <span class="math inline">\(t\)</span>-분포</h4>
<p><span class="math inline">\(t\)</span>-분포는 모집단 평균 검정에 특화된 확률 분포입니다. 정규분포처럼 중앙이 볼록하고(unimodal) 완벽히 좌우 대칭이며, 중심은 항상 0입니다. 형태도 매우 유사하지만 정규분포보다 양극단의 꼬리가 두꺼워 극단값이 나타날 확률이 약간 더 높습니다(이는 <span class="math inline">\(s\)</span>를 사용하여 발생한 추가적인 불확실성을 반영한 것입니다).</p>
<p><span class="math inline">\(t\)</span>-분포는 정규분포의 평균이나 분산 대신, 자유도(degrees of freedom, <span class="math inline">\(df\)</span> 또는 <span class="math inline">\(\nu\)</span>로 표기)라는 단 하나의 매개변수에 의해 모양이 결정됩니다. 자유도가 커질수록 표본이 크다는 뜻이므로 불확실성이 줄어들어, <span class="math inline">\(t\)</span>-분포는 표준 정규분포와 거의 똑같아집니다. 수학적으로 자유도가 무한대(<span class="math inline">\(\nu = \infty\)</span>)가 되면 <span class="math inline">\(t\)</span>-분포는 표준 정규분포와 완벽히 일치합니다.</p>
</section>
<section id="p-값-계산으로-돌아가기" class="level4" data-number="2.5.2">
<h4 data-number="2.5.2" class="anchored" data-anchor-id="p-값-계산으로-돌아가기"><span class="header-section-number">2.5.2</span> <span class="math inline">\(p\)</span>-값 계산으로 돌아가기</h4>
<p>모집단이 정규분포를 따르거나 표본이 충분히 크다면, 우리가 4단계에서 <span class="math inline">\(s\)</span>를 대입하여 만든 검정 통계량은 ’<span class="math inline">\(n-1\)</span>의 자유도를 갖는 <span class="math inline">\(t\)</span>-분포(<span class="math inline">\(t_{n-1}\)</span>)’를 따릅니다.</p>
<p><span class="math display">\[
t = \frac{\bar{x} - \mu_0}{s / \sqrt{n}} \sim t_{n-1}
\]</span></p>
<p>이제 분포의 정체를 알았으니 <span class="math inline">\(p\)</span>-값을 구할 수 있습니다. 대립 가설 방향에 따라 꼬리 확률을 구하는 논리는 표준 정규분포와 완전히 동일하며, 단지 참조하는 분포표가 <span class="math inline">\(t\)</span>-분포로 바뀌었을 뿐입니다.</p>
<table class="caption-top table">
<thead>
<tr class="header">
<th>대립 가설(<span class="math inline">\(H_A\)</span>)</th>
<th><span class="math inline">\(p\)</span>-값 공식</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td><span class="math inline">\(H_A : \mu &lt; \mu_0\)</span></td>
<td><span class="math inline">\(P(t_{n-1} \le t)\)</span></td>
</tr>
<tr class="even">
<td><span class="math inline">\(H_A : \mu &gt; \mu_0\)</span></td>
<td><span class="math inline">\(P(t_{n-1} \ge t)\)</span></td>
</tr>
<tr class="odd">
<td><span class="math inline">\(H_A : \mu \neq \mu_0\)</span></td>
<td><span class="math inline">\(2 \times P(t_{n-1} \ge \vert t \vert)\)</span></td>
</tr>
</tbody>
</table>
<p>R에서는 <code>pt</code> 함수를 사용하여 <span class="math inline">\(t\)</span>-분포의 누적 확률을 계산합니다. 입력 인자로 기준값 <code>q</code>와 자유도 <code>df</code>가 필요합니다.</p>
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb5"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb5-1"><a href="#cb5-1" aria-hidden="true" tabindex="-1"></a><span class="fu">pt</span>(<span class="at">q =</span> t_star, <span class="at">df =</span> df, <span class="at">lower.tail =</span> <span class="cn">TRUE</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<p>한 가지 중대한 주의사항이 있습니다. 이 검정 과정은 <span class="math inline">\(\bar{x}\)</span>에 대해 중심극한정리가 작동한다는 전제하에 설계되었습니다. 따라서 표본 크기가 충분히 크거나(일반적으로 <span class="math inline">\(n \ge 30\)</span>), 원본 데이터 자체가 완벽한 정규분포를 따를 때만 이 <span class="math inline">\(p\)</span>-값 계산이 유효합니다.</p>
<p>슬롯 머신 예시의 대립 가설은 <span class="math inline">\(H_A : \mu &lt; 13.13\)</span>이므로 단측 하측 검정입니다. 자유도는 <span class="math inline">\(n-1 = 344\)</span>입니다. 따라서 <span class="math inline">\(p\)</span>-값은 <span class="math inline">\(P(t_{344} &lt; -90.7084)\)</span>가 됩니다.</p>
<p>R 코드를 통해 계산해 보면, 이 확률은 약 <span class="math inline">\(1.377 \times 10^{-242}\)</span>이라는 0에 무한히 가까운 극단적인 숫자가 나옵니다. 표본 크기가 345로 충분히 크므로 중심극한정리 요건을 완벽히 충족하여 이 결과는 유효합니다.</p>
</section>
</section>
<section id="단계-결론-도출-1" class="level3" data-number="2.6">
<h3 data-number="2.6" class="anchored" data-anchor-id="단계-결론-도출-1"><span class="header-section-number">2.6</span> 6단계: 결론 도출</h3>
<p>비율 검정과 마찬가지로 정당화, 통계적 결정, 현실 맥락의 세 가지 요소를 포함해 결론을 작성합니다.</p>
<p>슬롯 머신 데이터 분석 결과, 산출된 <span class="math inline">\(p\)</span>-값(<span class="math inline">\(1.377 \times 10^{-242}\)</span>)은 유의 수준 <span class="math inline">\(\alpha = 0.05\)</span>보다 훨씬 작습니다(정당화). 따라서 귀무 가설을 강력히 기각합니다(결정). 결론적으로 카지노 측 비디오 슬롯 머신의 실제 평균 지급액은 법적 기준인 <span class="math inline">\(\$13.13\)</span>보다 고의로 적게 조작되었다는 통계적으로 매우 유의한 증거가 존재합니다(맥락).</p>
<p>제조업 품질 관리 예시를 통해 과정을 다시 빠르게 요약해 보겠습니다. 정밀 금속 와셔(washer)의 직경을 4.0mm로 맞추는 공정이 있습니다. 규격(4.0)을 벗어나면 기계를 정비해야 합니다. <span class="math inline">\(n=20\)</span>개의 표본을 검사한 결과 <span class="math inline">\(\bar{x} = 3.9865\)</span>, <span class="math inline">\(s = 0.073\)</span>이었습니다.</p>
<ol type="1">
<li>가설 설정: <span class="math inline">\(H_0 : \mu = 4.0\)</span>, <span class="math inline">\(H_A : \mu \neq 4.0\)</span> (어느 방향이든 규격 미달)</li>
<li>유의 수준: <span class="math inline">\(\alpha = 0.05\)</span></li>
<li>데이터 요약: <span class="math inline">\(n = 20, \bar{x} = 3.9865, s = 0.073\)</span></li>
<li>검정 통계량: <span class="math inline">\(t = \frac{3.9865 - 4.0}{0.073 / \sqrt{20}} \approx -0.827\)</span></li>
<li><span class="math inline">\(p\)</span>-값 계산: 대립 가설이 <span class="math inline">\(\neq\)</span>이므로 양측 확률입니다. 자유도 <span class="math inline">\(df = 19\)</span></li>
</ol>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb6"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb6-1"><a href="#cb6-1" aria-hidden="true" tabindex="-1"></a><span class="dv">2</span> <span class="sc">*</span> <span class="fu">pt</span>(<span class="at">q =</span> <span class="fl">0.827</span>, <span class="at">df =</span> <span class="dv">19</span>, <span class="at">lower.tail =</span> <span class="cn">FALSE</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0.4185027</code></pre>
</div>
</div>
<p>계산된 <span class="math inline">\(p\)</span>-값은 약 <span class="math inline">\(0.4185\)</span>입니다.</p>
<ol start="6" type="1">
<li>결론: <span class="math inline">\(p\)</span>-값(0.4185)이 <span class="math inline">\(\alpha(0.05)\)</span>보다 크므로 귀무 가설 기각에 실패합니다. 와셔 평균 직경이 4.0mm라는 기존 가정이 여전히 타당하므로 공정을 멈추고 재설정할 필요는 없습니다.</li>
</ol>
<p>단, <span class="math inline">\(n=20\)</span>으로 표본이 30개 미만이고 실제 데이터의 히스토그램을 그려 정규성 확인을 거치지 않았다면, <span class="math inline">\(t\)</span>-분포 기반의 이 결론은 다소 불확실할 수 있습니다.</p>
<p>실무에서는 R의 <code>t.test</code> 함수를 사용하여 데이터 벡터, 기준값 <code>mu</code>, 대립 가설 유형을 입력하면 이 모든 과정이 원클릭으로 자동 계산됩니다.</p>
</section>
<section id="연습-문제-1" class="level3" data-number="2.7">
<h3 data-number="2.7" class="anchored" data-anchor-id="연습-문제-1"><span class="header-section-number">2.7</span> 연습 문제</h3>
<p>미국 일반 사회 조사(GSS)는 10문항의 어휘력 테스트를 주기적으로 실시합니다. 2000년의 전국 평균 정답 수는 6.0개였습니다. 2004년 어휘력이 전체적으로 ’향상’되었는지 확인하기 위해 1438명을 조사한 결과, 표본 평균은 6.2점, 표본 표준편차는 2.06점이었습니다.</p>
<ol start="12" type="1">
<li><p>이 상황의 귀무 가설과 대립 가설은 무엇입니까?</p></li>
<li><p>검정 통계량 공식을 이용해 통계량 <span class="math inline">\(t\)</span>를 계산하십시오.</p></li>
<li><p>검정 통계량은 어떤 확률 분포(자유도 포함)를 따릅니까?</p></li>
<li><p>대립 가설에 근거하여 <span class="math inline">\(p\)</span>-값을 도출하십시오.</p></li>
<li><p>최종적으로 어휘력이 향상되었다고 결론 내릴 수 있습니까?</p></li>
</ol>
<p>소변 내 칼슘의 건강한 정상 농도는 리터당 2.5밀리몰(mmol)입니다. 칼슘 옥살레이트 신장 결석 환자들의 칼슘 농도 평균이 일반인보다 ‘더 높은지’ 검증하고자 합니다. 환자 <span class="math inline">\(n=34\)</span>명의 표본에서 표본 평균 <span class="math inline">\(\bar{x}=6.143\)</span>, 표본 분산 <span class="math inline">\(s^2=13.229\)</span>가 관찰되었습니다. (주의: 공식에 필요한 것은 표준편차 <span class="math inline">\(s\)</span>입니다.)</p>
<ol start="17" type="1">
<li><p>귀무 가설과 대립 가설을 명시하십시오.</p></li>
<li><p>검정 통계량 <span class="math inline">\(t\)</span>를 계산하십시오.</p></li>
<li><p>통계량이 따르는 확률 분포는 무엇입니까?</p></li>
<li><p>도출되는 <span class="math inline">\(p\)</span>-값은 얼마입니까?</p></li>
<li><p>분석 결과를 종합하여 최종 의료적 결론을 내리십시오.</p></li>
</ol>
</section>
</section>
<section id="단일-모수-검정에서-효과-크기를-함께-보기" class="level2" data-number="3">
<h2 data-number="3" class="anchored" data-anchor-id="단일-모수-검정에서-효과-크기를-함께-보기"><span class="header-section-number">3</span> 단일 모수 검정에서 효과 크기를 함께 보기</h2>
<p>가설 검정을 통한 <span class="math inline">\(p\)</span>-값 도출은 관측된 데이터와 귀무 가설 간의 불일치 정도를 판별하는 객관적 도구입니다. 하지만 <span class="math inline">\(p\)</span>-값 하나만으로는 표본 통계량과 귀무 가설 기준값 간 차이의 ’실제적 크기’를 가늠하기 어렵습니다. 표본 크기 <span class="math inline">\(n\)</span>이 수백만 건에 달하면, 현실에서는 아무 의미 없는 미세한 차이도 <span class="math inline">\(p\)</span>-값은 극도로 낮게(유의하게) 산출될 수 있습니다. 반대로 표본이 너무 작으면 실질적으로 중대한 차이가 있음에도 통계적으로는 유의하지 않다는 결론이 나올 수 있습니다.</p>
<p>이러한 함정을 피하기 위해, 단일 모수 검정 결과를 보고할 때는 다음의 입체적인 기준들을 반드시 함께 고려해야 합니다.</p>
<ol type="1">
<li><p>점 추정값 확인: 표본 통계량(<span class="math inline">\(\hat{p}\)</span>나 <span class="math inline">\(\bar{x}\)</span>)이 귀무 가설 기준값과 숫자상으로 정확히 얼마나 차이가 나는지 직관적으로 확인합니다.</p></li>
<li><p>효과 크기(effect size) 해석: 그 차이가 해당 도메인(원래 단위)에서 현실적으로 의미가 있는 수준인지 비판적으로 평가합니다.</p></li>
<li><p>신뢰 구간 병기: 가설 검정 결과뿐만 아니라 <span class="math inline">\((1-\alpha)\)</span> 신뢰 구간을 함께 제시하여 불확실성의 범위를 투명하게 드러냅니다.</p></li>
<li><p>실질적 유의성(practical significance): 단순히 <span class="math inline">\(p &lt; 0.05\)</span>라는 이유로 정책을 바꾸는 것이 아니라, 이 차이가 현실의 비즈니스나 임상 결정을 뒤집을 만큼 충분한 가치를 지니는지 종합적으로 판단합니다.</p></li>
</ol>
<p>R의 <code>prop.test()</code>나 <code>t.test()</code> 함수는 고맙게도 <span class="math inline">\(p\)</span>-값뿐만 아니라 점 추정치와 신뢰 구간을 한 번에 깔끔하게 출력해 줍니다.</p>
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb8"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb8-1"><a href="#cb8-1" aria-hidden="true" tabindex="-1"></a><span class="fu">prop.test</span>(</span>
<span id="cb8-2"><a href="#cb8-2" aria-hidden="true" tabindex="-1"></a>  <span class="at">x =</span> <span class="dv">12</span>,</span>
<span id="cb8-3"><a href="#cb8-3" aria-hidden="true" tabindex="-1"></a>  <span class="at">n =</span> <span class="dv">79</span>,</span>
<span id="cb8-4"><a href="#cb8-4" aria-hidden="true" tabindex="-1"></a>  <span class="at">p =</span> <span class="fl">0.14</span>,</span>
<span id="cb8-5"><a href="#cb8-5" aria-hidden="true" tabindex="-1"></a>  <span class="at">alternative =</span> <span class="st">"two.sided"</span>,</span>
<span id="cb8-6"><a href="#cb8-6" aria-hidden="true" tabindex="-1"></a>  <span class="at">correct =</span> <span class="cn">FALSE</span></span>
<span id="cb8-7"><a href="#cb8-7" aria-hidden="true" tabindex="-1"></a>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<p>통계 소프트웨어는 사람을 대신해 기계적으로 결정을 내려주는 장치가 아닙니다. 오직 표본 데이터가 귀무 가설과 얼마나 부합하는지를 수학적으로 요약해 주는 정교한 도구일 뿐입니다. 최종적인 해석과 판단의 책임은 언제나 데이터를 들여다보는 분석가에게 있습니다.</p>
</section>
<section id="결론" class="level2" data-number="4">
<h2 data-number="4" class="anchored" data-anchor-id="결론"><span class="header-section-number">4</span> 결론</h2>
<p>단일 모수에 대한 가설 검정은 우리가 직면한 거대한 모집단의 속성을 파악하는 가장 기초적이고 강력한 도구입니다. 단일 평균 검정은 모집단의 중심이 어디에 형성되어 있는지 정확히 진단해 주며, 비율 검정은 특정 사건이 발생할 참 확률을 객관적으로 평가하게 해 줍니다.</p>
<p>가설 검정은 (1) 가설 설정, (2) 유의 수준 선택, (3) 데이터 요약, (4) 통계량 계산, (5) <span class="math inline">\(p\)</span>-값 산출, (6) 결론 도출이라는 매우 투명하고 논리적인 6단계를 거칩니다. 이 체계적인 틀을 이해하면 앞으로 등장할 아무리 복잡한 고급 검정 기법이라도 쉽게 접근할 수 있습니다. 덧붙여 공식을 외우는 것을 넘어, ’중심극한정리’와 같은 필수 전제 조건과 가정을 숙지해야만 통계 모형이 붕괴되는 치명적인 분석 오류를 방지할 수 있습니다. 오늘 배운 절차와 엄밀한 논리 구조는 향후 이어질 두 집단 간의 비교와 복잡한 추론 모델에서도 변함없이 여러분의 나침반이 될 것입니다.</p>


</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
  window.document.addEventListener("DOMContentLoaded", function (event) {
    const icon = "";
    const anchorJS = new window.AnchorJS();
    anchorJS.options = {
      placement: 'right',
      icon: icon
    };
    anchorJS.add('.anchored');
    const isCodeAnnotation = (el) => {
      for (const clz of el.classList) {
        if (clz.startsWith('code-annotation-')) {                     
          return true;
        }
      }
      return false;
    }
    const onCopySuccess = function(e) {
      // button target
      const button = e.trigger;
      // don't keep focus
      button.blur();
      // flash "checked"
      button.classList.add('code-copy-button-checked');
      var currentTitle = button.getAttribute("title");
      button.setAttribute("title", "Copied!");
      let tooltip;
      if (window.bootstrap) {
        button.setAttribute("data-bs-toggle", "tooltip");
        button.setAttribute("data-bs-placement", "left");
        button.setAttribute("data-bs-title", "Copied!");
        tooltip = new bootstrap.Tooltip(button, 
          { trigger: "manual", 
            customClass: "code-copy-button-tooltip",
            offset: [0, -8]});
        tooltip.show();    
      }
      setTimeout(function() {
        if (tooltip) {
          tooltip.hide();
          button.removeAttribute("data-bs-title");
          button.removeAttribute("data-bs-toggle");
          button.removeAttribute("data-bs-placement");
        }
        button.setAttribute("title", currentTitle);
        button.classList.remove('code-copy-button-checked');
      }, 1000);
      // clear code selection
      e.clearSelection();
    }
    const getTextToCopy = function(trigger) {
      const outerScaffold = trigger.parentElement.cloneNode(true);
      const codeEl = outerScaffold.querySelector('code');
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
    const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
      text: getTextToCopy
    });
    clipboard.on('success', onCopySuccess);
    if (window.document.getElementById('quarto-embedded-source-code-modal')) {
      const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
        text: getTextToCopy,
        container: window.document.getElementById('quarto-embedded-source-code-modal')
      });
      clipboardModal.on('success', onCopySuccess);
    }
      var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
      var mailtoRegex = new RegExp(/^mailto:/);
        var filterRegex = new RegExp('/' + window.location.host + '/');
      var isInternal = (href) => {
          return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
      }
      // Inspect non-navigation links and adorn them if external
     var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
      for (var i=0; i<links.length; i++) {
        const link = links[i];
        if (!isInternal(link.href)) {
          // undo the damage that might have been done by quarto-nav.js in the case of
          // links that we want to consider external
          if (link.dataset.originalHref !== undefined) {
            link.href = link.dataset.originalHref;
          }
        }
      }
    function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
      const config = {
        allowHTML: true,
        maxWidth: 500,
        delay: 100,
        arrow: false,
        appendTo: function(el) {
            return el.parentElement;
        },
        interactive: true,
        interactiveBorder: 10,
        theme: 'quarto',
        placement: 'bottom-start',
      };
      if (contentFn) {
        config.content = contentFn;
      }
      if (onTriggerFn) {
        config.onTrigger = onTriggerFn;
      }
      if (onUntriggerFn) {
        config.onUntrigger = onUntriggerFn;
      }
      window.tippy(el, config); 
    }
    const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
    for (var i=0; i<noterefs.length; i++) {
      const ref = noterefs[i];
      tippyHover(ref, function() {
        // use id or data attribute instead here
        let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
        try { href = new URL(href).hash; } catch {}
        const id = href.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note) {
          return note.innerHTML;
        } else {
          return "";
        }
      });
    }
    const xrefs = window.document.querySelectorAll('a.quarto-xref');
    const processXRef = (id, note) => {
      // Strip column container classes
      const stripColumnClz = (el) => {
        el.classList.remove("page-full", "page-columns");
        if (el.children) {
          for (const child of el.children) {
            stripColumnClz(child);
          }
        }
      }
      stripColumnClz(note)
      if (id === null || id.startsWith('sec-')) {
        // Special case sections, only their first couple elements
        const container = document.createElement("div");
        if (note.children && note.children.length > 2) {
          container.appendChild(note.children[0].cloneNode(true));
          for (let i = 1; i < note.children.length; i++) {
            const child = note.children[i];
            if (child.tagName === "P" && child.innerText === "") {
              continue;
            } else {
              container.appendChild(child.cloneNode(true));
              break;
            }
          }
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(container);
          }
          return container.innerHTML
        } else {
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(note);
          }
          return note.innerHTML;
        }
      } else {
        // Remove any anchor links if they are present
        const anchorLink = note.querySelector('a.anchorjs-link');
        if (anchorLink) {
          anchorLink.remove();
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        if (note.classList.contains("callout")) {
          return note.outerHTML;
        } else {
          return note.innerHTML;
        }
      }
    }
    for (var i=0; i<xrefs.length; i++) {
      const xref = xrefs[i];
      tippyHover(xref, undefined, function(instance) {
        instance.disable();
        let url = xref.getAttribute('href');
        let hash = undefined; 
        if (url.startsWith('#')) {
          hash = url;
        } else {
          try { hash = new URL(url).hash; } catch {}
        }
        if (hash) {
          const id = hash.replace(/^#\/?/, "");
          const note = window.document.getElementById(id);
          if (note !== null) {
            try {
              const html = processXRef(id, note.cloneNode(true));
              instance.setContent(html);
            } finally {
              instance.enable();
              instance.show();
            }
          } else {
            // See if we can fetch this
            fetch(url.split('#')[0])
            .then(res => res.text())
            .then(html => {
              const parser = new DOMParser();
              const htmlDoc = parser.parseFromString(html, "text/html");
              const note = htmlDoc.getElementById(id);
              if (note !== null) {
                const html = processXRef(id, note);
                instance.setContent(html);
              } 
            }).finally(() => {
              instance.enable();
              instance.show();
            });
          }
        } else {
          // See if we can fetch a full url (with no hash to target)
          // This is a special case and we should probably do some content thinning / targeting
          fetch(url)
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.querySelector('main.content');
            if (note !== null) {
              // This should only happen for chapter cross references
              // (since there is no id in the URL)
              // remove the first header
              if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
                note.children[0].remove();
              }
              const html = processXRef(null, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      }, function(instance) {
      });
    }
        let selectedAnnoteEl;
        const selectorForAnnotation = ( cell, annotation) => {
          let cellAttr = 'data-code-cell="' + cell + '"';
          let lineAttr = 'data-code-annotation="' +  annotation + '"';
          const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
          return selector;
        }
        const selectCodeLines = (annoteEl) => {
          const doc = window.document;
          const targetCell = annoteEl.getAttribute("data-target-cell");
          const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
          const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
          const lines = annoteSpan.getAttribute("data-code-lines").split(",");
          const lineIds = lines.map((line) => {
            return targetCell + "-" + line;
          })
          let top = null;
          let height = null;
          let parent = null;
          if (lineIds.length > 0) {
              //compute the position of the single el (top and bottom and make a div)
              const el = window.document.getElementById(lineIds[0]);
              top = el.offsetTop;
              height = el.offsetHeight;
              parent = el.parentElement.parentElement;
            if (lineIds.length > 1) {
              const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
              const bottom = lastEl.offsetTop + lastEl.offsetHeight;
              height = bottom - top;
            }
            if (top !== null && height !== null && parent !== null) {
              // cook up a div (if necessary) and position it 
              let div = window.document.getElementById("code-annotation-line-highlight");
              if (div === null) {
                div = window.document.createElement("div");
                div.setAttribute("id", "code-annotation-line-highlight");
                div.style.position = 'absolute';
                parent.appendChild(div);
              }
              div.style.top = top - 2 + "px";
              div.style.height = height + 4 + "px";
              div.style.left = 0;
              let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
              if (gutterDiv === null) {
                gutterDiv = window.document.createElement("div");
                gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
                gutterDiv.style.position = 'absolute';
                const codeCell = window.document.getElementById(targetCell);
                const gutter = codeCell.querySelector('.code-annotation-gutter');
                gutter.appendChild(gutterDiv);
              }
              gutterDiv.style.top = top - 2 + "px";
              gutterDiv.style.height = height + 4 + "px";
            }
            selectedAnnoteEl = annoteEl;
          }
        };
        const unselectCodeLines = () => {
          const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
          elementsIds.forEach((elId) => {
            const div = window.document.getElementById(elId);
            if (div) {
              div.remove();
            }
          });
          selectedAnnoteEl = undefined;
        };
          // Handle positioning of the toggle
      window.addEventListener(
        "resize",
        throttle(() => {
          elRect = undefined;
          if (selectedAnnoteEl) {
            selectCodeLines(selectedAnnoteEl);
          }
        }, 10)
      );
      function throttle(fn, ms) {
      let throttle = false;
      let timer;
        return (...args) => {
          if(!throttle) { // first call gets through
              fn.apply(this, args);
              throttle = true;
          } else { // all the others get throttled
              if(timer) clearTimeout(timer); // cancel #2
              timer = setTimeout(() => {
                fn.apply(this, args);
                timer = throttle = false;
              }, ms);
          }
        };
      }
        // Attach click handler to the DT
        const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
        for (const annoteDlNode of annoteDls) {
          annoteDlNode.addEventListener('click', (event) => {
            const clickedEl = event.target;
            if (clickedEl !== selectedAnnoteEl) {
              unselectCodeLines();
              const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
              if (activeEl) {
                activeEl.classList.remove('code-annotation-active');
              }
              selectCodeLines(clickedEl);
              clickedEl.classList.add('code-annotation-active');
            } else {
              // Unselect the line
              unselectCodeLines();
              clickedEl.classList.remove('code-annotation-active');
            }
          });
        }
    const findCites = (el) => {
      const parentEl = el.parentElement;
      if (parentEl) {
        const cites = parentEl.dataset.cites;
        if (cites) {
          return {
            el,
            cites: cites.split(' ')
          };
        } else {
          return findCites(el.parentElement)
        }
      } else {
        return undefined;
      }
    };
    var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
    for (var i=0; i<bibliorefs.length; i++) {
      const ref = bibliorefs[i];
      const citeInfo = findCites(ref);
      if (citeInfo) {
        tippyHover(citeInfo.el, function() {
          var popup = window.document.createElement('div');
          citeInfo.cites.forEach(function(cite) {
            var citeDiv = window.document.createElement('div');
            citeDiv.classList.add('hanging-indent');
            citeDiv.classList.add('csl-entry');
            var biblioDiv = window.document.getElementById('ref-' + cite);
            if (biblioDiv) {
              citeDiv.innerHTML = biblioDiv.innerHTML;
            }
            popup.appendChild(citeDiv);
          });
          return popup.innerHTML;
        });
      }
    }
  });
  </script>
</div> <!-- /content -->




</body></html>