<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.10.18">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>단일 모수에 대한 신뢰 구간 – R과 데이터 분석 입문</title>
<style>
/* Default styles provided by pandoc.
** See https://pandoc.org/MANUAL.html#variables-for-html for config info.
*/
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: 1.5em;}
div.column{flex: auto;}
@media screen {
div.columns{gap: min(4vw, 1.5em);}
div.column{overflow-x: auto;}
}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
html { -webkit-text-size-adjust: 100%; }
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="../../site_libs/quarto-nav/quarto-nav.js"></script>
<script src="../../site_libs/quarto-nav/headroom.min.js"></script>
<script src="../../site_libs/clipboard/clipboard.min.js"></script>
<script src="../../site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="../../site_libs/quarto-search/fuse.min.js"></script>
<script src="../../site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="../../">
<script src="../../site_libs/quarto-html/quarto.js" type="module"></script>
<script src="../../site_libs/quarto-html/tabsets/tabsets.js" type="module"></script>
<script src="../../site_libs/quarto-html/popper.min.js"></script>
<script src="../../site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="../../site_libs/quarto-html/anchor.min.js"></script>
<link href="../../site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="../../site_libs/quarto-html/quarto-syntax-highlighting-64a204ab8560d761af7679ceaba22944.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="../../site_libs/bootstrap/bootstrap.min.js"></script>
<link href="../../site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="../../site_libs/bootstrap/bootstrap-d55203e86ba1a699a1ae3c3642d34712.min.css" rel="stylesheet" append-hash="true" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "sidebar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "start",
  "type": "textbox",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>

  <script src="https://cdnjs.cloudflare.com/polyfill/v3/polyfill.min.js?features=es6"></script>
  <script defer="" src="https://cdn.jsdelivr.net/npm/mathjax@4/tex-chtml.js" type="text/javascript"></script>

<script type="text/javascript">
const typesetMath = (el) => {
  if (window.MathJax) {
    // MathJax Typeset
    window.MathJax.typeset([el]);
  } else if (window.katex) {
    // KaTeX Render
    var mathElements = el.getElementsByClassName("math");
    var macros = [];
    for (var i = 0; i < mathElements.length; i++) {
      var texText = mathElements[i].firstChild;
      if (mathElements[i].tagName == "SPAN" && texText && texText.data) {
        window.katex.render(texText.data, mathElements[i], {
          displayMode: mathElements[i].classList.contains('display'),
          throwOnError: false,
          macros: macros,
          fleqn: false
        });
      }
    }
  }
}
window.Quarto = {
  typesetMath
};
</script>

<meta property="og:title" content="단일 모수에 대한 신뢰 구간 – R과 데이터 분석 입문">
<meta property="og:description" content="">
<meta property="og:site_name" content="R과 데이터 분석 입문">
<meta name="twitter:title" content="단일 모수에 대한 신뢰 구간 – R과 데이터 분석 입문">
<meta name="twitter:description" content="">
<meta name="twitter:card" content="summary">
</head>

<body class="nav-sidebar docked quarto-light">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
  <nav class="quarto-secondary-nav">
    <div class="container-fluid d-flex">
      <button type="button" class="quarto-btn-toggle btn" data-bs-toggle="collapse" role="button" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
        <i class="bi bi-layout-text-sidebar-reverse"></i>
      </button>
        <nav class="quarto-page-breadcrumbs" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item">
      R과 데이터 분석 입문
      </li></ol></nav>
        <a class="flex-grow-1" role="navigation" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">      
        </a>
      <button type="button" class="btn quarto-search-button" aria-label="Search" onclick="window.quartoOpenSearch();">
        <i class="bi bi-search"></i>
      </button>
    </div>
  </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article">
<!-- sidebar -->
  <nav id="quarto-sidebar" class="sidebar collapse collapse-horizontal quarto-sidebar-collapse-item sidebar-navigation docked overflow-auto">
    <div class="pt-lg-2 mt-2 text-left sidebar-header">
    <div class="sidebar-title mb-0 py-0">
      <a href="../../">R과 데이터 분석 입문</a> 
        <div class="sidebar-tools-main">
  <a href="" class="quarto-reader-toggle quarto-navigation-tool px-1" onclick="window.quartoToggleReader(); return false;" title="Toggle reader mode">
  <div class="quarto-reader-toggle-btn">
  <i class="bi"></i>
  </div>
</a>
</div>
    </div>
      </div>
        <div class="mt-2 flex-shrink-0 align-items-center">
        <div class="sidebar-search">
        <div id="quarto-search" class="" title="Search"></div>
        </div>
        </div>
    <div class="sidebar-menu-container"> 
    <ul class="list-unstyled mt-1">
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">R 언어</span></a>
  </div>
</li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-1" role="navigation" aria-expanded="false">
 <span class="menu-text">R과 데이터 분석</span></a>
          <a class="sidebar-item-toggle text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-1" role="navigation" aria-expanded="false" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-1" class="collapse list-unstyled sidebar-section depth1 ">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../notes/ch01.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">훑어보기</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../notes/ch02.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">훑어보기: 데이터 정리</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../notes/ch03.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">훑어보기: 데이터 변환</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../notes/ch04.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">훑어보기: 데이터 가져오기</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../notes/ch05.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">시각화: 계층</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../notes/ch06.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">시각화: EDA</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../notes/ch07.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">시각화: 관련 정보</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../notes/ch08.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">비교</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../notes/ch09.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">숫자 만들기</span></a>
  </div>
</li>
      </ul>
  </li>
    </ul>
    </div>
</nav>
<div id="quarto-sidebar-glass" class="quarto-sidebar-collapse-item" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item"></div>
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">On this page</h2>
   
  <ul>
  <li><a href="#p에-대한-신뢰-구간" id="toc-p에-대한-신뢰-구간" class="nav-link active" data-scroll-target="#p에-대한-신뢰-구간"><span class="header-section-number">1</span> <span class="math inline">\(p\)</span>에 대한 신뢰 구간</a>
  <ul class="collapse">
  <li><a href="#연습-문제" id="toc-연습-문제" class="nav-link" data-scroll-target="#연습-문제"><span class="header-section-number">1.1</span> 연습 문제</a></li>
  </ul></li>
  <li><a href="#mu에-대한-신뢰-구간" id="toc-mu에-대한-신뢰-구간" class="nav-link" data-scroll-target="#mu에-대한-신뢰-구간"><span class="header-section-number">2</span> <span class="math inline">\(\mu\)</span>에 대한 신뢰 구간</a>
  <ul class="collapse">
  <li><a href="#연습-문제-1" id="toc-연습-문제-1" class="nav-link" data-scroll-target="#연습-문제-1"><span class="header-section-number">2.1</span> 연습 문제</a></li>
  </ul></li>
  <li><a href="#신뢰-구간의-다른-용도" id="toc-신뢰-구간의-다른-용도" class="nav-link" data-scroll-target="#신뢰-구간의-다른-용도"><span class="header-section-number">3</span> 신뢰 구간의 다른 용도</a>
  <ul class="collapse">
  <li><a href="#p에-대한-신뢰-구간과-표본-크기-계산" id="toc-p에-대한-신뢰-구간과-표본-크기-계산" class="nav-link" data-scroll-target="#p에-대한-신뢰-구간과-표본-크기-계산"><span class="header-section-number">3.1</span> <span class="math inline">\(p\)</span>에 대한 신뢰 구간과 표본 크기 계산</a></li>
  <li><a href="#연습-문제-2" id="toc-연습-문제-2" class="nav-link" data-scroll-target="#연습-문제-2"><span class="header-section-number">3.2</span> 연습 문제</a></li>
  <li><a href="#mu에-대한-신뢰-구간과-가설-검정" id="toc-mu에-대한-신뢰-구간과-가설-검정" class="nav-link" data-scroll-target="#mu에-대한-신뢰-구간과-가설-검정"><span class="header-section-number">3.3</span> <span class="math inline">\(\mu\)</span>에 대한 신뢰 구간과 가설 검정</a></li>
  <li><a href="#연습-문제-3" id="toc-연습-문제-3" class="nav-link" data-scroll-target="#연습-문제-3"><span class="header-section-number">3.4</span> 연습 문제</a></li>
  </ul></li>
  <li><a href="#구간-추정과-검정-결과를-함께-읽기" id="toc-구간-추정과-검정-결과를-함께-읽기" class="nav-link" data-scroll-target="#구간-추정과-검정-결과를-함께-읽기"><span class="header-section-number">4</span> 구간 추정과 검정 결과를 함께 읽기</a></li>
  <li><a href="#r을-활용한-실습-단일-모수-가설-검정과-신뢰-구간" id="toc-r을-활용한-실습-단일-모수-가설-검정과-신뢰-구간" class="nav-link" data-scroll-target="#r을-활용한-실습-단일-모수-가설-검정과-신뢰-구간"><span class="header-section-number">5</span> R을 활용한 실습: 단일 모수 가설 검정과 신뢰 구간</a></li>
  <li><a href="#결론" id="toc-결론" class="nav-link" data-scroll-target="#결론"><span class="header-section-number">6</span> 결론</a></li>
  </ul>
</nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">단일 모수에 대한 신뢰 구간</h1>
</div>



<div class="quarto-title-meta">

    
  
    
  </div>
  


</header>


<blockquote class="blockquote">
<p>단순히 모비율 <span class="math inline">\(p\)</span>와 모평균 <span class="math inline">\(\mu\)</span>의 타당한 범위를 계산하는 것을 넘어, 데이터 기반 의사결정에 필요한 다각적인 용도를 소개합니다.</p>
</blockquote>
<section id="p에-대한-신뢰-구간" class="level2" data-number="1">
<h2 data-number="1" class="anchored" data-anchor-id="p에-대한-신뢰-구간"><span class="header-section-number">1</span> <span class="math inline">\(p\)</span>에 대한 신뢰 구간</h2>
<p><span class="math inline">\(p\)</span>에 관한 <span class="math inline">\((1-\alpha) \times 100\%\)</span> 신뢰 구간을 생성할 때, 우리는 앞서 다음과 같은 공식을 도출했습니다.</p>
<p><span class="math display">\[
(\hat{p}-{z^*}\text{s.e.}(\hat{p}),\hat{p}+{z^*}\text{s.e.}(\hat{p}))
\]</span></p>
<p>여기서 <span class="math inline">\(\hat{p}\)</span>은 표본 비율(sample proportion)이며, <span class="math inline">\({z^*}\)</span>는 <span class="math inline">\(P(N(0,1)&lt;{z^*}) = 1-\alpha/2\)</span>가 되도록 선택한 임계값(critical value)입니다. 또한 <span class="math inline">\(\text{s.e.}(\hat{p})\)</span>은 표본 비율의 표준 오차(standard error)를 나타냅니다. 현대 데이터 분석 환경에서는 R이나 파이썬 같은 도구를 이용해 임계값을 손쉽게 찾을 수 있으므로, 공식에 표준 오차만 대입하면 됩니다. 가설 검정과 마찬가지로 이 과정은 중심극한정리(central limit theorem)를 기반으로 합니다. 가설 검정 단계를 유도하며 중심극한정리에 의해 다음과 같은 성질을 확인했습니다.</p>
<p><span class="math display">\[
\hat{p} \sim N\left(p,\ \frac{p(1-p)}{n}\right)
\]</span></p>
<p>여기서 <span class="math inline">\(p\)</span>는 모집단 비율(population proportion)의 참값입니다. 이는 <span class="math inline">\(\hat{p}\)</span>의 표준 오차가 <span class="math inline">\(\text{s.e.}(\hat{p})=\sqrt{p(1-p)/n}\)</span>임을 의미합니다. 그러나 모집단 비율은 모수(parameter)이며 보통 알려지지 않은 값으로 간주하므로 우리는 <span class="math inline">\(p\)</span>의 참값을 알지 못합니다. 따라서 모집단 비율 <span class="math inline">\(p\)</span>를 추정하는 표준 오차 공식에 다른 값을 대입해야 합니다. 우리는 표본 비율 <span class="math inline">\(\hat{p}\)</span>이 모집단 비율 <span class="math inline">\(p\)</span>를 추정한다는 사실을 알고 있으므로, 표준 오차의 <span class="math inline">\(p\)</span> 대신 <span class="math inline">\(\hat{p}\)</span>을 대입할 수 있습니다. 그 결과는 다음과 같습니다.</p>
<p><span class="math display">\[
\text{s.e.}(\hat{p})=\sqrt{\frac{\hat{p}(1-\hat{p})}{n}}
\]</span></p>
<p>이러한 변경을 통해, <span class="math inline">\(p\)</span>에 대한 <span class="math inline">\((1-\alpha) \times 100\%\)</span> 신뢰 구간은 다음과 같이 도출됩니다.</p>
<p><span class="math display">\[
(\hat{p}-{z^*}\sqrt{\frac{\hat{p}(1-\hat{p})}{n}},\hat{p}+{z^*}\sqrt{\frac{\hat{p}(1-\hat{p})}{n}})
\]</span></p>
<p>여기서 <span class="math inline">\(\hat{p}\)</span>은 표본 비율, <span class="math inline">\(n\)</span>은 표본 크기, 그리고 <span class="math inline">\({z^*}\)</span>는 <span class="math inline">\(P(N(0,1)&lt;{z^*}) = 1-\alpha/2\)</span>가 되도록 선택된 임계값입니다. 신뢰 구간의 마지막 부분은 해석이며, 이는 이전에 논의한 바와 같습니다. 우리는 “계산한 구간이 <span class="math inline">\(p\)</span>의 참값을 포함할 것이라고 <span class="math inline">\((1-\alpha) \times 100\%\)</span> 확신(confident)한다”고 말함으로써 신뢰 구간을 해석합니다.</p>
<p>가설 검정과 마찬가지로 신뢰 구간을 생성할 때도 핵심적인 가정이 존재합니다. 임계값 <span class="math inline">\({z^*}\)</span>와 신뢰 구간을 얻기 위해 정규분포를 사용하려면 중심극한정리가 성립해야 합니다. 중심극한정리가 성립하려면 표본 크기가 충분히 커야 하며(일반적으로 <span class="math inline">\(n \ge 30\)</span>), 표본에 충분한 수의 성공과 실패(각각 최소 10개 이상)가 있어야 합니다. 즉, 신뢰 구간이 유효하려면 충분히 큰 표본 크기와 표본 내에 충분한 성공 및 실패 횟수를 확보해야 합니다.</p>
<p>예를 들어, 스테판 커리(Steph Curry)는 2016년에 362개의 자유투 중 325개를 성공시켰습니다. 스테판 커리가 자유투를 성공시킬 실제 확률 <span class="math inline">\(p\)</span>에 대한 99% 신뢰 구간(<span class="math inline">\(\alpha=0.01\)</span>)을 만들어 보겠습니다. 첫 번째 단계는 <span class="math inline">\(P(N(0,1)&lt;{z^*})=1-0.01/2=0.995\)</span>가 되는 임계값 <span class="math inline">\({z^*}\)</span>를 찾는 것입니다. R 코드를 사용하면 다음과 같습니다.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb1"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="fu">qnorm</span>(<span class="at">p =</span> <span class="fl">0.995</span>, <span class="at">mean =</span> <span class="dv">0</span>, <span class="at">sd =</span> <span class="dv">1</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 2.575829</code></pre>
</div>
</div>
<p>임계값이 <span class="math inline">\({z^*}=2.576\)</span>임을 알 수 있습니다. 임계값, 표본 비율 <span class="math inline">\(\hat{p}=325/362\)</span>, 그리고 표본 크기 <span class="math inline">\(n=362\)</span>를 사용하면 <span class="math inline">\(p\)</span>에 대한 99% 신뢰 구간은 다음과 같이 계산됩니다.</p>
<p><span class="math display">\[
\left(\hat{p}-2.576\sqrt{\frac{\hat{p}(1-\hat{p})}{362}},\ \hat{p}+2.576\sqrt{\frac{\hat{p}(1-\hat{p})}{362}}\right) = (0.857,\ 0.939)
\]</span></p>
<p>우리는 (0.857, 0.939) 구간이 스테판 커리가 자유투를 성공시킬 참 확률을 포함한다고 99% 확신합니다. 또한, 표본 크기가 충분히 크고(<span class="math inline">\(n=362\)</span>) 성공과 실패 횟수(성공 325회, 실패 <span class="math inline">\(362-325=37\)</span>회)가 충분하므로 도출된 결과를 신뢰할 수 있습니다.</p>
<p>앞서 언급한 <code>prop.test</code> 함수에는 <span class="math inline">\(p\)</span>에 대한 신뢰 구간을 계산하는 기능이 포함되어 있습니다. 이전과 같이 데이터를 입력하고 <code>conf.level</code> 옵션을 원하는 신뢰 수준으로 변경하면 <span class="math inline">\(p\)</span>에 대한 <span class="math inline">\((1-\alpha) \times 100\%\)</span> 신뢰 구간을 얻을 수 있습니다.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb3"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb3-1"><a href="#cb3-1" aria-hidden="true" tabindex="-1"></a><span class="fu">prop.test</span>(<span class="at">x =</span> <span class="dv">325</span>, <span class="at">n =</span> <span class="dv">362</span>, <span class="at">conf.level =</span> <span class="fl">0.99</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>
    1-sample proportions test with continuity correction

data:  325 out of 362, null probability 0.5
X-squared = 227.54, df = 1, p-value &lt; 2.2e-16
alternative hypothesis: true p is not equal to 0.5
99 percent confidence interval:
 0.8477740 0.9330161
sample estimates:
        p 
0.8977901 </code></pre>
</div>
</div>
<section id="연습-문제" class="level3" data-number="1.1">
<h3 data-number="1.1" class="anchored" data-anchor-id="연습-문제"><span class="header-section-number">1.1</span> 연습 문제</h3>
<ol type="1">
<li><p>마이크 트라웃(Mike Trout)은 2017년에 507번의 타석에서 224번 출루했습니다. 마이크 트라웃이 출루할 참 확률 <span class="math inline">\(p\)</span>에 대한 95% 신뢰 구간을 구하고 해석해 보십시오.</p></li>
<li><p>크랩스(Craps) 게임에서 한 개인이 패스 라인(Pass line)에 베팅하여 20번의 게임 중 8번을 이겼습니다. 패스 라인에 베팅하여 이길 참 확률 <span class="math inline">\(p\)</span>에 대한 99% 신뢰 구간을 구하고 해석해 보십시오.</p></li>
<li><p>780명의 여성 표본에서 349명이 자원봉사에 참여한 것으로 나타났습니다. 자원봉사에 참여하는 여성의 실제 비율에 대한 90% 신뢰 구간을 구하고 해석해 보십시오.</p></li>
</ol>
</section>
</section>
<section id="mu에-대한-신뢰-구간" class="level2" data-number="2">
<h2 data-number="2" class="anchored" data-anchor-id="mu에-대한-신뢰-구간"><span class="header-section-number">2</span> <span class="math inline">\(\mu\)</span>에 대한 신뢰 구간</h2>
<p>모평균(<span class="math inline">\(\mu\)</span>)에 대한 신뢰 구간을 생성할 때는 p에 대한 신뢰 구간을 도출할 때와 동일한 단계를 다수 거치게 됩니다. <span class="math inline">\(\mu\)</span>에 대한 <span class="math inline">\((1-\alpha)\)</span> 100% 신뢰 구간을 계산하는 목적은 다음과 같이 되는 구간 추정치 (lower, upper)를 도출하는 것입니다.</p>
<p><span class="math display">\[
P(\text{lower}&lt;\mu&lt;\text{upper})=1-\alpha
\]</span></p>
<p>이를 위해서는 <span class="math inline">\(\mu\)</span>를 확률 분포와 연결해야 합니다. 앞서 가설 검정에서 우리는 다음과 같은 성질을 확인했습니다.</p>
<p><span class="math display">\[
\frac{\bar{x}-\mu}{s/\sqrt{n}} \sim t_{n-1}
\]</span></p>
<p>이를 염두에 두고 <span class="math inline">\(t_{n-1}\)</span> 분포와 관련된 확률 문장부터 시작해 보겠습니다. 다음과 같이 되도록 하는 <span class="math inline">\(t^*\)</span>(마찬가지로 임계값이라 부름) 값을 선택합니다.</p>
<p><span class="math display">\[
P(-t^*&lt;t_{n-1}&lt;t^*)=1-\alpha
\]</span></p>
<p>이제 <span class="math inline">\(\frac{\bar{x}-\mu}{s/\sqrt{n}} \sim t_{n-1}\)</span>이므로, 확률 문장의 <span class="math inline">\(t_{n-1}\)</span> 대신 <span class="math inline">\(\frac{\bar{x}-\mu}{s/\sqrt{n}}\)</span>을 대입할 수 있으며, 그 결과는 다음과 같습니다.</p>
<p><span class="math display">\[
P\left(-t^*&lt;\frac{\bar{x}-\mu}{s/\sqrt{n}}&lt;t^*\right)=1-\alpha
\]</span></p>
<p>이 시점에서 확률 문장 내부의 대수학(algebra)을 사용하여 <span class="math inline">\(\mu\)</span>에 관해 풀면, 우리가 원하는 확률적 특성을 가진 구간 추정치를 얻게 됩니다.</p>
<p><span class="math display">\[
\begin{aligned}
P\left(-t^*&lt;\frac{\bar{x}-\mu}{s/\sqrt{n}}&lt;t^*\right) &amp;= 1-\alpha \\
P\left(-t^*\frac{s}{\sqrt{n}}&lt;\bar{x}-\mu&lt;t^*\frac{s}{\sqrt{n}}\right) &amp;= 1-\alpha \\
P\left(-\bar{x}-t^*\frac{s}{\sqrt{n}}&lt;-\mu&lt;-\bar{x}+t^*\frac{s}{\sqrt{n}}\right) &amp;= 1-\alpha \\
P\left(\bar{x}-t^*\frac{s}{\sqrt{n}}&lt;\mu&lt;\bar{x}+t^*\frac{s}{\sqrt{n}}\right) &amp;= 1-\alpha
\end{aligned}
\]</span></p>
<p>이제 우리는 <span class="math inline">\(P(\text{lower}&lt;\mu&lt;\text{upper})=1-\alpha\)</span>를 만족하는 구간 (lower, upper)을 확보했습니다. 이는 결과적으로 <span class="math inline">\(\mu\)</span>에 대한 <span class="math inline">\((1-\alpha) \times 100\%\)</span> 신뢰 구간이 다음과 같음을 의미합니다.</p>
<p><span class="math display">\[
\left(\bar{x}-t^*\frac{s}{\sqrt{n}},\ \bar{x}+t^*\frac{s}{\sqrt{n}}\right)
\]</span></p>
<p>따라서 <span class="math inline">\(\mu\)</span>에 대한 신뢰 구간을 계산하려면 표본에서 표본 평균 <span class="math inline">\(\bar{x}\)</span>, 표본 표준편차 <span class="math inline">\(s\)</span>, 그리고 표본 크기 <span class="math inline">\(n\)</span>을 얻어야 합니다. 이제 임계값 <span class="math inline">\(t^*\)</span>를 찾는 일만 남았습니다. p에 대한 신뢰 구간과 마찬가지로, 정의된 대로 <span class="math inline">\(t^*\)</span>(<span class="math inline">\(P(-t^* &lt; t_{n-1} &lt; t^*) = 1-\alpha\)</span>가 되도록 <span class="math inline">\(t^*\)</span>를 선택함)를 찾는 과정은 두 개의 확률을 구하는 과정이 포함되므로 까다로울 수 있습니다. 그러나 <span class="math inline">\(t\)</span>-분포는 대칭이므로 다음과 같이 <span class="math inline">\(t^*\)</span>를 선택하는 데 사용하는 확률을 조정할 수 있습니다.</p>
<p><span class="math display">\[
P(t_{n-1} &lt; t^*) = 1-\alpha/2
\]</span></p>
<p><span class="math inline">\(t^*\)</span> 값을 찾기 위해 다시 R을 활용해 보겠습니다. pnorm 함수에 대응하는 <span class="math inline">\(t\)</span>-분포 함수로 pt 함수가 있었듯이, 정규분포에서 임계값을 찾는 데 사용한 qnorm 함수에 대응하는 <span class="math inline">\(t\)</span>-분포 함수로 qt 함수가 존재합니다. <code>qt</code> 함수는 주어진 확률과 <span class="math inline">\(t\)</span>-분포의 자유도(degrees of freedom)를 바탕으로 <span class="math inline">\(t\)</span>-분포의 임계값을 찾아줍니다. 임계값과 관련된 확률 <span class="math inline">\(p\)</span>와 자유도 <span class="math inline">\(\nu\)</span>의 두 값이 <code>qt</code> 함수의 입력값이 되며, 코드는 아래와 같습니다.</p>
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb5"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb5-1"><a href="#cb5-1" aria-hidden="true" tabindex="-1"></a><span class="fu">qt</span>(<span class="at">p =</span> prob, <span class="at">df =</span> df)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<p>다른 모든 신뢰 구간과 마찬가지로, 신뢰 구간을 해석하는 것은 신뢰 구간 추론의 중요한 측면입니다. <span class="math inline">\(p\)</span>에 대한 신뢰 구간과 동일하게 <span class="math inline">\(\mu\)</span>에 대한 신뢰 구간 역시 해당 구간이 “맞는지”, 즉 모수 <span class="math inline">\(\mu\)</span>의 참값을 포함하는지에 대한 우리의 확신 관점에서 해석합니다. 이 경우 <span class="math inline">\(\mu\)</span>에 대한 <span class="math inline">\((1-\alpha) \times 100\%\)</span> 신뢰 구간을 해석하기 위해, “우리가 계산한 구간이 모평균 <span class="math inline">\(\mu\)</span>의 참값을 포함한다고 <span class="math inline">\((1-\alpha) \times 100\%\)</span> 확신한다”고 말합니다.</p>
<p>마지막으로, <span class="math inline">\(p\)</span>에 대한 신뢰 구간 및 가설 검정과 마찬가지로 <span class="math inline">\(\mu\)</span>에 대한 신뢰 구간에도 중요한 가정이 내재되어 있습니다. 우리의 신뢰 구간은 중심극한정리가 성립한다는 것을 암묵적으로 가정하며, 이는 표본 크기가 충분히 크거나 데이터가 정규분포를 따른다는 것을 뜻합니다. 신뢰 구간 결과가 유지되려면(즉, 평균에 대해 중심극한정리가 성립하려면) 표본 크기가 <span class="math inline">\(n\ge 30\)</span>이거나 데이터가 정규분포를 따라야 합니다.</p>
<p>우리가 케일(Kale)에서 발견되는 백만분율(ppm) 단위의 DDT 양인 <span class="math inline">\(\mu\)</span>에 대한 96% 신뢰 구간을 계산하는 데 관심이 있다고 가정해 보겠습니다. R의 MASS 라이브러리에 있는 DDT 데이터셋은 바로 이를 측정하며, 15개의 서로 다른 실험실에서 케일 표본의 DDT 양을 추정했습니다. 표본 평균은 <span class="math inline">\(\bar{x}=3.328\)</span>이고 표본 표준편차는 <span class="math inline">\(s=0.4372\)</span>입니다. 이제 임계값 <span class="math inline">\(t^*\)</span>만 찾으면 됩니다. 96% 신뢰 구간을 계산하는 경우 <span class="math inline">\((1-0.04)\times 100\% = 96\%\)</span>이므로 <span class="math inline">\(\alpha\)</span> 수준은 0.04입니다. 이는 <span class="math inline">\(P(t_{15-1} &lt; t^*) = 1-0.04/2=0.98\)</span>가 되도록 <span class="math inline">\(t^*\)</span>를 선택해야 함을 뜻합니다. 아래의 R 코드를 사용해 보겠습니다.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb6"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb6-1"><a href="#cb6-1" aria-hidden="true" tabindex="-1"></a><span class="fu">qt</span>(<span class="at">p =</span> <span class="fl">0.98</span>, <span class="at">df =</span> <span class="dv">14</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 2.263781</code></pre>
</div>
</div>
<p>계산 결과 <span class="math inline">\(t^*=2.263781\)</span>임을 알 수 있습니다. 이 모든 것을 종합하면, 케일 표본의 DDT 모평균 양에 대한 96% 신뢰 구간은 다음과 같이 도출됩니다.</p>
<p><span class="math display">\[
3.328 \pm 2.264 \frac{0.4372}{\sqrt{15}}=(3.0724,\ 3.5836)
\]</span></p>
<p>우리는 <span class="math inline">\((3.0724, 3.5836)\)</span> 구간이 <span class="math inline">\(\mu\)</span>의 참값을 포함한다고 96% 확신합니다. 그러나 표본 크기가 30보다 작으므로 결과에 대한 우려가 있을 수 있음을 유의해야 합니다. 하지만 데이터의 히스토그램을 확인하면 데이터가 대칭적임을 보여주며, 이는 합리적인 정규성을 시사하고 중심극한정리가 여전히 성립함을 뒷받침합니다. 따라서 우리의 결과는 신뢰할 만합니다. (<code>prop.test</code> 함수를 사용하여 <span class="math inline">\(p\)</span>에 대한 신뢰 구간을 얻을 수 있는 것과 마찬가지로, <code>t.test</code> 함수를 사용하여 <span class="math inline">\(\mu\)</span>에 대한 신뢰 구간을 얻을 수 있습니다. 이전과 마찬가지로 이 구간을 얻기 위해 원하는 신뢰 수준에 관한 정보만 추가하면 됩니다.)</p>
<section id="연습-문제-1" class="level3" data-number="2.1">
<h3 data-number="2.1" class="anchored" data-anchor-id="연습-문제-1"><span class="header-section-number">2.1</span> 연습 문제</h3>
<ol start="4" type="1">
<li><p>뉴욕시에서는 시의 대기 질에 관한 데이터를 매일 수집합니다. 116건의 관측치에서 오존 ppb의 평균은 <span class="math inline">\(\bar{x}=42.13\)</span>이었고 표본 표준편차는 <span class="math inline">\(s=32.99\)</span>이었습니다. <span class="math inline">\(\mu\)</span>에 대한 99% 신뢰 구간을 계산하고 해석해 보십시오.</p></li>
<li><p>한 연구에서 182명에게 키를 물어본 다음 실제 키를 측정하고 두 값의 차이를 계산했습니다. 표본 평균은 <span class="math inline">\(\bar{x}=2.07\)</span>(실제 키가 보고된 키보다 2.07cm 더 컸음)였고 표본 표준편차는 <span class="math inline">\(s=2.08\)</span>이었습니다. <span class="math inline">\(\mu\)</span>에 대한 90% 신뢰 구간을 계산하고 해석해 보십시오.</p></li>
<li><p>심장마비를 경험한 <span class="math inline">\(n=1295\)</span>명의 여성 중에서 표본 평균 연령은 <span class="math inline">\(\bar{x}=60.92\)</span>였고 표준편차는 <span class="math inline">\(s=7.042\)</span>였습니다. <span class="math inline">\(\mu\)</span>에 대한 95% 신뢰 구간을 계산하고 해석해 보십시오.</p></li>
</ol>
</section>
</section>
<section id="신뢰-구간의-다른-용도" class="level2" data-number="3">
<h2 data-number="3" class="anchored" data-anchor-id="신뢰-구간의-다른-용도"><span class="header-section-number">3</span> 신뢰 구간의 다른 용도</h2>
<p>지금까지 우리의 신뢰 구간은 통계적 추론의 두 번째 형태로서 가설 검정을 보완하여 타당한 값의 범위를 제공하는 데 사용되었습니다. 하지만 신뢰 구간의 형태와 도출 과정은 통계적 과정의 다른 측면에도 사용할 수 있습니다. 신뢰 구간은 향후 연구에 필요한 표본 크기를 결정하는 데 도움이 될 뿐만 아니라, 가설 검정 결과와 직접적인 연결 고리를 제공합니다.</p>
<section id="p에-대한-신뢰-구간과-표본-크기-계산" class="level3" data-number="3.1">
<h3 data-number="3.1" class="anchored" data-anchor-id="p에-대한-신뢰-구간과-표본-크기-계산"><span class="header-section-number">3.1</span> <span class="math inline">\(p\)</span>에 대한 신뢰 구간과 표본 크기 계산</h3>
<p>연구를 설계하고 데이터를 수집할 때 직면하는 큰 과제 중 하나는 연구 질문에 답하기에 충분한 표본 크기가 얼마인지 결정하는 일입니다. 우리가 살펴본 바와 같이, 표본 크기는 표준 오차, 신뢰 구간, 가설 검정에 영향을 미칩니다. 대다수 경우 표본 크기는 연구 리소스에 의해 결정되며, 예산이 넉넉할수록 더 많은 대상을 조사할 수 있습니다. 그러나 신뢰 구간은 표본 크기를 결정하는 유용한 지표가 됩니다. 처음 구간 추정치를 정의할 때, 기본적인 구간 추정치는 다음과 같이 정의된다고 설명했습니다.</p>
<p><span class="math display">\[
\text{점 추정치 (Point Estimate)} \pm \text{오차 한계 (Margin of Error)}
\]</span></p>
<p>이를 <span class="math inline">\(p\)</span>에 대한 신뢰 구간의 관점에서 정의해 보겠습니다. 다시 상기해 보면, <span class="math inline">\(p\)</span>에 대한 신뢰 구간은 다음과 같습니다.</p>
<p><span class="math display">\[
\hat{p} \pm z^*\sqrt{\frac{\hat{p}(1-\hat{p})}{n}}
\]</span></p>
<p>모비율 p의 경우, 해당 모집단 모수의 점 추정치는 표본 비율 <span class="math inline">\(\hat{p}\)</span>이며 오차 한계는 <span class="math inline">\(m = {z^*} \sqrt{\frac{\hat{p}(1-\hat{p})}{n}}\)</span>입니다. 오차 한계는 표본 크기 <span class="math inline">\(n\)</span>, <span class="math inline">\({z^*}\)</span>를 통해 결정되는 신뢰 수준, 그리고 표본 비율 <span class="math inline">\(\hat{p}\)</span>을 아는 것을 전제로 합니다. 만약 우리가 표본 크기를 알고 싶고, 오차 한계 <span class="math inline">\(m\)</span>, 표본 비율 <span class="math inline">\(\hat{p}\)</span>, 그리고 추정치에서 얻고자 하는 신뢰 수준(<span class="math inline">\({z^*}\)</span>를 통해 전달됨)을 알고 있다고 가정해 보겠습니다. 오차 한계 방정식을 사용하여 약간의 대수학을 거쳐 <span class="math inline">\(n\)</span>에 관해 풀면 다음과 같습니다.</p>
<p><span class="math display">\[
n = \frac{(z^*)^2\,\hat{p}(1-\hat{p})}{m^2}
\]</span></p>
<p>그렇다면 이 방정식을 연구 설계에 어떻게 활용할 수 있을까요? 이는 데이터 수집 후에야 결정되는 많은 정보를 아는 것에 의존합니다. 그러나 연구 전에 이 중 상당 부분에 관해 결정을 내릴 수 있습니다. 모집단 비율을 특정 오차 한계 내에서 추정하고 싶다고 정할 수 있으므로, m 값을 알 수 있습니다. 또한, 구간 추정치에 관해 얼마나 확신하고 싶은지(기본적으로 구간 추정치가 “맞을” 빈도를 설정함)를 정확히 정할 수 있습니다. 이는 어떤 <span class="math inline">\({z^*}\)</span> 값을 원하는지 아는 것과 같으며, R의 qnorm 함수를 사용하여 해당 임계값을 쉽게 찾을 수 있습니다. 마지막으로 표본 크기 계산을 완료하기 위해 빠진 것은 표본 비율 <span class="math inline">\(\hat{p}\)</span>뿐입니다.</p>
<p>우리가 어떤 표본 비율을 마주하게 될지 미리 확정할 수 없기 때문에, 이것이 공식에서 설명하기 까다로운 부분처럼 보일 수 있습니다. 그러나 특정 사례에서는 <span class="math inline">\(\hat{p}\)</span>이 어떠할지에 관한 정보를 미리 파악할 수 있습니다. 예를 들어, 많은 연구가 과거 연구에서 반복된 질문을 다시 던집니다. 따라서 과거 연구의 표본 비율이 얼마였는지 참고할 수 있으며, 이를 우리 연구에서 마주하게 될 <span class="math inline">\(\hat{p}\)</span>의 대용치(Proxy)로 활용할 수 있습니다.</p>
<p>하지만 이전 연구가 존재하지 않는 상황도 흔합니다. 그런 경우 우리는 어떻게 대처해야 할까요? 이전 조사가 없다면 “최악의 시나리오”를 가정해야 합니다. 즉, 필요한 표본 크기를 크게 만드는 값을 표본 비율로 가정하는 방식입니다. 오차 한계와 신뢰 수준이 일정하다면, 표본 크기는 <span class="math inline">\(\hat{p}=0.5\)</span>일 때 최대가 됩니다. 미적분학을 이용하거나 다양한 <span class="math inline">\(\hat{p}\)</span> 값에 대해 표본 크기를 직접 계산해 봄으로써 이를 증명할 수 있습니다. 결과적으로 모집단 비율을 오차 한계 m 이내에서 <span class="math inline">\((1-\alpha)\)</span> 100% 신뢰도로 추정하고 싶다면, 표본 크기는 다음과 같아야 합니다.</p>
<p><span class="math display">\[
n \ge \frac{(z^*)^2\,\tilde{p}(1-\tilde{p})}{m^2}
\]</span></p>
<p>여기서 <span class="math inline">\(P(N(0,1)&lt;{z^*}) = 1-\alpha/2\)</span>가 되도록 <span class="math inline">\({z^*}\)</span>를 설정하고, <span class="math inline">\(\tilde{p}\)</span>는 이전 연구가 있다면 그에 기반하여 설정하되, 없다면 최악의 시나리오(0.5)를 바탕으로 설정합니다.</p>
<p><span class="math display">\[
\tilde{p} =
\begin{cases}
  \text{이전 연구가 존재한다면 해당 연구의 표본 비율} \hat{p}, \\
  \text{이전 연구가 존재하지 않다면} 0.5
\end{cases}
\]</span></p>
<p>필요한 표본 크기를 계산할 때 종종 n은 정수가 아닌 값으로 산출됩니다. 물론 반 명의 사람을 표본으로 추출할 수는 없으므로, 계산된 n보다 크거나 같은 다음 정수로 올림해야 합니다. 내림하면 표본 크기 부족으로 인해 원하는 것보다 더 큰 오차 한계가 발생하게 됩니다. 올림을 적용함으로써 우리의 신뢰 구간이 처음 목표했던 것보다 약간 더 작은 안정적인 오차 한계를 갖도록 보장할 수 있습니다.</p>
<p>예를 들어, 50년 전보다 오늘날 자신과 같은 사람들의 삶이 더 나아졌다고 믿는 미국인의 실제 비율 <span class="math inline">\(p\)</span>를 추정하고 싶다고 가정해 보겠습니다. 조사를 설계하기 위해 <span class="math inline">\(p\)</span>를 0.04의 오차 한계 내에서 99.5% 신뢰도로 추정하기로 결정합니다. 우선 오차 한계가 <span class="math inline">\(m=0.04\)</span>임을 알 수 있습니다. 다음으로 임계값 <span class="math inline">\({z^*}\)</span>를 찾아야 합니다. 99.5% 신뢰도의 경우 <span class="math inline">\(\alpha\)</span> 값은 <span class="math inline">\(\alpha=0.005\)</span>이므로, <span class="math inline">\(P(N(0,1)&lt;{z^*})=1-0.005/2=0.9975\)</span>가 되도록 <span class="math inline">\({z^*}\)</span>를 선택합니다. R에서 <code>qnorm(p = 0.9975, mean = 0, sd = 1)</code> 코드를 실행하면 <span class="math inline">\({z^*}=2.807\)</span>임을 확인할 수 있습니다.</p>
<p>마지막으로 남은 요소는 <span class="math inline">\(\tilde{p}\)</span>입니다. 이전 연구에서 표본 비율에 대한 사전 지식이 없다고 가정하면, 최악의 시나리오를 적용하여 <span class="math inline">\(\tilde{p}=0.5\)</span>로 설정해야 합니다. 이 모든 것을 종합하면, <span class="math inline">\(p\)</span>를 0.04의 오차 한계 내에서 99.5% 신뢰도로 추정할 최소 표본 크기는 다음과 같습니다.</p>
<p><span class="math display">\[
n \ge \frac{(2.807)^2 \cdot 0.5(1-0.5)}{0.04^2} = 1231.133.
\]</span></p>
<p>따라서 최소 1232명의 피험자가 필요합니다. 반면에 문헌 조사를 통해 2017년 퓨 리서치 설문 조사에서 <span class="math inline">\(\hat{p}=0.37\)</span>임을 발견했다고 가정해 보겠습니다. 이 경우 <span class="math inline">\(\tilde{p}=0.37\)</span>이 되며 표본 크기 계산은 다음과 같이 수정됩니다.</p>
<p><span class="math display">\[
n = \frac{(2.807)^2 \cdot 0.37(1-0.37)}{0.04^2} = 1147.908.
\]</span></p>
<p>따라서 표본 크기는 1148명이 되어야 합니다. 필요한 표본 크기가 최악의 시나리오보다 줄어들었는데, 이는 표본 크기가 <span class="math inline">\(\tilde{p}=0.5\)</span>에서 최대화되기 때문에 당연히 예상되는 결과입니다.</p>
</section>
<section id="연습-문제-2" class="level3" data-number="3.2">
<h3 data-number="3.2" class="anchored" data-anchor-id="연습-문제-2"><span class="header-section-number">3.2</span> 연습 문제</h3>
<ol start="7" type="1">
<li><p>온라인 괴롭힘을 경험한 미국 성인의 실제 비율을 <span class="math inline">\(m=0.1\)</span>의 오차 한계 내에서 90% 신뢰도로 추정하고 싶다고 가정해 보겠습니다. 이전 연구에서는 <span class="math inline">\(\hat{p}=0.41\)</span>임을 발견했습니다. 여러분의 연구를 위해 어떤 표본 크기가 필요할까요?</p></li>
<li><p>그리스에서 외국 대학의 대학 교육을 마친 사람의 실제 비율을 <span class="math inline">\(m=0.05\)</span>의 오차 한계와 99% 신뢰도로 추정하고 싶다고 가정해 보겠습니다. 여러분의 연구를 위해 어떤 표본 크기가 필요할까요?</p></li>
<li><p>고등학교에서 심화 수업(Honors classes)을 들은 고등학생의 실제 비율을 <span class="math inline">\(m=0.01\)</span>의 오차 한계와 95% 신뢰도로 추정하고 싶다고 가정해 보겠습니다. 여러분의 연구를 위해 어떤 표본 크기가 필요할까요?</p></li>
</ol>
</section>
<section id="mu에-대한-신뢰-구간과-가설-검정" class="level3" data-number="3.3">
<h3 data-number="3.3" class="anchored" data-anchor-id="mu에-대한-신뢰-구간과-가설-검정"><span class="header-section-number">3.3</span> <span class="math inline">\(\mu\)</span>에 대한 신뢰 구간과 가설 검정</h3>
<p>가설 검정과 신뢰 구간은 우리의 두 가지 핵심 통계적 추론 형태입니다. 관련된 공식들, 특히 평균에 대한 검정과 구간을 살펴보면 둘 사이에 구조적인 연결 고리가 존재함을 짐작할 수 있습니다. 신뢰 구간과 가설 검정 모두 중심극한정리에 근거하며, 둘 다 표본 평균 <span class="math inline">\(\bar{x}\)</span>을 포함하고 표준 오차 <span class="math inline">\(\text{s.e.}(\bar{x})=\frac{s}{\sqrt{n}}\)</span>를 활용합니다. 이것이 단지 우연이라고 하기에는 너무나 많은 유사점이 발견됩니다. 사실, <span class="math inline">\(\mu\)</span>에 대한 <span class="math inline">\((1-\alpha) \times 100\%\)</span> 신뢰 구간과 하나의 특정 가설 검정 결과 사이에는 직접적인 수학적 연결 고리가 존재합니다. 바로 대립 가설이 <span class="math inline">\(H_A: \mu \neq \mu_0\)</span>인 양측 검정의 경우입니다.</p>
<p>가설 검정에서 우리의 목표는 대립 가설을 지지하여 귀무 가설을 기각할지(Reject) 아니면 기각하지 못할지(Fail to reject) 결정하는 것입니다. 귀무 가설을 기각하려면 <span class="math inline">\(p\)</span>-값이 유의 수준 <span class="math inline">\(\alpha\)</span>보다 작아야 합니다. 대립 가설 <span class="math inline">\(H_A: \mu \neq \mu_0\)</span>의 경우, 다음과 같은 조건에서 귀무 가설을 기각함을 의미합니다.</p>
<p><span class="math display">\[
2\times P(t_{n-1} \ge |t|) &lt; \alpha
\]</span></p>
<p>또는</p>
<p><span class="math display">\[
P(t_{n-1} \ge |t|) &lt; \alpha/2
\]</span></p>
<p>여기서 <span class="math inline">\(t\)</span>는 검정 통계량(test statistic)이며 <span class="math inline">\(t = \frac{\bar{x}-\mu_0}{s/\sqrt{n}}\)</span>입니다.</p>
<p>이 조건이 참이고 귀무 가설을 기각한다면, 이는 <span class="math inline">\(|t|&gt;t^*\)</span>임을 뜻하며, 여기서 <span class="math inline">\(t^*\)</span>는 <span class="math inline">\(P(t_{n-1} \ge t^*) = \alpha/2\)</span>가 되도록 설정됩니다.</p>
<p>즉 <span class="math inline">\(t^*\)</span> 오른쪽 꼬리의 면적은 <span class="math inline">\(\alpha/2\)</span>이고, <span class="math inline">\(|t|\)</span> 오른쪽 꼬리의 면적은 <span class="math inline">\(p\)</span>-값의 절반입니다.</p>
<p>(따라서 <span class="math inline">\(P(t_{n-1} \ge t^*) = \alpha/2\)</span>인 경우 <span class="math inline">\(|t|&gt;t^*\)</span>이면 <span class="math inline">\(H_A: \mu \neq \mu_0\)</span>를 지지하여 <span class="math inline">\(H_0: \mu = \mu_0\)</span>를 기각합니다.)</p>
<p><span class="math inline">\(P(t_{n-1} \ge t^*) = \alpha/2\)</span>라면, 이는 <span class="math inline">\(P(t_{n-1} \le t^*) = 1-\alpha/2\)</span>임을 뜻합니다.</p>
<p>이것이 귀무 가설을 기각하는 규칙이라면, 반대 경우로 다른 가능한 결정을 정의할 수 있습니다.</p>
<p>즉, <span class="math inline">\(P(t_{n-1} \le t^*) = 1-\alpha/2\)</span>가 되도록 <span class="math inline">\(t^*\)</span>를 선택했을 때 <span class="math inline">\(|t|&lt;t^*\)</span>이면 <span class="math inline">\(H_0: \mu = \mu_0\)</span>를 기각하는 데 실패할 것입니다.</p>
<p>가설 검정에서 계산하는 검정 통계량을 대입함으로써 이를 좀 더 구체적으로 확장할 수 있습니다.</p>
<p>그렇게 하면 다음과 같은 경우 귀무 가설을 기각하는 데 실패하게 됩니다.</p>
<p><span class="math display">\[
\left|\frac{\bar{x}-\mu_0}{s/\sqrt{n}}\right|&lt;t^*
\]</span></p>
<p><span class="math inline">\(\bar{x}\)</span>, <span class="math inline">\(s\)</span>, <span class="math inline">\(n\)</span> 값은 우리가 선택한 검정과 상관없이 연구 내내 고정된 값입니다. 마찬가지로 <span class="math inline">\(t^*\)</span>는 유의 수준 <span class="math inline">\(\alpha\)</span>를 설정하면 변하지 않습니다. 사실 이러한 검정들 전반에서 변할 수 있는 유일한 모수는 <span class="math inline">\(\mu_0\)</span>의 값뿐입니다. 즉, 표본과 정해진 유의 수준이 주어지면, <span class="math inline">\(\mu_0\)</span> 값이 기각으로 이어질지 기각 실패로 이어질지 결정할 수 있습니다. 위의 방정식에서 <span class="math inline">\(\mu_0\)</span>에 관해 풀면 이를 손쉽게 수행할 수 있습니다.</p>
<p>첫 번째 단계는 <span class="math inline">\(|t|&lt;t^*\)</span>라면 이는 <span class="math inline">\(-t^*&lt;t&lt;t^*\)</span>를 의미한다는 점을 파악하는 것입니다.</p>
<p>이를 염두에 두고 위의 방정식을 다시 쓰고 약간의 대수학을 사용하여 <span class="math inline">\(\mu_0\)</span>에 관해 풉니다. 이는 어떤 조건 하에서(즉, 어떤 <span class="math inline">\(\mu_0\)</span> 값에 대해) 귀무 가설 기각에 실패할지를 명확히 정의해 줍니다.</p>
<p><span class="math display">\[
\begin{aligned}
-t^* &amp;&lt; \frac{\bar{x}-\mu_0}{s/\sqrt{n}} &lt; t^* \\
-t^*\frac{s}{\sqrt{n}} &amp;&lt; \bar{x}-\mu_0 &lt; t^*\frac{s}{\sqrt{n}} \\
-\bar{x}-t^*\frac{s}{\sqrt{n}} &amp;&lt; -\mu_0 &lt; -\bar{x}+t^*\frac{s}{\sqrt{n}} \\
\bar{x}-t^*\frac{s}{\sqrt{n}} &amp;&lt; \mu_0 &lt; \bar{x}+t^*\frac{s}{\sqrt{n}}
\end{aligned}
\]</span></p>
<p>이는 <span class="math inline">\(\mu_0\)</span>가 다음 구간에 위치한다면 귀무 가설을 기각하는 데 실패함을 의미합니다.</p>
<p><span class="math display">\[
\left(\bar{x}-t^*\frac{s}{\sqrt{n}},\ \bar{x}+t^*\frac{s}{\sqrt{n}}\right)
\]</span></p>
<p>여기서 <span class="math inline">\(P(t_{n-1} \le t^*) = 1-\alpha/2\)</span>가 되도록 <span class="math inline">\(t^*\)</span>를 선택합니다. 자세히 살펴보면 이 구간이 바로 <span class="math inline">\(\mu\)</span>에 대한 우리의 <span class="math inline">\((1-\alpha) \times 100\%\)</span> 신뢰 구간과 정확히 일치함을 알 수 있습니다. 이것은 단순한 우연이 아닙니다. <span class="math inline">\(\mu\)</span>에 대한 <span class="math inline">\((1-\alpha) \times 100\%\)</span> 신뢰 구간을 생성한 다음, 동일한 <span class="math inline">\(\alpha\)</span> 유의 수준에서 <span class="math inline">\(H_0: \mu=\mu_0\)</span> 대 <span class="math inline">\(H_A: \mu \neq \mu_0\)</span>의 가설 검정을 수행하려는 경우, <span class="math inline">\(\mu_0\)</span>가 우리의 <span class="math inline">\((1-\alpha) \times 100\%\)</span> 신뢰 구간에 포함되어 있다면 귀무 가설을 기각하는 데 실패하게 됩니다. 반면 <span class="math inline">\(\mu_0\)</span>가 <span class="math inline">\((1-\alpha) \times 100\%\)</span> 신뢰 구간 바깥에 존재한다면, 해당 <span class="math inline">\(\alpha\)</span> 유의 수준에서 귀무 가설을 단호히 기각할 것입니다.</p>
<p>실제로 신뢰 구간을 계산하고 이 결과를 적용한 뒤 가설 검정을 통해 직접 확인해 보겠습니다. 와셔(Washer)를 제조하는 공장에서 와셔 크기의 모집단 평균이 4와 의미 있게 다른지 테스트하고자 했던 이전 예시를 떠올려 보십시오.</p>
<p>20개 와셔의 표본 평균은 3.9865였고 표본 표준편차는 <span class="math inline">\(s=0.073\)</span>이었습니다. 95% 신뢰 구간을 생성하려면 <code>qt(p = 0.975, df = 19)</code>를 사용하여 <span class="math inline">\(t^*\)</span>가 2.093임을 도출합니다. 이것과 표본 데이터를 종합하면 <span class="math inline">\(\mu\)</span>에 대한 95% 신뢰 구간은 다음과 같습니다.</p>
<p><span class="math display">\[
3.9865 \pm 2.093 \times \frac{0.073}{\sqrt{20}}=(3.952,\ 4.021)
\]</span></p>
<p>이를 염두에 두고 <span class="math inline">\(\alpha=0.05\)</span>에서 <span class="math inline">\(H_0: \mu=4\)</span> 대 <span class="math inline">\(H_A: \mu \neq 4\)</span>를 테스트한다면, 95% 신뢰 구간에 대한 <span class="math inline">\(\alpha\)</span> 수준이 <span class="math inline">\(\alpha=0.05\)</span>이므로 단지 95% 신뢰 구간만 확인하면 충분합니다.</p>
<p>4는 구간 (3.952, 4.021)(우리의 <span class="math inline">\(\mu\)</span>에 대한 95% 신뢰 구간)에 포함되어 있으므로 귀무 가설을 기각하는 데 실패할 것입니다. 이전 장을 되돌아보면 이 검정에 대한 <span class="math inline">\(p\)</span>-값이 0.4185027임을 확인했습니다. 이는 귀무 가설을 기각하는 데 실패해야 함을 명확히 보여주며, 신뢰 구간에 기반한 우리의 결론과 완벽하게 일치합니다.</p>
<p>이처럼 신뢰 구간과 가설 검정의 쌍대성을 활용하면 두 절차의 결론이 서로 일치하는지 교차 검증할 수 있습니다.</p>
</section>
<section id="연습-문제-3" class="level3" data-number="3.4">
<h3 data-number="3.4" class="anchored" data-anchor-id="연습-문제-3"><span class="header-section-number">3.4</span> 연습 문제</h3>
<p>영양 정보에 따르면 통밀가루에서 ppm 단위로 4.1의 구리가 발견될 것으로 예상됩니다. 이를 테스트하기 위해 연구자는 24개의 통밀가루 표본에 대한 데이터를 수집합니다. 분석 결과 구리의 표본 평균이 <span class="math inline">\(\bar{x}=4.28\)</span>이고 표본 표준편차는 <span class="math inline">\(s=5.297\)</span>임을 발견했습니다.</p>
<ol start="10" type="1">
<li><p><span class="math inline">\(\mu\)</span>에 대한 90% 신뢰 구간을 계산해 보십시오. <span class="math inline">\(\alpha=0.1\)</span> 수준에서 <span class="math inline">\(H_0: \mu=4.1\)</span> 대 <span class="math inline">\(H_A: \mu \neq 4.1\)</span>의 검정에서 귀무 가설을 기각하시겠습니까?</p></li>
<li><p><span class="math inline">\(\mu\)</span>에 대한 95% 신뢰 구간을 생성했다고 가정해 보겠습니다. <span class="math inline">\(\alpha=0.05\)</span> 수준에서 <span class="math inline">\(H_0: \mu=2\)</span> 대 <span class="math inline">\(H_A: \mu \neq 2\)</span>의 검정에서 귀무 가설을 기각하시겠습니까?</p></li>
<li><p><span class="math inline">\(\mu\)</span>에 대한 99% 신뢰 구간을 생성했다고 가정해 보겠습니다. <span class="math inline">\(\alpha=0.01\)</span> 수준에서 <span class="math inline">\(H_0: \mu=4.1\)</span> 대 <span class="math inline">\(H_A: \mu \neq 4.1\)</span>의 검정에서 귀무 가설을 기각하시겠습니까?</p></li>
</ol>
</section>
</section>
<section id="구간-추정과-검정-결과를-함께-읽기" class="level2" data-number="4">
<h2 data-number="4" class="anchored" data-anchor-id="구간-추정과-검정-결과를-함께-읽기"><span class="header-section-number">4</span> 구간 추정과 검정 결과를 함께 읽기</h2>
<p>단일 모수에 대한 신뢰 구간은 같은 문제에 대한 가설 검정과 밀접하게 연결되어 있습니다. 예를 들어 양측 검정에서 유의 수준이 0.05이고 95% 신뢰 구간이 귀무값을 포함하지 않는다면, 같은 데이터로 수행한 양측 검정은 대체로 귀무 가설을 기각하게 됩니다. 반대로 신뢰 구간이 귀무값을 포함하면 해당 유의 수준에서는 귀무 가설을 기각하기 어렵습니다.</p>
<p>그러나 두 절차의 근본적인 목적은 다릅니다. 검정은 특정 귀무값 하나와 데이터가 얼마나 충돌하는지 평가하는 반면, 신뢰 구간은 주어진 데이터와 양립 가능한 타당한 값들의 전체 범위를 제시합니다. 실무 분석 보고서에서는 이 두 가지 관점을 함께 서술하는 편이 훨씬 권장됩니다.</p>
</section>
<section id="r을-활용한-실습-단일-모수-가설-검정과-신뢰-구간" class="level2" data-number="5">
<h2 data-number="5" class="anchored" data-anchor-id="r을-활용한-실습-단일-모수-가설-검정과-신뢰-구간"><span class="header-section-number">5</span> R을 활용한 실습: 단일 모수 가설 검정과 신뢰 구간</h2>
<p>앞서 다룬 가설 검정과 신뢰 구간의 쌍대성을 R 코드로 확인해 보겠습니다. <code>t.test()</code> 함수는 이 두 가지 결과를 동시에 제공합니다.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb8"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb8-1"><a href="#cb8-1" aria-hidden="true" tabindex="-1"></a><span class="co"># 예시 데이터</span></span>
<span id="cb8-2"><a href="#cb8-2" aria-hidden="true" tabindex="-1"></a>sample_data <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="fl">12.1</span>, <span class="fl">11.8</span>, <span class="fl">12.4</span>, <span class="fl">12.0</span>, <span class="fl">11.9</span>, <span class="fl">12.5</span>, <span class="fl">11.7</span>, <span class="fl">12.2</span>, <span class="fl">11.9</span>, <span class="fl">12.1</span>)</span>
<span id="cb8-3"><a href="#cb8-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb8-4"><a href="#cb8-4" aria-hidden="true" tabindex="-1"></a><span class="co"># 모평균이 12인지 확인하는 양측 검정 및 95% 신뢰 구간 계산</span></span>
<span id="cb8-5"><a href="#cb8-5" aria-hidden="true" tabindex="-1"></a>result <span class="ot">&lt;-</span> <span class="fu">t.test</span>(</span>
<span id="cb8-6"><a href="#cb8-6" aria-hidden="true" tabindex="-1"></a>  <span class="at">x =</span> sample_data,</span>
<span id="cb8-7"><a href="#cb8-7" aria-hidden="true" tabindex="-1"></a>  <span class="at">mu =</span> <span class="dv">12</span>,</span>
<span id="cb8-8"><a href="#cb8-8" aria-hidden="true" tabindex="-1"></a>  <span class="at">alternative =</span> <span class="st">"two.sided"</span>,</span>
<span id="cb8-9"><a href="#cb8-9" aria-hidden="true" tabindex="-1"></a>  <span class="at">conf.level =</span> <span class="fl">0.95</span></span>
<span id="cb8-10"><a href="#cb8-10" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb8-11"><a href="#cb8-11" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb8-12"><a href="#cb8-12" aria-hidden="true" tabindex="-1"></a><span class="co"># 결과 출력</span></span>
<span id="cb8-13"><a href="#cb8-13" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(result)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>
    One Sample t-test

data:  sample_data
t = 0.74485, df = 9, p-value = 0.4754
alternative hypothesis: true mean is not equal to 12
95 percent confidence interval:
 11.87778 12.24222
sample estimates:
mean of x 
    12.06 </code></pre>
</div>
</div>
<p>이 출력에서 <code>p.value</code>는 귀무값(12)과의 충돌 정도를 보여주며, <code>conf.int</code>는 모평균의 타당한 범위를 제시합니다. 만약 95% 신뢰 구간 안에 12가 포함된다면, 유의 수준 0.05에서 귀무 가설을 기각할 수 없다는 결론과 일치합니다.</p>
<p>또한, 모비율 추정을 위한 적정 표본 크기를 R로 직접 계산해 볼 수 있습니다.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb10"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb10-1"><a href="#cb10-1" aria-hidden="true" tabindex="-1"></a><span class="co"># 표본 크기 계산 함수 정의</span></span>
<span id="cb10-2"><a href="#cb10-2" aria-hidden="true" tabindex="-1"></a>calculate_sample_size <span class="ot">&lt;-</span> <span class="cf">function</span>(margin_error, conf_level, <span class="at">p_est =</span> <span class="fl">0.5</span>) {</span>
<span id="cb10-3"><a href="#cb10-3" aria-hidden="true" tabindex="-1"></a>  alpha <span class="ot">&lt;-</span> <span class="dv">1</span> <span class="sc">-</span> conf_level</span>
<span id="cb10-4"><a href="#cb10-4" aria-hidden="true" tabindex="-1"></a>  z_star <span class="ot">&lt;-</span> <span class="fu">qnorm</span>(<span class="dv">1</span> <span class="sc">-</span> alpha <span class="sc">/</span> <span class="dv">2</span>)</span>
<span id="cb10-5"><a href="#cb10-5" aria-hidden="true" tabindex="-1"></a>  n <span class="ot">&lt;-</span> (z_star<span class="sc">^</span><span class="dv">2</span> <span class="sc">*</span> p_est <span class="sc">*</span> (<span class="dv">1</span> <span class="sc">-</span> p_est)) <span class="sc">/</span> margin_error<span class="sc">^</span><span class="dv">2</span></span>
<span id="cb10-6"><a href="#cb10-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">return</span>(<span class="fu">ceiling</span>(n)) <span class="co"># 정수로 올림</span></span>
<span id="cb10-7"><a href="#cb10-7" aria-hidden="true" tabindex="-1"></a>}</span>
<span id="cb10-8"><a href="#cb10-8" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb10-9"><a href="#cb10-9" aria-hidden="true" tabindex="-1"></a><span class="co"># 오차 한계 0.04, 99.5% 신뢰 수준, 사전 정보 없음(p=0.5)</span></span>
<span id="cb10-10"><a href="#cb10-10" aria-hidden="true" tabindex="-1"></a>n_required <span class="ot">&lt;-</span> <span class="fu">calculate_sample_size</span>(<span class="at">margin_error =</span> <span class="fl">0.04</span>, <span class="at">conf_level =</span> <span class="fl">0.995</span>)</span>
<span id="cb10-11"><a href="#cb10-11" aria-hidden="true" tabindex="-1"></a><span class="fu">cat</span>(<span class="st">"필요한 최소 표본 크기:"</span>, n_required, <span class="st">"명</span><span class="sc">\n</span><span class="st">"</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>필요한 최소 표본 크기: 1232 명</code></pre>
</div>
</div>
<p>이렇게 함수를 작성해두면, 분석 과정에서 신뢰 수준이나 오차 한계 요구사항이 변경될 때마다 필요한 표본 크기를 신속하고 정확하게 재계산할 수 있습니다.</p>
<p>특히 현대의 의료 데이터 분석이나 정책 효과성 검증 자료에서는 단순한 통계적 유의성 여부보다 신뢰 구간의 폭과 위치가 실질적인 의사결정에 더 중요한 단서를 제공합니다.</p>
</section>
<section id="결론" class="level2" data-number="6">
<h2 data-number="6" class="anchored" data-anchor-id="결론"><span class="header-section-number">6</span> 결론</h2>
<p>단일 모수에 대한 신뢰 구간은 가설 검정과 동일한 기본 가정 및 기초 수학적 정리에서 출발합니다. 그 중심에는 늘 데이터를 모수와 안정적으로 연결해 주는 중심극한정리가 자리 잡고 있습니다. 이러한 구조적 연결은 신뢰 구간에 풍부한 추가 용도를 부여하며, 단순한 타당성 범위를 넘어 가설을 기각하거나 향후 연구를 위한 최적의 표본 크기를 산출할 수 있게 돕습니다. 가설 검정과 마찬가지로, 신뢰 구간 절차는 모집단 평균과 비율에 대한 구간 모두에서 놀라운 일관성을 유지합니다. 이어지는 장에서 여러 그룹이 유사한지 비교분석하는 과정에서도 이러한 통계적 일관성이 그대로 이어지는 것을 확인하실 수 있습니다.</p>


</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
  window.document.addEventListener("DOMContentLoaded", function (event) {
    const icon = "";
    const anchorJS = new window.AnchorJS();
    anchorJS.options = {
      placement: 'right',
      icon: icon
    };
    anchorJS.add('.anchored');
    const isCodeAnnotation = (el) => {
      for (const clz of el.classList) {
        if (clz.startsWith('code-annotation-')) {                     
          return true;
        }
      }
      return false;
    }
    const onCopySuccess = function(e) {
      // button target
      const button = e.trigger;
      // don't keep focus
      button.blur();
      // flash "checked"
      button.classList.add('code-copy-button-checked');
      var currentTitle = button.getAttribute("title");
      button.setAttribute("title", "Copied!");
      let tooltip;
      if (window.bootstrap) {
        button.setAttribute("data-bs-toggle", "tooltip");
        button.setAttribute("data-bs-placement", "left");
        button.setAttribute("data-bs-title", "Copied!");
        tooltip = new bootstrap.Tooltip(button, 
          { trigger: "manual", 
            customClass: "code-copy-button-tooltip",
            offset: [0, -8]});
        tooltip.show();    
      }
      setTimeout(function() {
        if (tooltip) {
          tooltip.hide();
          button.removeAttribute("data-bs-title");
          button.removeAttribute("data-bs-toggle");
          button.removeAttribute("data-bs-placement");
        }
        button.setAttribute("title", currentTitle);
        button.classList.remove('code-copy-button-checked');
      }, 1000);
      // clear code selection
      e.clearSelection();
    }
    const getTextToCopy = function(trigger) {
      const outerScaffold = trigger.parentElement.cloneNode(true);
      const codeEl = outerScaffold.querySelector('code');
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
    const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
      text: getTextToCopy
    });
    clipboard.on('success', onCopySuccess);
    if (window.document.getElementById('quarto-embedded-source-code-modal')) {
      const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
        text: getTextToCopy,
        container: window.document.getElementById('quarto-embedded-source-code-modal')
      });
      clipboardModal.on('success', onCopySuccess);
    }
      var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
      var mailtoRegex = new RegExp(/^mailto:/);
        var filterRegex = new RegExp('/' + window.location.host + '/');
      var isInternal = (href) => {
          return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
      }
      // Inspect non-navigation links and adorn them if external
     var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
      for (var i=0; i<links.length; i++) {
        const link = links[i];
        if (!isInternal(link.href)) {
          // undo the damage that might have been done by quarto-nav.js in the case of
          // links that we want to consider external
          if (link.dataset.originalHref !== undefined) {
            link.href = link.dataset.originalHref;
          }
        }
      }
    function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
      const config = {
        allowHTML: true,
        maxWidth: 500,
        delay: 100,
        arrow: false,
        appendTo: function(el) {
            return el.parentElement;
        },
        interactive: true,
        interactiveBorder: 10,
        theme: 'quarto',
        placement: 'bottom-start',
      };
      if (contentFn) {
        config.content = contentFn;
      }
      if (onTriggerFn) {
        config.onTrigger = onTriggerFn;
      }
      if (onUntriggerFn) {
        config.onUntrigger = onUntriggerFn;
      }
      window.tippy(el, config); 
    }
    const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
    for (var i=0; i<noterefs.length; i++) {
      const ref = noterefs[i];
      tippyHover(ref, function() {
        // use id or data attribute instead here
        let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
        try { href = new URL(href).hash; } catch {}
        const id = href.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note) {
          return note.innerHTML;
        } else {
          return "";
        }
      });
    }
    const xrefs = window.document.querySelectorAll('a.quarto-xref');
    const processXRef = (id, note) => {
      // Strip column container classes
      const stripColumnClz = (el) => {
        el.classList.remove("page-full", "page-columns");
        if (el.children) {
          for (const child of el.children) {
            stripColumnClz(child);
          }
        }
      }
      stripColumnClz(note)
      if (id === null || id.startsWith('sec-')) {
        // Special case sections, only their first couple elements
        const container = document.createElement("div");
        if (note.children && note.children.length > 2) {
          container.appendChild(note.children[0].cloneNode(true));
          for (let i = 1; i < note.children.length; i++) {
            const child = note.children[i];
            if (child.tagName === "P" && child.innerText === "") {
              continue;
            } else {
              container.appendChild(child.cloneNode(true));
              break;
            }
          }
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(container);
          }
          return container.innerHTML
        } else {
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(note);
          }
          return note.innerHTML;
        }
      } else {
        // Remove any anchor links if they are present
        const anchorLink = note.querySelector('a.anchorjs-link');
        if (anchorLink) {
          anchorLink.remove();
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        if (note.classList.contains("callout")) {
          return note.outerHTML;
        } else {
          return note.innerHTML;
        }
      }
    }
    for (var i=0; i<xrefs.length; i++) {
      const xref = xrefs[i];
      tippyHover(xref, undefined, function(instance) {
        instance.disable();
        let url = xref.getAttribute('href');
        let hash = undefined; 
        if (url.startsWith('#')) {
          hash = url;
        } else {
          try { hash = new URL(url).hash; } catch {}
        }
        if (hash) {
          const id = hash.replace(/^#\/?/, "");
          const note = window.document.getElementById(id);
          if (note !== null) {
            try {
              const html = processXRef(id, note.cloneNode(true));
              instance.setContent(html);
            } finally {
              instance.enable();
              instance.show();
            }
          } else {
            // See if we can fetch this
            fetch(url.split('#')[0])
            .then(res => res.text())
            .then(html => {
              const parser = new DOMParser();
              const htmlDoc = parser.parseFromString(html, "text/html");
              const note = htmlDoc.getElementById(id);
              if (note !== null) {
                const html = processXRef(id, note);
                instance.setContent(html);
              } 
            }).finally(() => {
              instance.enable();
              instance.show();
            });
          }
        } else {
          // See if we can fetch a full url (with no hash to target)
          // This is a special case and we should probably do some content thinning / targeting
          fetch(url)
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.querySelector('main.content');
            if (note !== null) {
              // This should only happen for chapter cross references
              // (since there is no id in the URL)
              // remove the first header
              if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
                note.children[0].remove();
              }
              const html = processXRef(null, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      }, function(instance) {
      });
    }
        let selectedAnnoteEl;
        const selectorForAnnotation = ( cell, annotation) => {
          let cellAttr = 'data-code-cell="' + cell + '"';
          let lineAttr = 'data-code-annotation="' +  annotation + '"';
          const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
          return selector;
        }
        const selectCodeLines = (annoteEl) => {
          const doc = window.document;
          const targetCell = annoteEl.getAttribute("data-target-cell");
          const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
          const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
          const lines = annoteSpan.getAttribute("data-code-lines").split(",");
          const lineIds = lines.map((line) => {
            return targetCell + "-" + line;
          })
          let top = null;
          let height = null;
          let parent = null;
          if (lineIds.length > 0) {
              //compute the position of the single el (top and bottom and make a div)
              const el = window.document.getElementById(lineIds[0]);
              top = el.offsetTop;
              height = el.offsetHeight;
              parent = el.parentElement.parentElement;
            if (lineIds.length > 1) {
              const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
              const bottom = lastEl.offsetTop + lastEl.offsetHeight;
              height = bottom - top;
            }
            if (top !== null && height !== null && parent !== null) {
              // cook up a div (if necessary) and position it 
              let div = window.document.getElementById("code-annotation-line-highlight");
              if (div === null) {
                div = window.document.createElement("div");
                div.setAttribute("id", "code-annotation-line-highlight");
                div.style.position = 'absolute';
                parent.appendChild(div);
              }
              div.style.top = top - 2 + "px";
              div.style.height = height + 4 + "px";
              div.style.left = 0;
              let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
              if (gutterDiv === null) {
                gutterDiv = window.document.createElement("div");
                gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
                gutterDiv.style.position = 'absolute';
                const codeCell = window.document.getElementById(targetCell);
                const gutter = codeCell.querySelector('.code-annotation-gutter');
                gutter.appendChild(gutterDiv);
              }
              gutterDiv.style.top = top - 2 + "px";
              gutterDiv.style.height = height + 4 + "px";
            }
            selectedAnnoteEl = annoteEl;
          }
        };
        const unselectCodeLines = () => {
          const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
          elementsIds.forEach((elId) => {
            const div = window.document.getElementById(elId);
            if (div) {
              div.remove();
            }
          });
          selectedAnnoteEl = undefined;
        };
          // Handle positioning of the toggle
      window.addEventListener(
        "resize",
        throttle(() => {
          elRect = undefined;
          if (selectedAnnoteEl) {
            selectCodeLines(selectedAnnoteEl);
          }
        }, 10)
      );
      function throttle(fn, ms) {
      let throttle = false;
      let timer;
        return (...args) => {
          if(!throttle) { // first call gets through
              fn.apply(this, args);
              throttle = true;
          } else { // all the others get throttled
              if(timer) clearTimeout(timer); // cancel #2
              timer = setTimeout(() => {
                fn.apply(this, args);
                timer = throttle = false;
              }, ms);
          }
        };
      }
        // Attach click handler to the DT
        const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
        for (const annoteDlNode of annoteDls) {
          annoteDlNode.addEventListener('click', (event) => {
            const clickedEl = event.target;
            if (clickedEl !== selectedAnnoteEl) {
              unselectCodeLines();
              const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
              if (activeEl) {
                activeEl.classList.remove('code-annotation-active');
              }
              selectCodeLines(clickedEl);
              clickedEl.classList.add('code-annotation-active');
            } else {
              // Unselect the line
              unselectCodeLines();
              clickedEl.classList.remove('code-annotation-active');
            }
          });
        }
    const findCites = (el) => {
      const parentEl = el.parentElement;
      if (parentEl) {
        const cites = parentEl.dataset.cites;
        if (cites) {
          return {
            el,
            cites: cites.split(' ')
          };
        } else {
          return findCites(el.parentElement)
        }
      } else {
        return undefined;
      }
    };
    var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
    for (var i=0; i<bibliorefs.length; i++) {
      const ref = bibliorefs[i];
      const citeInfo = findCites(ref);
      if (citeInfo) {
        tippyHover(citeInfo.el, function() {
          var popup = window.document.createElement('div');
          citeInfo.cites.forEach(function(cite) {
            var citeDiv = window.document.createElement('div');
            citeDiv.classList.add('hanging-indent');
            citeDiv.classList.add('csl-entry');
            var biblioDiv = window.document.getElementById('ref-' + cite);
            if (biblioDiv) {
              citeDiv.innerHTML = biblioDiv.innerHTML;
            }
            popup.appendChild(citeDiv);
          });
          return popup.innerHTML;
        });
      }
    }
  });
  </script>
</div> <!-- /content -->




</body></html>